### ISSUE TITLE
Does not compiled. Unsupported swift version

### ISSUE THREAD

**Issue by Tayphoon** [GetStream/stream-chat-swift#1]
![image](https://user-images.githubusercontent.com/1618506/62819507-d23c5500-bb5e-11e9-85d8-315df5fb4293.png)

**Comment by tbarbugli** [comment]
which version of Swift are you using?

**Comment by Tayphoon** [comment]
This is because 3 in dependencies set 3.0 version for swift

**Comment by Tayphoon** [comment]
We may close the issue. Cocoapods use version from proj file what may have older swift version if project does not include swift.
