### ISSUE TITLE
Feature request: Ability to disable mutes and flags

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#10]
I can see `mutes` value comes from api in channel's config but it's not respected on the client: 
```
		"config": {
			"created_at": "2019-08-22T08:24:56.766147237Z",
			"updated_at": "2019-08-22T08:24:56.766147316Z",
			"name": "commerce",
			"typing_events": true,
			"read_events": true,
			"connect_events": true,
			"search": true,
			"reactions": true,
			"replies": true,
			"mutes": true,
			"message_retention": "infinite",
			"max_message_length": 5000,
			"automod": "disabled",
			"automod_behavior": "flag",
		}
```

I couldn't find a way to disable `flag` feature using channel's config or presenter's variable.

Disabling muting is particularly important for us because we use GetStream as a chat with our customer service. We don't want user to have ability to mute Customer Service Agent.

**Comment by buh** [comment]
Hi @mpodeszwa!
It's all manageable in the dashboard -> chat overview -> channel type.

**Comment by mpodeszwa** [comment]
![Screenshot 2019-09-05 at 11 12 27](https://user-images.githubusercontent.com/7826664/64328639-1986fb80-cfce-11e9-9274-4d9f516ffd28.png)
I can't see option for flags. And disabling mutes doesn't disable this option in ios client

**Comment by buh** [comment]
@mpodeszwa  
Try to remove commands here:
![commands](https://user-images.githubusercontent.com/284922/64329385-78994000-cfcf-11e9-9f13-e070408fc66a.png)

**Comment by mpodeszwa** [comment]
I have commands completely disabled. To be precise I can't type `/flag ...` but I can still long press on message and flag it or mute user

**Comment by buh** [comment]
Thanks! I'll do update for `flags`.

**Comment by buh** [comment]
Fixed in v.1.2.11
