### ISSUE TITLE
StreamChat framework contains nested framework StreamChatCore when using Carthage

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#100]
## What did you do?

I updated StreamChat to version 1.5.6 using Carthage. When I tried uploading build to the appstore I got following error:
```
2020-02-14 12:23:10.549 altool[88113:33733047] ERROR ITMS-90205: "Invalid Bundle. The bundle at '.app/Frameworks/StreamChat.framework' contains disallowed nested bundles."
2020-02-14 12:23:10.549 altool[88113:33733047] ERROR ITMS-90206: "Invalid Bundle. The bundle at '.app/Frameworks/StreamChat.framework' contains disallowed file 'Frameworks'.
```
After investigating closer I found out `StreamChat.framework` contains `StreamChatCore.framework` inside:
```
~> tree StreamChat.framework
StreamChat.framework
├── Assets.car
├── Frameworks
│   └── StreamChatCore.framework
│       ├── Info.plist
│       └── StreamChatCore
├── Headers
│   ├── StreamChat-Swift.h
│   └── StreamChat.h
├── Info.plist
├── Modules
│   ├── StreamChat.swiftmodule
│   │   ├── arm64-apple-ios.swiftdoc
│   │   ├── arm64-apple-ios.swiftmodule
│   │   ├── arm64.swiftdoc
│   │   ├── arm64.swiftmodule
│   │   ├── x86_64-apple-ios-simulator.swiftdoc
│   │   ├── x86_64-apple-ios-simulator.swiftmodule
│   │   ├── x86_64.swiftdoc
│   │   └── x86_64.swiftmodule
│   └── module.modulemap
└── StreamChat

5 directories, 16 files
```

## What did you expect to happen?
`StreamChat.framework` shouldn't contain `StreamChatCore.framework`. It should be included by the apps integrating the library.

## What happened instead?
`StreamChat.framework` contains `StreamChatCore.framework` and `altool` rejects the build before submitting

## GetStream Environment
**GetStream Chat version:** 1.5.6
**Xcode version:** 11.3.1
**Carthage version:** 0.34.0

## Additional context
It was fine at commit ad9e3c82d4dc5de93dfc6888606c8a4dac0276e6 .
To reproduce just build `StreamChat` using carthage

**Comment by buh** [comment]
Thanks @mpodeszwa 
We'll fix it quickly.

**Comment by buh** [comment]
@mpodeszwa please check the latest release [v.1.5.7](https://github.com/GetStream/stream-chat-swift/releases/tag/1.5.7)
