### ISSUE TITLE
3.2.0-beta.6 will not compile: Value of type 'Logger' has no member 'assertionFailure'

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1015]
## What did you do?
Install StreamChat 3.2.0-beta.6 and tried to compile

## What did you expect to happen?
Compile should succeed

## What happened instead?
I got a compile error:
```
.../Pods/StreamChatUI/Sources/StreamChatUI/CommonViews/BaseViews.swift:56:17: Value of type 'Logger' has no member 'assertionFailure'
```

## GetStream Environment
**GetStream Chat version:3.2.0-beta.6

**Comment by VojtaStavik** [comment]
Hi @srgray, this seems like a pod cache issue. Can you please try to clean your derived data a perform a clean build?

**Comment by VojtaStavik** [comment]
@adasiewiczr I'm closing this for now. Please re-open this issue in case performing a clean build didn't fix the issue.

**Comment by srgray** [comment]
A "clean build folder" did not fix the issue for me.
I was also able to reproduce the compile error with a new project that only has the StreamChat CocoaPod by doing:
- Create new Xcode project
- Add only the StreamChat pod: `pod 'StreamChatUI', '3.2.0-beta.6'` to Podfile
- `pod install`
- Clean/build

If I examine the source of StreamChat pod, I can see the `assertationFailure` method that is triggering the compile error. It looks as if I didn't get the appropriate version of pod installed? I will attach my Podfile.lock.

[Podfile.txt](https://github.com/GetStream/stream-chat-swift/files/6377517/Podfile.txt)
[Podfile.lock.txt](https://github.com/GetStream/stream-chat-swift/files/6377518/Podfile.lock.txt)

**Comment by srgray** [comment]
I just updated to `3.2.0-beta.8` and now I do not get the compile error.
This is no longer an issue for me.

**Comment by VojtaStavik** [comment]
Thank you for more info @srgray. I can't replicate now but it's definitely possible there could be issues with the CocoaPods setup you mentioned. The `StreamChatUI` spec doesn't explicitly specify the version of the `StreamChat` spec which makes it possible to end up in the setup with mismatching versions. We'll fix this in the next release. Thank you for pointing this out @srgray 🙏
