### ISSUE TITLE
UnreadCount subscription not available in v3 Swift SDK?

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1035]
## What did you do?
Trying to implement unread subscription per: https://getstream.io/chat/docs/ios-swift/unread/?language=swift

## What did you expect to happen?
To be able to implement something similar in my app

## What happened instead?
Compile error, I don't think there is a `subscribeToUnreadCount` method in my version of SDK.

## GetStream Environment
**GetStream Chat version:**
3.2.0-beta.8
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
StreamChat, StreamChatUI

**Comment by VojtaStavik** [comment]
@srgray, this part of the documentation hasn't been yet updated to reflect v3 changes. The unread count is available on `CurrentChatUserController` where you can also observe its changes.

**Comment by srgray** [comment]
I implemented a subscriber for it like this:
```
ChatClient.shared.currentUserController().unreadCountPublisher.sink { [weak self] unreadCount in
            DispatchQueue.main.async {
                if let inboxVC = self?.inboxNavVC.viewControllers.first as? InboxViewController {
                    inboxVC.updateTabBarUnreadDot()
                }
            }
        }.store(in: &subscriptions)
```
But when I add a message in a channel to that user (from another instance of my app), that subscriber is not triggered and I see this error in the console log:
```
2021-04-29 15:30:49.750 [ERROR] [NSManagedObjectContext 0x600000535fb0] [ChannelReadUpdaterMiddleware.swift:77] [increaseUnreadCountIfNeeded(for:userId:newMessageAt:session:)] > Can't increase unread count for messaging:!members-7Prp-2rk3VwL95caNEZvVM4EKeK8pE_QebVt_Txtxl8 because the `ChannelReadDTO` for the current user doesn't exist.
```

Any insight on that? (note: I have local caching turned off in my ChatClient configuration)
