### ISSUE TITLE
Network connectivity error is not human-readable

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#104]
## What did you do?

Some request failed because of poor internet connection.

## What did you expect to happen?

I expect error to be human readable

## What happened instead?

User sees this error:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-26 at 11 53 32](https://user-images.githubusercontent.com/7826664/75338831-ad57c700-588f-11ea-9356-004b699c9109.png)

**Comment by b-onc** [comment]
Closed with #106
