### ISSUE TITLE
Ban / Unban action is not synchronized.

### ISSUE THREAD

**Issue by momamene** [GetStream/stream-chat-swift#1079]
## What did you do?

I banned a user by using ChatMemberController

```Swift
let memberController = client.memberController(userId: <userId>, in: cid)
memberController.unban() { ... } 
// or memberController.ban() { ... } 
```

The other side, Screen shows Banned user list by using ChatMemberListController
```Swift
let query = ChannelMemberListQuery(
  cid: cid,
  filter: .equal(.isBanned, to: true),
  pageSize: pageSize
)
memberListController = client.memberListController(query: query)
print(memberListController.members)...
```

( Assure cid is the same ) 

## What did you expect to happen?

What i expect to happen is that `memberListController` is watching members included in cid and banned status synchronized. In other words, when i unban 'A' user, 'A' member should not be in the memberListController.members

## What happened instead?

`memberListController.members` not changed. Also nothing happened in `memberListController.membersChangesPublisher` and `ChatChannelMemberListControllerDelegate`
It seems that UserBannedEvent and UserUnbannedEvent are not handled in UserChannelBanEventsMiddleware
( Any related events are not called )

## GetStream Environment
**GetStream Chat version:**
3.10
**GetStream Chat frameworks:** StreamChat
StreamChat
**iOS version:**
14.5
**Swift version:**
5.3
**Xcode version:**
12.5
**Device:**
iPhone XS Max

**Comment by b-onc** [comment]
Hello @momamene ,

You should call `memberListController.synchronize()` so that it starts watching the members and calls the delegate methods. Can you try that and let me know if it works?

**Comment by momamene** [comment]
I already called `memberListController.synchronize()` before getting memberListController.members.
### Updated information:
When I **ban** a user, `ListChange.insert` change is called in the ChatChannelMemberListControllerDelegate, 
But When I **unban** a user, `ListChange.remove` change NOT called in the ChatChannelMemberListControllerDelegate.
( memberListController.members are also not updated )

**Comment by adamrushy** [comment]
I believe this issue is fixed in our latest version of the SDK, closing this issue.
