### ISSUE TITLE
App crash when user send oversize message

### ISSUE THREAD

**Issue by whiplash00** [GetStream/stream-chat-swift#1082]
## What did you do?
Attempt to send oversized message on iphone (eventual message must be large enough to fill up the screen)

## What did you expect to happen?
Expect app to work normally.

## What happened instead?
The app froze and eventually crashed. The oversized message is sent out though (verified after relaunching the app). Sending the same oversized message on an ipad (much larger screen) does not cause the issue to occur, indicating this is a UI bug.

## GetStream Environment
GetStream Chat version: 3.2.0
GetStream Chat frameworks: StreamChatUI - 3.1.6
iOS version: 14.5.1
Swift version: 5.3.3
Xcode version: 12.5
Device: iphone 12 Pro Max
--

<br class="Apple-interchange-newline">

**Comment by b-onc** [comment]
Hello,

Thanks for the info.
This is known and will be resolved in an upcoming release. We'll ping this ticket when it's released.

**Comment by b-onc** [comment]
Hello,

This is resolved with 4.0-beta.1. Please re-open if you still see this.
