### ISSUE TITLE
Unable to edit message midway once I use an emoji

### ISSUE THREAD

**Issue by gitwina** [GetStream/stream-chat-swift#1117]
## What did you do?
I pasted a message and tried to edit it midway, e.g., "testing 123 testing 123 <emoji>", where I moved the cursor to "test" as I wanted to do a mid-text edit.

## What did you expect to happen?
I expected to be able to edit.

## What happened instead?
The cursor goes back to the last character (which is in my case an emoji). and so I had to edit the message OUTSIDE of the app and then paste it back.

GetStream Environment
GetStream Chat version: 4.0.0
GetStream Chat frameworks: StreamChatUI - 4.0.0
iOS version: 14.5.1
Swift version: 5.3.3
Xcode version: 12.5
Device: iphone 11 Pro Max

**Comment by b-onc** [comment]
Hello @supermomos 

I've tested with the messages shown below:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/770464/120376456-96224780-c324-11eb-9f83-592db851813e.png">

but weren't able to reproduce. Can you provide a sample project, or exact message so I can reproduce?

**Comment by supermomos** [comment]
Pls see this video. After I input an emoji, whenever I want to go back and re-type a word, it brings me right back to the end, such that it is very difficult to edit other parts of the message.

https://www.dropbox.com/s/06vr0d4tm9xrdlv/Emoji%20bug%20for%20stream.mp4?dl=0
