### ISSUE TITLE
Local notification support

### ISSUE THREAD

**Issue by kcollignon** [GetStream/stream-chat-swift#1119]
I was wondering what the current 4.0-beta1 best practice is to handle push notifications when the app is running in the background? I was searching through an older option like `stayConnectedInBackground` but I do not think that is supported anymore?

I am successfully receiving push notifications however if I were to force close the app

**Comment by b-onc** [comment]
Hello @kcollignon,
Those were actually local notifications, not push notifications. We currently don't support them, they're in our backlog.

**Comment by kcollignon** [comment]
Hi @b-onc thanks for the info. Is there any way to still achieve the desired result in the interim? If I understand correctly, when users are getting new messages there is no way for the to know about it with an alert unless the app is forced closed?

**Comment by b-onc** [comment]
Hello @kcollignon 

A workaround for this would be:
1. Create a `ChannelController` for this purpose and assign a delegate.
2. In your delegate's `didUpdateMessages` func:
```swift
func channelController(
        _ channelController: ChatChannelController,
        didUpdateMessages changes: [ListChange<ChatMessage>]
    ) {
    // check if we're in background
   guard UIApplication.state == .background else { return }
   // post local notification
   let content = UNMutableNotificationContent()
   content.title = "\(message.user.name) @ \(channel.name ?? "")"
   ....
```
Please note that this is pseudocode.

Please check out [this page](https://www.hackingwithswift.com/books/ios-swiftui/scheduling-local-notifications) for information about local notifications.
