### ISSUE TITLE
Custom Events

### ISSUE THREAD

**Issue by thoughtspeed7** [GetStream/stream-chat-swift#1120]
I don't seem to find a way to send and listen to custom events on iOS. Not to be found on your documentation for iOS as well. Is this not supported from iOS yet?

**Comment by b-onc** [comment]
Hello @thoughtspeed7 
Custom events are not supported yet, it's in our Roadmap.

**Comment by thoughtspeed7** [comment]
So even listening for custom events is not supported on iOS yet?

**Comment by b-onc** [comment]
@thoughtspeed7 Correct, it's in our backlog and will be implemented.
