### ISSUE TITLE
Please Follow Semantic Versioning

### ISSUE THREAD

**Issue by joeblau** [GetStream/stream-chat-swift#1143]
## What did you do?

https://github.com/GetStream/stream-chat-swift/releases/tag/4.0-beta.1
Trying to use Swift PM to import `4.0-beta.1`

## What did you expect to happen?

I expect it to fail because you're not using somatic versioning.

## What happened instead?

The 4.0 beta release should be tagged `4.0.0-beta.1` or Xcode will not be able to natively process the current beta.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**  N/A
**Swift version:**  N/A
**Xcode version:** 12.5
**Device:** N/A

**Comment by VojtaStavik** [comment]
Thank you @joeblau for pointing this out. Unfortunately, we didn't realize SPM required the full version to always be specified, and noticed it after releasing. We're releasing the second beta today and the version will be specified correctly.

**Comment by b-onc** [comment]
Hello @joeblau ,

4.0.0-beta.2 released, and SPM should behave now. Thanks for heads up.

**Comment by joeblau** [comment]
Thanks @b-onc!
