### ISSUE TITLE
`first_name` and `last_name` not available anymore?

### ISSUE THREAD

**Issue by basememara** [GetStream/stream-chat-swift#1145]
## What did you do?

Do I have to add `first_name` and `last_name` to extended data or is this already there?

## What did you expect to happen?

I thought this was part of the user when updating a user profile.

## What happened instead?

Is this different than `name` which should be for `username`?

## GetStream Environment
**GetStream Chat version:** `main` branch
**GetStream Chat frameworks:** StreamChat

**Comment by b-onc** [comment]
Hello @basememara 

As you've said, you should create your own ExtraData for those fields. Only `name` is provided by default. Please check our [Working with ExtraData](https://github.com/GetStream/stream-chat-swift/wiki/Cheat-Sheet#working-with-extra-data) page.
