### ISSUE TITLE
How to upload certificate to Stream Chat

### ISSUE THREAD

**Issue by hoxtonhero** [GetStream/stream-chat-swift#1162]
I dont understand, how to do upload commands from that tutorial. https://getstream.io/chat/docs/react/push_ios/

We are developing app on iOS and unable to configure notifications. We've managed to create the .p12 cert, but i dont understand how to upload it with the JS code given in the example

**Comment by b-onc** [comment]
Hello @hoxtonhero ,

You can upload your certificate using dashboard. Please visit getstream.io, login, and visit Dashboard. Select your app, and you'll see a button for uploading your certificate.
