### ISSUE TITLE
UX Constraint violation using out-of-box StreamChatUI

### ISSUE THREAD

**Issue by whiplash00** [GetStream/stream-chat-swift#1163]
## What did you do?
Run streamChatUI on iphone

## What did you expect to happen?
No error/warning message

## What happened instead?
Constraint error popups:

1-06-07 15:33:43.923579+0800 Supermomos[15000:4671651] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x283adc5f0 StreamChatUI.ContainerStackView:0x10bf35d70.height == 0   (active)>",
    "<NSLayoutConstraint:0x283aa62b0 UILayoutGuide:0x2820f09a0'UIViewSafeAreaLayoutGuide'.bottom == StreamChatUI.CheckboxControl:0x10bf438d0.bottom   (active)>",
    "<NSLayoutConstraint:0x283aa6260 UILayoutGuide:0x2820f09a0'UIViewSafeAreaLayoutGuide'.top == StreamChatUI.CheckboxControl:0x10bf438d0.top   (active)>",
    "<NSLayoutConstraint:0x283aa6120 'UIViewSafeAreaLayoutGuide-bottom' V:[UILayoutGuide:0x2820f09a0'UIViewSafeAreaLayoutGuide']-(75)-|   (active, names: '|':StreamChatUI.ContainerStackView:0x10bf35d70 )>",
    "<NSLayoutConstraint:0x283aa6080 'UIViewSafeAreaLayoutGuide-top' V:|-(0)-[UILayoutGuide:0x2820f09a0'UIViewSafeAreaLayoutGuide']   (active, names: '|':StreamChatUI.ContainerStackView:0x10bf35d70 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x283aa62b0 UILayoutGuide:0x2820f09a0'UIViewSafeAreaLayoutGuide'.bottom == StreamChatUI.CheckboxControl:0x10bf438d0.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

## GetStream Environment
GetStream Environment
GetStream Chat version: 4.0.0
GetStream Chat frameworks: StreamChatUI - 4.0.0
iOS version: 14.5.1
Swift version: 5.3.3
Xcode version: 12.5
Device: iphone 12 Pro Max

**Comment by b-onc** [comment]
Hello @whiplash00 

Thanks for the report. We are aware these constraints warnings are present. We're currently in process of finalizing our UI SDK, and eliminating these warnings is part of the process.
