### ISSUE TITLE
Hide keyboard when tapped on message list

### ISSUE THREAD

**Issue by whiplash00** [GetStream/stream-chat-swift#1165]
## What did you do?
I am using StreamchatUI and _ChatMessageListVC as my view controller. Current way of hiding the keyboard is not typical of chat app (normally user expect to tap anywhere other than keyboard to hide keyboard, not do a drag up action) hence I added  the hideKeyboardWhenTappedAround() to _ChatMessageListVC.

## What did you expect to happen?
That everything will work as per normal.

## What happened instead?
The keyboard is indeed hidden when simply tapping anywhere, however the @mention is broken. The @mention user selection menu is opened but cannot be clicked on.

## GetStream Environment
GetStream Chat version: 4.0.0
GetStream Chat frameworks: StreamChatUI - 4.0.0
iOS version: 14.5.1
Swift version: 5.3.3
Xcode version: 12.5
Device: iphone 12 Pro Max

**Comment by b-onc** [comment]
Hello @whiplash00 ,

Can you share your `hideKeyboardWhenTappedAround` implementation?

**Comment by whiplash00** [comment]
@b-onc sorry didnt realize `hideKeyboardWhenTappedAround` is my own implementation. Here you go:

```
extension UIViewController {
    func hideKeyboardWhenTappedAround() {
        let tapGesture = UITapGestureRecognizer(target: self,
                                                action: #selector(hideKeyboard))
        view.addGestureRecognizer(tapGesture)
    }
    
    @objc func hideKeyboard() {
        view.endEditing(true)
    }
}
```

**Comment by whiplash00** [comment]
@b-onc I think this should be default behaviour? Should be able to tap anywhere to hide keyboard. Just my one cent. Cheers.

**Comment by b-onc** [comment]
Hello @whiplash00 ,

Thanks for the suggestion. We think this makes sense too, so we're adding it to our backlog. I'm keeping this issue open, converted to a feature request.

**Comment by whiplash00** [comment]
@b-onc Thank you!
