### ISSUE TITLE
Upgrade RxSwift & RxCocoa version to 6.2.0 in StreamChatCore

### ISSUE THREAD

**Issue by nizas** [GetStream/stream-chat-swift#1167]
**Is it possible to upgrade RxSwift and RxCocoa versions to 6.2.0 in StreamChatCore?**

## GetStream Environment
**GetStream Chat version:** **3.1.3**
**StreamChatCore version:** **2.6.7**
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat

**Comment by b-onc** [comment]
Hello @nizas ,

Apologizes for late reply.

StreamChatCore is not compatible with StreamChat 3.1.3, what's your intended usage? If you need RxSwift wrappers for v3 and up, it's on our roadmap but not possible yet.
