### ISSUE TITLE
Unable to get push notification

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#117]
## What did you do?
I just called your add device method with device token and it got every possible parameters
along with success .
<img width="1116" alt="Screenshot 2020-03-13 at 7 05 13 PM" src="https://user-images.githubusercontent.com/37240061/76625624-a9999500-655d-11ea-9c06-d21fec1369ea.png">

## What did you expect to happen?
Push Notification(s)

## What happened instead?
No Push Notifications 

## GetStream Environment
**GetStream Chat version:** 1.5.7 
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**iPhone 7 Plus

## Additional context
I debug and found that it is giving me successful device addition in terms of push notifications but  still no push notifications no idea .
<img width="1149" alt="Screenshot 2020-03-13 at 6 56 52 PM" src="https://user-images.githubusercontent.com/37240061/76625772-fa10f280-655d-11ea-90c1-5cdde2eba6de.png">
<img width="1680" alt="Screenshot 2020-03-13 at 6 51 42 PM" src="https://user-images.githubusercontent.com/37240061/76625782-fbdab600-655d-11ea-87d6-fffa85e7f11d.png">

**Comment by bogdan-getstream** [comment]
Hi @shireeshMs 
We are sending push notifications only to offline devices. If your user is connected we are sending websocket notification instead.
Also you can check push logs in dashboard.
What's your app id?

**Comment by buh** [comment]
iOS SDK Client will try to keep the connection in the background for about 1 min, then disconnect and you should get push notifications and while your app in the background you have to setup Notifications. Please check this doc: https://github.com/GetStream/stream-chat-swift/wiki/Push-Notifications

**Comment by bogdan-getstream** [comment]
I see your device was added successfully for user 

```
user@laptop ~ % stream chat:push:device:get
✔ What is the User ID? · 1016
┌──────────────────────────────────────────────────────────────────┬───────────────┐
│ Device ID                                                        │ Push provider │
├──────────────────────────────────────────────────────────────────┼───────────────┤
│ 1f5ae00031c4c6705375dbd54b0e4c190fc8666c68fba0ea5bab13ec2ca27160 │ apn           │
└──────────────────────────────────────────────────────────────────┴───────────────┘
```

Can you provide more details about your issue?
