### ISSUE TITLE
Video messages not loading

### ISSUE THREAD

**Issue by kcollignon** [GetStream/stream-chat-swift#1173]
## What did you do?
Used the web React SDK to drag and drop a video clip in to a channel and sent

## What did you expect to happen?
The embedded video to load on the app

## What happened instead?
It inserted a timestamp immediately but no video was shown. It was an empty message

## GetStream Environment
**GetStream Chat version:** 4.0-beta.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 14.6
**Swift version:**
**Xcode version:** 12.4
**Device:** iPhone Xr

## Additional context

![CleanShot 2021-06-09 at 22 24 10@2x](https://user-images.githubusercontent.com/489403/121469808-0149ca80-c972-11eb-9380-9ec4cc349cfb.png)

**Comment by b-onc** [comment]
Hello @kcollignon 
This is known, video attachments are not supported yet. They'll be supported in the next release.

**Comment by leojkwan** [comment]
@b-onc when you say next release, is that 4.0?

**Comment by kcollignon** [comment]
Hi @b-onc can you provide a little more clarity about which release you anticipate this feature being available? It's a rather important one I would imagine for users. Thank you!

**Comment by b-onc** [comment]
Hello @leojkwan @kcollignon 
Video attachments will be supported in the 4.0-RC release, which will be our next release. A draft PR for this feature will be opened today!

**Comment by VojtaStavik** [comment]
The support for this has been merged to `main` and will be available in the next release planned for this week.

**Comment by b-onc** [comment]
Video attachments support was released in 4.0.0-beta.4

**Comment by kcollignon** [comment]
Hi @b-onc do you know if anything special still needs to happen to get video attachments to work? I simulated the previous example, dragging a video from the desktop ReactJS version, and it looks like the timestamp shows on iOS but the video is not shown? This is on v 4.0beta7

<img width="1539" alt="CleanShot 2021-07-21 at 23 52 55@2x" src="https://user-images.githubusercontent.com/489403/126600104-27c33102-c003-47d6-9de5-fd4a91bb7008.png">
