### ISSUE TITLE
Message input area keeps disappearing 

### ISSUE THREAD

**Issue by ronnieguha** [GetStream/stream-chat-swift#118]
## What did you do?
Chat as usual...

## What did you expect to happen?
Message input box in chat to not disappear .

## What happened instead?

Input box disappears while typing. So you cannot send the message because the send button is not accessible.

If you scroll up and see message history, at some point, the message input area will reappear. That’s when the send button also shows up. Now you can send the message. 

But after sending the message, the input box will hide behind the keyboard again.

Now, go back to recent chat and come back, things might work properly again 

## GetStream Environment
**GetStream Chat version:**
1.5.7
**iOS version:**
13.3.1
**Swift version:**
5
**Xcode version:**
11.3.1
**Device:**
IPhone X

**Comment by b-onc** [comment]
Hello @ronnieguha ,

Can you provide a sample project, and/or video of this issue?

**Comment by ronnieguha** [comment]
@b-onc 
I tried looking at the bugsee video, but it blocks that time period when the input box hides.
I am going to try and send you a video from the phone directly

**Comment by ronnieguha** [comment]
try this please. after you confirm seeing this, I will delete it.
https://app.bugsee.com/#/issue/bcba68c7d04645aba368b4e484384383

**Comment by b-onc** [comment]
Hello @ronnieguha ,

Thanks for the videos, I can easily reproduce the issues.
It seems that there are 2 cases:
1. App is sent to background while keyboard is visible - upon returning to foreground, message input area disappears
2. Upon returning from a thread when keyboard is visible, message input area disappears

After testing in release/2.0 branch I can say that 2 is fully resolved and we have some progress on 1. We'll make sure this is resolved for 2.0 release, which is aimed for this week or next week.

**Comment by ronnieguha** [comment]
@b-onc ok the biggest one is while you’re typing and are in the thread itself.. sometimes I rush to type cos I’m scared that the input box would disappear (actually, a lot)

**Comment by ronnieguha** [comment]
@b-onc here’s the example of how it disappears while chatting https://app.bugsee.com/#/issue/f414b1f8536a4ff5a98486e82336a98f

**Comment by b-onc** [comment]
@ronnieguha Can you please check/test the PR and see if it resolves your issue? My testing shows that it's ok.

**Comment by ronnieguha** [comment]
Closing issue based on chatting for 1 day.. If it appears again, I will reopen. THANK YOU. You guys are the best.. ever.
