### ISSUE TITLE
SDK v4 Beta - Push Notifications

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1186]
As mentioned in: https://github.com/GetStream/stream-chat-swift/issues/1041#issuecomment-860663611
Can you confirm that push notifications are not expected to work yet with V4 Beta SDK? I see this note in the docs:
`The iOS SDK v3 beta does not yet fully support Notifications. Stay tuned.`

Note: I am able to successfully get a push notification delivered with the Stream V2 SDK. I think this confirms that my Stream Dashboard push notification configuration is correct.

## What did you do?
Tried to trigger a push notification using latest V4 Beta SDK

## What did you expect to happen?
Push Notification to be successfully delivered to device.

## What happened instead?
I got this error from V4 SDK: `publishing the message failed. code = "400"; error = "BadDeviceToken"; device is disabled`

## GetStream Environment
**GetStream Chat version:**
4.0.0-beta.2
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**Comment by b-onc** [comment]
Hello @srgray 

Thanks for the report. Just to double check, you're calling
```swift
chatClient.currentUserController().addDevice(token)
```
right?

**Comment by srgray** [comment]
Correct

**Comment by b-onc** [comment]
Hello @srgray 

We've checked this but it seems iOS SDK is working, the issue must lie somewhere in the configuration. 
This happens when device token and APN certificate are not from the same type of distribution (eg device token is from development mode and certficiate is a production one, or vice versa)

Please try to follow the configuration guide [here](https://getstream.io/chat/docs/ios-swift/push_ios/?language=swift) from scratch.

**Comment by srgray** [comment]
Ah, yes, indeed this was a configuration error on my part. It was a mismatch between development vs production. Thank you for looking into this!

**Comment by leojkwan** [comment]
@srgray I'm running into this problem as well— super frustrating how unintuitive integrating push is. Any help? Thanks.

**Comment by leojkwan** [comment]
Follow up: I finally got a push notification working by setting the "Development" toggle on Stream Chat dashboard to true, I think?

I'm noticing other folks in the issues reporting ` publishing the message failed. code = "400"; error = "BadDeviceToken"; device is disabled`, butI followed the instructions on https://getstream.io/chat/docs/ios-swift/push_ios/ pretty exactly.

I am certain I registered my APNS certificate as a production app. I'm running my project in debug production (production keys with debug build configs). Did not work.

<img width="175" alt="Screen Shot 2021-07-16 at 1 14 18 AM" src="https://user-images.githubusercontent.com/10264891/125895722-ab023117-3a67-421a-9c4e-1fc57bd2222e.png">

What doesn't make sense to me is the CLI instruction to push my .p8 token. I made sure I set production to true.

<img width="524" alt="Screen Shot 2021-07-16 at 1 14 34 AM" src="https://user-images.githubusercontent.com/10264891/125895955-4769eb48-c3b0-49c8-aef9-a601089403f0.png">

Any ideas here? I viewed my release entitlements file and apt-environment is set to production:

```
<dict>
	<key>aps-environment</key>
	<string>production</string>
</dict>
```

What could I be missing?

**Comment by srgray** [comment]
@leojkwan Yes, can confirm that setting the Stream Dashboard `Development` toggle to on/green means that you want to run against Apple's Development/Sandbox APNS environment. 
I'm not familiar with how to configure to run the app from Xcode and against Production APNS. I've only ever run my Xcode app against Development APNS. When we push our builds to TestFlight, those builds run against Production APNS.

**Comment by SagarSDagdu** [comment]
@leojkwan `Production` in terms of APNS environment means the build that is either signed with AdHoc / AppStore certificates when the app is archived and exported.
Generally, when running the app from Xcode, it is always a development build and it uses development (Sandbox) APNS

**Comment by leojkwan** [comment]
Thanks @SagarSDagdu & @srgray . I'm going to build for TestFlight and follow up.

What led me to think otherwise with the toggle was another toggle's logic. 'Disable Permission Checks' is set to true, but the control is disabled with a contradictory popover. 

![Screen Shot 2021-07-16 at 9 04 06 AM](https://user-images.githubusercontent.com/10264891/125952273-cddaaf9d-7d72-4a80-ac94-a6bc1ee546f5.png)
