### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#12]
## What did you do?

I'm closing one ChatViewController (this bug doesn't happen on first entrance to ChatViewController). Later I'm creating new instance and I do following configurations:
- I set `Client.shared.setUser`
- I create `ChannelPresenter`
- I add `Client` observations (onEvent)

If I do everything before websocket receives event `message` ChatViewController is stuck and messages will never be downloaded

## GetStream Environment
I've created commit to reproduce this issue:

https://github.com/GetStream/stream-chat-swift/commit/f3f201a48703cd643f7d735b6397b3164b3f9ae7

Note: I added delay to websocket response. I need it to reproduce issue on example app but it happens on my app without this delay.

## Additional context

I did some investigation and framework's state looks like this:
- `Websocket.isConnected == false` (lastConnectionId is nil)
- `Websocket.Connection == .connected`
- https://github.com/GetStream/stream-chat-swift/blob/master/Sources/Core/Client/WebSocket/WebSocket.swift#L272 this extension passes all requests through
- each request fails here: https://github.com/GetStream/stream-chat-swift/blob/master/Sources/Core/Client/Client%2BRequest.swift#L100
- 3 retries of requests are used before websocket event is received
- after receiving websocket event nothing happens

As a side note I've fixed my app by adding observation for event `.newMessages` only once before setting user but I'm worried this race condition may show up in different situation.

**Comment by buh** [comment]
Thanks! I'll check.

**Comment by buh** [comment]
Hi @mpodeszwa is it still a case for you with the latest version?

**Comment by mpodeszwa** [comment]
Hi @buh , it doesn't happen in my app right now

**Comment by buh** [comment]
Thanks @mpodeszwa, it was a lot of fixes since that release. I close the ticket, but will keep an eye on the case.
