### ISSUE TITLE
Sending empty message for extra data types

### ISSUE THREAD

**Issue by MuseerAnsari** [GetStream/stream-chat-swift#1221]
## What did you do?
Create ChatMessageListVC with custom data type to render Custom Card type into collection cells

```
typealias CustomExtraDataTypes = MyCustomExtraData
typealias ChatMessageListVC = _ChatMessageListVC<CustomExtraDataTypes>
typealias ChatClient = _ChatClient<CustomExtraDataTypes>
typealias ChatChannelController = _ChatChannelController<CustomExtraDataTypes>
typealias TokenProvider = _TokenProvider<CustomExtraDataTypes>
typealias ComposerVC = _ComposerVC<CustomExtraDataTypes>
```

And override cellForItem for collection view 
 
```
class MakerGroupViewController: ChatMessageListVC {

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        registerViews()
    } 

    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let message = channelController.messages[indexPath.row]
        print("(message.type ...\(message.extraData.messageType ?? "")")
        
        if message.extraData.messageType == MessageType.productBroadcast.rawValue {
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "MakerProductBroadcastCollectionViewCell", for: indexPath) as! MakerProductBroadcastCollectionViewCell
            cell.setupCellWithMessage(message: message)
            return cell
        } else {
            let cell: _СhatMessageCollectionViewCell<CustomExtraDataTypes> = self.collectionView.dequeueReusableCell(
                contentViewClass: cellContentClassForMessage(at: indexPath),
                attachmentViewInjectorType: attachmentViewInjectorClassForMessage(at: indexPath),
                layoutOptions: cellLayoutOptionsForMessage(at: indexPath),
                for: indexPath
            )
            cell.messageContentView?.delegate = self
            cell.messageContentView?.content = message
            return cell
        }
    }
}
```

## What did you expect to happen?
It should render custom card based on condition that seems working fine.
And i tried to send a message via message composer. it should send message

## What happened instead?
 But when i tried to send message via composer it's always sending a empty message 

## GetStream Environment
**GetStream Chat version:** 4.0-beta.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 14.4 
**Swift version:** 5
**Xcode version:** 12.4 
**Device:** iPhone 12Pro max simulator 

## Additional context
Same happening while I am trying to send image as well. after uploading the image it's become empty
Please let me know if I am missing something 
Thank you 

https://user-images.githubusercontent.com/17614820/123512954-eda79f00-d6a7-11eb-9e7d-6a4fd79dcc2c.mp4

**Comment by VojtaStavik** [comment]
Hi @MuseerAnsari, thank you for reporting this.

It's hard to exactly know what's going on there without the details about `MakerProductBroadcastCollectionViewCell`. The cells are self-sizing, so it can be also just some autolayout issue.

However, rather than providing a custom cell, try to override `open func cellContentClassForMessage(at indexPath: IndexPath)` and return your custom `ChatMessageContentView` implementation there. The cell itself is only a container with almost no logic.

More info about customizing the content can be found [here](https://github.com/GetStream/stream-chat-swift/blob/main/docusaurus/docs/iOS/guides/working-with-messagelist-layout.md).

**Comment by Museer21** [comment]
Hi @VojtaStavik 
I remove MakerProductBroadcastCollectionViewCell from my code, still happening the same.
Seems this this is not because of custom cell but with ExtraDataType. `ComposerVC` is not able to sent extra data types messages and image

**Comment by VojtaStavik** [comment]
I see you also opened a support ticket. Can you please share there your Application KEY and the channel id of the channel from the video?

**Comment by VojtaStavik** [comment]
Closing this in favor do the support ticket.
