### ISSUE TITLE
Question: What is replacement for `Notifications.parseMessageReference` in v4

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1226]
What is a replacement for `Notifications.parseMessageReference` in v4? I am migrating our project from v2, and we have a custom notification handler for our internal notifications.

Until now we used `Notifications.parseMessageReference` to determine if notification is sent from GetStream, and then use the returned references to construct a message view and open it.

I can't find methods in the SDK or any docs to explain how this is to be done now.

**Comment by MatejBalantic** [comment]
For anyone else stumbling upon this: I've just copied over the code from v2 and that serves us well for our use case


```swift

import Foundation
import UserNotifications

class NotificationsParser {
    private enum NotificationUserInfoKeys: String {
        case channelId = "channel_id"
        case channelType = "channel_type"
        case messageId = "message_id"
    }

    func parse(notificationResponse: UNNotificationResponse) -> ChatMessageReference? {
        let userInfo = notificationResponse.notification.request.content.userInfo

        guard let channelId = userInfo[NotificationUserInfoKeys.channelId.rawValue] as? String,
              let messageId = userInfo[NotificationUserInfoKeys.messageId.rawValue] as? String else {
            return nil
        }

        return ChatMessageReference(channelId: channelId, messageId: messageId)
    }
}

```

**Comment by tbarbugli** [comment]
@MatejBalantic thank you for sharing your solution! I am going to keep this open until we have this documented in the migration guide or backported to v4
