### ISSUE TITLE
Question: What is the replacement for subscribing for new messages?

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1227]
I am migrating our project from v2 to v4.

Until now, we've had a setup where we used `Client.shared.subscribe` to subscribe to all `(event.type == .messageNew) || (event.type == .notificationMessageNew)`, and then issue a local push notification.

That allowed us to show a push notification when app was in the foreground, which is a requirement for us.

How do you propose I migrate this functionality over to v4?

**Comment by VojtaStavik** [comment]
This is not currently available in the current beta of 4.0 but it's planned for the first production release. Tracked internally as CIS-430.

**Comment by MatejBalantic** [comment]
I'd be happy to build this part myself, but I struggle to understand how to even subscribe to all events like I was able to in v2 with the `Client.shared.subscribe` ?

**Comment by VojtaStavik** [comment]
We were changing the structure of the events a bit and were not ready to make them publicly available yet. Let me bump the priority of this in our backlog so it's not a blocker for you.

**Comment by MatejBalantic** [comment]
Thanks. Another alternative would be to optionally offer server-initiated push notifications even when the client is connected, that would be a perfect situation for us. Sending local push is just a workaround around (IMHO) broken setup where push is only delivered when clients are disconnected.

**Comment by VojtaStavik** [comment]
This is not publicly configurable but it's possible to change it. If you open a support ticket with this request our backend team will take care of it.

---

btw: We're aware of this issue and the backend team is working on a new version of the push notification system that will work like this by default.

**Comment by kcollignon** [comment]
@VojtaStavik do you by chance have an updated timeline on CIS-430?  Being able to receive push notifications when app is till running either in the foreground or background of the phone would be super helpful!

**Comment by b-onc** [comment]
Hello @kcollignon ,

We're aiming to release #1266 soon which will allow observing MessageNew events, therefore providing a way to show local notifications.

**Comment by b-onc** [comment]
Hello @kcollignon @MatejBalantic 

4.0.0-beta.8 is released and it has #1266 , which allows subscribing to MessageNew event.
