### ISSUE TITLE
Comments and replies not showing in chronological order (IOS), see the screenshot for reference

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1231]
## What did you do?
   I have done a chat between two users, both are IOS devices.

## What did you expect to happen?
    Comments and replies should be  in chronological order
    
## What happened instead?
  Comments and replies not showing in chronological order

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
![Simulator Screen Shot - iPhone 12 - 2021-06-29 at 08 22 18](https://user-images.githubusercontent.com/78809766/123798372-1d77c200-d8b5-11eb-9204-6b87a5f52203.png)

**Comment by VojtaStavik** [comment]
Can you provide more info about how to reproduce this? A video would be helpful too.

**Comment by vineethnkforios** [comment]
I think it's just because of the time difference between the local machine system time and the server time.

**Comment by tbarbugli** [comment]
interesting problem and thank you for reporting this. @VojtaStavik do we set the message.created_at on core data using the device clock?

**Comment by VojtaStavik** [comment]
Thank you for the additional information. I can confirm this issue happens when the local time of the sender is not in sync with the server time. The incorrect order appears only for the sender, the receiver sees the message in the correct order.

Thank you for finding this edge case, it will addressed in the next release.
