### ISSUE TITLE
Unable to add multiple images in iOS , see the screenshot for your reference

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1232]
## What did you do?
Try to add multiple images in iOS, but unable to find an option, It was there in the older version, the android version as well.

## What did you expect to happen?

Expect a button to add multiple Images

## What happened instead?

The a
![Simulator Screen Shot - iPhone 12 - 2021-06-29 at 09 21 48](https://user-images.githubusercontent.com/78809766/123805994-86166d00-d8bc-11eb-8bff-68603c4a412d.png)
dd image button is disappeared after selecting one image 

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by VojtaStavik** [comment]
What version of the framework are you using?

**Comment by vineethnkforios** [comment]
I was using the version stream-chat-swift-4.0.0-beta.3 .

Today I checked on stream-chat-swift-4.0.0-beta.4 and seems working...

**Comment by b-onc** [comment]
Hello @vineethnkforios 

This was a regression introduced in beta.3 and was fixed in beta.4, thanks for confirming.
