### ISSUE TITLE
Does V4 support ChatMessageAttachment ExtraData?

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1234]
## What did you do?
I'm trying to access custom properties on an `Attachment`. In V2 SDK, I used `Attachment.extraDataType` to accomplish this. Does V4 SDK have that capability? Similar to `MessageExtraData` in V4?

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.4
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**Comment by VojtaStavik** [comment]
Hi @srgray. v4 has much more advanced and (I hope) better support for working with custom attachments. You can find more information about this topic in the WIP guide https://github.com/GetStream/stream-chat-swift/blob/main/docusaurus/docs/iOS/guides/working-with-attachments.md .

**Comment by srgray** [comment]
@VojtaStavik Thanks for the link to docs. Can you help clarify something for me?
We have a process which adds messages with attachments to Stream channels. Here is a snippet of how we do that:

```
const attachment = {
            type: mediaType,
            thumb_url: thumbnailUrl,
            cnMediaId: mediaId,
            cnComments: commentCount,
        }
        if (mediaType === 'image') attachment['image_url'] = url
        if (mediaType === 'video') attachment['video_url'] = url
        const message = {
            text: caption || '',
            user_id: userId,
            attachments: [attachment],
        }
```

What we want is a `video` or `image` attachment with 2 extra properties: `cnMediaId` and `cnComments`. After reading through those docs, I don't see how I can access those 2 extra properties with the Stream V4 SDK _unless_ I use a custom attachment type. Is that correct? We were hoping to use the standard attachment types of `video` and `image` and still be able to access those 2 extra properties.
