### ISSUE TITLE
Is there a way to display author name on a chat message ?

### ISSUE THREAD

**Issue by BarragaoA** [GetStream/stream-chat-swift#1242]
## What did you do?
I'm upgrading StreamChat from version 2.X to 3.1.11. 
I'm displaying a chat channel :
`let chatVC = ChatChannelVC()
chatVC.channelController = channelController`
Everything seems to work, but we do not really know who is chatting. We can only see the picture of the author and the hour.
![image](https://user-images.githubusercontent.com/86778557/124122891-e3eeb480-da76-11eb-9814-21e83f5641cb.png

## What did you expect to happen?
Is there a way to display the author name too ?
I see that it is possible to custom the view with the version 4 of the sdk but I do not really want to use a beta version. I'm asking if it is possible to do that with the version 3.

## GetStream Environment
**GetStream Chat version:** 3.1.11
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 14.4.2
**Swift version:** 5.0
**Xcode version:** 12.5.1
**Device:**  iPhone Xr

Thank you for your help.

**Comment by b-onc** [comment]
Hello @BarragaoA ,

v4 is actually very stable now, it's still in beta since we keep doing small changes to the API, but it's really robust and works well. I'd suggest you to upgrade directly to v4, then you'll get this feature for free.

Unfortunately it's not available in v3 and won't be.

**Comment by BarragaoA** [comment]
Ok thank you for your answer. I will look into upgrading to v4 👍
