### ISSUE TITLE
Is it possible to customize search filter in User Mention search function?

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1243]
## What did you do?
I would like to search against custom User properties in the `ComposerVC.showMentionUsers`. It seems as though the `ChatUserSearchController.search` method doesn't allow me to customize the `query.filter`. That is set to search against User fields `name` and `id`. How should I change that behavior to search against a different custom User property?

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.4
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**Comment by b-onc** [comment]
Hello @srgray ,

We have #1206 open for this purpose. It should be merged and released in the upcoming versions

**Comment by b-onc** [comment]
Hello,
4.0.0-beta.5 is released with a fix for this. Please re-open if you still see this issue happening.

**Comment by srgray** [comment]
@b-onc This is working great for me, thanks!
Follow up question: I see that #1206 also added a `contains` Filter. Can I now use `contains` as a replacement for my current use of `autocomplete`? I tried and it didn't seem to work but maybe I didn't understand that change.

Example: User.name = "Stephen Gray"
Currently, I'm using a search filter like this: `Filter.autocomplete(.name, text: "Steph")` and it returns that user.
Should I expect to be able to now use a filter like this: `Filter.contains(.name, value: "teph") and have it return that user?
