### ISSUE TITLE
avatarURL doesn't clear once set

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#125]
## What did you do?
Setup a user with a avatarURL, then on next run of the app set it to nil.  
When in the chat controller the user still has the Image that was originally set

## What did you expect to happen?
The avatar should be gone and back to Initials

## What happened instead?
The old image is still part of the User json coming back

## GetStream Environment
◾️ Stream-Auth-Type = jwt
◾️ X-Stream-App-Environment = development
◾️ X-Stream-OS = iOS13.2.2
◾️ X-Stream-Client = stream-chat-swift-client-1.6.1

**Comment by b-onc** [comment]
Hello @khoogheem ,
You should use `updateUser` to remove field. `setUser` will retrieve server data, so you can also pass `name: ""` and user name will not be reset. We're currently optimizing this in our 2.0 branch.

From our docs:
> For example, if you're looking to sync your user base, you'll want to use the updateUser(s) method instead. It will also remove fields from the user if you don't send them in this update call.

https://getstream.io/chat/docs/update_users/?language=swift

Let me know if this helps.
