### ISSUE TITLE
iOS extra data is nil.

### ISSUE THREAD

**Issue by zinminphyo** [GetStream/stream-chat-swift#1252]
## What did you do?
- We are developing messaging app and contain poll message feature.Get-stream don't provide poll message so we created a poll mutation to make a poll message.When create a poll mutation, we provided a channel id and other datas.When poll create is succeed, we can get back a new message event.We make a custom extra data type that is containing poll-id and other custom datas .We make a poll GraphQL mutation that is provided by our backends and new message event has reached.When print out message object from new message associated enum, extra data is nil.When we align with our backends developer, poll-id and other extra-data is sent to GetStream dashboard and android is also get back extra data when new message event is arrived but iOS don't get back extra data.And message id is also same with android, web and iOS.

## What did you expect to happen?
- To get back poll-id from extra-data.shared.poll-id.

## What happened instead?
- Get back extra-data is nil.

## GetStream Environment
**GetStream Chat version:** 2.6.3
**GetStream Chat frameworks:** StreamChatClient
**iOS version:** 14.2
**Swift version:** 5.3
**Xcode version:** 12.2
**Device:** iphone 12 pro max simulator

**Comment by b-onc** [comment]
Hello @zinminphyo ,

Can you provide the code snippet you're using to parse extraData? Also, can you enable and share logs for the said message?

**Comment by zinminphyo** [comment]
This is our poll create GraphQL mutation.When create poll is succeed, we will get back new message event.

func createPoll(model: CreatePollServiceModel, completion: @escaping Service.Completion<String>) -> Service.Cancellable {
        let mutation = CreatePollForChatMutation(channel_id: model.channelId, title: model.title, is_allow_option: model.isallowedOptions, options: model.options)
        let cancellable = Service.GraphQL.chat.perform(mutation: mutation, queue: .global()) { (r) in
            if case let .success(result) = r {
                DispatchQueue.main.async {
                    guard let id = result.data?.createPollForChat?.id else {return}
                    completion(.success(id))
                }
            }
            if case let .failure(error) = r {
                completion(.failure(error))
            }
        }
        return .init {
            cancellable.cancel()
        }
    }



We can get back new message event when poll message is success from Get-Stream event like this.

 override func received(_ event: Event) {
        // If the event received is the desired event,
        // dispatch event to delegate
        
        if case let .messageNew(message, _, _, cid, _) = event {
            var message = message
            let replyId = message.ygsExtraData?.shared.replyId
            // convert to YMessage here.
            if nil != replyId {
                self.fetchReplyAndSend(message, for: cid)
            } else {
                
                self.delegate?.chatEventListener(
                    self,
                    didReceive: YGSMessage(message),
                    for: cid
                )
            }
            
            /*
            if let filter = filterForCid, cid == filter {}
            else { }
            */
        }
    }




When print out this new message, i got this message object.

Message return from GetStream is Message(id: "66ef0803-e6d6-4360-9256-c9f478ccc059", type: StreamChatClient.MessageType.regular, user: StreamChatClient.User, channel: nil, created: 2021-07-05 10:09:16 +0000, updated: 2021-07-05 10:09:16 +0000, deleted: nil, text: "", command: nil, args: nil, attachments: [], parentId: nil, showReplyInChannel: false, mentionedUsers: [], replyCount: 0, extraData: nil, latestReactions: [], ownReactions: [], reactionScores: [:], isSilent: true, i18n: nil)


But when i log this same message at web, extra-data is get back.

**Comment by zinminphyo** [comment]
Hello @b-onc can you help me?We need to fix as urgent bug.

**Comment by b-onc** [comment]
Hello @zinminphyo ,

You have to register extraData so it works.

Step 1. Create your ExtraData struct as Codable
```swift
struct MessageExtraData: Codable {
    let yourPropertyHere: String
}
```
Step 2. Register your ExtraData type. Do this even before initializing Client.
```swift
Message.extraDataType = MessageExtraData.self
```
Step 3. Cast your extraData as your type.
```swift
if let extraData = message.extraData as? MessageExtraData {
  extraData.yourPropertyHere //you can access now
}
```

**Comment by zinminphyo** [comment]
I already did like that.

static func registerCustomExtraDataTypes() {
            // Register channel custom extra data type
            Channel.extraDataType = YGSChannelExtraData.self
            // Register message custom extra data type
            Message.extraDataType = YGSMessageExtraData.self
        }



and get extra data just like above @b-onc

**Comment by b-onc** [comment]
When/where are you calling this func?

**Comment by zinminphyo** [comment]
static func configure(apiKey: String) {
            
            let config = Client.Config(
                apiKey: apiKey,
                baseURL: .singapore,
                stayConnectedInBackground: true,
                callbackQueue: .global(),
                logOptions: []
            )
            
            // Configure appropiately for individual development trait.
            Client.configureShared(
                config
            )
            
            registerCustomExtraDataTypes()
        }
        
        static func registerCustomExtraDataTypes() {
            // Register channel custom extra data type
            Channel.extraDataType = YGSChannelExtraData.self
            // Register message custom extra data type
            Message.extraDataType = YGSMessageExtraData.self
        }


when initializes client

**Comment by b-onc** [comment]
Can you try calling this func before calling configureShared? Also, can you enable and paste all logs here. We should investigate the message payload.

**Comment by zinminphyo** [comment]
To log message payload from message new event?

**Comment by b-onc** [comment]
If you enable logs and visit the channel this is happening, that'd be enough.

**Comment by zinminphyo** [comment]
Here this is poll message payload when fetch from GetStream.


▿ 1 : Message
    - id : "66ef0803-e6d6-4360-9256-c9f478ccc059"
    - type : StreamChatClient.MessageType.regular
    ▿ user : <User: 0x600003efd740>
    - channel : nil
    ▿ created : 2021-07-05 10:09:16 +0000
      - timeIntervalSinceReferenceDate : 647172556.9360001
    ▿ updated : 2021-07-05 10:09:16 +0000
      - timeIntervalSinceReferenceDate : 647172556.9360001
    - deleted : nil
    - text : ""
    - command : nil
    - args : nil
    - attachments : 0 elements
    - parentId : nil
    - showReplyInChannel : false
    - mentionedUsers : 0 elements
    - replyCount : 0
    - extraData : nil
    - latestReactions : 0 elements
    - ownReactions : 0 elements
    - reactionScores : 0 elements
    - isSilent : true
    - i18n : nil




Here is link message 

Message
    - id : "5c8b0434-1901-465d-8683-7eddbea27989"
    - type : StreamChatClient.MessageType.regular
    ▿ user : <User: 0x600003efda40>
    - channel : nil
    ▿ created : 2021-07-06 06:42:42 +0000
      - timeIntervalSinceReferenceDate : 647246562.029
    ▿ updated : 2021-07-06 06:42:42 +0000
      - timeIntervalSinceReferenceDate : 647246562.029
    - deleted : nil
    - text : "https://social-uat.yomastrategic.com/posts/ec854c70-da56-11eb-88c1-454d241520b9/detail"
    - command : nil
    - args : nil
    ▿ attachments : 1 element
      ▿ 0 : Attachment
        - title : "Yoma Social"
        ▿ author : Optional<String>
          - some : "Yoma Social"
        - text : nil
        - type : StreamChatClient.AttachmentType.link
        - actions : 0 elements
        ▿ url : Optional<URL>
          ▿ some : https://social-uat.yomastrategic.com/posts/ec854c70-da56-11eb-88c1-454d241520b9/detail
            - _url : https://social-uat.yomastrategic.com/posts/ec854c70-da56-11eb-88c1-454d241520b9/detail
        - imageURL : nil
        - file : nil
        - extraData : nil
    - parentId : nil
    - showReplyInChannel : false
    - mentionedUsers : 0 elements
    - replyCount : 0
    ▿ extraData : Optional<Decodable & Encodable>
      ▿ some : YGSMessageExtraData
        - typeString : ""
        - type : YomaChat.YGSMessageExtraData.ExtraDataType.unknown
        ▿ shared : SharedData
          - replyId : nil
          - pollId : nil
          - attachments : 0 elements
          - attachmentCount : 0
          - type : YomaChat.YMessageContentType.text
          - explicitMention : YomaChat.YGSMessageExplictMention.none
          - removedForSelfByIDs : 0 elements
          - savedForSelfByIDs : 0 elements
          - isRemovedForSelf : false
          - isSavedForSelf : false
          - isForwarded : false
        - memberAdd : nil
        - memberRemove : nil
        - adminPromote : nil
        - adminDemote : nil
        - channelChanges : nil
        - voIP : nil
        ▿ iosPrivateData : Optional<iOSPrivateData>
          ▿ some : iOSPrivateData
            ▿ tid : Optional<UUID>
              - some : 6579CD53-E965-4636-9E46-094C182A4F74
    - latestReactions : 0 elements
    - ownReactions : 0 elements
    - reactionScores : 0 elements
    - isSilent : false
    - i18n : nil

**Comment by zinminphyo** [comment]
@b-onc how to solve this issue?

**Comment by b-onc** [comment]
Hello @zinminphyo ,

I need to see what backend sends, not the message from iOS SDK. Can you enable the logs and paste them here? The logs will print out the raw payload from backend.

Also, can you share your `YGSChannelExtraData` too?

**Comment by zinminphyo** [comment]
Hello @b-onc it is message sent from our backends to GetStream.

$message = [
            'extraData' => [
                'type' => 'system_chat_poll',
                'shared' => [
                    'type' => 7,
                    'poll_id' => $chatPoll['id'],
                ],
                'data' => [
                    'subject' => [
                        'member_id' => auth()->id(),
                        'name' => auth()->user()->name,
                    ],
                ]
            ],
            'silent' => true,
        ];

**Comment by zinminphyo** [comment]
Here is YGSChannelExtraData
/// Custom extra data representation of the channel.
struct YGSChannelExtraData: ChannelExtraDataCodable {
    
    /// Default name of the channel
    /// as required by the codable protocol.
    var name: String?
    
    /// Default image url of the channel
    /// as required by the codable protocol.
    var imageURL: URL?
    
    /// Textual representation of the channel description.
    var textDescription: String?
    
    var readOnlyAttributes: ReadOnlyAttributes?
    
    
    func encode(to encoder: Encoder) throws {
        // Does not support encoding for now (it's ok not to)
        // because we are not going to send the whole channel to the
        // get stream.
    }
    
    init(from decoder: Decoder) throws {
        
        let bag = try decoder.container(keyedBy: CodingKeys.self)
        name = try bag.decodeIfPresent(
            String.self, forKey: .name
        )
        imageURL = try bag.decodeIfPresent(
            URL.self, forKey: .imageURL
        )
        
        let extraData = try? bag.nestedContainer(
            keyedBy: ExtraKeys.self,
            forKey: .extraData
        )
        
        textDescription = try extraData?.decodeIfPresent(
            String.self, forKey: .textDescription
        )
        
        readOnlyAttributes = try? extraData?.decode(
            ReadOnlyAttributes.self,
            forKey: .readOnlyAttributes
        )
        
    }
}

extension YGSChannelExtraData {
    
    enum CodingKeys: String, CodingKey {
        
        // default requirement.
        //
        // # Important
        // dont delete 'name' and 'imageURL'
        // or your life is fucked up, lose your job
        // for no reason and wonder around until you die.
        //
        case name
        case imageURL = "image"
        
        case extraData
        
        case textDescription = "description"
        case readOnlyAttributes = "read_only"
    }
    
    enum ExtraKeys: String, CodingKey {
        case textDescription = "description"
        case readOnlyAttributes = "read_only"
    }
}

**Comment by zinminphyo** [comment]
@b-onc hello bro any update for issue?

**Comment by zinminphyo** [comment]
hello bro @b-onc  any update for this issue?

**Comment by b-onc** [comment]
Hello @zinminphyo ,

Thanks for providing the info. 
Your backend sends extraData fields `type`, `shared`, and `data` but you're decoding `description` and `read_only`. These fields are not in the message response you're showing in the object.

Also, can you enable the logs and share them here? You can enable logs in `ClientConfig` by setting `logOptions: .info`, like:
```swift
 let config = Client.Config(apiKey: apiKey, baseURL: .usEast, logOptions: .info)
```

Please enable logs, receive a message with extraData in it, and paste all the logs from console to here. The console output will include Stream backend response for the message, and it'll clarify this issue.

**Comment by zinminphyo** [comment]
Hello @b-onc 
When I log poll message here is output.


[05 Aug 12:50:34.677] [DEBUG] 📦  {
  "user" : {
    "banned" : false,
    "id" : "systemUser",
    "updated_at" : "2020-09-07T10:45:33.852848Z",
    "online" : false,
    "role" : "user",
    "created_at" : "2020-09-07T10:45:33.851875Z"
  },
  "watcher_count" : 1,
  "channel_type" : "messaging",
  "channel_id" : "!members-C9mFqNlFvn4VQ1FMCpmuVgFnhjCGHKZOqxO6OWBcLLk",
  "created_at" : "2021-08-05T06:20:34.499917995Z",
  "total_unread_count" : 5,
  "message" : {
    "updated_at" : "2021-08-05T06:20:34.494276Z",
    "reply_count" : 0,
    "html" : "",
    "type" : "regular",
    "own_reactions" : [

    ],
    "cid" : "messaging:!members-C9mFqNlFvn4VQ1FMCpmuVgFnhjCGHKZOqxO6OWBcLLk",
    "id" : "c70b8d2c-a2ee-40c8-a382-d74c1c276cf0",
    "user" : {
      "banned" : false,
      "id" : "systemUser",
      "updated_at" : "2020-09-07T10:45:33.852848Z",
      "online" : false,
      "role" : "user",
      "created_at" : "2020-09-07T10:45:33.851875Z"
    },
    "shadowed" : false,
    "pinned_at" : null,
    "pin_expires" : null,
    "attachments" : [

    ],
    "reaction_counts" : null,
    "reaction_scores" : {

    },
    "silent" : true,
    "text" : "",
    "pinned_by" : null,
    "extraData" : {
      "type" : "system_chat_poll",
      "data" : {
        "subject" : {
          "member_id" : "3949f210-0854-11eb-9d41-0180b0d6c0dc",
          "name" : "tHA One"
        }
      },
      "shared" : {
        "poll_id" : "3e078790-f5b5-11eb-9173-87f9d3d91572",
        "type" : 7
      }
    },
    "created_at" : "2021-08-05T06:20:34.494276Z",
    "mentioned_users" : [

    ],
    "pinned" : false,
    "latest_reactions" : [

    ]
  },
  "unread_count" : 5,
  "unread_channels" : 3,
  "type" : "message.new",
  "cid" : "messaging:!members-C9mFqNlFvn4VQ1FMCpmuVgFnhjCGHKZOqxO6OWBcLLk"
}



But when i print new message event message object, message id is same but other data is nil.
Message(id: "c70b8d2c-a2ee-40c8-a382-d74c1c276cf0", type: StreamChatClient.MessageType.regular, user: StreamChatClient.User, channel: nil, created: 2021-08-05 06:20:34 +0000, updated: 2021-08-05 06:20:34 +0000, deleted: nil, text: "", command: nil, args: nil, attachments: [], parentId: nil, showReplyInChannel: false, mentionedUsers: [], replyCount: 0, extraData: nil, latestReactions: [], ownReactions: [], reactionScores: [:], isSilent: true, i18n: nil)



This is message new event.

if case let .messageNew(message, _, _, cid, _) = event {
var message = message
print("Message from get stream new event is \(message)")

**Comment by zinminphyo** [comment]
@b-onc  any update?

**Comment by b-onc** [comment]
Hello @zinminphyo 

I see that your extraData is encoded as:
```
"extraData" : {
      "type" : "system_chat_poll",
      "data" : {
        "subject" : {
          "member_id" : "3949f210-0854-11eb-9d41-0180b0d6c0dc",
          "name" : "tHA One"
        }
      },
      "shared" : {
        "poll_id" : "3e078790-f5b5-11eb-9173-87f9d3d91572",
        "type" : 7
      }
```

Can you share your `YGSMessageExtraData` struct?

**Comment by zinminphyo** [comment]
struct YGSMessageExtraData: Codable {
    
    /// Type of the extra data
    var typeString: String = ""
    var type: ExtraDataType = .unknown
    
    var shared = SharedData()
    
    var memberAdd: SystemMemberAdd?
    var memberRemove: SystemMemberRemove?
    var adminPromote: SystemAdminPromote?
    var adminDemote: SystemAdminDemote?
    var channelChanges: ChannelChanges?
    
    var voIP: VoIPExtraInfoData?
    
    /// Private ios data structure
    var iosPrivateData: iOSPrivateData?
    
    init() { }
    
    init(from decoder: Decoder) throws {
        
        let container = try decoder.container(keyedBy: BaseKey.self)
        
        let extraDataContainer = try? container.nestedContainer(
            keyedBy: ExtraDataKeys.self, forKey: .extraData
        )
        
        // decode the type
        type = try extraDataContainer?.decodeIfPresent(
            ExtraDataType.self, forKey: .type
        ) ?? .unknown
        
        typeString = try extraDataContainer?.decodeIfPresent(
            String.self, forKey: .type
        ) ?? ""
        
        shared = try extraDataContainer?.decodeIfPresent(
            SharedData.self, forKey: .shared
        ) ?? .init()
        
        iosPrivateData = try? extraDataContainer?.decodeIfPresent(
            iOSPrivateData.self, forKey: .iosPrivateData
        )
        
        if type == .systemMemberAdd {
            memberAdd = try extraDataContainer?.decodeIfPresent(
                SystemMemberAdd.self,
                forKey: .data
            )
        }
        
        if type == .systemMemberRemove {
            memberRemove = try extraDataContainer?.decodeIfPresent(
                SystemMemberRemove.self,
                forKey: .data
            )
        }
        
        if type == .systemAdminDemote {
            adminDemote = try extraDataContainer?.decodeIfPresent(
                SystemAdminDemote.self,
                forKey: .data
            )
        }
        
        if type == .systemAdminPromote {
            adminPromote = try extraDataContainer?.decodeIfPresent(
                SystemAdminPromote.self,
                forKey: .data
            )
        }
        
        let groupEdits = Set<ExtraDataType>([
            .systemGroupNameEdit,
            .systemGroupNameRemove,
            .systemGroupPhotoEdit,
            .systemGroupPhotoRemove,
            .systemGroupDescriptionEdit,
            .systemGroupDescriptionRemove,
            .systemGroupLeave,
            .systemGroupCreate,
        ])
        if groupEdits.contains(type) {
            channelChanges = try extraDataContainer?.decodeIfPresent(
                ChannelChanges.self, forKey: .data
            )
        }
        
        let callTypes = Set<ExtraDataType>([
            .callStart, .callEnd, .callJoin, .callLeft, .callMiss
        ])
        if callTypes.contains(type) {
            voIP = try extraDataContainer?.decodeIfPresent(
                VoIPExtraInfoData.self, forKey: .data
            )
        }
    }
    
    func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: BaseKey.self)
        
        var nested = container.nestedContainer(
            keyedBy: ExtraDataKeys.self,
            forKey: .extraData
        )
        
        try nested.encode(shared, forKey: .shared)
        
        try nested.encodeIfPresent(type, forKey: .type)
        
        try nested.encodeIfPresent(memberAdd, forKey: .data)
        try nested.encodeIfPresent(memberRemove, forKey: .data)
        
        try nested.encodeIfPresent(adminPromote, forKey: .data)
        try nested.encodeIfPresent(adminDemote, forKey: .data)
        
        try nested.encodeIfPresent(channelChanges, forKey: .data)
        
        // Decode iOSPrivateData only if it's not empty.
        try nested.encodeIfPresent(
            iosPrivateData, forKey: .iosPrivateData
        )
        
    }
}





extension YGSMessageExtraData {
    
    enum BaseKey: String, CodingKey {
        case extraData
        case type
    }
    
    enum ExtraDataKeys: String, CodingKey {
        case type
        case shared
        case data
        case iosPrivateData = "_ios"
    }
}




Here is shared data.

extension YGSMessageExtraData {
    
    struct SharedData: Codable {
        
        // MARK: Properties
        ///
        /// # Serialized
        /// Yes
        ///
        var replyId: String?
        
        // MARK: Properties
        ///
        /// # Serialized
        /// Yes
        ///
        var pollId: String?
        
        ///
        /// # Serialized
        /// Yes
        ///
        var attachments = [YGSAttachmentItem]()
        
        ///
        /// # Serialized
        /// Yes
        ///
        var attachmentCount: Int = 0
        
        ///
        /// # Serialized
        /// Yes
        ///
        var type: YMessageContentType = .text
        
        
        // MARK:- @property Feature: Mention All
        /// Explict mentions.
        /// This can be `@all`, `@here` or `@anything` in the future.
        ///
        /// Currently there is only `@everyone`.
        ///
        /// # Serialized
        /// Yes
        ///
        var explicitMention = YGSMessageExplictMention.none
        // MARK:-
        
        // MARK:- @property - Feature: Remove for only me
        /// IDs of users who deleted this message one sided(for their side only).
        ///
        /// Current user id containing in the array means,
        /// current user deleted this message for its self.
        ///
        /// # Serialized
        /// Yes
        ///
        var removedForSelfByIDs = [String]()
        
        
        var savedForSelfByIDs = [String]()
        
        /// Indicate whether the message is removed only for self (one side delete).
        ///
        /// This is meant to be a computed  property which is computed right after decoding process.
        /// Being `var` is for convenience.
        ///
        /// # Serialized
        /// No
        ///
        var isRemovedForSelf = false
        
        
        
        var isSavedForSelf = false
        // MARK:-
        
        
        /// Indicate if the message is forwarded.
        ///
        /// # Serialized
        /// Yes
        var isForwarded = false
        
        // MARK:- Initializers
        init() { }
        
        init(from decoder: Decoder) throws {
            
            let container = try? decoder.container(
                keyedBy: CodingKeys.self
            )
            
            replyId = try container?.decodeIfPresent(
                String.self, forKey: .replyId
            )
            
            pollId = try container?.decodeIfPresent(
                String.self, forKey: .pollId
            )
            
            attachments = (try? container?.decodeIfPresent(
                [YGSAttachmentItem].self, forKey: .attachments
            )) ?? []
            
            type = (try? container?.decodeIfPresent(
                YMessageContentType.self, forKey: .type
            )) ?? .text
            
            attachmentCount = try container?.decodeIfPresent(
                Int.self, forKey: .attachmentCount
            ) ?? 0
            
            try decodeMention(from: container)
            try? decodePartialDelete(from: container)
            
            isForwarded = try container?.decodeIfPresent(
                Bool.self, forKey: .isForwarded
            ) ?? false
            
            try? decodePartialSave(from: container)
            
        }
        // MARK:-
        
        
        
        // MARK:- @Function - Feature: Mention All
        private mutating func decodeMention(
            from container: KeyedDecodingContainer<Self.CodingKeys>?
        ) throws {
            /* Parse explict mention */
            explicitMention = try container?.decodeIfPresent(
                YGSMessageExplictMention.self, forKey: .explictMention
            ) ?? .none
        }
        // MARK:-
        
        
        
        // MARK:- @Function - Feature: Remove for only me
        private mutating func decodePartialDelete(
            from container: KeyedDecodingContainer<Self.CodingKeys>?
        ) throws {
            // parse the removers
            removedForSelfByIDs = try container?.decodeIfPresent(
                [String].self, forKey: .removedForSelfByIDs
            ) ?? []
            
            // compute if current user is in the array.
            // true means the user has deleted the message one side.
            isRemovedForSelf = removedForSelfByIDs.contains(Client.shared.user.id)
        }
        
        
        // MARK:- @Function - Feature: Save for only me
        private mutating func decodePartialSave(
            from container: KeyedDecodingContainer<Self.CodingKeys>?
        ) throws {
            savedForSelfByIDs = try container?.decodeIfPresent(
                [String].self, forKey: .savedForSelfByIDs) ?? []
            
            isSavedForSelf = savedForSelfByIDs.contains(Client.shared.user.id)
        }
    }
}



// MARK:- Encodable Conformance
extension YGSMessageExtraData.SharedData {
    
    func encode(to encoder: Encoder) throws {
        
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        try container.encodeIfPresent(
            replyId, forKey: .replyId
        )
        
        try container.encode(
            attachments, forKey: .attachments
        )
        
        try container.encode(
            type, forKey: .type
        )
        
        try container.encode(
            attachmentCount, forKey: .attachmentCount
        )
        
        try container.encode(
            explicitMention, forKey: .explictMention
        )
        
        // encode array of ids of removers
        try container.encode(
            removedForSelfByIDs, forKey: .removedForSelfByIDs
        )
        
        try container.encode(
            isForwarded, forKey: .isForwarded
        )
        
        print("Encoding ok")
    }
}




extension YGSMessageExtraData.SharedData {
    
    enum CodingKeys: String, CodingKey {
        
        case type = "type"
        
        case replyId = "reply_id"
        
        case attachments = "attachments"
        case attachmentCount = "att_count"
        
        /// Key for custom mentions like `@everyone`, `@here` or `@all`.
        ///
        /// Value type is expected to be `String`.
        ///
        case explictMention = "mentioned_users"
        
        /// Key for `deleted user ids of the message`.
        ///
        /// Value type is expected to be `[String]`.
        ///
        case removedForSelfByIDs = "deleted_user_ids"
        
        /// Key for `saved user ids of the message`.
        ///
        /// Value type is expected to be `[String]`.
        ///
        case savedForSelfByIDs = "saved_user_ids"
        
        /// Key for forwarded status.
        ///
        /// Value type is expected to be `Boolean`
        case isForwarded = "is_forward"
        
        
        case pollId = "poll_id"
    }
    
}

**Comment by HninKhine** [comment]
@b-onc Hello, I'm PM of the project using Feed and we are subscribing Feed Growth Plan. Our developer @zinminphyo had provided the requirement to track about poll id. Can we get the update ASAP?  It's urgent.

**Comment by HninKhine** [comment]
@b-onc  Any update please?

**Comment by shodgetts** [comment]
Hello @HninKhine , we're doing out best to find you resources here. @b-onc is on vacation right now and we're looking for another engineer to catch up on this issue. Thank you for your patience

**Comment by b-onc** [comment]
Hello @zinminphyo ,

Your extraData is encoded only in key `extraData` but you're trying to decode:
```swift
enum BaseKey: String, CodingKey {
        case extraData
        case type
    }
```
but there's no `type` in root object. You should remove `type` from `BaseKeys`.

A bigger problem is, the extraData type `"type" : "system_chat_poll",` does not have a corresponding `data` parsing logic. You're parsing `data` for these `type` values:
- systemMemberAdd
- systemMemberRemove
- systemAdminDemote
- systemAdminPromote
- .systemGroupNameEdit,
            .systemGroupNameRemove,
            .systemGroupPhotoEdit,
            .systemGroupPhotoRemove,
            .systemGroupDescriptionEdit,
            .systemGroupDescriptionRemove,
            .systemGroupLeave,
            .systemGroupCreate,
- .callStart, .callEnd, .callJoin, .callLeft, .callMiss

I guess your enum for `system_chat_poll` would at least include the word "Poll", and that's missing from the possible `type` values.

Overall, I'm pretty sure there's something wrong with your Codable logic. The SDK fails the parse your `extraData` and it returns `nil`. You should carefully debug your extraData decoding logic.

**Comment by zinminphyo** [comment]
hello @b-onc this is our Codable logic error.We can close this issue.Thanks a lot.
