### ISSUE TITLE
4.0.0-beta.5 TokenProvider parameter 'completion' is implicitly non-escaping

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1255]
It's not possible to use the TokenProvider as documented in the `changelog.md`, due to `TokenProvider`'s `completion` parameter being non-escaping.

You need to mark it escaping, otherwise this kind of code can't compile:

```swift
client.tokenProvider = { completion in
  service.fetchToken { token in
    completion(token) // <<<<<<<<<<<<<<<< Escaping closure captures non-escaping parameter 'completion'
  }
}
```

**Comment by b-onc** [comment]
Hello @MatejBalantic ,

Thanks for the quick heads up! We've re-released beta.5 with this fixed. If you update your cocoapods trunk (invalidating the cache), it should use the new tag position, and should include the fix now.

**Comment by MatejBalantic** [comment]
Thanks so much for a super quick reaction, I can confirm this is now fixed. I needed some time to figure out where the SPM cache is located, nuking the ` ~/Library/Caches/org.swift.swiftpm/` helped.

Can I also sincerely ask you to next time release a different tag/version, because this kind of tag force pushes already caused a major disruption for us once on another dependency. It's really important for us that versions are reproducible between different CI and dev machines, and permanently immutable. 

This time it didn't cause any issues (for us), but it might in the future.

**Comment by b-onc** [comment]
Hello @MatejBalantic ,

Thanks for the feedback and sorry for the inconvenience. We try to follow a release procedure and normally wouldn't re-push a tag, we made an exception this time (since the release was 1 hour old)

We'll be extra careful not to repeat this again.
