### ISSUE TITLE
Crash in ChatMessageListView: Attempted to scroll the table view to an out-of-bounds row (1) when there are only 1 rows in section 0.

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1261]
Got this crash on Crashlytics. Happened to one of our beta users:

SDK version: 4.0.0-beta6

<img width="1256" alt="Screenshot 2021-07-09 at 10 16 03 AM" src="https://user-images.githubusercontent.com/994179/125046901-b91be600-e09e-11eb-8e5f-46d72b3aa0e3.png">

**Comment by MatejBalantic** [comment]
Got steps to reproduce this from our user, it consistently crashes:

1. Open a new DM channel with a user you never talked to
2. Write the first message and hit submit
3. Crash

**Comment by MatejBalantic** [comment]
Please do let me know if there's something we can do to work around this until it's fixed. Sadly we were planning to release new version of our app with v4 SDK tonight, but this is a big enough crash that we'll need to revert the changes if we can't work around it

**Comment by VojtaStavik** [comment]
Thank you for reporting this. We'll get back to you shortly.

**Comment by VojtaStavik** [comment]
@MatejBalantic, can you please try to use the version of the SDK from the `release/preview` branch and confirm if the issue is no longer there for you?

**Comment by MatejBalantic** [comment]
Thanks for such an express fix, I really appreciate it. This solved the problem for us and we are shipping the app today with SDK v4 to the Apple Review.
