### ISSUE TITLE
StreamChatUI.Appearance customization per view

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1268]
## What did you do?
I would like to have different values for `Appearance` customizations on a per-view basis. For example, I would like to have a certain value for `Appearance.colorPalette.background` for `ChatChannelListVC` but a different value for that same property for `ChatMessageListVC`. I am only able to globally set the value for `Appearance.colorPalette.background` and have it applied to all views that reference that property. Does the `Appearance` feature support having different values for the same property for different views?

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.4
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**Comment by VojtaStavik** [comment]
Hi @srgray. The components always try to get the current `Appearance` from the responder chain and if they fail, they use `Appearance.default` as the fallback. This is still a bit experimental feature but it should work. You can try doing something like this (pseudo code):
```
var customAppearance = Appearance()
customApppearance.something = .... do your changes here

// You have to assign it before the view is loaded
messageListVC.appearance = customAppearance

// customAppearance will be used instead of `.default` for the VC and all its components 
```

Please let me know if this helps or if you see any issues.

**Comment by VojtaStavik** [comment]
In case you're looking for true per-view customization, you can always just subclass a component, override `setUpAppearance` method, and do your customization there:
```swift
class CustomOnlineIndicator: OnlineIndicatorView { 
  override func setUpAppearance() { 
    super.setUpAppearance()
    backgroundColor = .red
  }
}

Compoments.default.onlineIndicatorView = CustomOnlineIndicator.self
```

**Comment by srgray** [comment]
@VojtaStavik OK, yes, setting a modified `Appearance` object on my view before loading did the trick. Thank you!
