### ISSUE TITLE
TokenProvider set static

### ISSUE THREAD

**Issue by elemanhillary** [GetStream/stream-chat-swift#1278]
In the new API how do we set TokenProvider
I can nolonger set static token

**Comment by dmigach** [comment]
Hello!
API for connection has changed, you can find more details about it in [Release 4.0.0-beta.5 changelog](https://github.com/GetStream/stream-chat-swift/releases/tag/4.0.0-beta.5)

You now need to create an instance of `ChatClient` and in your case call `client.connectUser` with a static token:
```swift
let client = ChatClient(config: config)
client.connectUser(userInfo: .init(id: userId), token: token)
```
