### ISSUE TITLE
[release/2.0] Unable to watch events

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#128]
## What did you do?
I tried to add events on ChatViewController and ChannelViewController but it says this result is unused .
Giving one of the example of my issue .

<img width="940" alt="Screenshot 2020-03-22 at 9 12 15 PM" src="https://user-images.githubusercontent.com/37240061/77253693-dc403d80-6c81-11ea-8921-72e252347c89.png">

## What did you expect to happen?
should able to get every possible event like online event .

## What happened instead?

once it is set to online ,afterwards it never turns offline if user has terminated the app even .
## GetStream Environment
**GetStream Chat version:**release/2.0
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**iPhone/Simulator

**Comment by buh** [comment]
Hi @shireeshMs 
In 2.0 we moved all rx API to the rx subset, please try this:
```
Client.shared.rx.onEvent(eventType: .messagiing) { event in 
    ...
}
```

**Comment by shireeshMs** [comment]
> Hi @shireeshMs
> In 2.0 we moved all rx API to the `.rx` subset, please try this:
> 
> ```
> Client.shared.rx.onEvent(eventType: .messaging) { event in 
>     ...
> }
> ```
> 
> or you can use API in a class way
> 
> ```
> subscription = Client.shared.onEvent(eventType: .messaging) { result in 
>     if let event = result.value {
>         ...
>     }
> }
> ```
> 
> Keep `subscription` until you need it and then call `subscription.cancel()` or set to nil.

thank you ,let thing for user presence how to do this.

**Comment by shireeshMs** [comment]
Can you please tell me I am able to get user presence only when and afterwards it never changes .
I have done this
// 1.
 subscription =  channelPresenter.channelDidUpdate { [weak self] channel in
//            self?.title = channelPresenter.channel.name
            self?.setChatTitle(channel: channelPresenter.channel)
            self?.touchMembersCount()
        }
 //2.
subscription =   Client.shared.onEvent(eventType: .userPresenceChanged) { (x) in
            if case .userPresenceChanged(let f) = x.value{
                if let ch =  self.channelPresenter?.channel{
                    print("\(f.0.name) userPresenceChanged to \(f.0.isOnline)")
                    self.setChatTitle(channel:ch , isOnline: f.0.isOnline)
                }
            }
        }
  //3.  
  subscription =    self.channelPresenter?.channel.onEvent(eventType: .userStopWatching, { (x) in
            if case .userPresenceChanged(let f) = x.value{
                if let ch =  self.channelPresenter?.channel{
                    print("\(f.0.name) userStopWatching  \(f.0.isOnline)")
                    self.setChatTitle(channel:ch , isOnline: f.0.isOnline)
                }
            }
        })
on my chatViewController but still no updation on it .

**Comment by shireeshMs** [comment]
?

**Comment by b-onc** [comment]
Hello @shireeshMs ,
We're investigating this issue and will get back to you as soon as possible.

**Comment by shireeshMs** [comment]
> Hello @shireeshMs ,
> We're investigating this issue and will get back to you as soon as possible.
> Where do you keep your `subscription` property? Ideally it should be a class property in your `ChatViewController `subclass.

Yes this is how its done.

**Comment by shireeshMs** [comment]
@b-onc

**Comment by shireeshMs** [comment]
@b-onc pinging you again .

**Comment by b-onc** [comment]
Hello @shireeshMs ,
You don't need to ping us everyday, we're aware of these issues and we'll get back to you as soon as possible :) Unfortunately our hands are quite full nowadays, so it might take a couple of days.

**Comment by shireeshMs** [comment]
@b-onc I am sorry but we are also having less time before making it live.
Ok we will wait .

**Comment by b-onc** [comment]
Hello @shireeshMs ,
We've introduced some API changes to our events subscriptions.

Now you can easily do:
```swift
// Subscribe for user presence events.
let subscription = Client.shared.subscribe(forEvents: [.userPresenceChanged]) { event in
    // handle user presence changed event
}
// Cancel subscription when you want to stop receiving events
subscription.cancel()
```

Can you try the new API and let us know if it works for you?

Make sure you create a new `subscription` value for each subscription you create.
