### ISSUE TITLE
ChatMessageListView.updateMessages(with:completion:) Crash

### ISSUE THREAD

**Issue by osawhoop** [GetStream/stream-chat-swift#1283]
## What did you do?
I just created an instance of a channel and I got the crash, second time I opened the channel it did not crash

## What did you expect to happen?
Not crash and show the messages of the channel

## What happened instead?
It crashes

## GetStream Environment
**GetStream Chat version:**4.0.0-beta.5
**GetStream Chat frameworks:** StreamChatUI
**iOS version:**14.6
**Swift version:**5
**Xcode version:**12.5.1
**Device:**iPhone 12 mini

## Additional context
Attaching crash log

**Comment by dmigach** [comment]
Hello @osawhoop!
Is it possible to [symbolicate](https://developer.apple.com/documentation/xcode/adding-identifiable-symbol-names-to-a-crash-report#Symbolicate-the-Crash-Report-in-Xcode) the crash report?

**Comment by osawhoop** [comment]
I hope this one works, thanks!
[StreamChatTest.crash.zip](https://github.com/GetStream/stream-chat-swift/files/6830787/StreamChatTest.crash.zip)

**Comment by dmigach** [comment]
Hello @osawhoop! The [PR](https://github.com/GetStream/stream-chat-swift/pull/1286/files) addressing the issue was merged, we're preparing a release that's going to include this change
