### ISSUE TITLE
App Crashes on-closing ChannelList

### ISSUE THREAD

**Issue by elemanhillary** [GetStream/stream-chat-swift#1285]
Open channel list and act like a user who opened the channel list by mistake and close it immediately.

It will crash with `Fatal error: Attempted to read an unowned reference but the object was already deallocated`

<img width="797" alt="Screen Shot 2021-07-16 at 4 07 27 PM" src="https://user-images.githubusercontent.com/14273401/125952713-7683c5e3-6032-46fa-8785-5acd35e1817a.png">

**Comment by elemanhillary** [comment]
Don't am pretty sure we need to use `weak` instead of `unowned` because using `unowned` expect the object wont be nil which is the reason why its crashing since by the time i close `ChannelList` it gets deallocated thus being nil. wish i knew where this could is i would made a quick fix

**Comment by evsaev** [comment]
Thank you for reporting this @elemanhillary 🙏 Tracked internally as [CIS-1030](https://stream-io.atlassian.net/browse/CIS-1030), we'll have a look ASAP.

**Comment by evsaev** [comment]
We allow to create any number of `ChatClient` instance so it's possible to build `Slack` like app with multiple workspaces. 

If one client is enough for your purposes, consider having a singleton (until we have a proper fix for the crash): 
```swift
extension ChatClient {
    static let shared: ChatClient = {
        let config = ChatClientConfig(apiKey: .init("API_KEY"))
        let client = ChatClient(config: config)
        return client
    }()
}
```

Let me know if it helped
