### ISSUE TITLE
release/2.0 with tagging by @

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#129]
## What are you trying to achieve?
I am trying to achieve the tagging work as WhatsApp shows like @UserName 

## If possible, how can you achieve this currently?
Not at all .I was not able to achieve it all 

## What would be the better way?
You suggest !
## GetStream Environment
**GetStream Chat version:**release/2.0
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**iPhone/Simulator

**Comment by buh** [comment]
It should work. Type `@` and the name of a **member** of your channel.

**Comment by shireeshMs** [comment]
No it is not there in ,if might be please guide me .
DOnt close the issue before I got my solution please .

**Comment by shireeshMs** [comment]
> It should work. Type `@` and the name of a **member** of your channel.

It is

**Comment by buh** [comment]
Did you try to use a member name of the channel?

**Comment by shireeshMs** [comment]
Yes

**Comment by buh** [comment]
I've just checked: 
![image](https://user-images.githubusercontent.com/284922/77303749-c10e1600-6cf3-11ea-8a25-92fc60fe67da.jpeg)

Can you show me how you tried?

**Comment by shireeshMs** [comment]
It seems like that I have to write manually his full name right?
is there any way to pop up the list like WhatsApp
