### ISSUE TITLE
Manually set light/dark mode

### ISSUE THREAD

**Issue by seankcw** [GetStream/stream-chat-swift#1292]
It would be nice if I can config the appearance settings, for example, auto/light/dark.

**Comment by b-onc** [comment]
Hello @seankcw ,

Overriding the window’s interface style should override for all its subviews. Alternatively, you can override for a single UIView/UIViewController. You can do so as:
```swift
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    private var coordinator: DemoAppCoordinator!
    var window: UIWindow?
    
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let scene = scene as? UIWindowScene else { return }
        let window = UIWindow(windowScene: scene)
        
        self.window = window
        window.makeKeyAndVisible()
        scene.windows.forEach { $0.overrideUserInterfaceStyle = .dark }
    }
}
```
More information [here](https://stackoverflow.com/questions/66391172/how-to-change-app-theme-light-dark-programmatically-in-swift-5) and [here](https://developer.apple.com/documentation/uikit/uiview/3238086-overrideuserinterfacestyle)

**Comment by seankcw** [comment]
@b-onc `overrideUserInterfaceStyle` required iOS 13+
What if my app supports my own theme settings and iOS 11+?
