### ISSUE TITLE
Push Notifications: Device token registration

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#13]
Hi guys, 

we started to integrate push notification into our app based on `StreamChatCore`.

As far as I can see the SDK dosen't support register/unregister device token, right now. But I also saw that you already added a draft to `Endpoint` for add, remove and list of device tokens. I implemented the `addDevice` call to do some testing on our side which worked so far.

Could you give as a little bit more insights when do you plan to support register/unregister device tokens via the SDK?

Thx
Jan

**Comment by buh** [comment]
Hey @janweinkauff!
Thanks for the question. Push Notifications is in progress. Probably will be in the next release.
I'll let you know.

**Comment by buh** [comment]
@janweinkauff please check v.1.3.1
Client has `addDevice` and `removeDevice` methods.
The current user has a devices property, it will updated when the client will be connected.
