### ISSUE TITLE
Unable to get Channel Member details under push notifications Userinfo

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#130]
## What did you do?
Received message from other and tapped on push but there is no member details .

## What did you expect to happen?
it should return me member count

## What happened instead?
Member count is 0,and unable to see who has sent the message .

## GetStream Environment
**GetStream Chat version:**release/2.0
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**iPhone/Simulator

## Additional context
unable to find code in Channel Presenter,as previously it was giving me enough data related to member but not in this branch

**Comment by b-onc** [comment]
Hello @shireeshMs , which part of code were you able to use in 1.x but can't find in 2.0 branch? Can you post more info?

**Comment by shireeshMs** [comment]
Yes When we receive push from one source we are not able to get member detail or in simple words User details   .

**Comment by shireeshMs** [comment]
@b-onc pinging you again .

**Comment by b-onc** [comment]
Hello @shireeshMs ,
Can you provide more info? Actual code/videos? I don't understand what you're trying to achieve.
