### ISSUE TITLE
StreamChatUI accessibilityIdentifiers

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1302]
## What are you trying to achieve?
Our automated testing relies heavily on being able to find elements on the screen via `accessibilityIdentifier` properties on UIViews. A recent change (4.0.0-beta.4 -> 4.0.0-beta.6) has hidden many of the elements in StreamChatUI from our automated testing framework (Appium). Was this an intentional change? Do you have any insight into why these elements might not be discoverable via accessibility?

An example of a view that is not visible anymore (but was before) is the AvatarView in a ChatMessage cell.

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.6
**GetStream Chat frameworks:** StreamChatUI

**Comment by srgray** [comment]
Update: Our automated testing can find the elements if I explicitly enable accessibility on them, such as:

`authorAvatarView?.isAccessibilityElement = true`

**Comment by b-onc** [comment]
Hello @srgray ,

This definitely wasn't an intentional change. We're looking into this.

**Comment by nuno-vieira** [comment]
Hi, @srgray is this still reproducible on the most recent versions?
We did not change anything in terms of accessibility in the versions from beta4 to beta6. So are you sure it wasn't misconfiguration in the App?

Anyways, let us know if this still happens on beta11+

**Comment by srgray** [comment]
@nuno-vieira Yes, this is still happening for me on the latest SDK. But my work-around above is still valid and is an acceptable one for us.

**Comment by tbarbugli** [comment]
Thank you for providing this info, I will close this for now and track it in our internal backlog :)
