### ISSUE TITLE
Users always appear online

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1306]
## What did you do?

As a user, I open a direct messages channel and observe the channel header.

## What did you expect to happen?

The header online status text should reflect actual online state.

## What happened instead?

<img width="390" alt="Screenshot 2021-07-22 at 2 03 43 PM" src="https://user-images.githubusercontent.com/994179/126636243-757abe8a-786c-4244-94bc-15f5489fec13.png">

The header always says "Online", even when user is clearly not.

## GetStream Environment
**GetStream Chat version:**
4.0.0-beta.8

## Additional context

Using breakpoints I actually pinpointed the source of the bug. [This line](https://github.com/GetStream/stream-chat-swift/blob/main/Sources/StreamChatUI/ChatMessageList/ChatMessageListVC.swift#L312) incorrectly assumes that the `lastActiveMembers.first` is actually the user I am chatting with.

Where in fact the `lastActiveMember.first` will almost always be the currently logged in user, thus of course always will be online.

**Comment by b-onc** [comment]
Hello @MatejBalantic ,

Thanks for the report. This is actually known and actively worked on, the fix is in #1294.

**Comment by MatejBalantic** [comment]
@b-onc Thanks for fixing it, I can confirm the issue is resolved in the latest commit.
