### ISSUE TITLE
How to customize message composer

### ISSUE THREAD

**Issue by elemanhillary** [GetStream/stream-chat-swift#1308]
How do we customize a message composer

**Comment by tbarbugli** [comment]
@elemanhillary we are going to ship our new UI docs next week, in the meantime if you can look at the markdown source (it's fairly readable)

- [Message Composer](https://github.com/GetStream/stream-chat-swift/blob/main/docusaurus/docs/iOS/components/message-composer.md)
- [Customizing Message Composer Guide](https://github.com/GetStream/stream-chat-swift/blob/main/docusaurus/docs/iOS/guides/customize-message-composer.md)

What kind of customizations do you want to make to the composer? Feel free to drop a screenshot if you have some designs and you can share

@nuno-vieira ^^^

**Comment by elemanhillary** [comment]
Closing issue as the solution appears to be in the links provided by @tbarbugli
