### ISSUE TITLE
Received  message from one channel showing up on another different channel .

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#131]
## What did you do?
I was chatting with A user ,received message from user B and and get shows up on current chat with User A

## What did you expect to happen?
it should not be added  on different channel of course 
## What happened instead?
 message from one channel showing up on another channel - while you’re chatting if someone else sends you a message. That message shows up on your active 1-1 chat 

## GetStream Environment
**GetStream Chat version:**release/2.0
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**iPhone/Simulator

**Comment by b-onc** [comment]
Hello @shireeshMs can you provide more context for this issue? Steps to reproduce? A sample project? I can't reproduce this issue with this description.

**Comment by ronnieguha** [comment]
@b-onc here’s one video I captured. Happened to me twice today and was able to capture one
https://app.bugsee.com/#/issue/3d246844657b492492e4983bb8e400cd

**Comment by ronnieguha** [comment]
@b-onc Today I noticed that I started seeing typing events of another user into another 1-1 channel as well. So, both typing events and also the new messages show up in someone else's channel - BUT, only I see that other person's message in my 1-1 channel with someone else.. The other person in this 1-1 channel does not see it.

**Comment by b-onc** [comment]
Hello @ronnieguha ,
Thanks for the videos, the BugSee platform is very useful. However, I see that videos are very blurry and not clear at all. Do you also see it that way or is it just my browser?

**Comment by ronnieguha** [comment]
@b-onc bugsee gives HIPAA related applications to make it blurry. That's why it is blurry (not your browser) :-) As of yesterday, since now we have almost 50 people in our dev platform using the app - I see others' typing events and new messages in another chat as well.
Day 1 that we go live, I am expecting to have all 110 of our staff on it. Please help

**Comment by b-onc** [comment]
@ronnieguha I see, is it possible for you to send a clear video? You can email us on support@getstream.io

**Comment by ronnieguha** [comment]
@b-onc ok, @shireeshMs can you remove the blurry nature of bugsee for 1 build so I can send a video with a clear screen to getstream?

**Comment by ronnieguha** [comment]
![3C2A690F-E0E7-4D7B-BBFE-477F416E12D2](https://user-images.githubusercontent.com/2109530/78260922-8c0c7b00-74cc-11ea-804a-f11e26db7c33.png)

**Comment by ronnieguha** [comment]
@b-onc i hope this helps . As you can tell , I am on the 1-1 channel with Shashank, however the user NP’s chat shows here (Shashank does Not see it)

**Comment by b-onc** [comment]
@ronnieguha Did you send the video via email? @shireeshMs uploaded an image

**Comment by ronnieguha** [comment]
@b-onc i uploaded the image :-)
