### ISSUE TITLE
Inconsistent updates from ChatChannelListController

### ISSUE THREAD

**Issue by osawhoop** [GetStream/stream-chat-swift#1316]
## What did you do?
Just open a channel and I saw the log error.

## What did you expect to happen?
Not to see that error log.

## What happened instead?
I saw the error log.

## GetStream Environment
**GetStream Chat version: 4.0.0-beta.7**
**GetStream Chat frameworks: StreamChat, StreamChatUI**
**iOS version: 14.5**
**Swift version: 5**
**Xcode version: 12.5.1**
**Device: iPhone 12 mini (Simulator)**

## Additional context
Moves: []
Inserts: [[0, 35], [0, 39], [0, 37], [0, 12], [0, 23], [0, 38], [0, 36], [0, 11], [0, 32], [0, 4], [0, 24], [0, 30], [0, 41], [0, 10], [0, 40], [0, 31], [0, 42], [0, 34], [0, 21], [0, 29], [0, 3], [0, 20], [0, 27], [0, 0], [0, 18], [0, 33], [0, 1], [0, 14], [0, 25], [0, 19], [0, 26], [0, 15], [0, 16], [0, 13], [0, 28], [0, 17], [0, 2], [0, 22]]
updates: [[0, 5], [0, 16], [0, 6]]
removes: []

**Comment by tbarbugli** [comment]
@osawhoop do you still get this on latest release? (beta10)
