### ISSUE TITLE
Cannot disconnect with ChatMessageListVC

### ISSUE THREAD

**Issue by seankcw** [GetStream/stream-chat-swift#1317]
May I know how to release the ChatMessageListVC? I can still receive the message event after I poped the ChatMessageListVC. 

SDK version: 4.0-beta.8

Example:
Step 1  - Start Chat messaging VC
```
let channelController = ChatClient.shared.channelController(for: "channelId")
let messageVC = ChatMessageListVC()
self.navigationController?.pushViewController(messageVC, animated: true)
```
Step 2 - Tap Back button or pop Chat messaging VC

Step 3 - Opponent send message to my device
`didUpdateChannel` will still observe channel change in the background

```
 ///
    func channelController(
        _ channelController: _ChatChannelController<ExtraData>,
        didUpdateChannel channel: EntityChange<_ChatChannel<ExtraData>>
    )
```

**Comment by dmigach** [comment]
Hello @seankcw!
I checked this behaviour in our setup and see that `ChatMessageListVC` gets deallocated the moment you pop it, so could you please provide more details:
*  What's happening with `channelController` you create at the first line of your snippet?
*  Is it possible to check a memory graph for  `ChatMessageListVC` after you pop the screen? Ideally with `Malloc Stack Logging` enabled in diagnostics options for a scheme you run with

**Comment by seankcw** [comment]
@dmigach, thank you for your help. I've reviewed my code again, it's related to my implementation.
