### ISSUE TITLE
SDK does not compile in XCode 13.0 beta 3

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1319]
SDK version: 4.0.0-beta.8
XCode: 13.0 beta 3
The errors reported by the compiler:

`Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift:66:23: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

`Sources/StreamChatUI/Navigation/ChatMessageListRouter.swift:66:30: 'open(_:options:completionHandler:)' is unavailable in application extensions for iOS`

This is clearly related to a recent SPM change discussed in this thread:
https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/24

Firebase recently issued a pull request addressing this issue in their SDK:
https://github.com/firebase/firebase-ios-sdk/pull/8405

To allow stream chat SDK to compile with the XCode beta (and thus be tested on iOS 15) this needs to be addressed in a similar way here

**Comment by tbarbugli** [comment]
@MatejBalantic thank you for letting us know, looking into a solution for this now

**Comment by tbarbugli** [comment]
@MatejBalantic we have a PR that fixes this, do you mind giving it a go? https://github.com/GetStream/stream-chat-swift/pull/1333

**Comment by DominikBucher12** [comment]
Hello @MatejBalantic ,

sorry for the delay. We have solved the issue by marking the functions `unavailable` in AppExtensions. However we will proceed with caution and monitor how the situation works out in the Swift team. It is possible that this solution won't be needed if Swift team decides not to include `AppExtensions` targets in SPM Packages by default.

**Comment by MatejBalantic** [comment]
@DominikBucher12  Thanks for fixing it, I can confirm the issue is resolved in the latest commit.
