### ISSUE TITLE
Updating current user is not reflected in Client

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#132]
## What did you do?
I tried to change the current user Name by  
Client.shared.update(user: Client.shared.user) { _ in
                print("done\(Client.shared.user)")
            }

but it won't get update It gives same name which was previous then changed name .
## What did you expect to happen?
It should update the user Name without killing the app .

## What happened instead?

It does not ,all the time I have to kill the app .
## GetStream Environment
**GetStream Chat version:**release/2.0
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**iPhone/Simulator

## Additional context
This is the same thing happening with chatViewController,where I am trying add or remove member from chat it never update on screen until and unless user go back to list screen and come again ,When user again come back on ChatViewController found updated members .

**Comment by b-onc** [comment]
Hello @shireeshMs ,
Thanks for the bug report, we can reproduce this issue and will fix it in the upcoming patches.
