### ISSUE TITLE
Custom attachment view not sized correctly

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1325]
## What did you do?
I created a custom attachment view for chat messages following the guide at: https://getstream.io/tutorials/ios-chat/#creating-custom-attachment-views

## What did you expect to happen?
I expected the custom attachment view to display at the correct size

## What happened instead?
The custom attachment view image (the content that is loaded asynchronously) does not display correctly until the user scrolls that cell offscreen and then back onscreen.

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.8
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 14.5
**Device:** iPhone 11 simulator

## Additional context
See attachment view immediately after it is displayed the first time:
![FirstDisplay](https://user-images.githubusercontent.com/4721220/127160215-c64c5fd3-cd62-49de-af2f-3d23c5aed789.png)
See attachment view after the user has scrolled it offscreen and then back onscreen:
![AfterRedisplayingCell](https://user-images.githubusercontent.com/4721220/127160241-793968ef-03ed-463a-ac5e-e5ad611e63fe.png)

Custom attachment view code:
```
import Foundation
import StreamChatUI
import StreamChat
import Nuke

class ImgurImageAttachmentView: UIView {
    var content: ChatMessageLinkAttachment? { didSet { updateContent() } }

    lazy var imagePreview: UIImageView = {
        let view = UIImageView()
        view.contentMode = .scaleAspectFill
        view.layer.cornerRadius = 8
        view.clipsToBounds = true
        view.translatesAutoresizingMaskIntoConstraints = false
        view.isUserInteractionEnabled = false
        return view
    }()

    lazy var imgurLogoView: UIImageView = {
        let view = UIImageView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

    override public init(frame: CGRect) {
        super.init(frame: frame)

        addSubview(imagePreview)

        NSLayoutConstraint.activate([
            imagePreview.topAnchor.constraint(equalTo: topAnchor),
            imagePreview.bottomAnchor.constraint(equalTo: bottomAnchor),
            imagePreview.leadingAnchor.constraint(equalTo: leadingAnchor),
            imagePreview.trailingAnchor.constraint(equalTo: trailingAnchor)
        ])

        let logo = UIImage(named: "imgur_logo")!

        addSubview(imgurLogoView)
        imgurLogoView.image = logo

        let logoWidth: CGFloat = 100
        let logoRatio = logo.size.height / logo.size.width

        NSLayoutConstraint.activate([
            imgurLogoView.bottomAnchor.constraint(equalTo: bottomAnchor),
            imgurLogoView.trailingAnchor.constraint(equalTo: trailingAnchor),
            imgurLogoView.widthAnchor.constraint(equalToConstant: logoWidth),
            imgurLogoView.heightAnchor.constraint(equalToConstant: logoWidth * logoRatio)
        ])
    }

    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }

    func updateContent() {
        guard let payload = content?.payload else {
            return
        }

        let request = ImageRequest(url: payload.assetURL!)
        Nuke.loadImage(with: request, into: imagePreview)
    }
}

class ImgurImageAttachmentViewInjector: AttachmentViewInjector {
    let imgurImageAttachmentView: ImgurImageAttachmentView = {
        let view = ImgurImageAttachmentView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

    override open func contentViewDidLayout(options: ChatMessageLayoutOptions) {
        contentView.bubbleContentContainer.insertArrangedSubview(
            imgurImageAttachmentView,
            at: 0,
            respectsLayoutMargins: true
        )

        let constraint = imgurImageAttachmentView.widthAnchor.constraint(equalTo: contentView.widthAnchor)
        constraint.priority = .defaultLow
        constraint.isActive = true
    }

    override open func contentViewDidUpdateContent() {
        imgurImageAttachmentView.content = attachments(payloadType: LinkAttachmentPayload.self).first
    }
}

private func hasImgurLinkAttachment(message: ChatMessage) -> Bool {
    guard let imageAttachment = message.attachments(payloadType: LinkAttachmentPayload.self).first else {
        return false
    }

    guard let host = imageAttachment.assetURL?.host else {
        return false
    }

    return host.hasSuffix("imgur.com")
}

class MyAttachmentViewCatalog: AttachmentViewCatalog {
    override class func attachmentViewInjectorClassFor(
        message: ChatMessage,
        components: Components
    ) -> AttachmentViewInjector
        .Type? {
        if hasImgurLinkAttachment(message: message) {
            return ImgurImageAttachmentViewInjector.self
        }

        return super.attachmentViewInjectorClassFor(message: message, components: components)
    }
}
```

**Comment by b-onc** [comment]
Hello @srgray 

That's expected, it takes some time to load the attachment image/preview. What we do in our attachments is, we hide the meta elements (like the logo in your attachment) until we load the content.

So in your code, you should add:
```swift
// add this in ImgurImageAttachmentView.init
imgurLogoView.isHidden = true

// and in ImgurImageAttachmentView.updateContent
imgurLogoView.isHidden = false
```

then it'll behave like the built-in attachments: only displays URL before it loads the data, then displays the preview.

**Comment by srgray** [comment]
@b-onc Yes, I understand that the `imagePreview` content is loaded asynchronously and takes a while. But the true bug here is not with the `imgurLogoView`, it is with the `imagePreview` itself. `imagePreview` doesn't resize/display correctly even after the image data is loaded asynchronously. In other words, the chat channel will display as the first screenshot above forever UNTIL the user forces the cell offscreen and then back onscreen.

How can I get the cell/attachment view to update to display contents of `imagePreview` after the image data has loaded but WITHOUT waiting for the cell to be scrolled offscreen?

**Comment by b-onc** [comment]
@srgray that's interesting, in my testing (using the class you've provided) the image loaded correctly, without having to reload/scroll... can you provide a sample project for this?

**Comment by srgray** [comment]
OK, interesting...yes, here is the sample project I'm using.
I'm building with Xcode 12.5 and running on iPhone 11 simulator iOS 14.5
[StreamTest.zip](https://github.com/GetStream/stream-chat-swift/files/6894529/StreamTest.zip)

**Comment by b-onc** [comment]
Hello @srgray, thanks for the test project. We can reproduce this and are looking into it.

**Comment by SagarSDagdu** [comment]
Hello @srgray, I suggest you to have some initial height for your `imgurImageAttachmentView` in `ImgurImageAttachmentViewInjector` to fix this issue.
Example:

```swift
override open func contentViewDidLayout(options: ChatMessageLayoutOptions) {
        contentView.bubbleContentContainer.insertArrangedSubview(
            imgurImageAttachmentView,
            at: 0,
            respectsLayoutMargins: true
        )

        let constraint = imgurImageAttachmentView.widthAnchor.constraint(equalTo: contentView.widthAnchor)
        constraint.priority = .defaultLow
        constraint.isActive = true

        // The height for the imageAttachmentView
        let heightConstraint = imgurImageAttachmentView.heightAnchor.constraint(equalTo: imgurImageAttachmentView.widthAnchor, multiplier: 0.5)
        heightConstraint.priority = .defaultLow
        heightConstraint.isActive = true
}

```

You can have a look at `ChatMessageLinkPreviewView`'s `setUpLayout()` method where we have done something similar. Let me know if this solves the issue for you

**Comment by srgray** [comment]
@SagarSDagdu Yes, I think this is a good work-around for us. Since we don't know the exact height, the chat message cell still resizes once it is scrolled off and back on the screen. But at least we have some initial height to show the content.
Thanks!
