### ISSUE TITLE
Get payload data from MessageNewEvent for local push notifications 

### ISSUE THREAD

**Issue by energo** [GetStream/stream-chat-swift#1332]
In continuation of the previous [discussion](https://github.com/GetStream/stream-chat-swift/pull/1266), in the way to show notifications when the app in the background we need to use an event listener

```
class CustomChannelListVC: ChatChannelListVC, EventsControllerDelegate {
    
    var eventsController: EventsController!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        eventsController = controller.client.eventsController()
        eventsController.delegate = self
    }
    
    func eventsController(_ controller: EventsController, didReceiveEvent event: Event) {
        switch event {
        case let event as MessageNewEvent:
            // do what you need with the event
            print(event.messageId)
            // you can check if the app is in BG state and show local notification here
        default:
            break
        }
    }
}
```

We already have all data that we needed to show a local notification in "payload" property at "MessageNewEvent" object.
For title "name", "chat name" and for body "message text" 
But seems its accessibly only for SDK uses, and not in public API.

<img width="786" alt="Screenshot 2021-07-28 at 15 33 35" src="https://user-images.githubusercontent.com/1804123/127530365-8ad675f6-e79c-404c-a881-79387691bf09.png">

**Comment by kcollignon** [comment]
@b-onc I seem to be struggling with this as well. Have you all been able to take a look at this yet?

**Comment by tbarbugli** [comment]
@kcollignon ideally this event had a `message` property, team is looking into this and I think we'll be able to address it this week

**Comment by evsaev** [comment]
Hey @kcollignon @energo 👋 

The PR that adds models to events will be merged soon 👍

Thanks for your patience!

**Comment by energo** [comment]
> Hey @kcollignon @energo 👋
> 
> The PR that adds models to events will be merged soon 👍
> 
> Thanks for your patience!

Great news, thank you @evsaev
