### ISSUE TITLE
Input field breaks with when text with a lot of lines is entered

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1335]
## What did you do?

Entered a lot of text into the input field.

## What did you expect to happen?

The input field should grow until it can, then start scrolling.

## What happened instead?

Input field grew until it could, but after that it does not scroll anymore. Any text entered is off-screen, and can't be reached with scrolling.

## GetStream Environment
**GetStream Chat version:**
4.0.0-beta.8

## Additional context

[See this video](https://user-images.githubusercontent.com/994179/127681422-3b9a987c-aff4-4587-aca8-01f7858db035.mov)

**Comment by tbarbugli** [comment]
@MatejBalantic there is a PR that should solve this (https://github.com/GetStream/stream-chat-swift/pull/1303) can you let us know if that solves the problem?

**Comment by MatejBalantic** [comment]
@tbarbugli  Thanks for fixing it, I can confirm the issue is resolved in the latest commit.
