### ISSUE TITLE
Crashes in Demo App - New Chat Creation - 4.0.0-beta.8

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1336]
Trying to create a new chat in demo project version 4.0.0-beta.8

## App crashes see the screenshots.
![1 2](https://user-images.githubusercontent.com/78809766/127809690-4ce445f1-ff7f-487b-82c9-deb5a5d89a43.png)
![1 1](https://user-images.githubusercontent.com/78809766/127809696-17c70a26-f606-4f78-86b9-74c768467911.png)

Error Log:
logs:
Task <28031967-2A36-4883-903E-3DE1EF1AF752>.<132> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=./static/media/photo-1548946526-f69e2424cf45.cdd62d22.jpeg, NSErrorFailingURLKey=./static/media/photo-1548946526-f69e2424cf45.cdd62d22.jpeg, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <28031967-2A36-4883-903E-3DE1EF1AF752>.<132>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <28031967-2A36-4883-903E-3DE1EF1AF752>.<132>, NSUnderlyingError=0x6000001f0780 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}
2021-08-02 01:33:15.737478-0400 ChatSample[4974:60421] Task <AA1F4E82-979D-46FE-894F-E74EE94E32F1>.<136> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSLocalizedDescription=unsupported URL, NSErrorFailingURLStringKey=./static/media/photo-1548946526-f69e2424cf45.cdd62d22.jpeg, NSErrorFailingURLKey=./static/media/photo-1548946526-f69e2424cf45.cdd62d22.jpeg, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <AA1F4E82-979D-46FE-894F-E74EE94E32F1>.<136>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <AA1F4E82-979D-46FE-894F-E74EE94E32F1>.<136>, NSUnderlyingError=0x6000001f0a20 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}}

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by tbarbugli** [comment]
@vineethnkforios that's unfortunately, thank you for reporting this. Could you share the full stack trace here?

**Comment by SagarSDagdu** [comment]
@vineethnkforios  Thanks for reporting this. We have found the root cause of this issue and are working on a fix.
