### ISSUE TITLE
Cocoapod crash when try to build with swift 5.5

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#1339]
Hello. We has been using streamchat '2.6.3' for a year. 
I just installed the Xcode 13 (beta 4). 
My current swift version in the system is Apple Swift version **5.5** (swiftlang-1300.0.27.6 clang-1300.0.27.2)
As soon as I understand, Streamchat uses Starscream pod. 

I try to call pod install and observe the issue 
`Prebuilding Starscream...
> Processing Starscream-Info.plist
> Copying Starscream-umbrella.h

[x] /Users/lexin/Downloads/Xcode-beta 4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/usr/lib/swift/Network.swiftmodule/armv7-apple-ios.swiftinterface:1254:19: 'NWConnection' is only available in iOS 12.0 or newer

extension Network.NWConnection {
`

pod file contains platform :ios, '13.0'
deployment target in the project is '13.0'

**Comment by b-onc** [comment]
Hello @lexin ,

Thanks for also opening an issue in Starscream repo. We'll closely monitor Starscream and update our dependency as soon as this issue is fixed.

**Comment by nuno-vieira** [comment]
Hi @lexin !

The source of the issue seems to be Xcode 13beta4, as you can see from this thread: https://developer.apple.com/forums/thread/687152

Hopefully, it should be fixed in the next Xcode betas. 

Thank you for the report anyways!

**Comment by lexin** [comment]
Thanks! Will try it with latest beta.
