### ISSUE TITLE
Question: What is the recommended way to be notified after `connectUser` is completed?

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1341]
What is the recommended way for me to notify various ViewControllers in my app that the Stream call to `connectUser` has completed?
I see that `connectUser` has a `completion` closure. Should I post my own app-wide notification so that various ViewControllers can know the process has completed? Or is there already a delegate somewhere in Stream that provides this functionality? (I tried to use `CurrentChatUserControllerDelegate` but that doesn't seem to fire after the `connectUser` has completed).

Specific use case:
One of my ViewControllers is a subclass of `ChatChannelListVC` and I need to call `.synchronize()` on it AFTER `connectUser` has completed.

StreamChatUI version 4.0.0-beta.8

**Comment by b-onc** [comment]
Hello @srgray ,

Exactly as you said. By the time completion of `connectUser` is called, the SDK has already created the WS connection and has a valid connectionId, you can safely call `synchronize` on controllers.
