### ISSUE TITLE
Channels list didn't load

### ISSUE THREAD

**Issue by JustMyKnight** [GetStream/stream-chat-swift#1345]
## What did you do?

I just add standard ChatChannelListVC into my application, on the previous beta8 everything was fine, but in beta9 it's only active indicator forever. 
## What did you expect to happen?
Load the channel list for the current user.
## What happened instead?
It's active indicator, when open ChatChannelListVC and nothing else. But when i create chat direct with selected user works fine. 
## GetStream Environment
**GetStream Chat version:**
4.0.0-beta.9
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
4.0.0-beta.9
**iOS version:**
14.5
**Swift version:**
Swift 5
**Xcode version:**
12.5
**Device:**
Simulator and iPhone X, iPhone 12 Pro

**Comment by tbarbugli** [comment]
@JustMyKnight thank you for reporting this. A couple questions to speed up the resolution of this problem:

- Can you share the code that you use to present the `ChatChannelListVC`? (good if you include the code that creates the chat client and connects the user as well) 
- Did you check if there are any errors in the logs? (if yes can you attach here)

**Comment by tbarbugli** [comment]
@JustMyKnight this should be fixed on the latest release (beta10). Please re-open if you still experience this problem after the update
