### ISSUE TITLE
API Ergonomics

### ISSUE THREAD

**Issue by gonzalonunez** [GetStream/stream-chat-swift#1349]
## What are you trying to achieve?
Requiring a `config:` on initialization for `ChatClient` forces optionals to leak out to external APIs when configuring `ChatClient` with an API key that is only known at runtime.

My app uses `.xcconfig`s to differentiate between a Production environment and a Staging environment, which means we have two separate StreamChat API keys. In the `UIApplicationDelegate`, we retrieve the API key from the `Info.plist` and configure the `ChatClient`.

Since the `ChatClient` requires the `ChatClientConfig` to be initialized and our API key is not known at compile-time, this leaks optionals out downstream to all uses of `ChatClient`. For example:

```swift
  private var chatClient: ChatClient?

  public func configure(apiKey: String) {
    let config = ChatClientConfig(apiKey: APIKey(apiKey))
    let client = ChatClient(config: config)
    client.connectAnonymousUser()
    chatClient = client
  }

  // Since `ChatClient` has to be optional, so does `ChannelController?` and everything else.
  public func channelController(for cid: ChannelId) -> ChannelController? {
    chatClient?.channelController(for: cid)
  }
```

## If possible, how can you achieve this currently?
Currently, I have a bunch of `assertionFailure`s littered throughout the application. It's also possible to force-unwrap, but I do not feel comfortable going that route for an application of this scale.
```swift
  private func connectUser(
    with sessionInfo: SessionInfo,
    receiveOn scheduler: AnySchedulerOf<DispatchQueue>) -> AnyCancellable
  {
    guard let chatClient = chatClient else {
      assertionFailure("""
      Expected a non-nil cancellable when authenticating DefaultStreamChatService. \
      Did you forget to call configure(apiKey:)?
      """)
      return AnyCancellable { }
    }
    
    // ...
   }
```

## What would be the better way?
One solution is to follow what [RevenueCat](https://github.com/RevenueCat/purchases-ios/blob/557cc7a7e176abb020603d3c8ab916de1f8af338/Purchases/Public/RCPurchases.m#L179) does:

1. Allow initialization of `ChatClient` with no parameters.
2. Have a separate `configure(with config: ChatClientConfig)` method.

There are several options regarding what to do in the case of an un-configured `ChatClient` when calling the other methods:
1. Mark methods as `throws`, although this leads to a similar type of issue (but less bad, IMO).
2. Return errors via the existing asynchronous mechanisms, like `connectUser`'s `completion:`.

## GetStream Environment
**GetStream Chat version:** `4.0.0-beta.9`
**GetStream Chat frameworks:** `StreamChat`
**iOS version:** Any
**Swift version:** Any
**Xcode version:** Any
**Device:** Any

## Additional context
I'm enjoying my experience with `StreamChat` thus far, thank you all for the great work that you're doing 🙏

**Comment by b-onc** [comment]
Hello @gonzalonunez 

We're glad to hear you're having a positive experience with our SDK!

Regarding your question, I think you should implement your own "singleton" instance and configure it once (in your AppDelegate or SceneDelegate). An example of this is shown in our iOS tutorial: https://getstream.io/tutorials/ios-chat/

You declare the delegate:
```swift
import StreamChat

extension ChatClient {
    static var shared: ChatClient!
}
```
and then you create/configure it, once or as many times as you need:
```swift
func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
) {
    let config = ChatClientConfig(apiKey: .init("YOUR API KEY HERE"))
    let token =
        Token(
            stringLiteral: "YOUR TOKEN HERE"
        )

    /// create an instance of ChatClient and share it using the singleton
    ChatClient.shared = ChatClient(config: config)

    /// connect to chat
    ChatClient.shared.connectUser(
        userInfo: UserInfo(
            id: "tutorial-droid",
            name: "Tutorial Droid",
            imageURL: URL(string: "https://bit.ly/2TIt8NR")
        ),
        token: token
    )
}
```

**Comment by gonzalonunez** [comment]
Thanks for the quick reply @b-onc! IMO this would count as force-unwrapping, which I highlighted above.

It's a reasonable workaround, but I just wanted to highlight a potential improvement to the API ergonomics. I understand if it's lower-priority or if the team disagrees with the general direction though :)

Thank you! I'll go ahead and close the issue, feel free to reopen if it you all would like of course.
