### ISSUE TITLE
Firebase crash  

### ISSUE THREAD

**Issue by MuseerAnsari** [GetStream/stream-chat-swift#1350]
## What did you do?
Follow implementation guid line 

## What did you expect to happen?
NA

## What happened instead?
Some time its reporting crash in firebase crashlytics, but not reproducible 

## GetStream Environment
**GetStream Chat version:** 4.0-beta.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 14.4 
<img width="985" alt="Screenshot 2021-08-10 at 3 30 22 PM" src="https://user-images.githubusercontent.com/17614820/128847938-93f35cec-3750-4f4a-903e-dee42ec49a89.png">

**Swift version:** 5
**Xcode version:** 12.4, many
**Device:** iPhone 12 Pro max and many

**Comment by tbarbugli** [comment]
@MuseerAnsari we recently fixed this and we are going to release a patch in a couple hours (beta-10). I will post a message here when the release is available.

**Comment by tbarbugli** [comment]
@MuseerAnsari beta10 is released, please re-open if you experience the same problem after the update.
