### ISSUE TITLE
Endless connecting, no token refresh

### ISSUE THREAD

**Issue by jderes** [GetStream/stream-chat-swift#1351]
## What did you do?
Connect user with expired token. Details:
I'm using beta-9. On app launch i'm setting up ChatClient with TokenProvider and calling connectUser with a token cached locally. Obviously sometimes the token is expired. 

## What did you expect to happen?
Some kind of error and a token refresh through TokenProvider i have set.

## What happened instead?
Token not refreshing. Endless errors loop. After debugging the ChatClient methods i can see that webSocketClient didUpdateConnectionState is constantly in .connecting state. Why doesn't expired token trigger .disconnected state with proper error?
What am i doing wrong?

The errors i'm getting in the endless loop in the console are:

`[connection] nw_read_request_report [C24] Receive failed with error "Invalid argument"
Connection 24: received failure notification
[connection] nw_read_request_report [C24] Receive failed with error "Socket is not connected"
[websocket] Read completed with an error Socket is not connected
[connection] nw_flow_add_write_request [C24.1 3.65.55.155:443 failed socket-flow (satisfied (Path is satisfied), interface: en0)] cannot accept write requests`

`[io.getStream.chat.core.web_socket_engine_queue] [URLSessionWebSocketEngine.swift:62] [doRead()] > Failed receiving Web Socket Message with error: Error Domain=kNWErrorDomainPOSIX Code=57 "Socket is not connected" UserInfo={NSDescription=Socket is not connected}
Task <EEF9551F-3026-4B0F-AEE3-03697657A8F7>.<2> finished with error [57] Error Domain=kNWErrorDomainPOSIX Code=57 "Socket is not connected" UserInfo={NSDescription=Socket is not connected, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalWebSocketTask <EEF9551F-3026-4B0F-AEE3-03697657A8F7>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalWebSocketTask <EEF9551F-3026-4B0F-AEE3-03697657A8F7>.<2>}`

`[connection] nw_write_request_report [C24] Send failed with error "Socket is not connected"`

**Comment by tbarbugli** [comment]
@jderes thank you for reporting this, can you share the code for your TokenProvider and ideally share the code used to generate the fresh one? @dmigach do we have any logging in place regarding this?

**Comment by tbarbugli** [comment]
we are releasing beta10 at the moment, it would be great if you could give that (or latest main) a spin and let us know if you notice any difference.

**Comment by jderes** [comment]
Thank you for looking into this. Here is my TokenProvider, it's just a function stored as a property in a singleton, so it's not deallocated:

`tokenProvider = { completion in
            log.info("TokenProvider")
            if !Preferences.getJWTToken().isEmpty {
                let tk = Token.init(stringLiteral: Preferences.getJWTToken())
                
                completion(.success(tk))
            } else {
                log.error("No JWT token")
                completion(.failure(ClientError("No JWT token")))
            }
}`

where Preferences.getJWTToken() returns the token stored in a disk cache. The value is updated based on our applications backend refresh mechanism etc.
The problem is TokenProvider not being called. When i debug the error loop in ChatClient, i can see tokenProvider there, so it's not nil.

I'm gonna try beta 10, but i think podspec has not been updated yet, so i can't download it.

Thanks

**Comment by dmigach** [comment]
@jderes Thank you for reporting this! There is a server-side issue that's currently being investigated, we'll keep you posted on the status

**Comment by tbarbugli** [comment]
@jderes this issue should be resolved now, you don't need to take any action. Please re-open this ticket if you still experience problems.

**Comment by jderes** [comment]
It's fixed, thank you.
