### ISSUE TITLE
User Role is getting as "user" for all members 

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1356]
## What did you do?
Logs like below

print("******************************** ******************************** ********************************")
_ = selctedChatChannelController.channel?.cachedMembers.map { member in
print("member is:",member.id)
print("member is:",member.name as Any)
print("member is:",member.userRole as Any)

        print("member is online:",member.isOnline as Any)
        
        print("member is online:",member.memberRole as Any)
        
        self.existingMembersArray.add(member.id);
    }
    
    
    print("TEAM  is:",selctedChatChannelController.channel?.team as Any)
    
    print("createdBy  is:",selctedChatChannelController.channel?.createdBy?.id as Any)
    print("createdBy  is:",selctedChatChannelController.channel?.createdBy?.name as Any)
    
    print("********************************  ********************************  ********************************")

## What did you expect to happen?
anjuar must be "owner"

## What happened instead?

member is: aali01
member is: Optional("akbar ali")
member is: user
member is online: false
member is online: MemberRole(rawValue: "member")
member is: 1gokul
member is: Optional("123 gokul")
member is: user
member is online: false
member is online: MemberRole(rawValue: "member")
member is: anjuar
member is: Optional("Anju AR")
member is: user
member is online: true
member is online: MemberRole(rawValue: "member")
member is: a_george
member is: Optional("Ayina george")
member is: user
member is online: false
member is online: MemberRole(rawValue: "member")
TEAM is: Optional("PRERELEASE")
createdBy is: Optional("anjuar")
createdBy is: Optional("Anju AR")

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by b-onc** [comment]
Hello @vineethnkforios ,

As we are already helping you in issue #1355, there's no need for 2nd issue. We'll re-open #1355 if we see that's an SDK issue.

**Comment by vineethnkforios** [comment]
ok
