### ISSUE TITLE
Last seen format is always in minutes

### ISSUE THREAD

**Issue by simkepal** [GetStream/stream-chat-swift#1358]
## What did you do?
As a user, I open a direct messages channel

## What did you expect to happen?
I expect to show more human readable time, when user was last seen online. For example 1h ago, 5 days ago, etc.

## What happened instead?
The last seen timestamp is always in minutes, although there are even days passed already ("seen 136.801 minutes ago")

![IMG_1762](https://user-images.githubusercontent.com/1116275/128885740-b2b94181-83de-45a1-aefa-dedc8b33a7b0.jpg)

## GetStream Environment
**GetStream Chat version:** 
4.0.0-beta.8
commit: 14bf8f68ff48f7c63f775b3dea9630dd3a825204

**Comment by tbarbugli** [comment]
@simkepal thank you for reporting this

**Comment by tbarbugli** [comment]
#1368 solves this + adds localized strings for this
