### ISSUE TITLE
Crash when cancel send Gif in group

### ISSUE THREAD

**Issue by vankien96** [GetStream/stream-chat-swift#1366]
## What did you do?
Go to group chat, send a gif, and click cancel in Gif preview.

## What did you expect to happen?
Not crash

## What happened instead?
Crash app

## GetStream Environment
**GetStream Chat version:** 4.0 beta 10
**GetStream Chat frameworks: ** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 14.5
**Swift version:**  5.4.2
**Xcode version:** 12.5
**Device:** Simulator

## Additional context
Only happen in group chat channel, it still works in direct message channel.

![image](https://user-images.githubusercontent.com/26648523/129201988-02338af1-279b-4be1-a823-b088bd37e135.png)
![image](https://user-images.githubusercontent.com/26648523/129202016-d3a1f26d-965b-4048-ba4c-31bff3ce13e7.png)

**Comment by tbarbugli** [comment]
@vankien96 thank you for reporting this, one interesting thing from stacktrace is that it includes `_ChatMessageListVC` but that class was removed and replaced by `ChatMessageListVC` before the beta-10 release. Is it possible that you are running on an older (spm cache?) version?

**Comment by vankien96** [comment]
@tbarbugli Ah, sorry about that, It also happens in the older version. That image is from beta8
This is the beta 10:
![image](https://user-images.githubusercontent.com/26648523/129356381-3e0766ce-b2ea-4549-a327-1388df7fb821.png)

**Comment by tbarbugli** [comment]
@vankien96 I can finally reproduce the problem on my end by canceling a giphy message on channels that have a single message. I have a pretty good idea about how to solve this (for now at least :))

If you dont mind testing a draft PR, feel free to test the `fix-messagelist-crash` branch. Curious to hear if that solves the issue for you as well.

**Comment by vankien96** [comment]
@tbarbugli Wow nice, I checked it resolved my issue.

**Comment by tbarbugli** [comment]
@vankien96 happy to hear that, we merged that into main and we'll release a new version in a couple days
