### ISSUE TITLE
Question: Filter messages

### ISSUE THREAD

**Issue by Dimocrat** [GetStream/stream-chat-swift#1372]
Hi! I'm using GetStream for live chat, but I need to reproduce chat history for recorded live. So, for the recorded video I have to show chat history at the same time that it was on live. Is it any way to make it? I thought about filtering messaging by timestamp and update chat, but I haven't found any methods for that.

**Comment by petyosi** [comment]
@Dimocrat sorry for the delayed response on our side. Our clients have implemented a similar behavior, but unfortunately, not with the iOS SDK. In summary, the idea is to pre-load the messages from a certain channel and then "replay" them based on their timestamp. 

At present, our channel view controller does not support rendering messages from a source other than the real client, so you will have to bring your own UI for that purpose. Should you decide to do that, you can grab the source code from our SDK and modify it for your purpose. 

I am sorry for not being able to provide a more out-of-the box solution for your implementation. I will log this as a future potential improvement in our SDK. Please let me know if you need any further assistance with this.
