### ISSUE TITLE
StreamChat is not finishing background tasks - app terminated.

### ISSUE THREAD

**Issue by astas79** [GetStream/stream-chat-swift#1377]
When app with integrated ChatUI goes to background - IOS terminates the app with following message:

[BackgroundTask] Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x2833cf1c0>: taskID = 96, taskName = Called by Test, from $s10StreamChat26IOSBackgroundTaskSchedulerC05beginD017expirationHandlerSbyycSg_tF, creationTime = 159368 (elapsed = 27). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.

## What did you expect to happen?
App stays in the background in suspended state, instead of being terminated.

## What happened instead?
App gets terminated.

## GetStream Environment
beta.11
StreamChatUI
**iOS 14.7

**Comment by dmigach** [comment]
Hello @astas79 ! 
Thanks for reporting this, I'm going to reproduce it and will let you know once I know more about the issue.

**Comment by dmigach** [comment]
I spotted a minor inconsistency in logic related to your issue, but it's not clear if this could cause it. I wasn't able to reproduce the issue, so you can either try providing more details on how to reproduce this, or wait until the next release and check out if the issue still persists for you
