### ISSUE TITLE
No Such Module Reachability 

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#138]
## What did you do?
I have taken the pull from release/2.0,and keep getting error of No Such module Reachability .
Cant even build the project .

## What did you expect to happen?

It should not give me an error .
## What happened instead?

It keep giving me error of No such module Reachability in InternetConnection
## GetStream Environment
**GetStream Chat version:**branch release/2.0
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**iPhone/Simulator

**Comment by b-onc** [comment]
Hello @shireeshMs ,
It was an error we caused by updating our pods.
Can you please try removing your Pods folder and Podfile.lock and then do `pod install --repo-update`?

**Comment by shireeshMs** [comment]
@b-onc thanks for the quick response.
Fortunately i got no issue but now after updating it ,giving this error .

<img width="1680" alt="Screenshot 2020-03-31 at 12 31 52 AM" src="https://user-images.githubusercontent.com/37240061/77951020-07143c80-72e7-11ea-9f05-6c34dcc45601.png">

sharing pod here 
<img width="1680" alt="Screenshot 2020-03-31 at 1 21 23 AM" src="https://user-images.githubusercontent.com/37240061/77955542-fb784400-72ed-11ea-959e-68dca77b6ba2.png">

sharing the error 
<img width="1680" alt="Screenshot 2020-03-31 at 1 21 09 AM" src="https://user-images.githubusercontent.com/37240061/77955565-0501ac00-72ee-11ea-90ff-d16ed367e527.png">


Please let me if I am doing anything wrong,although I follow the same process as per your suggested way.

**Comment by shireeshMs** [comment]
Now even I cant get back to any other branch !

**Comment by ronnieguha** [comment]
@b-onc is there a plan to merge this into master? We are building on top of the 2.0 release. Thanks.

**Comment by buh** [comment]
Hi @ronnieguha we are planning to release on this week

**Comment by ronnieguha** [comment]
@buh YAY!! Thank you !!

**Comment by buh** [comment]
Hey @shireeshMs 
I'm sorry to hear about your issues. 2.0 is still in development and we don't increment versions of libraries and pods can be updated incorrectly. Please try to clean pod cache, DeliveredData, restart Xcode, clean project. Let me know if it helps.

**Comment by buh** [comment]
@shireeshMs I think I found the issue. I'll fix it soon.

**Comment by buh** [comment]
Fixed! Please add all SDK frameworks in your `Podfile`, for example:
```ruby
platform :ios, '11.0'
inhibit_all_warnings!

target 'ChatDemo' do
  use_frameworks!
  pod 'StreamChatClient', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'release/2.0'
  pod 'StreamChatCore', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'release/2.0'
  pod 'StreamChat', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'release/2.0'
end
```

**Comment by shireeshMs** [comment]
@buh Hello thanks for response, it helped me just  I need to do change from my side .
just one quickie whether I need to git pull release/2.0 or not after this pod installation
