### ISSUE TITLE
Can't install version 4.0

### ISSUE THREAD

**Issue by abdelrahman-badary** [GetStream/stream-chat-swift#1384]
## What did you do?
On the official website page https://getstream.io/chat/docs/ios-swift/ it says to use `pod 'StreamChat', '~> 4.0'` to install the SDK

## What did you expect to happen?
I expected the SDK to be installed when I run `pod install`

## What happened instead?
i get 
`[!] CocoaPods could not find compatible versions for pod "StreamChat":
  In Podfile:
    StreamChat (~> 4.0)
`
I tried to run `pod repo update` and `pod install` after it but with no luck, is version 4.0 officially released or not yet.

**Comment by tbarbugli** [comment]
@abdelrahman-badary thank you for pointing this out, the docs are indeed incorrect. The latest release on v4 is `4.0.0-beta.11`
