### ISSUE TITLE
ChatChannelListCollectionViewCell is showing a deleted message as the "latest message"

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1396]
## What did you do?
- Select a chat channel from `ChatChannelListVC` and send a new message in that channel
- Delete that message
- Return to `ChatChannelListVC`

## What did you expect to happen?
I expected the latest non-deleted message to be displayed in the `ChatChannelListCollectionViewCell`

## What happened instead?
The deleted message shows as the most recent message in `ChatChannelListCollectionViewCell`

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.10
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**Comment by tbarbugli** [comment]
@srgray thank you for reporting this. I am going to talk about this with the other SDK teams, sounds like this should be configurable at the SDK level (some apps like WhatsApp behave this way)

**Comment by petyosi** [comment]
@srgray indeed, the behavior you describe is more convenient from an end user perspective. We will take this into account and put it in our backlog.

**Comment by petyosi** [comment]
@srgray an update, we have taken this into account and will look into making it happen in our near-term development effort. I don't have a concrete ETA, but we will post an update here once this is available. Thank you for your help!
