### ISSUE TITLE
Incorrect chat offset on first start

### ISSUE THREAD

**Issue by JustMyKnight** [GetStream/stream-chat-swift#1410]
## What did you do?
I add ChatMessageListVC as child in view container and when i open chat first time last message send time is behind the message composer view. So, after i scroll chat the "scrollToLatestMessageButton" is appear and didn't disappear anymore. But when i open same VC second time everything is fine.
## What did you expect to happen?
The scrollToLatestMessageButton is hidden, when i scroll to the last message. The start offset of the message is correct.

## What happened instead?
The scrollToLatestMessageButton didn't disappear on first open chat VC. The scroll is incorrect.

## GetStream Environment
**GetStream Chat version:**
4.0.0-beta.11
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
4.0.0-beta.11
**iOS version:**
14.7.1
**Swift version:**
Swift 5
**Xcode version:**
12.5
**Device:**
iPhone X, iPhone 12 Pro

**Comment by nuno-vieira** [comment]
Hi, @JustMyKnight can you clarify how the "last message send time is behind the message composer view"? Is the message list below the composer somehow? Can you provide a sample project with your setup so that we can reproduce it and help you?

Thank you!

**Comment by JustMyKnight** [comment]
Hi, @nuno-vieira, yes, the part of the message, where send time, is below composer on the first open chat. I will send sample project soon.

**Comment by nuno-vieira** [comment]
Hi @JustMyKnight We were able to find the issue, and the fix will be available next Friday. 

Thank you for the report!

**Comment by tbarbugli** [comment]
This should be fixed now on the latest release, please re-open if needed
