### ISSUE TITLE
Ability to hook into ChatViewController/Compose message sending

### ISSUE THREAD

**Issue by psylinse** [GetStream/stream-chat-swift#142]
Is there a recommended way to hook into message sending? Specifically, I'm trying to encrypt a message before sending it over the wire. The combination of final classes (`ChannelPresenter`) and extension functions (`ChatViewController+Composer#createComposeView` and `ChatViewController+Composer#send`) make it hard (impossible?) to hook into sending. 

Here is my source where I'm modifying the `ChatViewController`: https://github.com/psylinse/stream-ios-encrypted-chat/blob/master/ios/EncryptedChat/EncryptedChatViewController.swift

Sorry if I'm missing something obvious!

**Comment by b-onc** [comment]
Hello @psylinse 
I see that it's currently not possible to hook into sending while using our UI components. I'm adding this as a request to our backlog - you can expect this to come out in 2.1 in the next weeks!

**Comment by psylinse** [comment]
Awesome, thank you! 

FWIW, I'd love to be able to hook in as "low" as possible, i.e. in `client.sendMessage` or `channel.send`. Maybe even `ChannelPresenter` in the same style as `MessageExtraDataCallback`, although that feels too high. A custom UI many not use those presenters. That way if someone goes to custom widgets, they still get this behavior. This is useful in my case and also if someone wants to do message logging/analytics. 

That said, it'd be nice to be able to customize the `ComposeView` a bit more.

**Comment by cardoso** [comment]
@psylinse please take a look at #154 and see whether it satisfies your requirements

**Comment by psylinse** [comment]
This looks good to me, thank you!
