### ISSUE TITLE
Search Bar/Search Option on  ChatChannelListVC iOS- Swift

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1428]
## What are you trying to achieve?
Search Bar/Search Option on  ChatChannelListVC iOS- Swift

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by kojiba** [comment]
Hello @vineethnkforios ,
Thanks for contacting us, 

Currently there is no UI for search component,
But this work is put to the backlog, 

We will notify about this functionality in Release Notes when it will be ready.
You could subscribe to repo using Watch -> Custom -> Releases

Best regards, Illia
