### ISSUE TITLE
Unable to update the version '4.0.0-RC' on Cocoapods

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1432]
## What did you do?

I write as below on my .podfile
pod 'StreamChatUI', '~> 4.0.0-RC'

## What did you expect to happen?
 I have already updated till   4.0.0-beta.11'
My .pofile was 
# pod 'StreamChatUI', '~> 4.0.0-beta.11'"

## What happened instead?
![Screenshot 2021-09-07 at 6 09 56 AM](https://user-images.githubusercontent.com/78809766/132327485-13eadbd4-a51c-4ade-bf9d-7726d19bea62.png)

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by b-onc** [comment]
Hello @vineethnkforios ,

The warning you're seeing is not related to StreamChat SDK.

Are you seeing a different issue?

**Comment by vineethnkforios** [comment]
pod --version
1.10.1
MAC-2:MobIOSDigitalAgency EveroMac2$ pod install --repo-update
Updating local specs repositories

CocoaPods 1.11.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.0.beta.2

Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 6 total pods installed.

[!] Automatically assigning platform `iOS` with version `14.1` on target `DIGITALAgency` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `DIGITALAgency [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-DIGITALAgency/Pods-DIGITALAgency.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `DIGITALAgency [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-DIGITALAgency/Pods-DIGITALAgency.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `DIGITALAgency [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-DIGITALAgency/Pods-DIGITALAgency.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `DIGITALAgency [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-DIGITALAgency/Pods-DIGITALAgency.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `DIGITALAgency [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-DIGITALAgency/Pods-DIGITALAgency.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `DIGITALAgency [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-DIGITALAgency/Pods-DIGITALAgency.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

**Comment by vineethnkforios** [comment]
My .Podfile is 

pod 'StreamChatUI', '~> 4.0.0-RC'

Is this  correct ?

**Comment by b-onc** [comment]
Hello @vineethnkforios ,

It's correct and I don't see any errors in the output you've shared.

**Comment by vineethnkforios** [comment]
Normally the cocoa pods update command will list the old sdk and new sdk versionss during the update command.

I have double-check the files manually (eg: ChatMessage.swift) and found differences

**Comment by netrager** [comment]
I can confirm, that there is a problem with the RC update. I was updating from beta.10 to RC
Like @vineethnkforios my podfile contains 
`pod 'StreamChatUI', '~> 4.0.0-RC'`

but cococapods updated only to beta.11 and my podfile.lock contains now following lines:

`- StreamChat (4.0.0-beta.11):
    - Starscream (~> 4.0)
  - StreamChatUI (4.0.0-beta.11):
    - Nuke (~> 9.0)
    - StreamChat (= 4.0.0-beta.11)
    - SwiftyGif (~> 5.0)
  - SwiftyGif (5.4.0)

DEPENDENCIES:
  - Firebase/Analytics
  - Firebase/Core
  - Firebase/Performance
  - GoogleMaps
  - GooglePlaces
  - Instabug
  - StreamChatUI (~> 4.0.0-RC)`

**Comment by b-onc** [comment]
It seems like there's an issue with Cocoapods not parsing the version (4.0.0-RC) correctly. I'm investigating this.
Meanwhile, please use
```ruby
pod 'StreamChatUI', :git => 'https://github.com/GetStream/stream-chat-swift/', :tag => '4.0.0-RC'
```
this works and the result is the same

**Comment by tbarbugli** [comment]
@vineethnkforios v4.0.0 is released now
