### ISSUE TITLE
Conditional conformace to Hashable for ChatMessageAttachment based on Payload

### ISSUE THREAD

**Issue by gonzalonunez** [GetStream/stream-chat-swift#1441]
## What are you trying to achieve?
Work with some existing APIs that require conformance to `Hashable`.

## If possible, how can you achieve this currently?
Everything seems to be possible – I can either manually conform `StreamChat`'s types or wrap them in my own conforming types 1:1.

## What would be the better way?
StreamChat changes all of the `Equatable` conformances to `Hashable`, which would supersede the existing `Equatable` requirement and be a relatively lightweight change.

## GetStream Environment
**GetStream Chat version:** 4.0.0-beta.9
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** Any
**Swift version:** Any
**Xcode version:** Any
**Device:** Any

## Additional context
N/A

**Comment by gonzalonunez** [comment]
This would include all of the existing attachment payload types too: `ImageAttachmentPayload`, `VideoAttachmentPayload`, etc.

**Comment by tbarbugli** [comment]
@gonzalonunez I dont really understand this issue, do you mind providing more information? Are you facing any specific problem?

**Comment by gonzalonunez** [comment]
@tbarbugli I'm building some UI of my own and want to use `StreamChat`'s attachment types directly in my models, which need to be `Hashable`.

I can put up a PR if you'd like — I'm interesting in the following being added to `StreamChat`:

```
extension ChatMessageAttachment: Hashable where Payload: Hashable { }
```

**Comment by tbarbugli** [comment]
@gonzalonunez thank you for sharing the extra information. AFAICT adding this should do it:

```swift
extension ChatMessageAttachment: Hashable where Payload: Equatable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(id.hashValue)
    }
}
```

Let me know how that goes, if that works fine I am happy to add this to the SDK

**Comment by tbarbugli** [comment]
@evsaev please confirm ^^^

**Comment by tbarbugli** [comment]
@gonzalonunez did the extension work for you?

**Comment by gonzalonunez** [comment]
@tbarbugli

Looks like it will work, but from what I can tell it is not "technically" correct given that the conformances to `Hashable` and `Equatable` are different. From the [Hashable documentation](https://developer.apple.com/documentation/swift/hashable):
> Hashing a value means feeding its essential components into a hash function, represented by the Hasher type. Essential components are those that contribute to the type’s implementation of Equatable. Two instances that are equal must feed the same values to Hasher in hash(into:), in the same order.

I see there is already the following for `Equatable`:
```swift
extension ChatMessageAttachment: Equatable where Payload: Equatable {}
```

Why not add it for `Hashable` too, and then conform all of the existing types as well:
```swift
extension ImageAttachmentPayload: Hashable { }
extension LinkAttachmentPayload: Hashable { }
extension VideoAttachmentPayload: Hashable { }
// ...
```

Granted, I don't know what problems this would cause in reality – probably none 😅

**Comment by tbarbugli** [comment]
All attachment types are not `Hashable` on the main branch (release coming up today)

**Comment by gonzalonunez** [comment]
Thank you @tbarbugli! 🙏🏻
