### ISSUE TITLE
Provide search option which is absolutely necessary for an chat history 

### ISSUE THREAD

**Issue by anjuarevero** [GetStream/stream-chat-swift#1444]
## What are you trying to achieve?
Need a search option to find an existing person from chat history , otherwise user need to scroll down and find out the person/message from older chat 

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by vineethnkforios** [comment]
looking for the same impementation in swift , Is there any samples ?

**Comment by nuno-vieira** [comment]
Hi @vineethnkforios We currently don't support this yet in the iOS SDK, sorry for the inconvenience. 

We will post an update here once we have an estimation on when the feature will be available.

Best Regards,
Nuno Vieirs

**Comment by adamrushy** [comment]
I have migrated this same topic to our [Discussions](https://github.com/GetStream/stream-chat-swift/discussions/1608) page so we can gauge community interest.
