### ISSUE TITLE
When 1 chat individually to a person ,the edit options is become similar to a Channel . Why there is no difference between a normal chat and Channel ?

### ISSUE THREAD

**Issue by anjuarevero** [GetStream/stream-chat-swift#1445]
## What did you do?
I send a direct message , For me it showing View info, Leave channel, Add member , Delete Member etc .So what is the difference between a channel and Direct message  ?
Normal direct message chat options is entirely different from a channel right ?
Referred WhatsApp, Fb messenger, Teams etc  .

## What did you expect to happen?
Direct chat should have chat features like Hide chat , delete chat etc and Channel features should have their own

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by shodgetts** [comment]
Hello and thanks for submitting an issue to our GitHub repository. We’re glad you’re getting hands on with the product. The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed.
In case our understanding is incorrect and you are describing a bug, we apologise, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.
