### ISSUE TITLE
ChatReactionsBubbleView is not used from Components class

### ISSUE THREAD

**Issue by abdelrahman-badary** [GetStream/stream-chat-swift#1450]
## What did you do?
I am trying customise the `ChatReactionsBubbleView` class but inside `ChatMessageContentView` it is not used from the `Components` class, specfically inside the method called `createReactionsBubbleView()` the object is instantiated using this class always `ChatReactionsBubbleView` and there is the following comment 
"// TODO: view type should be taken from `components` once `_ReactionsBubbleView` is audited". Is this something that will change with the 4.0 release or not?

## What did you expect to happen?
That I am able to use a different class for this component like the rest of the components in the SDK

## What happened instead?
The class is hardcoded in the SDK files and I can't override it.

## GetStream Environment
**GetStream Chat version:**  
'StreamChatUI', '4.0.0-RC'
**GetStream Chat frameworks:** StreamChatUI

**Comment by kojiba** [comment]
Hello @abdelrahman-badary ,

Thank you for contacting us,
Engineering team will answer soon,

Best regards, Illia

**Comment by kojiba** [comment]
Hello @abdelrahman-badary 

The needed changes are merged in https://github.com/GetStream/stream-chat-swift/pull/1451

Will be available in a new minor update (4.0.1) on the end of this or next week. 
Please close request if you don't have any further questions.

Best regards, Illia
