### ISSUE TITLE
How to send uploaded file url into custom keys in Attachment

### ISSUE THREAD

**Issue by architdhupar** [GetStream/stream-chat-swift#1452]
Hi 

We have custom attachment payload keys. We are not able to understand how to parse the url of uploaded file/image and other informations in the attachment payload  custom keys while creating message. Kindly help us with the same.

Here are the details: 
Library used: 4.0.0-beta.11

Custom Attachment Payload(with Keys needed): 

struct Attachment {
    let name: String?
    let fileSize: String?
    let assetUrl: String?
    let imageUrl: String?
    let image: String?
    let url: String?
    let text: String?
    let type: String?
    let title: String?
    let titleLink: String?
    let thumbUrl: String?
}

**Comment by evsaev** [comment]
Hey @architdhupar 👋 

To extend a image/file/video attachment with custom fields declare a `Codable` type first:
```swift
struct CommentPayload: Codable {
 let comment: String
}
```

Then, initiate sending a message with image/file/video attachment like that:
```swift
// 1. Create custom payload.
let commentPayload = CommentPayload(comment: "Happy birthday! 🎉")
// 2. Create an envelope for built-in attachment with custom payload.
let envelope = AnyAttachmentEnvelope(localFileURL: *url*, attachmentType: .image, extraData: commentPayload)
// 3. Send the message with attachment
channelController.createNewMessage(..., attachments: [envelope])
```

When message is sent an attachment JSON would looks like this:
```swift
{
 "type": "image",
 "title": "cake.png",
 "image_url": "https://getstream.io/attachments/cake.png",
 "thumb_url": "https://getstream.io/attachments/cake_thumb.png",
 "comment": "Happy birthday! 🎉"
}
```

To get the custom fields back from attachment do the following:
```swift
// 1. Get an attachment from the message
let attachment = message.imageAttachments.first (if you working with files, it's gonna be `fileAttachments`)

// 2. Get your custom payload from attachment.
let commentPayload = attachment?.extraData(ofType: CommentPayload.self)

// 3. Access your custom fields
print(commentPayload?.comment ?? "There's no comment :(") // Happy birthday! 🎉
```

Let me know if it helps 🙂

**Comment by architdhupar** [comment]
Hi @evsaev,
Thanks for your reply.

are there any similar methods like sendImage/sendFile in iOS just like in Android(or node) which uploads the image/file and gives the url of uploaded file in completion?

Thanks again.

**Comment by evsaev** [comment]
Hey @architdhupar 👋 

iOS SDK behaves differently from Android: when sending is initiated for a message containing **file/image/video/audio** attachments, attachments get saved to the local database with **local URLs** and queued by `AttachmentUploader`. When uploading of a given attachment is completed, the **local URLs** and replaced with **remote URLs** and when we're done with all attachment a message is sent to the backend. 

So, answering your question, when `message.imageAttachments.first?.uploadingState.state` becomes `.uploaded` it means attachment all **URLs** in attachment are remote.

**Comment by evsaev** [comment]
hey @architdhupar 👋 I hope we're able to help! In case of any questions feel free to open a GitHub issue 👍

**Comment by evsaev** [comment]
Hey @iosamar 👋 

Let me have a deeper look into this 👀 In the meantime, could you show your custom attachment payload type so we better understand what extra data you're sending with image attachment?

Thank you!

**Comment by evsaev** [comment]
Good day @iosamar 👋

I can confirm that we send an image attachment and get it back without the `thumb_url` field. If you're using Stream's CDN, there's a way to modify `image_url` and get a thumbnail providing `w/h/crop/resize` query params to the URL.

Here is how we do it on iOS: https://github.com/GetStream/stream-chat-swift/blob/11ed5928786c19f559db24ce06d121ff7b813bf2/Sources/StreamChatUI/Utils/ImageCDN.swift#L62

Hope it helps 🙌
