### ISSUE TITLE
Direct Message - Same user can be added again and again for a DM, while taking the user for the next time , redirect to the chat window 

### ISSUE THREAD

**Issue by anjuarevero** [GetStream/stream-chat-swift#1454]
## What did you do?
Direct Message - Same user can be added again and again for a DM, 
## What did you expect to happen?
while taking the user for the next time , redirect to the chat window b/w the users .

## What happened instead?

It added new chat channel again and again 
## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by tbarbugli** [comment]
I am not really sure what you mean by `added again and again for a DM` perhaps you can share some code or a video of how you are experiencing this problem?

**Comment by tbarbugli** [comment]
@anjuarevero please reopen if you can provide some more information about the issue
