### ISSUE TITLE
Token refresh only works the first time (some times a second try, but then fails)

### ISSUE THREAD

**Issue by yensi-vega** [GetStream/stream-chat-swift#1463]
**### What did you do?**
For testing we set up 2 min for token expiration in our token generator server.
- When the token has expired and we try to send a message, its internal local state is set to `.sendingFailed`
- On this scenario, se call `reloadUserIfNeeded` which use our token provider closure.
- In the first token expiration, we got the new token and send the same message with success
- We wait for another token expiration (2 min)
- Second try: some times we got the same behavior described before, i.e. we are able to continue the conversation, but some times doesn't. (described bellow) 
- Third try: when we call `reloadUserIfNeeded` we got successfully the token from our server, but not able to connect to stream chat and we got this error: `[websocket] Read completed with an error Operation canceled`,  the App gets stuck and does not respond anymore.

**What did you expect to happen?**
- We should be able always to send a new message when the token has expired, calling the `reloadUserIfNeed` since we got successfully the new token from our server.

**GetStream Environment**
GetStream Chat version: 3.1.11
 GetStream Chat frameworks: StreamChat
 Swift version: 5
 Xcode version: 12.5.1
 Device: sim iPhone 11, iOS 14.5

**Additional context**
Our Chat Client Configuration (it works)
![image](https://user-images.githubusercontent.com/47642891/134029923-b9eb4f7d-cb36-4394-bf3a-09cb8dd40223.png)

Capturing the `sendingFailed` local state for the message after the token has expired
![image](https://user-images.githubusercontent.com/47642891/134030635-f1b983e2-4eee-48ba-b0e4-89e6ae6e7688.png)

![image](https://user-images.githubusercontent.com/47642891/134031176-629b8220-4bf6-4229-989e-5dc7a22c8654.png)

Thanks in advance for giving this issue a check.

**Comment by yensi-vega** [comment]
Thanks for quick reply. We will start the update and let you know if we need a hand on that.

**Comment by yensi-vega** [comment]
Hi @nuno-vieira , I'm wondering if there is a kind of `update guide` (from 3.1.11 to 4.0.1)
 
Thanks in advance.

**Comment by b-onc** [comment]
Hello @yensi-vega ,

The migration guide can be found [here](https://github.com/GetStream/stream-chat-swift/blob/main/docusaurus/docs/iOS/guides/migrating-from-3-to-4.md)

**Comment by tbarbugli** [comment]
Closing this issue, please feel free to open issues if you find any issue with the migration from 3.x to 4.x
