### ISSUE TITLE
Unable to compile StreamChat SDK

### ISSUE THREAD

**Issue by aqeelbhat** [GetStream/stream-chat-swift#147]
## What did you do?
pod 'StreamChat'
then
pod install --repo-update

## What did you expect to happen?
install stream chat SDK with no build errors

## What happened instead?
installed stream chat SDK with errors

## GetStream Environment
**GetStream Chat version:**
1.6.1
**iOS version:**
13.0
**Swift version:**
5.0
**Xcode version:**
11.4
**Device:**
iPhone 11 Pro

## Additional context
<img width="1680" alt="Screen Shot 2020-04-01 at 11 26 45 PM" src="https://user-images.githubusercontent.com/46371231/78170996-630acc80-7471-11ea-9809-f232cfd1391f.png">

**Comment by aqeelbhat** [comment]
**Cocoapods** -  **v1.9.1**
**macOS** - **v10.15.4**

**Comment by b-onc** [comment]
Hello @aqeelbhat ,
Thanks a lot for letting us know of this issue. It was caused by a dependency misconfiguration, which we have resolved and rolled out 1.6.2. If you remove your `Podfile.lock` file and run `pod install --repo-update` again, it should be resolved.

**Comment by aqeelbhat** [comment]
Any estimate for releasing docs for v1.x to v2.0 migration? It seems like the v2.0 release introduces breaking changes.

**Comment by buh** [comment]
Hey @aqeelbhat 
We are working on it. I think it will be ready on the next. If you have questions about 2.0 migration let us know we can help you.

**Comment by alaxicsmith** [comment]
I'm still seeing this bug on my end, too

**Comment by b-onc** [comment]
Which version are you using?

**Comment by alaxicsmith** [comment]
I'm using 2.0.1 @b-onc

**Comment by b-onc** [comment]
@alaxicsmith I've tried 2.0.1 and it works. It's probably a misconfiguration on your end. Can you check if you've outdated lock file?
