### ISSUE TITLE
Muted user's messages still appear in message list

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1471]
## What did you do?
I muted a user

## What did you expect to happen?
I expected not to see new messages from that user

## What happened instead?
I still see messages from that user

## GetStream Environment
**GetStream Chat version:** 4.0.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**Comment by tbarbugli** [comment]
@srgray the SDK does not make any assumption on how apps deal with muted users. We'll add a an example snippet just show how hiding muted messages can be done.
