### ISSUE TITLE
Question: Recommended way to display a custom message cell

### ISSUE THREAD

**Issue by nicol3a** [GetStream/stream-chat-swift#1473]
## What are you trying to achieve?
Display a custom message cell. We send regular text messages with custom data in `extraData`. It could be something like "User created a task", "Task deleted", etc. It's a like a message sent by the system. We want this message cell displayed full width.

How can we do that in the most simple way? I looked at AttachmentInjector, I managed to display the message, but it's not ideal.

## If possible, how can you achieve this currently?
We tried to do it via an attachment view injector. But it's a bit hacky.
```swift
class StreamStatusMessageAttachmentViewInjector: AttachmentViewInjector {
    let statusMessageAttachmentView: StreamStatusMessageAttachmentView = {
        let view = StreamStatusMessageAttachmentView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

    override open func contentViewDidLayout(options: ChatMessageLayoutOptions) {
        contentView.mainContainer.removeAllArrangedSubviews()

        contentView.addSubview(statusMessageAttachmentView)

        NSLayoutConstraint.activate([
            statusMessageAttachmentView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 2),
            statusMessageAttachmentView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 0),
            statusMessageAttachmentView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: -.padding8),
            statusMessageAttachmentView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: 0)
        ])

        let constraint = statusMessageAttachmentView.widthAnchor.constraint(equalTo: contentView.widthAnchor)
        constraint.priority = .defaultLow
        constraint.isActive = true
    }
}
```

![Simulator Screen Shot - iPhone 13 - 2021-09-23 at 08 59 56](https://user-images.githubusercontent.com/1519558/134512646-6f96ce1a-1921-43ef-9e8f-ef175c904639.png)

## What would be the better way?
Something like a message injector? Basically a way to inject a custom cell for a message (by parsing the `extraData` property in our case).

We're currently using StreamChat v2, where it is easier because we can override the `override func messageCell(at indexPath: IndexPath, message: StreamChatClient.Message, readUsers: [StreamChatClient.User]) -> UITableViewCell` function in `ChatViewController` subclass.

## GetStream Environment
**GetStream Chat version:** 4.0.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat 4.0.0
**iOS version:** 15.0
**Swift version:** 5
**Xcode version:** 13.0
**Device:** Simulator, device

**Comment by tbarbugli** [comment]
@nicol3a can you include an example of the message custom data here?

**Comment by nicol3a** [comment]
The `extraData` property usually looks like this:
```json
{
    "system_message_type": "task_deleted",
    "cid": "messaging:0Cyo4m6J5HXXXXXXX",
    "data": {
        "task_id": "XXXXX",
        "type": "todo"
    }
}
```

At the time when we thought about how to represent our custom messages, we looked into creating a `system` message but it wasn't what we needed (because no push notifs were sent if I remember correctly). And now we're using this system in production since Feb 2021, so we'd like to keep it this way.

With my current solution using `AttachmentViewInjector`, I'm doing this:

```swift
class MyAttachmentViewCatalog: AttachmentViewCatalog {
    override class func attachmentViewInjectorClassFor(
        message: ChatMessage,
        components: Components
    ) -> AttachmentViewInjector.Type? {
        if let systemMessageType = message.extraData["system_message_type"] {
            return true
        }

        return super.attachmentViewInjectorClassFor(message: message, components: components)
    }
}

class StreamStatusMessageAttachmentViewInjector: AttachmentViewInjector {
    override open func contentViewDidUpdateContent() {
        guard let extraData = contentView.content?.extraData else { return }

        // Parse `extraData` property and extract custom data

        statusMessageAttachmentView.update(/* passing my custom data here */)
    }
}
```

Hope it helps! Thanks.

**Comment by nicol3a** [comment]
Thank you, a little bit cleaner than what I did with `AttachmentViewInjector` :-)
