### ISSUE TITLE
MessageDeletedEvent never received 

### ISSUE THREAD

**Issue by abdelrahman-badary** [GetStream/stream-chat-swift#1477]
## What did you do?
I am trying to listen to channel events through the `ChatChannelController.eventsController ` I receive various events but never the MessageDeletedEvent, the message is being deleted from our backend, I have tried to listen to the channel events and I tried to listen to the chat client events but neither received the event.

## What did you expect to happen?
To receive the MessageDeletedEvent

## What happened instead?
nothing 

## GetStream Environment
**GetStream Chat version:** 4.0.1
**GetStream Chat frameworks:** StreamChat, StreamChatClient
**iOS version:** 14.0

**Comment by abdelrahman-badary** [comment]
So an update about this, we noticed that the SDK fails to parse the event internally because the user object is missing from the event payload so the init method fails in this line  `userId = try response.value(at: \.user?.id)` inside the `MessageDeletedEvent` class. same issue reported in the Android SKD https://github.com/GetStream/stream-chat-android/issues/2360

**Comment by evsaev** [comment]
Hey @abdelrahman-badary 👋 

Thanks for reporting this! You're absolutely right, if message deletion is triggered server-side the `user` is missing and event parsing phase fails and events is not get posted.

It's already fixed in #1459 and will be merged soon 👍
