### ISSUE TITLE
ChatChannelListVC doesn't properly filter channels

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1484]
## What did you do?
Attempt to display ChatChannelListVC for only `.messaging` channels of which my user is a member

## What did you expect to happen?
Only `.messaging` channels that my user is a member of should be displayed

## What happened instead?
ChatChannelListVC displays some channels that are `.livestream` type

## GetStream Environment
**GetStream Chat version:** 4.0.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
See attached sample project:
[StreamChannelList.zip](https://github.com/GetStream/stream-chat-swift/files/7238763/StreamChannelList.zip)

Steps to reproduce:
- Open app
- Tap to 'Enter Channel List'. Notice, as expected, only 1 .messaging channel is displayed
- Tap Back and then tap 'Enter livestream1 channel'
- Wait for messages to render
- Tap Back and then tap 'Enter Channel List'
- Notice that now the .livestream channel is displayed in the channel list. This is the undesired behavior

**Comment by tbarbugli** [comment]
thank you for sharing this, looks like the relevant bits of code is

```swift
private lazy var chatChannelListVC: CNChatChannelListVC = {
        let chatChannelsVC = CNChatChannelListVC()
        let userIds = [userId] //show channels that have me in them
        let channelListController = ChatClient.shared
            .channelListController(
                query: ChannelListQuery(
                    filter: Filter.and([
                        .containMembers(userIds: userIds),
                        .equal(.type, to: .messaging)
                    ])
                )
            )
        chatChannelsVC.controller = channelListController
        return chatChannelsVC
    }()
```

which looks correct, we are looking into it

**Comment by tbarbugli** [comment]
quick update, the ChannelListQuery you use creates the right JSON payload:

```json
{"limit":20,"watch":true,"message_limit":25,"filter_conditions":{"$and":[{"members":{"$in":["a","b"]}},{"type":{"$eq":"messaging"}}]}}
```

more digging required

**Comment by srgray** [comment]
Hi @b-onc ,

Thanks for the suggested work-around. I am not able to get my delegate callback to fire, it is only using the default implementation declared in the protocol extension. Can you take a quick look and let me know if I am doing something wrong?
[StreamChannelListDelegateWorkaround.zip](https://github.com/GetStream/stream-chat-swift/files/7254439/StreamChannelListDelegateWorkaround.zip)

**Comment by b-onc** [comment]
Hello @srgray ,
Thanks a lot for the sample project, it helped tremendously.
There are 2 issues, 1 comes from user error and 1 comes from SDK
User Error: You assign ViewController as delegate to ChannelListController, but ChannelListVC assigns itself as delegate, overriding yours. Your implementations won't be called.
SDK Error: You can't override delegate methods in your ChannelListVC subclass because ChannelListVC doesn't implement them.

I'll PR the fix for SDK error shortly and then you'll be able to override delegate methods in your ChannelListVC subclass and return `false` for `type != .messaging` channels.
