### ISSUE TITLE
Chat client APIs randomly fail due to JSON decoding

### ISSUE THREAD

**Issue by basememara** [GetStream/stream-chat-swift#1487]
## What did you do?
Called `chatClient.channelListController(...)`

## What did you expect to happen?
Data retrieved from the chat client with no errors.

## What happened instead?
Randomly no data is returned from the chat client and get the following error in the console:

```
An error occured while fetching the channel list | Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "channels", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "messages", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), MessagePayloadsCodingKeys(stringValue: "user", intValue: nil), UserPayloadsCodingKeys(stringValue: "last_active", intValue: nil)], debugDescription: "Invalid date: 2021-09-28T08:17:18.030196604Z", underlyingError: nil)) | Context: ["app_state": "active"]
```

## GetStream Environment
**GetStream Chat version:** 4.0.2
**GetStream Chat frameworks:** StreamChat
**iOS version:** 15
**Swift version:** 5.5
**Xcode version:** 13
**Device:** simulator

## Additional context
See PR #1486 for further details and fix.

**Comment by tbarbugli** [comment]
fixed on main branch (thank you!)
