### ISSUE TITLE
Keyboard's autosuggest is hiding the composer input text field

### ISSUE THREAD

**Issue by dmrschmidt** [GetStream/stream-chat-swift#1494]
## What did you do?

Updated from 4.0.1 to 4.0.2. Now, when tapping into the composer text field and the keyboard appears, the text field is not scrolled up enough. They text entry field is covered by the autosuggest recommendations.

## What did you expect to happen?

The text entry field should've not been covered.

## What happened instead?

The text entry field (and submit button) were covered by the keyboard.

## GetStream Environment
**GetStream Chat version:** 4.0.2
**GetStream Chat frameworks:** StreamChatUI
**iOS version:** 15.0
**Swift version:** 5.x
**Xcode version:** 13
**Device:** iPhone 13 Mini

## Additional context

I suspect either https://github.com/GetStream/stream-chat-swift/pull/1470 or https://github.com/GetStream/stream-chat-swift/pull/1464 to be the culprit.

see screenshots

### 4.0.1
   
![Simulator Screen Shot - iPhone 13 mini - 2021-09-30 at 12 03 09](https://user-images.githubusercontent.com/69365/135434875-e3573bb4-6913-4d25-b556-b67b1e830b49.png)

### 4.0.2

![Simulator Screen Shot - iPhone 13 mini - 2021-09-30 at 11 03 23](https://user-images.githubusercontent.com/69365/135434974-95320646-248b-4515-9769-cd81a0fd5f89.png)

**Comment by nuno-vieira** [comment]
Hi @dmrschmidt ! Thank you for the detailed report! We will look into this and get back to you as soon as possible.

**Comment by nuno-vieira** [comment]
Hi @dmrschmidt The fix is now available on the `main` branch, and it will be officially available in the next release, this Friday.

I'll close the issue, feel free to open it again if you find any problem.

Thank you!

**Comment by dmrschmidt** [comment]
That was super fast! Thanks so much for the update and your amazing work!
