### ISSUE TITLE
Members of a channel

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#15]
I was trying to get the members of a channel. I found the `members` set on the `Channel` type but it seems to be always empty.

I tried to trace back the path how the `members` property of a `Channel` is set but couldn't find a way which is working. Unfortunately, the response from the API dosen't contains members on the level of a channel, if we fetch channels with a `ChannelPresenter`.

But, what I also discoverd was the `members` set on the `ChannelPresenter` type which is set by parsing a `ChannelResponse` in `private func parseResponse(_ query: ChannelResponse) -> ViewChanges`. Unfortunately the `members` property is not public so it can't be used outside of StreamChatCore.

My questions are:
- Did I miss the correct way how to get/fill the members of a channel? If yes, how?
- Or is this a misssing feature which will come in the future?

Why we need this?
- We build a custom channels view controller where we present the members of a channel for every channel cell as subtitle

**Comment by buh** [comment]
@janweinkauff thanks for your question. So, yes, `ChannelResponse` has members and it should be definitely available in the `ChannelPresenter`. We will be fixed in the next release. Probably today.

**Comment by buh** [comment]
Fixed in v1.3.2. The Channel now will have updated members after response. ChannelPresenter will have updated channel.
