### ISSUE TITLE
Android and iOS experience is not same 

### ISSUE THREAD

**Issue by Museer21** [GetStream/stream-chat-swift#1507]
## What did you do?
Display default cell in iOS 
`super.collectionView(collectionView, cellForItemAt: indexPath)`
## What did you expect to happen?
iOS and Android cell display should be same while sending same text including html string. please have a look in given screen shots 
![Screenshot_20210930-114706](https://user-images.githubusercontent.com/83453288/135961009-8834fb5d-9157-4987-9626-e300ec950d4d.jpg)
![simulator_screenshot_CCF69410-9661-47CB-8780-153D6D0EE1FB](https://user-images.githubusercontent.com/83453288/135961015-eb51bbfe-1b50-4c17-b927-ca1c67ca6a47.png)

## What happened instead?
iOS and Android cell display are different 

## GetStream Environment
**GetStream Chat version:** 'StreamChat', '4.0-beta.1'
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore 'StreamChatUI', '4.0-beta.1'
**iOS version:** 14.4
**Swift version:** 5
**Xcode version:** 12.4
**Device:** iPhone 11 pro max

**Comment by tbarbugli** [comment]
I think you for sharing this, it would be great if you could answer a few questions:

- How is the message in your example being posted? Can you share the payload as well so we can reproduce it?
- Are you using a custom Message component in your app? If yes can you include the code used there?

**Comment by adamrushy** [comment]
@Museer21 if a link is inserted directly inside the chat it will render the link for you, see attached screenshot. Are you able to share more code, for example, is this a custom attachment you're using?

![LinkPreview](https://user-images.githubusercontent.com/1519998/136207153-26a6a446-cca5-4da5-aa40-192d390fd06b.jpg)
