### ISSUE TITLE
Unread Count.

### ISSUE THREAD

**Issue by iosamar** [GetStream/stream-chat-swift#1511]
Hi, 

I am trying to show unread count and my code for the same is :- 

let config = ChatClientConfig(apiKey: APIKey(apiKey))
            let tokenClient =
                Token(
                    stringLiteral: token
                )
            ChatClient.shared = ChatClient(config: config)
            ChatClient.shared.connectUser(
                userInfo: UserInfo(
                    id: userNameID,
                    name: userNameID
                ),
                token: tokenClient
            )

            let client = ChatClient.shared.channelController(for: ChannelId(type: .team, id: interactionId))
            client.synchronize()
            
            let currentUserController = ChatClient.shared.currentUserController()
            currentUserController.delegate = CurrentUserDelegate()
            currentUserController.synchronize()
            
            self.chatVc = ChatVC.init()
            Components.default.messageListVC = ChatVC.self
            Components.default.messageComposerVC = MessageComposerVC.self
            Components.default.messageComposerView = MessageCompserView.self
            Components.default.messageContentView = ChatMessageView.self
            
            
       and delegate class for the same is :- 
            
            class CurrentUserDelegate: CurrentChatUserControllerDelegate {
    func currentUserController(_ controller: CurrentChatUserController,
                               didChangeCurrentUserUnreadCount: UnreadCount) {
        // handle unread count change
    }
}

but this delegate function is not get triggered when new message received.
so please let me know wether i am on correct path or i missed something.

**Comment by tbarbugli** [comment]
A couple quick questions:

- is the user a member on the channel that you are observing? (if not sure, please share how you create the test channel)
- are you sending the test message with a different user (the unread count is not changed when for messages from the same user)

**Comment by iosamar** [comment]
answer of first question:- yes the user is the member of the channel that i am observing.
answer of second question:- yes i am sending message from different user from same channel.

**Comment by tbarbugli** [comment]
@iosamar the `currentUserController` controller holds a weak reference to its delegate. Can you make `currentUserController` a var and store it so you know it will not get collected?

```swift
var currentUserController: CurrentChatUserController!
```

```swift
currentUserController = ChatClient.shared.currentUserController()
```

**Comment by iosamar** [comment]
@tbarbugli,  thanks for the reply,
i tried the way you are telling but couldn't help.
let me share you code again


 var chatChannelController: ChatChannelController?
 var currentUserController: CurrentChatUserController!

inCallVm.initChatVc = {  [weak self](chatCredential) in
            guard let self = self else { return }
            
            guard let apiKey = chatCredential.apiKey, let token = chatCredential.token, let userNameID = chatCredential.user?.username, let interactionId = UserDefaults.standard.value(forKey: "interactionUUID") as? String else { return }
            
            let config = ChatClientConfig(apiKey: APIKey(apiKey))
            let tokenClient =
                Token(
                    stringLiteral: token
                )
            ChatClient.shared = ChatClient(config: config)
            ChatClient.shared.connectUser(
                userInfo: UserInfo(
                    id: userNameID,
                    name: userNameID
                ),
                token: tokenClient
            )

            self.chatChannelController = ChatClient.shared.channelController(for: ChannelId(type: .team, id: interactionId))
           
            self.currentUserController = ChatClient.shared.currentUserController()
            self.currentUserController.delegate = CurrentUserDelegate()
            self.currentUserController?.synchronize()
            
            Components.default.messageListVC = ChatVC.self
            Components.default.messageComposerVC = MessageComposerVC.self
            Components.default.messageComposerView = MessageCompserView.self
            Components.default.messageContentView = ChatMessageView.self
    
        }

class CurrentUserDelegate: CurrentChatUserControllerDelegate {
    func currentUserController(_ controller: CurrentChatUserController,
                               didChangeCurrentUserUnreadCount: UnreadCount) {
        // handle unread count change
    }
}

**Comment by nuno-vieira** [comment]
@iosamar Sorry, there was a typo on Tomasso's response, what is incorrect in your snippet is this part:
`currentUserController.delegate = CurrentUserDelegate()`

You need to store the `CurrentUserDelegate()` in a strong reference or it will be automatically deallocated since the controller holds a weak ref to the delegate. Since a weak reference doesn't increment the reference count, it will always be 0 and it will never allocate memory for the delegate. 

So make sure you store the `CurrentUserDelegate()` in a property of a class.
