### ISSUE TITLE
Channel Controller not accessible in ChatChannelListVC

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-swift#1514]
## What did you do?
I want channel controller instance for get the message list according to channel selected 

## What did you expect to happen?
No instance exist of channel controller in ChatChannelListVC so please provide the proper documentation as its not exist in that class

## What happened instead?
channelcontroller instance should contains in ChatChannelListVC so we can use it as per updated documentation

## GetStream Environment
**GetStream Chat version:** 4.0.3
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 14.0
**Swift version:** 5
**Xcode version:** 12.3
**Device:** 12 Pro Max

## Additional context
![Screenshot 2021-10-05 at 7 03 33 PM](https://user-images.githubusercontent.com/54673061/136033291-d9f4260a-0867-4969-9ea5-5efb1603fc3e.png)

**Comment by nuno-vieira** [comment]
Hi @iosiappmemes the README has now been updated with the most recent docs, it should not contain anymore links to the old docs. Sorry for the inconvenience! 

Thanks for the report!
