### ISSUE TITLE
Unexpected warning: `Invalid Resource 'Sources/StreamChatUI/Resources': File not found`

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#1515]
## What did you do?

Build an XCode project with stream-chat-swift embedded & imported via SPM

## What did you expect to happen?

No warnings

## What happened instead?

Received a following warning when building it
```
Invalid Resource 'Sources/StreamChatUI/Resources': File not found.
```

## GetStream Environment
**GetStream Chat version:**
4.0.1

**Comment by adamrushy** [comment]
Thanks for reporting @MatejBalantic looking into this now 👍

**Comment by adamrushy** [comment]
Hey, @MatejBalantic I have raised PR to fix this warning https://github.com/GetStream/stream-chat-swift/pull/1516

Please let me know if this fixes your issue, thanks again for spotting this.
