### ISSUE TITLE
New member can view and access the previous chat history in a channel or  direct chat

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1520]
## the new member can view the previous chat/chat history

Is there an option to hide the previous chat /chat history when adding a new member to the direct chat/ channel ?

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by nuno-vieira** [comment]
Hi @vineethnkforios @AmalJose-01 ! 

As of right now, this feature is not available. We will discuss it internally with the backend team and will update you as soon as possible on when this feature will be planed.

Thanks for the report!

Nuno
