### ISSUE TITLE
Unable to add members in a direct message

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1530]
## I have created a direct message with 2 members initially, and when I try to add another member to the direct message group then returns an error.

I can add the same users to a newly created channel...

Is the direct message is working like above ?

iOS SDK Version 4.0.4

I think the SDK version (4.0) was working for both direct message/Channel case

## What did you expect to happen?
 Able to add the other users too

## What happened instead?
Attached screenshot

![Screenshot 2021-10-08 at 6 01 32 AM](https://user-images.githubusercontent.com/78809766/136537907-01a1159b-3329-4bbc-8b18-f4cdd5edebe6.png)

## GetStream Environment
**GetStream Chat version:**4.0.4
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**ios 15
**Swift version:**5
**Xcode version:**
**Device:**iphone, ipad

**Comment by tbarbugli** [comment]
can you share the code that you are using?

**Comment by vineethnkforios** [comment]
@nuno-vieira @tbarbugli Thanks for your quick response..

**Comment by vineethnkforios** [comment]
It's ok...
I have one more query : When leaving from a channel the channel is also deleted from the history -
