### ISSUE TITLE
Removing a member is not currently working, and is able to still access the channel/DM

### ISSUE THREAD

**Issue by anjuarevero** [GetStream/stream-chat-swift#1546]
## What did you do?
Remove a member from channel /DM (Owner removed a member after few chats )

## What did you expect to happen?

Removed member should not able to view the channel/DM
## What happened instead?
Removed member list is not updating , he will be able to see and send message to the channel/DM again 

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by abhijithevero** [comment]
Similar Issue found in DM channel
Spinner stops me

**Comment by vineethnkforios** [comment]
In my case remove Members functionality is working and has no errors, but after removing the channel list is not updating...

**Comment by adamrushy** [comment]
@vineethnkforios @anjuarevero 

We have started working on a 'patch' to get this issue resolved quickly. We have a long term fix that we're also working on which will take a little longer to work on. Thanks for your patience 👍🏼

**Comment by vankien96** [comment]
@adamrushy I face the same issue. Hopefully, you can fix it soon.
