### ISSUE TITLE
App crashes when trying to get / access to the ChatChannelController observableObject

### ISSUE THREAD

**Issue by yensi-vega** [GetStream/stream-chat-swift#1550]
## What did you do?
We implemented a chat view using SwiftUI (with SDK 3.x), and to get support for iOS 13.x (but we use mostly > iOS 14.x), we use EnvironmentObject instead StateObject and it worked well.
After update our App to use StreamChat 4.0.1, we tested the App in iOS 13.5 and the App crashes when accessing to ChatChannelController observableObject (When it didn't happen before)
Note: The App works on iOS 14 and iOS 15.

## What did you expect to happen?
The app does not crash in iOS  13.5

## What happened instead?
The App Crashes with EXEC_BAD_ACCESS exception

## GetStream Environment
**GetStream Chat version:** SDK 4.0.1
**GetStream Chat frameworks:**  StreamChat
**iOS version:** 13.5
**Swift version:** 5
**Xcode version:** 13.0
**Device:** sim iPhone 11 

## Additional context
![image](https://user-images.githubusercontent.com/47642891/137362636-fe42d413-240e-41ab-b149-d9323dd0fa12.png)

chatViewModel is an environmentObject and contains and optional ChatClientController
`var maybeStreamChannel: ChatChannelController?`

ChatView receive an ChatClientController observableObject as ObserverdObject
![image](https://user-images.githubusercontent.com/47642891/137363262-e01032d3-f93c-4d11-9dc4-9849bda69ba7.png)

This was working well before in iOS 13, but now it doesn't

We really will appreciate some advice in order to support iOS 13 to our clients.

Thanks in advance.

**Comment by bielikb** [comment]
Hi @yensi-vega could you please check if the issue still occurs on the latest release (v4.5.0)?

If it still occurs, could you please provide us with a simple sample app (in a zip format or as a fork) that showcases your issue? We will than get it from there. 

☝️We have a [standalone repo with a simple integration app](https://github.com/GetStream/stream-chat-swift-integration-apps) that you could leverage - it will save you some time with setting up your own app.

Thanks!

Best,
Boris

**Comment by bielikb** [comment]
Hi @yensi-vega just checking once again. Could you please follow the above suggested steps from my previous post?

PS: the latest version is 4.5.1

**Comment by nuno-vieira** [comment]
This issue should be resolved now @yensi-vega. Feel free to re-open if you find any problem.

Thank you for the report!
