### ISSUE TITLE
Using CocoaPods, with Xcode 13 is failing to load assets

### ISSUE THREAD

**Issue by adamrushy** [GetStream/stream-chat-swift#1566]
## Issue

We are currently aware of the issue within CocoaPods and archiving using Xcode 13. We have raised this issue with CocoaPods [here](https://github.com/CocoaPods/CocoaPods/issues/11011) and we'll continue to monitor the situation.

If your project can, we recommend switching to use Swift Package Manager or Carthage. However, if you need to use CocoaPods there is a short term fix that you can apply.

1. Locate the assets catalog file (StreamChatUI -> Resources -> Assets)
2. Show the file inspector panel within Xcode
3. Make sure both (StreamChatUI & StreamChatUI-StreamChatUI) targets are selected.

![Screenshot 2021-10-18 at 14 43 57](https://user-images.githubusercontent.com/1519998/138104850-18922b09-2610-4fb2-89e8-6ab42b2f4f8e.png)

## What did you do?

1. Integrate using CocoaPods
2. Archive the project using Xcode 13
3. Publish on TestFlight

## What did you expect to happen?

1. Icons are loaded from the bundle file.

## What happened instead?

1. All the assets are missing

**Comment by adamrushy** [comment]
Just an update on this, we've expedited internally and doing some more investigation as we've not had a response from CocoaPods just yet. We'll keep you updated, thank you.

**Comment by adamrushy** [comment]
@whiplash00 I have raised a PR that should resolve this issue. I was wondering if you can for me on your project? https://github.com/GetStream/stream-chat-swift/pull/1602

**Comment by whiplash00** [comment]
@adamrushy happy to do so.
