### ISSUE TITLE
NotificationMessageNewEvent not triggered

### ISSUE THREAD

**Issue by jderes** [GetStream/stream-chat-swift#1587]
Hello,
I want to display local notifications for new messages from user's channels.
After the app starts i set EventsHandler's delegate and i'm properly receiving NotificationMessageNewEvent events: 
`public func eventsController(_ controller: EventsController, didReceiveEvent event: StreamChat.Event) {`
 `          guard let event = event as? NotificationMessageNewEvent else { return }`
`           log.info("new message: \(event.message.text)")`
 `}`
However, when i open the channel screen (ChatChannelVC) and leave it, the notifications stop coming. 
ChatChannelVC is deallocated correctly. Instead i'm starting to receive MessageNewEvent events. 
I'm not sure why is this happening, can i "leave" the channel somehow to get the events back?
What is the correct approach when i want to see new message events for channels i'm not currently seeing and that i'm member of ?

**Comment by tbarbugli** [comment]
The `NotificationMessageNewEvent` is fired for channel members that are not watching the channel, once you start watching the channel the `MessageNewEvent` event is fired instead.

You can either stop watching the channel when the ChatChannelVC is removed from screen (just keep in mind that other users will see that user leaving the channel) or you can listen for both `MessageNewEvent` and `NotificationMessageNewEvent` channel events.

The `stopWatching` method is exposed by the `ChannelController` class.

**Comment by jderes** [comment]
That makes sense, thanks.
