### ISSUE TITLE
Some full screen photos (Live Photos) weird flicker when presented / dismissed to / from full screen.

### ISSUE THREAD

**Issue by vladpre92** [GetStream/stream-chat-swift#1588]
## What did you do?
Open channel screen.
Tap images to present them full screen.

## What did you expect to happen?
All of them to be displayed full screen without flicker.

## What happened instead?
Some of them present full screen with weird flicker.

## GetStream Environment
**GetStream Chat version:** 4.2.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 15.0
**Swift version:** 5
**Xcode version:** 13.1
**Device:** Simulators, iPhone 7

## Additional context
After some testing, it seems that this problem happens mostly with images from gallery captured with camera as Live Photos.

I reproduced this using your demo app.

https://user-images.githubusercontent.com/3681654/139290367-33661a07-4eb4-4d24-828f-68ec6123376e.mov

Thank you!

**Comment by nuno-vieira** [comment]
Hi @vladpre92, this issue doesn't seem reproducible in the more recent versions of the SDK, can you confirm?

Thank you!

**Comment by vladpre92** [comment]
Hello,
Yes indeed with newer versions (I use 4.7.0) is very hard to reproduce this. I tested with live photos just now. Before, I was able to reproduce this issue with any photo taken with phone camera.

**Comment by bielikb** [comment]
Hi @vladpre92,

I was able to repro this issue. I created issue in our internal backlog. We will try to fix this issue in one of the following updates.
Once released, we'll keep you updated.

Best,
Boris

**Comment by bielikb** [comment]
Hi @vladpre92,

we just released [new version of our SDK 4.14.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.14.0) that contains the fix for your reported issue.

Feel free to grab it at your convenience.

Thanks again for your help! 🙌

Best,
Boris
