### ISSUE TITLE
How to localise popup titles?

### ISSUE THREAD

**Issue by NullIsOne** [GetStream/stream-chat-swift#159]
I have a multi-language application.
For example, I want set localised title for `AddFileContainerView` and all default uploading option titles. 
You have hardcoded English strings in source code.
So, I've tried to override some open method. 
I see that [createComposerAddFileContainerView](https://github.com/GetStream/stream-chat-swift/blob/af7a3cad248b4f6e9c430809108c5dcbf9c0eec9/Sources/UI/Chat/Chat%20View%20Controller/ChatViewController%2BComposer.swift#L338) is open.
But got `Overriding non-@objc declarations from extensions is not supported`
Any suggestions, how to add localised titles?

**Comment by b-onc** [comment]
Hello @NullIsOne 
Thank you for this ticket, it surfaces a problem: our `open` functions should not be in extensions.
Localization of popup titles is not supported at the moment, but it's definitely in our roadmap.

**Comment by NullIsOne** [comment]
Ok.
I'll wait for updates.

**Comment by arthurchambsp** [comment]
Hello !

Almost same use case here. I have a multi-language application and I want to translate "This message was deleted." text but it's hardcoded too.

I stay tuned for localisation updates 👍

**Comment by NullIsOne** [comment]
Btw, I made a [fork](https://github.com/nsrgh/stream-chat-swift/tree/lokalisation) with localisation support and include German translation.
Maybe someone can find it useful.
