### ISSUE TITLE
StreamChatUI via XCFramework

### ISSUE THREAD

**Issue by j-j-m** [GetStream/stream-chat-swift#1594]
## What are you trying to achieve?
Due to a version incompatibility in Starscream (also used by AWS Amplify) I am trying to use `StreamChatUI` in an XCFramework via a binaryTarget in SPM. `StreamChat` works in this way but  `StreamChatUI` results in a bunch of missing symbols.

I have tried manually building the framework into an XCFramework and also using the built products from Carthage.

## If possible, how can you achieve this currently?

I can't AFAIK

## What would be the better way?
would be awesome if you packaged XCFrameworks along with your releases (if possible)

## GetStream Environment
**GetStream Chat version:** 4.2.0
**GetStream Chat frameworks:** StreamChatUI
**iOS version:** 15
**Swift version:** 5.5.1
**Xcode version:** 13
**Device:** any

**Comment by adamrushy** [comment]
Thanks for opening this @j-j-m this is a topic we're discussing currently internally and we'll update you on the progress of this. Thank you.
