### ISSUE TITLE
Channel type is "messaging" for watch requests

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#16]
### Context
- One channel with type "team"
- One channel with type "messaging"

### Steps
1.) Start app
2.) Fetch channels for type "team" via `ChannelsPresenter`
3.) Fetch channels for type "messaging" via `ChannelsPresenter`
4.) SDK starts watching on a "team" channel

## What did you expect to happen?
The channel with type "team" is not visible all channels with type "messaging".

## What happened instead?
The channel with type "team" is duplicated and the new channel gets the type "messaging".

I did a little debugging and found out that the SDK **always** tries to watch a channel based on the `channel_id` **and** the default type "messaging" (Channel.swift:88), see `ChannelPresenter.swift:99` and `Client+Event.swift:36`.

This causes the *watch* request (POST) to create a new channel for the given `channel_id` with type "messaging" because there is no channel with `messaging:channel_id` only a channel for the cid `team:channel_id`.

## GetStream Environment
**GetStream Chat version: 1.3.0 **

**Comment by buh** [comment]
Thanks @janweinkauff! I'll fix it today.

**Comment by buh** [comment]
Fixed in v.3.2
