### ISSUE TITLE
When Pod Updated Version 4.1.0 to 4.5.0  errors found .

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#1629]
## What did you do?
Updated Streamchat Version 4.1.0 to 4.5.0

## What did you expect to happen?
No errors

## What happened instead?
2 errors found 
Error No1:
Class Name : MessageDTO.swift
Function Name: func saveMessage(payload: MessagePayload, for cid: ChannelId?) throws -> MessageDTO? {

Error No2:
Class Name : DatabaseSession.swift
Function Name: func saveEvent(payload: EventPayload) throws {

See the screenshots
![Screen Shot 2021-11-17 at 1 29 18 AM](https://user-images.githubusercontent.com/78809766/142149703-f9743c4a-efc2-4060-8b95-8ed152f64ff6.png)
![Screen Shot 2021-11-17 at 1 30 00 AM](https://user-images.githubusercontent.com/78809766/142149708-9e791e4d-9807-4d6c-b5c7-7e83aef98978.png)

Modified the code like below and seems ok for now. Can we proceed like this ?
***************************************
MessageDTO.swift
***************************************.  *************************************** 
func saveMessage(payload: MessagePayload, for cid: ChannelId?) throws -> MessageDTO? {
        guard payload.channel != nil || cid != nil else {
            throw ClientError.MessagePayloadSavingFailure("""
            Either `payload.channel` or `cid` must be provided to sucessfuly save the message payload.
            - `payload.channel` value: \(String(describing: payload.channel))
            - `cid` value: \(String(describing: cid))
            """)
        }

        if let cid = cid, let payloadCid = payload.channel?.cid {
            log.assert(cid == payloadCid, "`cid` provided is different from the `payload.channel.cid`.")
        }

        var channelDTO: ChannelDTO?

        if let channelPayload = payload.channel {
            channelDTO = try saveChannel(payload: channelPayload, query: nil)
        } else if let cid = cid {
            channelDTO = ChannelDTO.load(cid: cid, context: self)
        } else {
            log.assertionFailure("Should never happen because either `cid` or `payload.channel` should be present.")
            return nil
        }
        /*
        guard let channelDTO = channelDTO else {
            log.assertionFailure("Should never happen, a channel should have been fetched.")
            return nil
        }*/
        
        return try saveMessage(payload: payload, channelDTO: channelDTO!)
    }
***************************************.  ***************************************. 

DatabaseSession.swift

func saveEvent(payload: EventPayload) throws {
        // Save a user data.
        if let userPayload = payload.user {
            try saveUser(payload: userPayload)
        }
        
        var channelDTO: ChannelDTO?

        // Member events are handled in `MemberEventMiddleware`
        
        // Save a channel detail data.
        if let channelDetailPayload = payload.channel {
            channelDTO = try saveChannel(payload: channelDetailPayload, query: nil)
        }
        
        if let currentUserPayload = payload.currentUser {
            try saveCurrentUser(payload: currentUserPayload)
        }
        
        if let unreadCount = payload.unreadCount {
            try saveCurrentUserUnreadCount(count: unreadCount)
        }
        
        if let currentUser = currentUser, let date = payload.createdAt {
            currentUser.lastReceivedEventDate = date
        }

        guard let message = payload.message, let cid = payload.cid else {
            return
        }

        guard let context = self as? NSManagedObjectContext else {
            return
        }

        if channelDTO == nil {
            channelDTO = ChannelDTO.load(cid: cid, context: context)
        }

        /*
        guard let channelDTO = channelDTO else {
            log.info("event contains a cid that is not yet known, skipping")
            return
        }*/

        let messageDoesNotExist = MessageDTO.load(id: message.id, context: context) == nil
        
        let eventsThatCreateMessages: Set<EventType> = [
            .channelUpdated, .messageNew, .notificationMessageNew
        ]

        if messageDoesNotExist && !eventsThatCreateMessages.contains(payload.eventType) {
            return
        }
        
        try saveMessage(payload: message, channelDTO: channelDTO!)
    }

***************************************.  ***************************************

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by tbarbugli** [comment]
thank you for reporting this, could you share the version of XCode that you are using?

**Comment by vineethnkforios** [comment]
> thank you for reporting this, could you share the version of XCode that you are using?

12.5.1

**Comment by bielikb** [comment]
Hi @vineethnkforios,

thanks for clarifying the version of the Xcode that you're using.
We're currently working on providing fix for this issue and we will cover the issue in upcoming release.

If you want to get unblocked faster, you could upgrade (if possible) to Xcode 13.0+ where variable shadowing is correctly handled by compiler.

**Comment by tbarbugli** [comment]
@vineethnkforios if you have the chance, it would be great if you give the `fix-xcode12-shadow` a test and see if that works for your case. We are working on a fix for this as well as run CI on Xcode 12 and 13 but that is going to take a few days

**Comment by tbarbugli** [comment]
quick update, this is now fixed on main and will be release on the coming days

**Comment by bielikb** [comment]
Hi @vineethnkforios,

we just released new version [4.5.1](https://github.com/GetStream/stream-chat-swift/releases/tag/4.5.1) that contains fix for your issue.

Can you please give it a try and let us know if your issue got resolved by 4.5.1?

Thanks!

Best,
Boris
