### ISSUE TITLE
Error while creating chat

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#165]
## What did you do?
trying to create chat(one to one and group )

## What did you expect to happen?

that chat should be created .
## What happened instead?

Chat is been created ,but gives error on first time afterwards it never gives error 

![Simulator Screen Shot - iPhone X - 2020-04-09 at 19 01 31](https://user-images.githubusercontent.com/37240061/78904263-e17ef400-7a99-11ea-8934-d7ae2532021b.png)

## GetStream Environment
**GetStream Chat version:**2.0.1
**iOS version:**13.3
**Swift version:**5
**Xcode version:**11.3.1
**Device:**Simulator

**Comment by b-onc** [comment]
Hello @shireeshMs 
Are you using our master branch? I see that something is broken is master but shouldn't be in 2.0.1

**Comment by shireeshMs** [comment]
Yes I have taken pull from master and then after deleting the podfile.lock
file run pod install(yes its says stream chat 2-0-1 ).

Any idea how to dig this,as i had taken pull for network issues and now i
can see it is working with just this issue which
“streamcharclient.anyError.error.1”
