### ISSUE TITLE
Make dateFormatter open in ChatMessageContentView

### ISSUE THREAD

**Issue by kishinmanglani** [GetStream/stream-chat-swift#1667]
## Make dateFormatter open in `ChatMessageContentView` to allow for custom `DateFormatter`

`dateFormatter` is currently `public`, not `open`, so I can't override 

## GetStream Environment
**GetStream Chat version: 4.6

**Comment by b-onc** [comment]
Hello @kishinmanglani ,

Thank you for the report. We'll make sure `dateFormatter` can be customized in a future release, although I can't promise a version for it.
Fortunately, there's a workaround: You can create and use your own `DateFormatter` to customize `timestampLabel`:
```swift
class CustomMessageContentView: ChatMessageContentView {
    
    lazy var customDateFormatter: DateFormatter = {
        DateFormatter()
    }()
    
    override open func updateContent() {
        super.updateContent()
        
        if let createdAt = content?.createdAt {
            timestampLabel?.text = customDateFormatter.string(from: createdAt)
        } else {
            timestampLabel?.text = "before big bang"
        }
   }
}
```

Let me know if this resolves your question.

**Comment by bielikb** [comment]
Hi @kishinmanglani,

our latest release 4.10.0 now provides a way to format the timestamps in more convenient way. Make sure to check our [Data Formatting](https://getstream.io/chat/docs/sdk/ios/uikit/data-formatting/) article to learn more.
