### ISSUE TITLE
ChatMessage.currentUserReactions is not accurate

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#1677]
## What did you do?
I want to access `ChatMessage.currentUserReactions` from my `ChatMessageContentView` subclass method `updateContent`. The simplest way to see the bug behavior is to add a print statement to the Stream Demo app (see below).

## What did you expect to happen?
I expected the contents of `ChatMessage.currentUserReactions` to always be accurate.

## What happened instead?
The contents of `ChatMessage.currentUserReactions` is _sometimes_ accurate but not always. The release which introduced this behavior is 4.5.0.

## GetStream Environment
**GetStream Chat version:** 4.5.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
The simplest way to recreate this is to add a print statement at the end of `ChatMessageContentView.updateContent()`:
```
        if content?.text == "Hey" {
            print("currentUserReactions: \(content?.currentUserReactions ?? [])")
        }
```
Replace the string comparison with something that uniquely identifies one message in the chat, just to keep it simple.

When you add a reaction to a message, the following prints are seen in the console:
```
currentUserReactions: [StreamChat.ChatMessageReaction(type: StreamChat.MessageReactionType(rawValue: "haha"), score: 1, createdAt: 2021-12-08 23:54:16 +0000, updatedAt: 2021-12-08 23:54:16 +0000, author: StreamChat.ChatUser, extraData: [:])]
currentUserReactions: [StreamChat.ChatMessageReaction(type: StreamChat.MessageReactionType(rawValue: "haha"), score: 1, createdAt: 2021-12-08 23:54:16 +0000, updatedAt: 2021-12-08 23:54:16 +0000, author: StreamChat.ChatUser, extraData: [:])]
currentUserReactions: [StreamChat.ChatMessageReaction(type: StreamChat.MessageReactionType(rawValue: "haha"), score: 1, createdAt: 2021-12-08 23:54:16 +0000, updatedAt: 2021-12-08 23:54:16 +0000, author: StreamChat.ChatUser, extraData: [:])]
currentUserReactions: []
currentUserReactions: []
currentUserReactions: []
```

The first few prints are accurate but the last few are not and that is the bug behavior.

**Comment by evsaev** [comment]
Hey there @srgray 👋 

Thanks for the report and especially for the extensive context! 
I'm looking into this issue and will keep you posted with the updates.

Thank you!

**Comment by evsaev** [comment]
@srgray yes, I can confirm the issue takes place. I'm taking it to work and will ping you once it's fixed.

**Comment by evsaev** [comment]
Hey @srgray 👋 

We've just rolled out the [4.5.2](https://github.com/GetStream/stream-chat-swift/releases/tag/4.5.2 ) release with the fix. Feel free to reopen this issue it you'll notice the regression is still there.

Thank you so much! 🤝
