### ISSUE TITLE
Namespace Conflict with User

### ISSUE THREAD

**Issue by alaxicsmith** [GetStream/stream-chat-swift#168]
## What did you do?

When trying to initialize a user with stream, I'm getting a namespace conflict because I have a model named 'User'. 

## What did you expect to happen?

I expected to be able to initialize the User.

## What happened instead?

Received an error as a result of conflicting namespaces, because it was trying to reference my User model.

## Additional context

I attempted to use a typealias, still no luck.

**Comment by buh** [comment]
Hi @alaxicsmith 
Try this: `StreamChatClient.User(id: ...)`

**Comment by alaxicsmith** [comment]
@buh Awesome, that worked. Would be helpful to cover this in the docs, since 'User' is a common class name.

**Comment by buh** [comment]
Thanks, we’ll add this in our docs.
