### ISSUE TITLE
Query request to set presence state adds duplicated member

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#17]
## What did you do?
- We have a channel with two users where the current user is a member
- If we enter the channel to subscribe messages, the presence state will be set by SDK via the query call

## What did you expect to happen?
- The query call changes only the presence state

## What happened instead?
- The presence state is changed
- The SDK adds also a duplicate to the members **set** of the channel

Which will result  in an empty channel on the next try because of the failed query HTTP call which returns the following error message:
```
{
	"code": 4,
	"message": "GetOrCreateChannel failed with error: \"Duplicate members passed to get or create channel, only send 1 member once\"",
	"StatusCode": 400,
	"duration": "0.00ms"
}
```

## GetStream Environment
**GetStream Chat version: 1.3.2** 

## Additional context

We tried to trace back the issue and found out that the code at `Channel+Requests.swift:23`
```
if let user = User.current {
  members.insert(user.asMember)
}
```
adds the duplicate. This is confusing because it should be a **set** and ignore users with the same identity. So, we checked the equality operator on the member type, see `Member.swift:72`.
```
public static func == (lhs: Member, rhs: Member) -> Bool {
  return lhs.user == rhs.user
    && lhs.created == rhs.created
    && lhs.updated == rhs.updated
}
```
Besides the identity of the user the function also checks for dates which are different for the `User.current` than the orignial user because they are initialize with the current date, see `User.swift:99`
```
created = .default
updated = .default
```
The initializer of the user type is used to do the intial setup with `Client.shared.set(user:token:)`

**Comment by buh** [comment]
Hi Jan!
Thanks! I'll fix it today.

**Comment by buh** [comment]
Fixed v.1.3.3
Please check a new observable channel variable: `onlineUsers`, that could be useful for you.
https://getstream.github.io/stream-chat-swift/core/Classes/Channel.html#/s:14StreamChatCore7ChannelC11onlineUsers7RxCocoa14SharedSequenceVyAE21DriverSharingStrategyVSayAA4UserVGGvp

So, you no need to open chat screen to get online users:
For example:
https://github.com/GetStream/stream-chat-swift/blob/master/Example/ChatExample/RootViewController.swift#L32-L46

**Comment by janweinkauff** [comment]
Looks great, I will test it - Thanks! 👌🏻

**Comment by buh** [comment]
Please check new changes in SDK.
https://github.com/GetStream/stream-chat-swift/releases/tag/1.3.3

**Comment by janweinkauff** [comment]
Hey @buh, I started to test your fixes and I would like to claim that this part of the `Hashable` implementation must also change (Members.swift:76) from:
```
public func hash(into hasher: inout Hasher) {
  hasher.combine(user)
  hasher.combine(created)
  hasher.combine(updated)
}
```
to:
```
public func hash(into hasher: inout Hasher) {
  hasher.combine(user)
}
```
Otherwise the `set` type will no be able to recognize an identity collision.

**Comment by buh** [comment]
Thanks, a lot! But for now it anyway should work.

**Comment by janweinkauff** [comment]
Yes, usually it would work but not in this case because the `created` and `updated` dates of `user.asMember` will be the current date of instance creation (.default) which will not match with the original values of the same member which is returned by the API.

**Comment by buh** [comment]
Yes, but I changed API to use array :)

**Comment by janweinkauff** [comment]
Ah, now I understand your point of view :-D I was talking about the `members` set and you may talk   about the `onlineUsers` array, right?

**Comment by buh** [comment]
Sorry for misunderstanding, I changes members to array, so control the uniqueness by the API, but probably will change members to `Set` back ;)

**Comment by janweinkauff** [comment]
Ah sorry, I was only talking about 1.3.3 because we use always the last pod version - I didn't saw your last commits - I guess you mean this one:
https://github.com/GetStream/stream-chat-swift/commit/93896b6a7d76db8013f0dee3434dd357109b0c83

**Comment by buh** [comment]
Oh, I'm sorry, I thought I released it. So, no, I'll definitely will back to Set :)

**Comment by janweinkauff** [comment]
Ok, enough of confusion, I will just wait for your next release 😂

**Comment by buh** [comment]
Thanks, any other issues? wishes? :)

**Comment by janweinkauff** [comment]
Not yet and certainly in the future 😉
