### ISSUE TITLE
Separate set/delete of user metadata from connection 

### ISSUE THREAD

**Issue by j-j-m** [GetStream/stream-chat-swift#1705]
## What are you trying to achieve?

when I set extraData on a user 

```swift
userClient.updateUserData(
                            userExtraData: [
                                "recentChannels" : .array(array)
                            ],
                            completion: nil
                        )
```

I can see this data reflected in the data explorer. 

now if I rebuild my app and execute the following

```swift
chatClient.connectUser(
                    userInfo: .init(
                        id: username,
                        name: username
                    ),
                    token: Token(stringLiteral: token)
                )
```

the extra data is wiped...  this is also the case with the imageURL, etc

## What would be the better way?

it would be wonderful to separate the setting/deletion of user metadata from connecting a user

## GetStream Environment
**GetStream Chat version:** 4.5.1
**GetStream Chat frameworks:** StreamChat
**iOS version:** 15
**Swift version:** 5.x
**Xcode version:** 13.1
**Device:** all?

**Comment by tbarbugli** [comment]
@j-j-m thank you for reporting this, I am looking into it and will let you know soon

**Comment by tbarbugli** [comment]
@j-j-m I am having trouble reproducing this problem on iOS. Just to clarify both `updateUserData` and `connectUser` use an upsert approach for user fields.

This is what I did to try and reproduce the problem:

```swift
ChatClient.shared = ChatClient(config: config)
ChatClient.shared.connectUser(
    userInfo: .init(id: username, name: username),
    token: token
) { error in
    if let error = error {
        log.error("connecting the user failed \(error)")
        return
    }
    ChatClient.shared.currentUserController().updateUserData(userExtraData: [
        "testing-this": .number(3.14)
    ])
}
```

I tried all possible combinations with and without the `updateUserData` call but I did not manage to get `connectUser` or  `updateUserData` to remove a field by omission.

Do you mind looking into this and see if you can reproduce this on your end? (or let me know if I am missing something)

**Comment by j-j-m** [comment]
I think you may be missing something. if you run the code you posted above then remove the 
```swift
ChatClient.shared.currentUserController().updateUserData(userExtraData: [
        "testing-this": .number(3.14)
    ])
 ```   
 from the connect user callback and run your code again does the "testing-this" field remain?
 
 In my case I am adding a channel id to an array on my users extraData to track my recently viewed channels. when I restart the app this and subsequently reconnect a user this extra data is cleared after `chatClient.connectUser` is called

**Comment by tbarbugli** [comment]
@j-j-m I tried all possible combinations (running connect+updateUserData, then connect only, then updateUserData again, ...) but never managed to reproduce this. Do you have any other code update users? (perhaps running server-side)

**Comment by j-j-m** [comment]
I really don't think so, but I can make 100% certain. I wonder if maybe this is because I am using a development app.

**Comment by j-j-m** [comment]
you know that might be it. I see updateUser being called when our server side code generates a token. probably don't need to do that.

**Comment by j-j-m** [comment]
This was the case. thanks for helping me work through this.
