### ISSUE TITLE
Presenting message popup actions without reactions view controller causes glitch on options list view

### ISSUE THREAD

**Issue by vladpre92** [GetStream/stream-chat-swift#1710]
## What did you do?
Tried to present popup actions list for a message, but without  reactions view controller.

## What did you expect to happen?
Show message popup actions list without glitch.

## What happened instead?
Message popup actions list presented with glitch.

## GetStream Environment
**GetStream Chat version:** 4.5.2
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.0
**Swift version:** 5
**Xcode version:** 13.1
**Device:** All devices

## Additional context

Hi guys,

Tried to present message actions popup list without reactions view controller but I get a glitch that you can see in the attached videos.
Basically I've subclassed ChatMessageListRouter and overriden `showMessageActionsPopup` method with:

```
    override func showMessageActionsPopUp(
        messageContentView: ChatMessageContentView,
        messageActionsController: ChatMessageActionsVC,
        messageReactionsController: ChatMessageReactionsVC?
    ) {
        let isNewPost = messageContentView.content?.isNewPost ?? false
        let isVoiceNote = messageContentView.content?.isVoiceNote ?? false
        if isNewPost {
            return
        } else {
            super.showMessageActionsPopUp(
                messageContentView: messageContentView,
                messageActionsController: messageActionsController,
                messageReactionsController: isVoiceNote ? nil : messageReactionsController
            )
        }
    }
```

Thank you!

https://user-images.githubusercontent.com/3681654/146782675-24ba86d7-5a09-406b-8507-a58f6f02296f.MP4

https://user-images.githubusercontent.com/3681654/146782685-18bc2299-c82f-4d53-95ba-9b1b8d74933f.MP4

**Comment by nuno-vieira** [comment]
Hi @vladpre92!

Thanks for reporting this issue! We will tackle this as soon as possible and let you know when we have a fix for this 🙂 

Best,
Nuno

**Comment by tbarbugli** [comment]
@nuno-vieira easy way to reproduce this (ChatMessageListRouter)

![image](https://user-images.githubusercontent.com/88735/147890771-70c4f880-60fb-402a-a21b-1b461f1e7a09.png)

If you enable slow animations you can see clearly what is going on

**Comment by nuno-vieira** [comment]
Hi @vladpre92!

Thank you for your patience on this one! This fix will be part of the next release 👍

We will close the issue once the next release is published.

Best,
Nuno

**Comment by evsaev** [comment]
Hi @vladpre92,

I'm happy to say that [4.15.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.15.0) containing the fix for the reported issue is released 🎉

I'm closing the issue but feel free to reopen if you still face it 🙂 

Thanks and enjoy your day!

Best,
Pavel
