### ISSUE TITLE
Recent Chat is not getting updated after creating any new group or 1-1 chat .

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#173]
## What did you do?
I initiated the chat of types :
1-1 Chat
Group Chat

## What did you expect to happen?
I expect them they should appear in my recent chat but no luck mate !

## What happened instead?
ahhh thats interesting ,I would like to tell in both cases respectively:
1)If I initiate a new chat with User A it will update recent chat of User A but on my side it won't appear(sometimes it does but most of the time no luck) .
2)If I initiate a group chat by adding members(User A,UserB,UserC)so what happens next it will update All three user A,b and C's recent chat and will show newly created chat on their side on the contrary it won't appear on my side .

Note*** This newly created chat thread do get appear to me only when I receive any message from newly created chat .

## GetStream Environment
**GetStream Chat version:**2.0.1
**iOS version:**13.4.1
**Swift version:**5
**Xcode version:**11.4
**Device:**iPhone and Simulator

**Comment by buh** [comment]
Hi @shireeshMs!
Can you show me the code for both cases? How do you create channels?
Did you see `.notificationAddedToChannel` event in logs on your side?
Thanks a lot!

**Comment by kanekv** [comment]
We are seeing same problem as well (on 1.5.5 sdk version though). But conversations seem to never update in a lot of circumstances.

**Comment by shireeshMs** [comment]
@buh here is what I have written for both cases :
1)1-1 Chat 
<img width="1630" alt="Screenshot 2020-04-16 at 8 46 01 PM" src="https://user-images.githubusercontent.com/37240061/79473834-4bac1180-8023-11ea-948b-655b4e569dc8.png">
2) group Chat
here this screenshot just displays the loop i iterate to get all members
<img width="1625" alt="Screenshot 2020-04-16 at 8 47 38 PM" src="https://user-images.githubusercontent.com/37240061/79474003-84e48180-8023-11ea-9949-90d3e7442fa5.png">

this is the code for creating group chat
<img width="1632" alt="Screenshot 2020-04-16 at 8 47 13 PM" src="https://user-images.githubusercontent.com/37240061/79474095-a04f8c80-8023-11ea-9aaf-efb5bb2da276.png">

then after notification post on my channels controller ,tried presenter.reload() but could not get any luck .

**Comment by buh** [comment]
Thanks @shireeshMs!
I'll take a look.
