### ISSUE TITLE
ChatMessageCell dateSeparatorView property should be public

### ISSUE THREAD

**Issue by vladpre92** [GetStream/stream-chat-swift#1739]
## What did you do?
Tried to override ChatMessageCell dateSeparatorView content format.

## What did you expect to happen?
To be able to do it.

## What happened instead?
I can't.

## GetStream Environment
**GetStream Chat version:** 4.7.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** Any
**Swift version:** 5
**Xcode version:** 13.1
**Device:** Any

## Additional context
Hi guys!

Tried to override the date format for date overlay view for a message list view using `func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell` delegate method from `ChatMessageListVC` but I couldn't because of the internal access of this view (`dateSeparatorView` from `ChatMessageCell`).

I think we should be allowed to do this. Or...is there another approach to do this?

Thank you!

**Comment by nuno-vieira** [comment]
Hi @vladpre92! Indeed the `dateSeparatorView` is meant to be internal for now. Anyway, one way should be able to change this is by changing the `DateFormatter.messageListDateOverlay` but unfortunately the formatted is a `static let` and it should be a `static var` instead. We can open a quick PR to change this. Would this be enough for you? Or by changing only the formatter is not enough for you? If it is not, we can consider opening the `dateSeparatorView`.

Thank you again!

**Comment by vladpre92** [comment]
Thank you for your prompt response!
Either way is ok for us. 
Thank you!

**Comment by bielikb** [comment]
Hi @vladpre92,

we're going to add possibility to configure your formatters in one of the following releases.

We will notify you, once this is done.

Best,
Boris

**Comment by nuno-vieira** [comment]
Hi @vladpre92,

Thank you for your patience!

Our latest release 4.10.0 now provides a way to format the timestamps in a more convenient way. Make sure to check our [Data Formatting](https://getstream.io/chat/docs/sdk/ios/uikit/data-formatting/) article to learn more.

In your particular case, if you change the `Appereance.formatters.messageListSeparator`with your custom one, it will change the style on both the ribbon between each message group and also the top overlay ribbon. Let us know if you have any questions on how to use the formatters. If you do, please re-open this issue 🙂
