### ISSUE TITLE
channelRole key required in ChatChannelMember

### ISSUE THREAD

**Issue by Mohammed-Shafeer** [GetStream/stream-chat-swift#1750]
## What did you do?
channelRole key is missing in ChatChannelMember

## What did you expect to happen?
channelRole key should be present

## What happened instead?
channelRole key is missing

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by tbarbugli** [comment]
@Mohammed-Shafeer can you provide some more information about this? From which type is `channelRole` missing?

**Comment by Mohammed-Shafeer** [comment]
I have exposed the _channelRole_ key in the following [PR](https://github.com/GetStream/stream-chat-swift/pull/1751)
Please check 
Thanks Much

**Comment by adamrushy** [comment]
Hey, @Mohammed-Shafeer thanks for opening this issue and the PR.

We're having to make some tweaks to your requested changes and we'll let you know when it's ready 👍🏼 

Thanks,
Adam

**Comment by bielikb** [comment]
Hey @Mohammed-Shafeer,

we track the work internally, for now, we're going to close your PR and resolve the issue in one of the following iOS releases.

Thanks for your findings, they're really appreciatted.
We will keep you updated!

Best,
Boris

**Comment by adamrushy** [comment]
Hey, @Mohammed-Shafeer 

I have linked the PR for this work and I want to thank you for your patience.

Thank you,
Adam
