### ISSUE TITLE
Cannot perform actions on long messages.

### ISSUE THREAD

**Issue by virbedi** [GetStream/stream-chat-swift#1756]
## What did you do?
Sent a long message in chat.
Tried to long press on message to get action list.

## What did you expect to happen?
Action list for message is visible

## What happened instead?
Could not see the action list, long message took up entire screen.

## GetStream Environment
**GetStream Chat version:** = StreamChatUI 4.8
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS 15.2
**Swift version:** Swift 5
**Xcode version:** 13.2.1
**Device:** iPhone 7 Plus, iPhone 13 Pro Max, iPhone 13 (Simulator)

## Additional context

https://user-images.githubusercontent.com/43729852/149596872-0b01b93e-c9f2-4829-b083-d0c97e1bd08c.MP4

**Comment by bielikb** [comment]
Hi @virbedi, 

I was able to reproduce this issue. Ill file a bug internally and we will cover this issue in one of the following releases.
Ill let you know once this is resolved.

Thanks for reporting!

Best,
Boris

**Comment by virbedi** [comment]
Hello, is there any update on this? 
As of `4.11.0` I am still facing this issue.

**Comment by nuno-vieira** [comment]
Hi @virbedi!

We are really sorry! This was a mistake on our side and probably a miss-click on the closing of the issue. This is not yet fixed you are correct 👍 Anyways, this is still being tracked internally so we would not forget about fixing it 🙂 

Best,
Nuno

**Comment by virbedi** [comment]
Thanks for the quick response @nuno-vieira. I'll keep an eye out for the fix

**Comment by b-onc** [comment]
Internally tracked as CIS-1219

**Comment by nuno-vieira** [comment]
Hi @virbedi!

Thank you for your patience on this one! This fix will be part of the next release 👍

We will close the issue once the next release is published.

Best,
Nuno

**Comment by virbedi** [comment]
@nuno-vieira Thanks for the update, looking forward to the next release 🚀
