### ISSUE TITLE
Image cache broken on older devices

### ISSUE THREAD

**Issue by vladpre92** [GetStream/stream-chat-swift#1759]
## What did you do?
Updated to 4.9.0. Also installed DemoApp from this repository.

## What did you expect to happen?
Image caching to work.

## What happened instead?
It seems image caching is broken.

## GetStream Environment
**GetStream Chat version:** 4.9.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.0
**Swift version:** 5.0
**Xcode version:** 13.1
**Device:** iPhone 7 or any simulator.

## Additional context

https://user-images.githubusercontent.com/3681654/150148004-3b6358cf-804c-4723-aa1a-ebc8ba7c41f7.MP4

https://user-images.githubusercontent.com/3681654/150148566-dc740aac-22b2-48dc-be91-786d8fdbe66a.mp4

Thank you!

**Comment by bielikb** [comment]
Hi @vladpre92,

thanks for reporting this issue. I create a bug issue to cover this work internally.
Ive tried to reproduce this issue internally using our demo app and the same channel on both iOS simulator + device (iPhone 12 Pro - iOS 15.2) but in the end couldnt repro this issue.

If this issue is 100% reproducible on your side, could you please write the steps down? 
Thanks!

Best,
Boris

**Comment by vladpre92** [comment]
I begin to think this is a hardware issue or something. Maybe too much image processing for my iPhone 7. I had the feeling that I could reproduce it on simulator as well but I was wrong. It's all good on my simulator.
I can reproduce it 100% only on my iPhone 7. I didn't have this problem with 4.8.0 on the same device so maybe this version is harsher on the hardware when displaying images?

**Comment by bielikb** [comment]
I see. We will try to investigate.

Will keep you updated!

Best,
Boris

**Comment by bielikb** [comment]
Hi @vladpre92,

Just a followup here. I added this issue to our internal backlog and we will tackle it in one of the following releases.

Best,
Boris

**Comment by nuno-vieira** [comment]
Hi, @vladpre92 Are you still able to reproduce this on your iPhone 7, especially with 4.12.0+ above?

I can't manage to reproduce this on any device. The oldest device I have tho is an iPhone XR.  Is there any chance your Device has the storage full?

Best,
Nuno

**Comment by vladpre92** [comment]
Hi @nuno-vieira . No, I can't reproduce it anymore with 4.13.0 on my iPhone 7. I don't think my storage was full when I recorded the above demo video.
Thank you!
