### ISSUE TITLE
Flag Message is not working 2.x

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#176]
## What did you do?
Click on a message from a different user and Flag it.  The post is never sent so nothing shows up in dashboard for Moderation.  Seems like it broke after 1.6.2??

```
    func flag(message: Message, _ completion: @escaping Client.Completion<FlagMessageResponse>) -> URLSessionTask {
        if message.id.isEmpty {
            completion(.failure(.emptyMessageId))
            return .empty
        }
        
        if user.isCurrent {
            completion(.success(.init(messageId: message.id, created: Date(), updated: Date())))
            return .empty
        }
        
        let completion = doAfter(completion) { _ in
            Message.flaggedIds.insert(message.id)
        }
        
        return toggleFlagMessage(message, endpoint: .flagMessage(message), completion)
    }
```

it stops at the `user.isCurrent`. but I assume you really want to check if the Messages user is not the current user..

BTW - our JS version of the same chat room with the same user sending a Flag Message works correctly

**Comment by buh** [comment]
Thanks @khoogheem!
You're right. It's a bug. It will be fixed in 2.1.

**Comment by khoogheem** [comment]
Can you also Test Mute User... We see that the Mute User message shows up but messages from that user still come in afterwards...

I suspect it is a similar issue

**Comment by buh** [comment]
Mute user will do this:
- disable push notifications
- disable unread count update.
But new messages will be available.
I can add a flag in the client to not show messages from muted users.

**Comment by khoogheem** [comment]
That does not seem to be what the JS sdk does... it no longer shows messages from that user (which seems typical for most chat type applications when you mute someone)

**Comment by buh** [comment]
It will be fixed in 2.1 (#186)

**Comment by khoogheem** [comment]
Any idea of 2.1 release?

**Comment by buh** [comment]
We're planning to make it today/tomorrow.
