### ISSUE TITLE
i want to display user avatars who read messages in bottom of bubbleview

### ISSUE THREAD

**Issue by soyeb313** [GetStream/stream-chat-swift#1778]
## What are you trying to achieve?

i want to display user avatars who read messages in bottom of bubbleview
## If possible, how can you achieve this currently?
No idea about this... i am tried to inject read status  data in contentview but  not working..

## GetStream Environment
**GetStream Chat version:** 4.0.0'
**GetStream Chat frameworks:** StreamChat, StreamChatUI  4.0.0
**iOS version:** IOS 15
**Swift version:**  Swift 5.2
**Xcode version:** 13
![13-Team-PatientChat-Team](https://user-images.githubusercontent.com/64627799/152407914-29d8f825-af23-44e7-9923-7cccff6dfd01.jpg)

**Device:**

**Comment by nuno-vieira** [comment]
Hi @soyeb313!

This is currently a missing feature on the iOS SDK that will be soon ready.

Meanwhile, if you can't wait, you can have access to the channel reads information in the message cell like this:

```swift
class CustomMessageContentView: ChatMessageContentView {
    override open func updateContent() {
        super.updateContent()
        
        if let content = content,
           let cid = content.cid,
           let channel = ChatClient.shared.channelController(for: cid).channel,
           let timestampLabel = timestampLabel {
              let readUsers = channel.reads.filter { $0.lastReadAt > content.createdAt }.map(\.user)
              timestampLabel.text = readUsers.compactMap(\.name).joined(separator: ", ") + " - " + (timestampLabel.text ?? "")
        }
   }
}
```

This is just an example, but with this, you can see how to get the reads information in the message view.

Let us know if you have any questions! 

Thank you,
Nuno
