### ISSUE TITLE
Trying to search by messages and then unable to show filtered results on Channels VC

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#179]
## What did you do?
I implemented search query for user to search b y message i.e telegram home vc search for messages or user .

## What did you expect to happen?
I am expecting it should show the searched results and when I tapped on cancel button of search controller it should remove the filtered results in short presenter.reload should back the results for channels VC 

## What happened instead?
nothing .
I tried to initiate presenter with custom filter(which I am using for SearchQuery filter parameter ).
but it gives all blank vc for channels controller and then it never returns the home screen channels ever ,in short it always returns blank once I tried with the desired filter to presenter .

## GetStream Environment
**GetStream Chat version:**2.0.1
**iOS version:**13.4
**Swift version:**5
**Xcode version:**11.4
**Device:**iPhone/Simulator 

## Additional context
it will be great help if you provide any snippet or example sudo code how to implement search and show its result .

**Comment by b-onc** [comment]
Hello @shireeshMs ,
Assigning custom data to be displayed in the tableview of ChannelsViewController is not possible at the moment.
While you can assign a new presenter in `ChannelsViewController` and it'll correctly load new channels.
For example, after user presses a button:
```swift
oldPresenter = presenter
presenter = ChannelsPresenter(filter: .equal("name", to: "Channel 2"))
```
this'll take affect and you'll only see `Channel 2` in your channel list.
When user presses another button, you can revert to the old one:
```swift
presenter = oldPresenter
```

If you're seeing an empty list, please check your logs. Your filter might be incorrect, or the result of your query might be returning an empty list.
