### ISSUE TITLE
In ChannelView, Swipe-to-navigate-back causes the scrollView to shift offset if keyboard is up.

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swift#1793]
https://user-images.githubusercontent.com/97132583/154113306-521e72f9-77c7-4f86-875f-9b6be433391d.mp4

## What did you do?
In ChatView, bring up the keyboard. Swipe to navigate back to thread list. Notice that the message list scrollView is scrolling down as you swipe.

## What did you expect to happen?
The scrollView offset should be stable during the swipe

## What happened instead?
The scrollView offset steadily decreases as you swipe.
Try Signal, iMessages, WhatsApp, Messenger. None of them have this behavior.

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS 15.3
**Swift version:** 5.5.2
**Xcode version:** 13.2.1
**Device:** iPhone 13 Pro

**Comment by nuno-vieira** [comment]
Hi @linhewinner !

Thank you for the report! We will investigate this as soon as possible and will update you whenever we have a fix. 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @linhewinner!

Sorry for a long time without updates. I've already identified the root cause of the issue and will provide a fix very soon. It should be available on the next release 4.21.0. 

We will let you know once we officially release it. 

Thank you for your patience.

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi!

This issue is now solved in the **4.21.1** release.

Thank you for your patience! 

Best,
Nuno
