### ISSUE TITLE
ThreadList tap state (row highlight state)  doesn't go away in airplane mode

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swift#1794]
https://user-images.githubusercontent.com/97132583/154114497-77afc1ec-9c43-4bdf-b031-ab89a3b834e2.mp4

## What did you do?
Turn on airplane mode. Tap on a row in Thread List. Navigate back.

## What did you expect to happen?
The tap state of the row should go away.

## What happened instead?
The tap state of the row doesn't go away (the tapped row is still displayed as highlighted).
Note that this only happens in airplane mode. When network is healthy, this bug doesn't reproduce.

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.3
**Swift version:** 5.5.2
**Xcode version:** 13.2.1
**Device:** iPhone 13 Pro

**Comment by nuno-vieira** [comment]
Hi @linhewinner!

Thank you for the report! We will investigate this as soon as possible and will update you whenever we have a fix. 

Best,
Nuno

**Comment by polqf** [comment]
This issue will be fixed once https://github.com/GetStream/stream-chat-swift/pull/1831 is merged.
You can expect this to be included in the following release, most probably.

**Comment by polqf** [comment]
Hello! We just released 4.12.0, you can check the changelog [here](https://github.com/GetStream/stream-chat-swift/releases/tag/4.12.0).
This issue should be fixed now. Feel free to reopen it if needed

**Comment by linhewinner** [comment]
confirmed that this is fixed. thanks!
