### ISSUE TITLE
Custom ordering of MessageReactionType

### ISSUE THREAD

**Issue by tomSidebar** [GetStream/stream-chat-swift#1796]
## What are you trying to achieve?
Customizing the order message reactions.

## If possible, how can you achieve this currently?
Currently not possible, reactions get sorted and displayed alphabetically (following https://getstream.io/chat/docs/sdk/ios/uikit/views/reactions/#custom-reactions-and-images).

## What would be the better way?
Retain the order in which the custom reactions are being added OR add a comparator function for MessageReactionType.

## GetStream Environment
**GetStream Chat version: 4.10.0**
**GetStream Chat frameworks: StreamChat, StreamChatUI**
**iOS version: 14.8**
**Swift version: 5.5.2**
**Xcode version: 13.2.1**
**Device: iPhone 11**

**Comment by linhewinner** [comment]
Note that it's not just the reactions attached to a message (which can be accomplished by sorting by createdAt)

We are also talking about the Reaction picker itself.
That list is also sorted alphabetically.

**Comment by polqf** [comment]
Hello! We just released 4.12.0, you can check the changelog [here](https://github.com/GetStream/stream-chat-swift/releases/tag/4.12.0).
This issue should be fixed now. Feel free to reopen it if needed

**Comment by nuno-vieira** [comment]
Hi @linhewinner!

This is now merged into develop. We will let you know when this issue is released 🙂 
The ETA for the next release is in 2 weeks.

Best,
Nuno

**Comment by evsaev** [comment]
Hi @linhewinner,

I'm happy to say that [4.15.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.15.0) containing the requested change is released 🎉 
Here is the [guide](https://getstream.io/chat/docs/sdk/ios/uikit/views/reactions/#custom-reactions-sorting) explaining how to provide custom sorting for reactions.
Thanks and enjoy your day!

Best,
Pavel
