### ISSUE TITLE
Make `version` public

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#18]
Just a proposal for improvement, make `static let version: String` (Client+Request.swift:12) public. This would help to identify at runtime which version of stream-chat is used.

For example, we use this in crash reports and also for user support requests. Would make our life a little bit easier 🤩

**Comment by buh** [comment]
Fixed in [v.1.3.4](https://github.com/GetStream/stream-chat-swift/releases/tag/1.3.4)
