### ISSUE TITLE
Need Help before App Store deploying

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#180]
Hello Team,
I would like to know if there any important thing need to be added (i.e in info plist or any key point I need to make note before making App Store archiving) before App Store release .
Thanks in advance team for this help as it will help us to have any not expected delay for release .

**Comment by b-onc** [comment]
Hello @shireeshMs ,
If you're using camera/mic, you should add their usage descriptions.
Please check "Message Attachments" at https://getstream.io/tutorials/ios-chat/
