### ISSUE TITLE
Change send button size

### ISSUE THREAD

**Issue by tomSidebar** [GetStream/stream-chat-swift#1809]
## What are you trying to achieve?
Trying to increase the size of the send button in the Message composer to match the height of the message input.

## If possible, how can you achieve this currently?
Haven't been able to make this work yet.

## What would be the better way?
Offer some customization option for button sizes similar to other offered customizations (https://getstream.io/chat/docs/sdk/ios/uikit/components/message-composer/).

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 14.8
**Swift version:**
**Xcode version:** 
**Device:** iPhone 11

**Comment by bielikb** [comment]
Hi @tomSidebar,

you can achieve this customisation by following these steps.

1. Create your own custom subclass of `ComposerView` that will set the desired dimensions of the `sendButton`/`confirmationButton`

```
class CustomComposerView: ComposerView {

    override func setUpLayout() {
        super.setUpLayout()

        [sendButton, confirmButton].forEach { button in
       
           // 1. Lock the button height anchor the height of the message input,
            NSLayoutConstraint.activate(
                [
                    button.heightAnchor.constraint(equalToConstant: inputMessageView.textView.heightConstraint?.constant ?? 38)
                ]
            )
            
            // 2. Customize the insets/alignment of the button's imageView to meet your needs
            // The following code is just an example of further customization
            button.contentVerticalAlignment = .fill
            button.contentHorizontalAlignment = .fill
        }
    }
}
```

2. Leverage the new subclass in your integration
```
Components.default.messageComposerView = CustomComposerView.self
```

This will result in following layout.

<img width="396" alt="Screenshot 2022-02-23 at 12 28 48" src="https://user-images.githubusercontent.com/4924709/155312419-0673fc82-8e4e-4aaa-b381-d4f814310463.png">

---

You can also provide your own instance of the `sendButton` or `confirmationButton` as needed.

```
Components.default.sendButton = MySendButton.self
Components.default.confirmButton = MyConfirmationButton.self
```

Please let me know, if this answered your question.

Best,
Boris Bielik

**Comment by tomSidebar** [comment]
@bielikb Thank you so much! This is exactly what I needed!
