### ISSUE TITLE
how to add scroll in the command Container view(taken reference with CommandContainerView for /command) which shows the list of members like @ tag

### ISSUE THREAD

**Issue by shireeshMs** [GetStream/stream-chat-swift#181]
Hello team,
I am unable to add scroll although I have managed to do so by taking your guys reference as you have done for "/ "command view under composer of chat view controller but facing one issue like if list is full of more than 15 members ,then due to not scrolling we can get only half of the list or till that view is found its height .

Need to know how to add scroll so that I should not face this issue .

**Comment by b-onc** [comment]
Hello @shireeshMs ,
Commands window does not show up for mentioned users, so I've understood it as you've created/extended functionality of ComposerView so it shows a list of users when @ is tapped.
The commands are displayed in a stack view, if you want to make them scrollable you should embed that stack inside a scroll view (`ComposerHelperContainerView.swift:#L35`)
See https://stackoverflow.com/questions/31668970/is-it-possible-for-uistackview-to-scroll for more info.
