### ISSUE TITLE
ChatMessageSearchController's sorting is not working

### ISSUE THREAD

**Issue by EuyjaeHwang** [GetStream/stream-chat-swift#1821]
## What did you do?
I searched message by using ChatMessageSearchController
```Swift
let query = MessageSearchQuery(
    channelFilter: .equal(.cid, to: cid),
    messageFilter: .and([.autocomplete(.text, text: query)]),
    sort: [.init(key: .id, isAscending: false)]
  )
messageSearchController = client.messageSearchController()
messageSearchController.search(query: query)
```

## What did you expect to happen?
I expected the results to be sorted in descending order of created time

## What happened instead?
The results were the same(in ascending order) regardless of the `sort` (`sort: [ .init(key: .id, isAscending: false)]` and `sort: [ .init(key: .id, isAscending: true)]` result was same)
Am I using the wrong query????

## GetStream Environment
**GetStream Chat version:** 4.10.1
**GetStream Chat frameworks:** StreamChat
**iOS version:** 15.x, 14.x
**Swift version:** 5.5.2
**Xcode version:** 13.2.1
**Device:** all of iPhone, iPad supporting iOS 14+

**Comment by tbarbugli** [comment]
@EuyjaeHwang your query is sorting by `id` and not by `created_at`, did you try changing that?

**Comment by EuyjaeHwang** [comment]
@tbarbugli `MessageSearchSortingKey` is enum and has only 2 case(id, relevance).
is any other method to apply another sorting key?

**Comment by b-onc** [comment]
Hello @EuyjaeHwang ,

It's a bug within the SDK, `query.sort` is not being considered when fetching data from DB. We'll roll a fix with the next version.
