### ISSUE TITLE
How to custom the font/color of a message in the bubble for `isSentByCurrentUser`

### ISSUE THREAD

**Issue by gorbat-o** [GetStream/stream-chat-swift#1834]
## What are you trying to achieve?
I want to customize the font/color just for `isSentByCurrentUser` right now this is applied across both bubble message.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/7542553/157366277-8ab6ddb9-29fc-4e78-ad0c-11b6eced5fdc.png">

## If possible, how can you achieve this currently?
I didn't find a way yet, but it seems that it will be a lot of class overrides and some extensions around these files:
* ChatMessageCell
```swift
extension ChatMessageCell {
    var textViewColor: UIColor? {
        set {
            messageContentView?.textViewColor = textViewColor
        }
        get {
            messageContentView?.textViewColor
        }
    }
}
```

And somehow override this function: `override open func updateContent()` in `ChatMessageContentView` where it sets a static color that is not configurable case by case.
or better, create a different appearance and give it as a parameter somewhere, I haven't found where yet. This library has a lot to go through.

```swift
// Text
        var textColor = appearance.colorPalette.text // <<< here
        var textFont = appearance.fonts.body
        
        if content?.isDeleted == true {
            textColor = appearance.colorPalette.textLowEmphasis
        } else if content?.shouldRenderAsJumbomoji == true {
            textFont = appearance.fonts.emoji
        } else if content?.type == .system || content?.type == .error {
            textFont = appearance.fonts.caption1.bold
            textColor = appearance.colorPalette.textLowEmphasis
        }
        
        textView?.textColor = textColor // <<< here
        textView?.font = textFont
        textView?.text = content?.textContent
```

Any help would be really appreciated! Thank you!

**Comment by adamrushy** [comment]
Hello, @gorbat-o 

Thanks for raising this issue. I am sorry you're struggling to find the resolution to what you're attempting.

Do take a look [here](https://getstream.io/chat/docs/sdk/ios/uikit/components/custom-components/) it contains documentation about how all our components work and the easiest way to customize all of them.

Anyway, to get you going right away I have provided some sample code for you.

First, create a new class that will override our implementation:

```swift
import StreamChatUI

class CustomChatMessageContentView: ChatMessageContentView {}
```

Then go ahead and override our `updateContent()` function

```swift
override func updateContent() {
    super.updateContent()
    bubbleView?.backgroundColor = content?.isSentByCurrentUser == true ? .blue : .gray
    textView?.textColor = content?.isSentByCurrentUser == true ? .white : .black
 }
```

It's key that you call super on these implementations unless you're going to completely override the logic.

The final step is to register your custom class within the Components.

```swift
Components.default.messageContentView = CustomChatMessageContentView.self
```

This will set the background color and text color for the sender. I hope this helps :]

**Comment by nuno-vieira** [comment]
Hi @gorbat-o!

This [doc](https://getstream.io/chat/docs/sdk/ios/uikit/components/message/) is also probably a good read to understand on how customizable is our message view 👍 

Best,
Nuno

**Comment by adamrushy** [comment]
Closing this issue for now. Let us know if we can help with anything else @gorbat-o

**Comment by gorbat-o** [comment]
Thank you for that quick answer!
I read the documentations but haven't found any particular way to override `ChatMessageContentView`. But then I indeed realized that it all goes through `Components.default`
Again thank you! 🙏
