### ISSUE TITLE
ChannelListVC has stale view upon reconnection because /sync endpoint returns a channel without "reactions" payload

### ISSUE THREAD

**Issue by linhewinner** [GetStream/stream-chat-swift#1835]
## What did you do?
If I disconnect the app, send a message and reconnect the app (by using Airplane mode), I noticed that the new message isn't getting picked up by the ChannelListVC.

Most of my clients are working fine, but every once in a while, a client would get into a state where this bug consistently repros.

I managed to chase this down to ConnectionRecoveryUpdater, where the /sync endpoint is failing to parse the response due to this error:
```
2022-03-08 21:54:06.220 [ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:75] [decodeRequestResponse(data:response:error:)] > keyNotFound(CodingKeys(stringValue: "reactions", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "events", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "channel", intValue: nil), ChannelCodingKeys(stringValue: "config", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"reactions\", intValue: nil) (\"reactions\").", underlyingError: nil))
```

Looking at ChannelConfig, it expects a "reactions" payload but there isn't one in the response.
This seems like a backend issue. Can you guys (client team) talk to the backend guys to fix this?

I know I know, you are gonna tell me to not use local persistence in production but that's not an option for my business. It is tablestake. While local persistence is not perfect, I need it. Not having it probably means I need to stop the payment and go over to SendBird :)
So hopefully Stream's backend should fix this issue (or I hope you guys will roll out the much anticipated rewrite of local persistence so I can use it with more ease of mind)

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by polqf** [comment]
Hi @linhewinner,
Thank you for your report. We've started an internal investigation, and we'll come back to you whenever this is completed 😄

**Comment by linhewinner** [comment]
I also think ConnectionRecoveryUpdater should be more defensive of malformed backend response. Here, in the case of an unknown error, the else branch does not call completion():

https://github.com/GetStream/stream-chat-swift/blob/c18de959292ed01e064640f6a0a085afaf158c96/Sources/StreamChat/Workers/Background/ConnectionRecoveryUpdater.swift#L169

I think we should ideally call completion() in the "else" branch so when sync response is malformed, at least we will refetch the threads

**Comment by polqf** [comment]
@linhewinner We are realising an overhaul around this area pretty soon: https://github.com/GetStream/stream-chat-swift/pull/1831. As you pointed out, the current logic has some deficiencies.

**Comment by polqf** [comment]
Hello! We just released 4.12.0, you can check the changelog [here](https://github.com/GetStream/stream-chat-swift/releases/tag/4.12.0).
This issue should be fixed now. Feel free to reopen it if needed

**Comment by linhewinner** [comment]
@polqf It's not clear to me why the new release would fix this problem.

1. Did you guys find a bug in the backend where /sync endpoint would sometimes return channelConfigs without the "reactions" field? and fix that bug?
2. In the new release, is the client code still calling /sync endpoint? If so, could it still encounter the same decoding error? Is the client decoding path not expecting the ".reactions" field anymore?

If you can point to some PRs that convincingly fixes this issue, I'd feel more comfortable closing this issue.

(I am trying an upgrade but this is a sporadic repro because it depends on the server returning malformed response ... so it's not as simple as "I upgraded and there is no bug")

**Comment by polqf** [comment]
Hi @linhewinner,
The new release should be fixing things from 3 different angles:

1. As you pointed out, we were working on our local persistence layer. You can check #1755, where the work has been done. This should be a major improvement over offline support
2. The issue was reported and tackled by our backend team
3. We also made sure that if there's any individual event that comes wrongly formatted in this particular endpoint, it would only skip that unique event, and not fail the decoding of the whole request.

Hope this answer your questions. Feel free to ask any other doubts

**Comment by linhewinner** [comment]
Cool! 3 is really reassuring.

I am particularly interested in the second point. What did the backend team fix? Our Sentry log shows this from 10 minutes ago:

```
[ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:75] [decodeRequestResponse(data:response:error:)] > keyNotFound(CodingKeys(stringValue: "reactions", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "events", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "channel", intValue: nil), ChannelCodingKeys(stringValue: "config", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"reactions\", intValue: nil) (\"reactions\").", underlyingError: nil))
```

The backend is still returning responses without the required field "config.reactions"

**Comment by polqf** [comment]
Thanks for the report. I'll go ahead and pass this information

**Comment by linhewinner** [comment]
I just read the code. Love the fixes:

1. MissingEventsPayload uses decodeArrayIgnoringFailures so that one bad event won't ruin the entire "events"
2. SyncRepository.syncLocalState's OperationQueue ensures that even if SyncEventsOperation fails, RefetchChannelListQueryOperation would still execute (this wasn't the case in 4.10.0 because a failed /sync call would lead to channelListRefetch not executing)

These two combined make the reconnection recovery very robust. Thanks and great job!

Although I am still spooked by the "missing .reactions field" exception. Some sync events are being ignored ... and I don't know which ones. Hopefully backend can hunt those down and fix them.
