### ISSUE TITLE
Memory Leak in URLSessionWebSocketEnginer

### ISSUE THREAD

**Issue by DispoKen** [GetStream/stream-chat-swift#1843]
## What did you do?

Initialize the stream API
## What did you expect to happen?

No memory Leaks
## What happened instead?
Got memory Leaks

## GetStream Environment
**GetStream Chat version: 4.11.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.0
**Swift version:** 5.5
**Xcode version:** 13.2.1
**Device:** iphone X

## Additional context
Seems like a possible retain cycle here
<img width="1525" alt="Screen Shot 2022-03-10 at 2 35 25 PM" src="https://user-images.githubusercontent.com/89225304/157766815-94a1ad94-4cdd-4cba-b746-12cbedc79989.png">

**Comment by nuno-vieira** [comment]
Hi @DispoKen!

These memory leaks come from the Foundation framework. It seems that the WebSocket implementation from Apple does include some memory leaks. This is not related to the StreamChat SDK. 

Anyways, thank you for opening the issue!

Best,
nuno
