### ISSUE TITLE
Changes to ChatMessageContentView only take place for some messages

### ISSUE THREAD

**Issue by virbedi** [GetStream/stream-chat-swift#1853]
## What did you do?
I have an override of class `ChatMessageContentView` where in the func `createAvatarView()` I add an icon and border to the view if the users account satisfies certain conditions. 

## What did you expect to happen?
If conditions were satisfied, the user's `ChatAvatarView` would have a mini icon and border around it for all their messages.

## What happened instead?
The user's AvatarView reflects the changes sometimes and often does not. 
This changes on scrolling through a long thread.

## GetStream Environment
**GetStream Chat version:** 4.10.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.3.1
**Swift version:**
**Xcode version:**13.3
**Device:**iPhone 13 Pro Max

## Additional context
Here's an image where user Siming and Coach Jenny satisfy the conditions for having the custom ChatAvatarView. However in a long thread only some of their avatars have the outline and icon.
<img src="https://user-images.githubusercontent.com/43729852/158498897-7bc461d0-3195-4f9e-b120-878e8df5f517.png" width="260"/>

**Comment by polqf** [comment]
Hi @virbedi,

Could you please share how your code looks inside `createAvatarView`?

**Comment by virbedi** [comment]
Thanks @nuno-vieira and @polqf, I'll look into the links provided 👍🏽

**Comment by b-onc** [comment]
Hello @virbedi ,

Is the issue still ongoing?

**Comment by virbedi** [comment]
@b-onc I decided to add this modification in `updateContent`() and remove it in `prepareForReuse`() instead of overriding the `ChatMessageLayoutOption`. 
The issue I was facing was because I was not clearing out the modifications before reuse. Thanks!

**Comment by virbedi** [comment]
@b-onc I am running into another issue with overriding `prepareForReuse()` in `ChatMessageContentView`. Is there a reason this function is not marked as `open` like most other functions in the class?

**Comment by nuno-vieira** [comment]
Hi @virbedi!

You should follow the `ChatMessageLayoutOption` approach, or you will most likely run into problems like for example the view not being updated properly. Any reason why you don't go this route? Do you need any help with this? We can provide you with an example for your use case. 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @virbedi!

After doing further analyse, in your case you actually don't need to create a new layout option. Probably the better approach here is to customize the AvatarView. The advantage of this is that if you want to use this badge in other places of the codebase where there is an avatar you can too. Here is an example:


```swift
class CustomMessageView: ChatMessageContentView {
    override func updateContent() {
        super.updateContent()

        if content?.extraData["verified"] == .bool(true) {
            if let authorAvatarView = authorAvatarView as? CustomAvatarView {
                authorAvatarView.verifiedBadgeView.isHidden = false
            }
        }
    }
}

class CustomAvatarView: ChatAvatarView {
    lazy var verifiedBadgeView: UIImageView = {
        let imageView = UIImageView(image: UIImage(systemName: "checkmark.circle.fill"))
        imageView.translatesAutoresizingMaskIntoConstraints = false
        imageView.backgroundColor = UIColor.cyan
        imageView.clipsToBounds = true
        imageView.layer.borderWidth = 2
        imageView.layer.borderColor = UIColor.white.cgColor
        return imageView
    }()

    override func setUpLayout() {
        super.setUpLayout()

        verifiedBadgeView.isHidden = true
        addSubview(verifiedBadgeView)
        NSLayoutConstraint.activate([
            verifiedBadgeView.bottomAnchor.constraint(equalTo: bottomAnchor),
            verifiedBadgeView.trailingAnchor.constraint(equalTo: trailingAnchor)
        ])
    }

    override func layoutSubviews() {
        super.layoutSubviews()

        verifiedBadgeView.layer.cornerRadius = verifiedBadgeView.frame.width / 2
    }
}
```

All our codebase uses this `ChatAvatarView`, directly, or through our parent components like `ChatUserAvatarView` and `ChatChannelAvatarView`. So with this, you can render your badge everywhere.

Let me know if this works fine for you!

Best,
Nuno

**Comment by virbedi** [comment]
Thanks for the follow up @nuno-vieira! This is more in line with what I was trying to achieve without updating the layout options. I was able to achieve what I was trying by updating the ChatAvatarView class as suggested here.
Appreciate your help on this! 
<img src="https://media.giphy.com/media/KB8C86UMgLDThpt4WT/giphy.gif" width="100" />
