### ISSUE TITLE
public option for choosing WebSocket Engine

### ISSUE THREAD

**Issue by tokirin** [GetStream/stream-chat-swift#1857]
## What are you trying to achieve?
```Swift
// WebSocketClient.swift
var createEngine: CreateEngine = {
    if #available(iOS 13, *) {
        return URLSessionWebSocketEngine(request: $0, sessionConfiguration: $1, callbackQueue: $2)
    } else {
        return StarscreamWebSocketProvider(request: $0, sessionConfiguration: $1, callbackQueue: $2)
    }
}
        
```
The Websocket connection recovery is very unstable in our customer's environment.
So we are testing both `URLSessionWebSocketEngine` and `StarscreamWebSocketProvider`
In our reseach, `StarscreamWebSocketProvider` has much better performance and recover better
so we want to choose websocket client for application.

## If possible, how can you achieve this currently?
fork and modify

## What would be the better way?
Add option to ChatClientConfig

```Swift
var config: ChatClientConfig = .init(apiKey: .init(streamApiKey))
config.webSocketClient = .system
//or
config.webSocketClient = .starscream
```

## GetStream Environment
**GetStream Chat version:** 4.11.0
**GetStream Chat frameworks:** StreamChat
**iOS version:** 15.3.0
**Swift version:** 5.x.x
**Xcode version:** 13.2.1
**Device:** iPhone 12 Pro

**Comment by polqf** [comment]
Hi @tokirin, please use 4.12.0. We've been working on a completed overhaul around recovery logic, and has just been released. It should fix your issues 😄
