### ISSUE TITLE
Push Notification sound is not working

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#1858]
## What did you do?
- configure push notification with APS
- receive notification when other send message to me

## What did you expect to happen?
- Notification should display with sound (on App kill state)
- It should has a value in **sound** key
`<UNNotificationContent: 0x2838d5500; title: New message from ABC, subtitle: (null), body: DEF, summaryArgument: (null), summaryArgumentCount: 0, categoryIdentifier: stream.chat, launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null), realert: 0, interruptionLevel: 1, relevanceScore: 0.00`

## What happened instead?
- Display notification without sound

## GetStream Environment
**GetStream Chat version:** 4.12.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.0.2
**Swift version:** 5
**Xcode version:** 13.2
**Device:** Iphone X

**Comment by polqf** [comment]
Hi @ajay-simform

Please look at our documentation to customize Push Notifications https://getstream.io/chat/docs/sdk/ios/guides/push-notifications/#notification-service-extension. Feel free to reopen this issue if you have more questions

**Comment by Zee-93** [comment]
> Hi @ajay-simform
> 
> Please look at our documentation to customize Push Notifications https://getstream.io/chat/docs/sdk/ios/guides/push-notifications/#notification-service-extension. Feel free to reopen this issue if you have more questions

@polqf That link is not working. Could you please send the updated one?
