### ISSUE TITLE
Message Composer gets covered by keyboard on app switching

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#188]
Sounds like this might have been an issue in the past and some fixes have been put in.  

I have not tested this on a non X device.  But if you switch apps with the keyboard up and then come back to the Chat app.. the message composer is behind the keyboard.  Swipe down and it will show again as expected.  However if you start another message the keyboard re-hides the composer

**Comment by b-onc** [comment]
Hello,
Please use the issue template when creating new issues.
Which version of the sdk are you using? Which devices?

**Comment by khoogheem** [comment]
2.0.0.... I have seen it on the iPhone 11 and our QA has on the Xs Max
