### ISSUE TITLE
Question about usersRead of a message

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#19]
We are trying to understand how to check if a message was read by a specific user.

Our app subscribes to the view changes of a channel and uses the items which are returned by `ViewChanges.itemAdded` - Then we iterate over every item (`ChatItem`) and cast it with `case message(Message, _ usersRead: [User])` to a message and the list of users which should already read the message. Unfortunately the list is always empty.
The `last_read` in `read` on the channel JSON response shows a younger date then all messages in the channel, so as I understand it right now all messages should be seen as read but we never get a list of usersRead.

Could you explain how we can check if a user has read a message?

**Comment by buh** [comment]
The read state shows who read messages of the current user. Please, check Example project, so for example open the general channel and post something, then you'll see how another users will read the message. Additionally you can open the chat on web and you'll see read events on the iOS client. Does it help?

**Comment by janweinkauff** [comment]
Is it possible to see if I as the current user read a message in a channel?

**Comment by buh** [comment]
Hey @janweinkauff!
For your last question, probably you want to show where new messages for the current user. It's possible and it's in our plans.
