### ISSUE TITLE
Crash ChatMessageListView.updateMessages

### ISSUE THREAD

**Issue by BarragaoA** [GetStream/stream-chat-swift#1949]
Hello, I got the following crash since 4.8.0. I'm now on the last version (4.13.1) and still got it.

## GetStream Environment
**GetStream Chat version: 4.13.1 **
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
Sorry I do not know how to reproduce but it seems to happen quite often, 17 users the last 7days 

<img width="1063" alt="Capture d’écran 2022-04-25 à 09 26 23" src="https://user-images.githubusercontent.com/86778557/165041836-1cc9b273-9396-438c-b99d-ced2a97b2f06.png">

Thanks for your help

**Comment by bielikb** [comment]
Hi @BarragaoA,

thanks for the crash report!

I'll create an issue internally for this crash. If you have any more context - eg info about the user scenario that invoked this crash, that's always useful as the chances our team will be able to repro & fix the issue your users are experiencing will increase.

One possible solution for your issue could be leveraging our `_messageListDiffingEnabled` feature that leverages `Diffable Datasources` (iOS 13.0+).

Here's how you can enable it.
```
Components.default._messageListDiffingEnabled = true
```

Please note that this is an experimental feature that our team has tested and is actively working on, yet this feature is not widely used in production, so use it with caution!

If you opt in to this feature, please let us know if that resolved your issue!
Thanks!

**Comment by adamrushy** [comment]
Hey, @BarragaoA just checking if you had any updates on the diffable feature and if this worked for you?

**Comment by BarragaoA** [comment]
Hello, 

I did not enable it yet since you warn us about the fact that it is an experimental feature.
But I got more and more crash so I'm going to update the sdk to 4.14.0 and enable it

**Comment by adamrushy** [comment]
Hey, @BarragaoA yes please do - although experimental we're seeing really positive results :]

**Comment by BarragaoA** [comment]
Hello,
I just send a production app with the version 4.14.0 and messageListDiffingEnabled = true.
I'll keep you informed 🙂

**Comment by nuno-vieira** [comment]
Hi @BarragaoA!

We already have other customers successfully using this and it is a very safe approach right now. Probably next release we will also switch this flag to true by default 🙂 

Please, feel free to re-open the issue if you find any problems.

Best,
Nuno
