### ISSUE TITLE
Chat UI geting red..

### ISSUE THREAD

**Issue by soyeb313** [GetStream/stream-chat-swift#1957]
## What did you do?
i  have to installed   Dolby.io’s Client SDK. when open seesion of dolby sdk then Chat UI Avatar view and icon view is display red color.

## What did you expect to happen?
Display prorper Chat window UI

## What happened instead?
i  have to installed   Dolby.io’s Client SDK. when open seesion of dolby sdk then Chat UI Avatar view and icon view is display red color.

## GetStream Environment
**GetStream Chat version:** pod 'StreamChat', '~> 4.0.0'
  pod 'StreamChatUI', '~> 4.0.0'
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** : 15
**Swift version:** swift 5.0
![simulator_screenshot_1D8FE5EA-50B6-45D9-99D4-4FDAFBE171E7](https://user-images.githubusercontent.com/64627799/165385063-a633417e-5299-474d-aa3a-8f35ebe76cf2.png)

**Xcode version:** Xcode15
![simulator_screenshot_B7E954D8-988F-4A1C-85DD-965BF4E7EC64](https://user
![simulator_screenshot_581FC4BF-C00B-4C69-BC3D-709DA9C4B57B](https://user-images.githubusercontent.com/64627799/165385124-a26a4679-486d-46a1-9fae-8f748a10a768.png)
-images.githubusercontent.com/64627799/165385078-942c7f81-027b-41fb-90d1-259454b12573.png)

**Device:** IPhone 12 PRO

**Comment by evsaev** [comment]
Hey, @soyeb313  thanks for reporting this! We'll look into it and get back to you shortly.

**Comment by evsaev** [comment]
Hey @soyeb313 👋 

Would you provide me with the following inputs:
1. Is it `VoxeetSDK` meant under Dolby's SDK?
2. Would share with me the resolved versions of `StreamChat/StreamChatUI` and Dolby's SDK you are using? (if you're using CocoaPods, you can find them in `Podfile.lock`)
3. Did I get you right that without opening a session everything works fine? Would you share the code snippet where the session is opened that leads to the issue with broken icons?

Thanks and enjoy your day!

Best,
Pavel

**Comment by soyeb313** [comment]
### @evsaev  Thanks for your response.. Below is the answer your question.
1.Is it VoxeetSDK meant under Dolby's SDK?
==> Yes (VoxeetUXKit.shared.initialize())
2.Would share with me the resolved versions of StreamChat/StreamChatUI and Dolby's SDK you are using? (if you're using CocoaPods, you can find them in Podfile.lock)
==> - StreamChat (~> 4.0.0)
       - StreamChatUI (~> 4.0.0)
       - VoxeetUXKit (~> 1.3)
 3.  Did I get you right that without opening a session everything works fine? 
 ==> without open session (VoxeetSDK)   working fine. but when open session then icons are broken. below is code of open session of VoxeetSDK.

**` VoxeetSDK.shared.notification.delegate = self
        let info = VTParticipantInfo(externalID:UserDefaults.standard.value(forKey: User_defaults_Constants.UserId) as? String, name: UserDefaults.standard.value(forKey: User_defaults_Constants.username) as? String, avatarURL: "https://www.gravatar.com/avatar/1234")
        VoxeetSDK.shared.session.open(info: info) { error in }`**

**Comment by evsaev** [comment]
Hey @soyeb313, thanks for the provided info 🙌 

I'll look into this as soon as I can and will get back in case of other questions or updates.

Best,
Pavel

**Comment by evsaev** [comment]
Hey @soyeb313,

Writing to give you an update that we're investigating the issue and will keep you posted with the progress.

Thanks!

Best,
Pavel

**Comment by adamrushy** [comment]
Hey, @soyeb313 

I believe we fixed this exact problem late last year. It was regarding using unique bundle identifiers otherwise it would fail to load the assets. You can read more information [here](https://github.com/GetStream/stream-chat-swift/issues/1566)

It was released within version [4.4.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.4.0)

I would recommend updating to this version (our the latest version) and checking if this issue is fixed for you.

Thanks,
Adam

**Comment by adamrushy** [comment]
Closing this issue on the above solution. Let me know if you need any more support @soyeb313 :]

**Comment by melbinexperion** [comment]
I am experiencing this issue in streamchat-swift-ui.  Although quick fix mentioned in  #1456  fixed it.

**Comment by melbin97** [comment]
I am experiencing this issue in streamchat-swift-ui (v 4.17). Although quick fix mentioned in #1566 fixed it. Is it fixed in any version @adamrushy
