### ISSUE TITLE
Can't get correct channelList when user switch

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#1977]
## What did you do?
- switching multiple users.

## What did you expect to happen?
- channel list should display correctly.

## What happened instead?
- It is not displaying the correct channel list.
- In case if it displayed a channel list, its sorting is not correct.
- sometimes channel List becomes totally empty.

## GetStream Environment
**GetStream Chat version:** 4.14.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.2
**Swift version:** 5
**Xcode version:** 13.2
**Device:** iPhone-12

https://user-images.githubusercontent.com/47667077/166918935-60d103ae-0300-401c-87b7-bda0d54ede6d.mp4

**Comment by evsaev** [comment]
Hey there @ajay-simform 👋

The thing, when the chat client is connected with another user, the `ChatChannelListVC` should be recreated in case the underlying channel query involves a condition with `currentUserId`. 

In `DemoApp`, the query matches channels where the current user is a member so we can't keep using the same screen after switching a user without resetting the `ChatChannelListVC.controller` with the query for the new user.

That's a known issue and we will tackle it as soon as we can.

Thanks for your report! 

Best,
Pavel

**Comment by ajay-simform** [comment]
Hi @evsaev 
Thanks for the update!
I hope this issue will resolve ASAP. This is a major blocker for us. 🤞

**Comment by evsaev** [comment]
Hey @ajay-simform 👋 

We've got an [issue](https://github.com/GetStream/stream-chat-swift/issues/1976#issuecomment-1118713102 ) yesterday similar to yours. 

The suggested solution was to recreate `ChatChannelListVC` when the user is switched. 

Would you try that and see if that resolves the issue?

Best,
Pavel

**Comment by nuno-vieira** [comment]
Hi @ajay-simform!

You should re-create the `ChatChannelListVC` instead of reusing the same instance of the channel list view:
```swift
let newController = ChatClient.shared.channelListController(query: .init(filter: .equal(.type, to: .messaging)))
let channelListVC = ChatChannelListVC.make(with: newController)
```
Feel free to re-open the issue if you have any issues. 

Best,
Nuno
