### ISSUE TITLE
Access to gallery without asking permissions

### ISSUE THREAD

**Issue by arthurchambsp** [GetStream/stream-chat-swift#199]
## What did you do?
I open a chat and try to upload a photo or video from my gallery.

## What did you expect to happen?
I expect a native popup asking my authorization to access my gallery.

## What happened instead?
It just opens my galley, without asking me first.

## GetStream Environment
**GetStream Chat version:**
`2.0.1`
**iOS version:**
All
**Swift version:**
5.1
**Xcode version:**
Version 11.3.1 (11C505)
**Device:**
iPhone X

## Additional context
When the UIImagePicker is opened, if I cancel, I have an error popup for permissions. And then I realise it never asks me my permission to access my gallery.
So I dig in your code and in `ViewController+ImagePicker.swift`, in this method :
```
func showImagePicker(sourceType: UIImagePickerController.SourceType, _ completion: @escaping ImagePickerCompletion) {
        if UIImagePickerController.isSourceTypeAvailable(sourceType) {
            showAuthorizeImagePicker(sourceType: sourceType, completion)
            return
        }
        
        let status = PHPhotoLibrary.authorizationStatus()
        
        switch status {
        case .notDetermined:
            PHPhotoLibrary.requestAuthorization { [weak self] status in
                DispatchQueue.main.async {
                    if status == .authorized {
                        self?.showAuthorizeImagePicker(sourceType: sourceType, completion)
                    } else {
                        completion(nil, status)
                    }
                }
            }
        case .restricted, .denied:
            completion(nil, status)
        case .authorized:
            showAuthorizeImagePicker(sourceType: sourceType, completion)
        @unknown default:
            print(#file, #function, #line, "Unknown authorization status: \(status.rawValue)")
            return
        }
    }
```

I go through the first if with sourceType = .savedAlbums, so I return and requestAuthorization is never called. 

Here's a video : [https://photos.app.goo.gl/Ke5S3UVtv72kcXjGA](https://photos.app.goo.gl/Ke5S3UVtv72kcXjGA)

Best regards,
Arthur

**Comment by buh** [comment]
Hi @arthurchambsp 
Thanks for the video. We'll check.

**Comment by buh** [comment]
#215
