### ISSUE TITLE
Can't Ban/Unban user from channel

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swift#1995]
## What did you do?
- upgrade to permission V2
- gave user banned permission to the `User` and `ChannelMember`.
- create a channel
- Add multiple members with a channel creator
- Block/unblock channel members with a channel creator from the FE side

`let controller = ChatClient.shared.memberController(userId: user.id, in: channelId)
`
`
controller.ban { error in
print(error)
}
`

## What did you expect to happen?
- user ban/unban successfully with channel creator without any error

## What happened instead?
- Received an error

`
{ "code" : 17, "message" : "Ban failed with error: \"User 'xxxx' with roles ['user', 'channel_member'] is not allowed to perform action BanChannelMember in scope 'messaging'\"", "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response", "StatusCode" : 403, "duration" : "0.00ms"})
`

## GetStream Environment
**GetStream Chat version:** 4.14.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.2
**Swift version:** 5
**Xcode version:** 13.2
**Device:** Iphone XS

**Comment by mdhanif-simformsolutions** [comment]
sure. Here's the configuration which I have set for adding permissions. 
Channel Member :- 
<img width="709" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/63775307/168226267-5db6703f-39e4-4f9a-8d60-3e2e77c3541d.png">
User :- 
<img width="708" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/63775307/168226253-c16fd709-0096-41ea-be6a-46582afee422.png">

Please do let me know if there's anything else required from my end.

**Comment by mdhanif-simformsolutions** [comment]
Thank you for update @adamrushy. 
I don't see anywhere where I can use "BanChannelMember". You can check the permission list I have posted above in screenshots.
Just FYI I am using Version2 of Permissions.

**Comment by adamrushy** [comment]
Thank you, @mdhanif-simformsolutions 

We can actually push this fix sooner, can you share the app ID you're using, please?

**Comment by adamrushy** [comment]
@mdhanif-simformsolutions just checking in on my previous message :]

**Comment by mdhanif-simformsolutions** [comment]
Hey @adamrushy I am not sure If I it would be safe to should share my app ID here. Is there any other fix/way we can look for ?

**Comment by adamrushy** [comment]
@mdhanif-simformsolutions can you email me directly at adam.rush@getstream.io :]

**Comment by adamrushy** [comment]
Hey, @mdhanif-simformsolutions we have pushed the fix live just now - please can you check 👍🏼

**Comment by AnatolyRugalev** [comment]
Hey @mdhanif-simformsolutions,

Previously we assumed location of your app and there's a chance that this assumption was incorrect. My apologies for this.

Most probably the patch did not arrive yet to the part of our infrastructure where you application is hosted. We can speed things up for you if you can send us your application id. As far as I know Adam haven't got it. Having your app id will also allow us to reproduce and troubleshoot the issue better.

You can hit me directly with it at anatoly@getstream.io. If you don't feel comfortable sending it directly to me, you can also submit [a support ticket](https://getstream.io/contact/support/) with a reference to this GitHub issue.

**Comment by adamrushy** [comment]
Hey, @mdhanif-simformsolutions just checking if you saw our previous messages?

**Comment by adamrushy** [comment]
Hey, @mdhanif-simformsolutions this has now been fully rolled out. Let me know if you have any further questions and thanks for reporting this to us :]

**Comment by mdhanif-simformsolutions** [comment]
Hi @adamrushy @AnatolyRugalev apologies for late reply and thanks for the quick solutions.

Now I am able to successfully ban user from the group there are no issues with that but when I try to unban same user then again I get the error which was previously reported  in this [comment](https://github.com/GetStream/stream-chat-swift/issues/1995#issuecomment-1127767533) screenshot for the permissions are added in this [comment](https://github.com/GetStream/stream-chat-swift/issues/1995#issuecomment-1125711463).

Please let me know if I am missing something here.

**Comment by AnatolyRugalev** [comment]
Hey @mdhanif-simformsolutions 

Thank you for the response. Indeed, this issue was only resolved for `ban`. I am reopening the issue and will let you know when it's fixed. In a meanwhile, you can send us your application ID so we can deploy a fix for your location sooner.

anatoly@getstream.io

**Comment by nuno-vieira** [comment]
This issue is now resolved!

Thank you!

**Comment by mdhanif-simformsolutions** [comment]
Hi @nuno-vieira , @AnatolyRugalev 
I am trying to unban user from channel but when I try to do so it gives me success result but still when I pass query to get the list of ban user's I get the same results no updates. 
I tried to create a new `memberController` from my channel cid and user id now when i print the users of the `memberController` it still gives me `isBannedFromChannel` variable as `true`. Not sure why ? 

Adding  query :- 
```
        let controller = viewModel.chatClient.memberController(userId: selectedUser.id, in: channel.cid)
        controller.unban { error in
            guard error == nil else {
                return
            }
            let userController = viewModel.chatClient.memberController(userId: selectedUser.id, in: channel.cid)
}       
```
if i print `userController.member.isBannedFromChannel` its still `true`. 

Query for getting all the banned members from the channel :- 
```
memberController = viewModel.chatClient.memberListController(
            query: .init(
                cid: channel.cid,
                filter: .equal(.isBanned, to: true),
                pageSize: 30))
        memberController?.synchronize { error in
            guard error == nil else {
                return
            }
            blockedUsers = memberController?.members.compactMap({$0}) ?? []
        }
```

After this as well i get the old same response. Any suggestions ?

**Comment by nuno-vieira** [comment]
Hi @mdhanif-simformsolutions,

You need to call `synchronize()` and use the `delegate` to get data changes. The completion block will only notify if the call was successful or not, but it won't have the most updated data in the completion block. 

Thanks,
Nuno

**Comment by mdhanif-simformsolutions** [comment]
Hi @nuno-vieira 
Understood about the completion block but why it isn't giving me updated data calling the above mentioned query again ?

**Comment by mdhanif-simformsolutions** [comment]
Hi @nuno-vieira @AnatolyRugalev any update on this ?
Thanks

**Comment by polqf** [comment]
Hi @mdhanif-simformsolutions,

What @nuno-vieira tried to say is that you need to follow the following steps
1. Create the controller
2. Call sychronize
3. Call unban
4. Wait for the delegate to tell you that the member has been unbaned

**Comment by nuno-vieira** [comment]
Hi @mdhanif-simformsolutions  !

Sorry, this is indeed a real issue! Could you please open an issue here on Github so that we can track it? We are working on a fix at the moment. 

Best,
Nuno
