### ISSUE TITLE
App Crash in dependency library RxAppState

### ISSUE THREAD

**Issue by Tayphoon** [GetStream/stream-chat-swift#2]
https://github.com/pixeldock/RxAppState/issues/28

**Comment by buh** [comment]
Hi @Tayphoon !
Thanks! I'll update the repo when it will be fixed .

**Comment by Tayphoon** [comment]
I make sample app you can reproduce crash 
[StreamSample.zip](https://github.com/GetStream/stream-chat-swift/files/3617723/StreamSample.zip)

**Comment by Tayphoon** [comment]
Any updates?

**Comment by buh** [comment]
@Tayphoon does it work for you now?
