### ISSUE TITLE
No ViewChanges.itemRemoved on delete channel

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#20]
## What did you do?
Delete channel with `func deleteChannel() -> Observable<Void>` (Channel+Requests.swift:79).

## What did you expect to happen?
Channel is deleted and the `ViewChanges.itemRemoved` is send.

## What happened instead?
Channel is deleted but no `ViewChanges.itemRemoved` is send.

## GetStream Environment
**GetStream Chat version:** 1.3.3
**iOS version:** 12.4.1
**Swift version:** 4.2
**Xcode version:** 10.3
**Device:** iPhone X

**Comment by buh** [comment]
@janweinkauff thanks! I'll check.

**Comment by janweinkauff** [comment]
Haha ... I have to excuse, I recognized just right now that the `deleteChannel()` call we use is something I added to your fork. 🙈

This is the implementation:
```
/// Deletes the channel.
///
/// - Returns: an observable event.
func deleteChannel() -> Observable<Void> {
   let request: Observable<EmptyData> = Client.shared.rx.request(endpoint: .deleteChannel(self))
   return Client.shared.connectedRequest(request.map({ _ in Void() }))
}
```
Maybe I did something wrong.

**Comment by buh** [comment]
I'll check your fork and add it.

**Comment by janweinkauff** [comment]
I found a failing parse attempt of the returned response, I guess this relates to the issue:
```
🦄❌  😡 Decode response in parseMessage(_:)[268]
🦄❌  dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize EventType from invalid String value channel.deleted", underlyingError: nil)) in parseMessage(_:)[268]
```

**Comment by tbarbugli** [comment]
@buh does the swift API client crash when an unknown event type is received? If yes, we need to make sure to add some kind of `unknown` event type or any new/custom event introduced by the API will require upgrading to latest version

**Comment by buh** [comment]
@tbarbugli the client won’t crash with inconsistent data, it will return error and UI will skip a response. 
This issue I already fixed.

**Comment by buh** [comment]
@janweinkauff fixed in v.1.3.6 Please check the Example project (channels in dark mode).
