### ISSUE TITLE
makeLoadingView not called

### ISSUE THREAD

**Issue by Subtextaps** [GetStream/stream-chat-swift#2020]
## What did you do?
Updated the package dependency to StreamChatSwiftUI 4.15.0

## What did you expect to happen?
The method to be called as it was before updating the SDK

## What happened instead?
Nothing. The method is implemented in a ViewFactory instance and was called correctly under the previous package

## GetStream Environment
**GetStream Chat version: 4.15.0
**GetStream Chat frameworks: StreamChat, StreamChatSwiftUI
**iOS version: 15.2
**Swift version: 5
**Xcode version: 13.2
**Device: iPhone 13 Pro Max (Xcode Simulator 13.2)

**Comment by polqf** [comment]
@Subtextaps please move this issue to the correct repo: https://github.com/GetStream/stream-chat-swiftui

**Comment by Subtextaps** [comment]
Will do – thanks!
