### ISSUE TITLE
MemberPayload Parsing Deprecated Roles

### ISSUE THREAD

**Issue by davefoxy** [GetStream/stream-chat-swift#2025]
## What did you do?

I'm trying to use the `channel_role` property on a member but it is not parsed in the application. Instead, `MemberPayload` [is parsing the `role` property](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/APIClient/Endpoints/Payloads/MemberPayload.swift#L32). 

According to the REST docs, this property is deprecated and the backend docs ask to use `channel_role` instead.

<img width="845" alt="Screen Shot 2022-05-26 at 23 06 03" src="https://user-images.githubusercontent.com/1051547/170504037-7385ed8e-31a1-4b89-955d-191b90e9ac79.png">

Note on `role` deprecation here: https://getstream.io/chat/docs/rest/#channels-updatechannel-request (click on `add_members` to drill down to the above screenshot).

## What did you expect to happen?

I expect `channel_role` to be parsed and held in `ChatChannelMember` or to at least have a separate property for `channel_role`.

## What happened instead?

The SDK parses `role` instead.

> Note that we're using the SwiftUI SDK so we'd need the fix available there.

## GetStream Environment
**GetStream Chat version:** 4.15.0
**GetStream Chat frameworks:** StreamChat
**iOS version:** Any
**Swift version:** Any
**Xcode version:** Any
**Device:** Any

## Additional Context

We are trying to store channel-specific data on a user and `extraData` is not appropriate as it's not on a per-channel basis. We essentially have a "VIP member status" concept which needs to be different per chat channel. We decided to use `channel_role` for storing a custom user role but ran into this problem.

If it's not possible or you feel this is a bad direction to go in, any other ideas of how to tackle this would be appreciated.

**Comment by adamrushy** [comment]
Hey, @davefoxy 

Thank you so much for bringing this to our attention, luckily I have this prepared in our backlog of work and I will keep you updated on the progress of this :]

Thanks again,
Adam

**Comment by davefoxy** [comment]
Thanks @adamrushy 
Can you give me an ETA for the fix please? It's kind of a high priority item for a release next week 🙏

**Comment by adamrushy** [comment]
Hey, @davefoxy 

I have created the PR and linked it to the issue. In the meantime, feel free to test using this branch :]

We'll look to get this through testing and ready for release.

Thanks,
Adam

**Comment by davefoxy** [comment]
@adamrushy Just a note that I think you missed another key: https://github.com/GetStream/stream-chat-swift/pull/2028#issuecomment-1149215004
