### ISSUE TITLE
Hide channel with clearHistory doesn't show when new message receive

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2039]
## What did you do?
- login with users x and y on a different device
- x sends a direct message to y
- x will hide the channel with clearing history `channelController.hideChannel(clearHistory: true, completion: nil)`
- y will hide the channel with clearing history `channelController.hideChannel(clearHistory: true, completion: nil)`
- x and y close the app
- x and y re-open the app
- x send a direct message to y
- y doesn't see channel in the channelList

## What did you expect to happen?
- should the channel visible when a new message receive after hiding channel

## What happened instead?
- channel doesn't show in channel list

## GetStream Environment
**GetStream Chat version:** 4.15.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.2
**Swift version:** 5.3
**Xcode version:** 13.2
**Device:** iphone-XS

**Comment by b-onc** [comment]
Hey @ajay-simform 

We were able to pinpoint and resolve the issue. The PR is linked to this ticket. It'd be awesome if you can test the PR & tell us if the issue is resolved!

**Comment by polqf** [comment]
Hi @ajay-simform, we just released [4.17.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.17.0) which contains a fix for the issue you reported.

Let us know if we can help you with something else
