### ISSUE TITLE
App freeze when switch accounts

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2046]
## What did you do?
- Switch login users by disconnect previous user with `ChatClient.shared.connectionController().disconnect()` and connect new user with `ChatClient.shared.connectUser(userInfo: userInfo, token: accessToken)`
- On switch users re-create ChatChannelListVC to solve the **wrong channel list issue**. (Issue link: https://github.com/GetStream/stream-chat-swift/issues/1977)
- Now correct channel list shows but sometimes it freezes the app.
- The CPU usage drastically dropped to 0% and memory usage is being consistent.
- This happens randomly. re-produce rate will be higher if I do nothing after switching accounts for sometimes.

## What did you expect to happen?
- The app doesn't freeze after switching accounts.
- CPU usage doesn't drop dramatically.

## GetStream Environment
**GetStream Chat version:** 4.15.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.2
**Swift version:** 5
**Xcode version:** 13.2
**Device:** IphoneXS

## Additional context
<img width="1391" alt="Screenshot 2022-06-01 at 6 32 46 PM" src="https://user-images.githubusercontent.com/47667077/171566199-659e3421-c683-4457-8b8a-bde4eae7845a.png">

<img width="1401" alt="Screenshot 2022-06-01 at 6 33 02 PM" src="https://user-images.githubusercontent.com/47667077/171566239-a27a0fd7-5092-4c49-9c88-0930ae9460b2.png">

**Comment by polqf** [comment]
Hi @ajay-simform,

Can you post a snippet of your code? You are not supposed to recreate the controller until the `connectUser` call reaches completion.

```swift
        ChatClient.shared.connectionController().disconnect()
        ChatClient.shared.connectUser(userInfo: newUser.userInfo, token: newUser.token) { [weak self] error in
            if let error = error {
                // Handle error
            } else {
                self?.setupRemoteNotifications()
                DispatchQueue.main.async {
                    self?.presentChat(for: user)
                }
            }
        }
```

This is what I've been testing, and it works for me

Let me know if this helps.
