### ISSUE TITLE
Unpin All message

### ISSUE THREAD

**Issue by jitendra-simform** [GetStream/stream-chat-swift#2054]
## What are you trying to achieve?
Please suggest how we can do Unpin all pinned messages 

Thanks

**Comment by polqf** [comment]
Hi @jitendra-simform ,

At the moment we don't provide a way to unpin all messages from a channel.
You can access ChatChannel's `pinnedMessages` to get all the pinned messages.
Then, you can create a `MessageController` for each of them, and call `unpin(completion:)`

**Comment by jitendra-simform** [comment]
No @polqf , as of now
Thanks
