### ISSUE TITLE
Pin Message "Only For me" And "Pin and notify other"

### ISSUE THREAD

**Issue by jitendra-simform** [GetStream/stream-chat-swift#2055]
## What are you trying to achieve?
Please suggest how we can achieve Pin "Only For me" And "Pin and notify other" feature 

Thanks

**Comment by polqf** [comment]
Hi @jitendra-simform,

I am sorry but this is not possible with Stream. Whenever you pin a message, you are pinning it to a channel, not for a user only.
If you were to need this, you would need to use your own backend to achieve it.

**Comment by jitendra-simform** [comment]
Thanks @polqf for quick response and support
