### ISSUE TITLE
SearchQuery not working as expected. 

### ISSUE THREAD

**Issue by alaxicsmith** [GetStream/stream-chat-swift#208]
## What did you do?

I want to search all messages for a specific user. I used the code below: 

```
let query = SearchQuery(filter: .in("members", [StreamChatClient.User.current.id]),
                                query: query,
                                pagination: .limit(10) + .offset(10))
        Client.shared.search(query: query) { result in
            guard let messages = result.value else {
                completion([StreamChatClient.Message]())
                return
            }
            
            completion(messages)
     }
```
## What did you expect to happen?

I expected an array of messages to be returned. 

## What happened instead?

An empty array was returned, despite seeing messages that match the query. 

## GetStream Environment
**GetStream Chat version:**
2.0
**iOS version:**
iOS 13.2.3
**Swift version:**
5.0
**Xcode version:**
11.2.1
**Device:**
iPhone 11 Pro

**Comment by b-onc** [comment]
Closing since this is being handled in our official support channel.

**Comment by alaxicsmith** [comment]
I’m still waiting for a response. Last item we need before we can deploy this.
