### ISSUE TITLE
Include message padding in the MessageViewStyle struct

### ISSUE THREAD

**Issue by KevinMiller-TheWing** [GetStream/stream-chat-swift#209]
## What are you trying to achieve?
I would like to be able to set the padding between the `messageLabel` and its superview, `messageContainerView` in order to style the `MessageTableViewCell` cell to match specifications from my designer. 

## If possible, how can you achieve this currently?
I'm not able to do this without unlocking `StreamChat` framework, and I'd rather not do that.  

## What would be the better way?
The padding values are defined in `CGFloat+Extensions.swift`. I would propose adding  a new property, perhaps something like `messageContainerPadding` to the `MessageViewStyle` struct. This property would have a default value of the constant defined in the `CGFloat` extension. The style struct would then be used when the constraints are made in the `setupIfNeeded(style:)` method in  `MessageTableViewCell`

I'm happy to make a PR to do the above.

## GetStream Environment
**GetStream Chat version:** 2.0.1
**iOS version:** 13.3
**Swift version:** 5
**Xcode version:** 11.3.1 
**Device:** Any

**Comment by buh** [comment]
Hi @KevinMiller-TheWing !
Thanks for your message! We're trying to make the message view customizable as much as possible. Did you check this page with styles? https://github.com/GetStream/stream-chat-swift/wiki/Styles It would be great if you can share a part of your design to see the issue.
We're open for your PR!

**Comment by KevinMiller-TheWing** [comment]
Sure thing! 
This is the styling I would like, that I made by adjusting `messageHorizontalInset` and `messageVerticalInset` 
 
![Screen Shot 2020-04-23 at 6 18 51 PM](https://user-images.githubusercontent.com/52974770/80155362-95e74280-858f-11ea-86ff-32e17786698f.png)

And here is what is possible using only the style struct: 
![Screen Shot 2020-04-23 at 6 21 21 PM](https://user-images.githubusercontent.com/52974770/80155415-ad263000-858f-11ea-9ca8-3771bbde7aed.png)

You can see the difference is subtle, but the top one has more spacing between the message container and the text. With a larger font and a larger lineheight, the extra spacing is necessary.  I don't think this achievable with the built in style struct.

**Comment by b-onc** [comment]
Hello @KevinMiller-TheWing 
We'd be glad to review your PR!

**Comment by buh** [comment]
Merged #216
