### ISSUE TITLE
Crash on direct chat, force unwrap on channelController.cid!

### ISSUE THREAD

**Issue by michallaskowski** [GetStream/stream-chat-swift#2091]
## What did you do?
Tried to open a direct chat with a user.

## What did you expect to happen?
Chat to be opened.

## What happened instead?
App crashes on `messageComposerVC.channelController = client.channelController(for: channelController.cid!)`
Line 75, ChatChannelVC.swift
`channelController.cid` is nil, and force unwrap crashes the app.

## GetStream Environment
**GetStream Chat version:** 4.16.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.4.1
**Swift version:** Swift 5.6
**Xcode version:** 13.4.1
**Device:** iPhone 13

## Additional context
For some reason seems to be working fine on our production builds (TestFlight), fails on Staging builds (TestFlight) and local builds from Xcode using the same Production scheme, or Staging scheme.

**Comment by b-onc** [comment]
Hello @michallaskowski ,
Can you share the full code?

**Comment by polqf** [comment]
Hi @michallaskowski, we just released [4.17.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.17.0) which contains a fix for the crash you reported.

Let us know if we can help you with something else
