### ISSUE TITLE
Message List Scroll Issue

### ISSUE THREAD

**Issue by jitendra-simform** [GetStream/stream-chat-swift#2094]
## What did you do?
Send message to other user

## What did you expect to happen?
Receiver user message list screen should not jump or auto scroll 

## What happened instead?
Receiver user message list screen jump and auto scroll

## GetStream Environment
GetStream Chat version: 4.15
GetStream
iOS version: 15.2
Swift version: 5
Xcode version: 13.2
Device: Simulator

https://user-images.githubusercontent.com/97155807/174076637-6a6c4164-94b3-45af-816d-694d49e02c01.mov

**Comment by b-onc** [comment]
Hello @jitendra-simform ,

This is known and internally tracked as CIS-1347.

**Comment by nuno-vieira** [comment]
Hi @jitendra-simform!

This issue will be released in the 4.21.0 version.

We'll let you know, once we publish the release. The ETA is next week. 

Best,
Nuno

**Comment by jitendra-simform** [comment]
> 

Thanks for update @nuno-vieira

**Comment by nuno-vieira** [comment]
Hi!

This issue is now solved in the **4.21.1** release.

Thank you for your patience! 

Best,
Nuno
