### ISSUE TITLE
Xcode 14 compilation bug

### ISSUE THREAD

**Issue by Lomovsky-Alex** [GetStream/stream-chat-swift#2117]
## What did you do?
I'm trying to build the project with the latest StreamChat library version (v4.17.0; installed via CocoaPods)

## What did you expect to happen?
The project should be built without errors. 

## What happened instead?
I get the same error from 7 different classes in Xcode 14 beta 1:
Stored properties cannot be marked potentially unavailable with '@available'

## GetStream Environment
**GetStream Chat version:*4.17.0*
**GetStream Chat frameworks: StreamChat, StreamChatUI
**iOS version:*16*
**Swift version:*5.7*
**Xcode version:*14 beta 1*
**Device:*iPhone 13 Pro Simulator*

## Additional context
As far as I'm concerned, you need to update library to new Swift 5.7

<img width="1118" alt="Screenshot 2022-06-24 at 11 40 25" src="https://user-images.githubusercontent.com/84700615/175498571-668675b0-8a70-4533-8826-b2afb13d186c.png">
<img width="369" alt="Screenshot 2022-06-24 at 11 40 33" src="https://user-images.githubusercontent.com/84700615/175498576-587ce43c-57fe-4bdb-86d5-fa4f9cffe379.png">

**Comment by adamrushy** [comment]
Hey, @Lomovsky-Alex 

We actually created a branch for the moment which resolves the issues here, of course, this is early betas so things could change. You can read more on the discussion [here](https://github.com/GetStream/stream-chat-swift/discussions/2079)

I hope this helps 👍🏼

**Comment by Lomovsky-Alex** [comment]
> Hey, @Lomovsky-Alex
> 
> We actually created a branch for the moment which resolves the issues here, of course, this is early betas so things could change. You can read more on the discussion [here](https://github.com/GetStream/stream-chat-swift/discussions/2079)
> 
> I hope this helps 👍🏼

Thank you, I'll check this. Have a nice day ☺️

**Comment by bielikb** [comment]
@Lomovsky-Alex the beta branch can be digested via SPM only. Hope that's fine with you.
