### ISSUE TITLE
Sending giphy without preview when clicked on any giphy from list

### ISSUE THREAD

**Issue by SSaleemSSI** [GetStream/stream-chat-swift#2120]
## What are you trying to achieve?
I have implemented giphy controller which will reveal all giphy from where we can search giphy as well. What i want is to send that giphy directly when user click on them.

## If possible, how can you achieve this currently?
Its not currently not possible

## What would be the better way?
![Simulator Screen Shot - iPhone 8 Plus - 2022-06-24 at 13 21 59](https://user-images.githubusercontent.com/86655959/175556853-ca57d8ca-292a-437b-aee3-6d3bca9c0c2a.png)

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by SSaleemSSI** [comment]
Thanks for the reply. I am able to populate the giphys but when on clicked on them i am not able to create a new messge with the attachement for giphy

**Comment by bielikb** [comment]
@SSaleemSSI,

I see. we're not exposing the initializer for `GiphyAttachmentPayload`. 
In that case you would be able to call something in these lines:

```
...
let gifURL = media.url(rendition: .fixedWidth, fileType: .gif)

// StreamChat part
let attachment = GiphyAttachmentPayload(title: "Title of the giphy", previewURL: gifURL, actions: [])
let attachments = [AnyAttachmentPayload(payload: attachment)]
channelController?.createNewMessage(
    text: "",
    attachments: attachments)
)
```

**Comment by SSaleemSSI** [comment]
Sure i'll update the Library. Thanks for the help. @bielikb

**Comment by SSaleemSSI** [comment]
Hi @bielikb i have to reach you again with an issue as i was able to send the giphy with new code merged from mobile devices but when showing giphy on web there were missing some properties like **WIDTH** and **HEIGHT** in the original object of giphy. Can u tell me why is that?
`media.url(rendition: .original, fileType: .gif)`
this is what i am sending as URL

**Comment by SSaleemSSI** [comment]
@bielikb 
Besides the problem on web with the giphy object view there is another issue on mobile as all giphys have fixed height and width. We need to aspect ratio so that text on bottom doesn't cut in mobile. Smaller giphy are zooming due to fixed height and width.

**Comment by bielikb** [comment]
Hi @SSaleemSSI I see. Currently this is not possible. We could expose extra data field for your giphys where you could send this additional info and then parse it on your end
