### ISSUE TITLE
Can't build SDK on Xcode 14 beta

### ISSUE THREAD

**Issue by atineoSE** [GetStream/stream-chat-swift#2123]
## What did you do?
I tried compiling the demo project [here](https://github.com/GetStream/swiftui-chat-tutorial) in Xcode 14.0 beta.

## What did you expect to happen?
I expected to be able to run the demo app just as with the latest stable version of Xcode.

## What happened instead?
I got 5 compile errors stating:
```
Stored properties cannot be marked potentially unavailable with '@available'
```

## GetStream Environment
**GetStream Chat version:** 4.6.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 15.0 (deployment target in demo project)
**Swift version:** 5
**Xcode version:** 14.0 beta
**Device:** N/A

## Additional context
Compatibility with Xcode 14 will be important once it gets out of beta and becomes the default IDE.

**Comment by bielikb** [comment]
Hi @atineoSE 

please leverage our `xcode14` branch while `Xcode 14.0` is in beta development.

You can learn more [here](https://github.com/GetStream/stream-chat-swift/discussions/2079)

**Comment by atineoSE** [comment]
Awesome, thanks!
