### ISSUE TITLE
Getting [String] array from a RawJSON response

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-swift#2127]
## What are you trying to achieve?

I want to achieve a list of strings in [String] format from a RawJSON custom object , consisting of RawJSON strings. The response is a RawJSON object like below:

Optional(StreamChat.RawJSON.array([StreamChat.RawJSON.string("173"), StreamChat.RawJSON.string("143")]))

but i am not able to get this response in [String] array variable

## If possible, how can you achieve this currently?

At the moment, i am using a decoder to get this response in a string like below:

       let adminsRawJSON: RawJSON = self.channelController?.channel?.extraData["channel_admins"]
        var data = try? encoder.encode(adminsRawJSON)
        let adminStr:String  = String(data: data!, encoding: .utf8)
        
which isn't helping me^ as it converts all the strings to a simple string

## What would be the better way?

I want the ["channel_admins"] response to get stored in a [String] instead of RawJSON

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by b-onc** [comment]
Hello @muaviyaijaz123 ,

Will this work for you?
```swift
let rawJSONArray = RawJSON.array([.string("Hello"), .string("there"), .string("General"), .string("Kenobi")])
        
if case let .array(rawJSONStrings) = rawJSONArray {
    let fullString = rawJSONStrings.compactMap { if case let .string(str) = $0 { return str } else { return nil } }.joined(separator: " ")
    print(fullString)
}
```
prints "Hello there General Kenobi"

**Comment by muaviyaijaz123** [comment]
@b-onc well no . What you are doing here would help me in inserting data back to that custom field. I am getting this data from backend in RawJSON variable nesting a RawJSOn array inside. What I want is below:
<img width="894" alt="Screen Shot 2022-06-28 at 5 28 09 PM" src="https://user-images.githubusercontent.com/90596703/176178766-93aa7b8f-92dc-4d79-b3e1-4678d0884ff6.png">

**Comment by b-onc** [comment]
@muaviyaijaz123 In this case you need to extend `ChatChannel` like so:
```swift
extension ChatChannel {
    var channelAdmins: [String]? {
        if case let .array(rawJSONStrings) = extraData["channel_admins"] {
            return rawJSONStrings.compactMap { if case let .string(str) = $0 { return str } else { return nil } }
        }
        return nil
    }
}
```

Then you can access your field:
```swift
let strings: self.channelController?.channel?.channelAdmins
```

**Comment by muaviyaijaz123** [comment]
@b-onc  It worked! Thanks a lot mate !

**Comment by b-onc** [comment]
You're welcome!

**Comment by muaviyaijaz123** [comment]
@b-onc  Hi, can you help me in parsing this data into a Dictionary array in swift coming from backend in custom field:

            message.extraData[activity_members] 
            
which return this response in RawJSON:
     
     Optional(StreamChat.RawJSON.array([StreamChat.RawJSON.dictionary(["id": StreamChat.RawJSON.string("143"), "name": StreamChat.RawJSON.string("shahid.iqbal+2344")])]))

**Comment by hugobernalstream** [comment]
Hi @muaviyaijaz123,

Thank you for reaching out. Have you tried using the Raw values helpers? if this case you can parse from the RawJSON type to dictionary using `.dictionaryValue` property. For instance:
```
let extraData = message.extraData
let flightPrice = extraData["flight"]?.dictionaryValue?["price"]?.numberValue ?? 0
``` 

This was added in our 4.19.0 release. You can find more info here: https://getstream.io/chat/docs/sdk/ios/uikit/extra-data/#reading-extra-data

Let me know if this helps.

Regards,
Hugo
