### ISSUE TITLE
No push notifications or notification.message_new event sent for giphy message

### ISSUE THREAD

**Issue by arthurchambsp** [GetStream/stream-chat-swift#213]
## What did you do?
I send a message with /giphy command in a web interface.

## What did you expect to happen?
I expect to receive a push notification when my user is offline and an `notification.message_new` event when he's online

## What happened instead?
No push notification nor `notification.message_new` event triggered

## GetStream Environment
**GetStream Chat version:**
`2.0.1`
**iOS version:**
`13.3.1`
**Swift version:**
`5.0`
**Xcode version:**
`Version 11.3.1 (11C505)`
**Device:**
`iPhone X`

**Comment by b-onc** [comment]
Hello @arthurchambsp ,

Are you sure you setup the push notifications correctly?
Please follow
https://getstream.io/chat/docs/push_ios/?language=swift
to setup your Keys, and
https://getstream.io/chat/docs/push_devices/?language=swift
to add the device id (so it's eligible to receive notifications)

You can follow these steps to make sure your config is correct and working:
1. Clone our repo for push testing: https://github.com/GetStream/chat-push-test
2. Configure necessary fields in the iOS test app: App ID, App Secret, Server location
3. Run the app, grant notification permission, copy the command it outputs and background the app
4. Register our APNS certificate for example app, following page: https://getstream.io/chat/docs/push_ios/?language=swift
5. Install stream-chat-cli: https://github.com/GetStream/stream-cli
6. Run the command the iOS app outputted in step 3 in your macos terminal
If done correctly, you should not see any errors after running command in step 6, and should correctly receive notification in your device.

**Comment by arthurchambsp** [comment]
Hello @b-onc 

I have no issues with all other types of messages, my issue is only related to giphy message.

**Comment by b-onc** [comment]
Hello @arthurchambsp , thanks for raising this.
Our backend team has made a fix for this and no Swift SDK changes will be needed: https://github.com/GetStream/chat/pull/1003/files

I'm closing this issue.

**Comment by b-onc** [comment]
Hello @arthurchambsp , thanks for raising this.
Our backend team has made a fix for this and no Swift SDK changes will be needed

I'm closing this issue.
