### ISSUE TITLE
Filtering channels through query defined not working 

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-swift#2134]
## What did you do?
I want to filter channels based on my query defined  in ChannelListQuery class. Here is my following code snippet:

-->Query applied in ChannelListQuery class:
// ------
       static func containChannelID(channelIds: [ChannelId]) -> Filter<Scope> {
          .in(.cid, values: channelIds)
        }
// ------

-->My Class code: (extending ChannelListVC class)

       var pinnedChannelsArray = ChatClient.shared.currentUserController().currentUser?.pinnedChannels. //custom field getting my pinned channels
        print("Pinned array size: \(pinnedChannelsArray!.count)")
        print("Pinned array 1st element: \(pinnedChannelsArray![0])") //printing first element of pinned array
        var channelID : [ChannelId] = [] // a channel id array
        for cid in pinnedChannelsArray!{
            do{
                channelID.append(try ChannelId.init(cid: cid )). // create a cid from and append it in list
            }
            catch{
                print("in catch block")
            }
        }
        let pinnedchannelListQuery: ChannelListQuery = ChannelListQuery( filter: .containChannelID(  //query applied
                channelIds: channelID
            )
        )    
  
            finalQuery = pinnedchannelListQuery
            print("Pinned query: \(finalQuery)")
     
        let channelListController = ChatClient.shared.channelListController(query: finalQuery). //query applied
        for channel in channelListController.channels{
            print("Channel cid: \(channel.cid)").    //prints the wrong channels (all of them) that do not match the query
        }
        controller = channelListController
        print("No of channels found: \(controller.channels.count)")
        
 --> Logs:
        
<img width="822" alt="Screen Shot 2022-06-30 at 11 29 44 AM" src="https://user-images.githubusercontent.com/90596703/176608277-98ec8498-1202-42c4-a570-7a2604f54455.png">
The query should only return the green one highlighted but as you can see in logs it returns all the channels

## What did you expect to happen?
 I expected to get only one filtered channel matching the cid i gave in the array

## What happened instead?
I got all of the channels though the query only should match one result. 

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by muaviyaijaz123** [comment]
I Changed the query to check on dates too and it is working but i still don't get it why it wasn't on previous query

**Comment by bielikb** [comment]
Hi @muaviyaijaz123 we will check the above internally. thanks for the report
