### ISSUE TITLE
Add channel ownCapability variable in ChannelDetailPayload

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2140]
## What are you trying to achieve?
- Need to access channel `own_capabilities` in `ChannelDetailPayload`
- Please add `capability` variable in ChannelDetailPayload for us to access.

## GetStream Environment
**GetStream Chat version:** 4.17.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.5
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone-13

## Additional context
<img width="568" alt="image (5)" src="https://user-images.githubusercontent.com/47667077/177162878-dcde3b6e-6bef-452b-8bf3-1704eb1a4a74.png">

**Comment by nuno-vieira** [comment]
Hi @ajay-simform!

This is a feature currently missing from the iOS SDK. The iOS SDK is still relying on the `channel.config`. If for some reason the `channel.config` is not enough for you, you can still access the capabilities in the extra data field. Let us know if that unblocks you.

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi!

The issue has been fixed in the 4.22.0 release! 🚀 

Thank you for your patient!

Best,
Nuno
