### ISSUE TITLE
Filter Channels Based on lastMessageAt and channelcreatedAt

### ISSUE THREAD

**Issue by SSaleemSSI** [GetStream/stream-chat-swift#2150]
## What are you trying to achieve?
When we create a channel its lastMessageAt field is missing, how can i apply filter on createdAt if lastMessageAt field is missing?
What i am trying to achieved is I have to filter channels based on lastMessageAt if they are 24 hours old. I am able to filter them in case if lastMessageAt exists as stated below:
```
let tempChannelListQuery: ChannelListQuery = .init(
            filter: .and([
.and([
.less(.lastMessageAt, than: Calendar.current.date(byAdding: .day, value: -1, to: Date())!) , 
.notcontainChennelID(
                channelIds: channelID
            )]), 
.containMembers(userIds: [ChatClient.shared.currentUserId!])])
           )
```

How can i filter a channel on created_at field if its lastMessageAt field is missing because that channel does not have any messages.

## If possible, how can you achieve this currently?
Currently not possible.

## What would be the better way?
Have filter query which will check if one field doesn't exists then it check on second field just like if else.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
<img width="382" alt="Screenshot 2022-07-07 at 2 15 36 PM" src="https://user-images.githubusercontent.com/86655959/177738493-db68f5c2-6679-4409-b53d-084727159ceb.png">
<img width="368" alt="Screenshot 2022-07-07 at 2 15 28 PM" src="https://user-images.githubusercontent.com/86655959/177738508-6959cf23-6fb2-45d1-8d61-492138c73cac.png">

Just like shown in this pic in channel one field is missing and in other field exists, its impossible to filter the field for these two channels, what if i want to check if these two channels are 24 hours older using lastMessageAt field but query always return one channel due to field existence.

**Comment by nuno-vieira** [comment]
Hi @SSaleemSSI,

What you basically want is to filter messages that the `lastMessageAt` is older than 24 hours **or** the `channel.createdAt` is lower than 24 hours. So you need to apply an `or` operator.

So in your query, where you have the `less()` filter, you should replace with:
```swift
.or([
      .less(.lastMessageAt, than: Calendar.current.date(byAdding: .day, value: -1, to: Date())!),
      .less(.createdAt, than: Calendar.current.date(byAdding: .day, value: -1, to: Date())!)
  ]),
```

Final query:
```swift
let tempChannelListQuery: ChannelListQuery = .init(
                filter: .and([
                    .and([
                        .or([
                            .less(.lastMessageAt, than: Calendar.current.date(byAdding: .day, value: -1, to: Date())!),
                            .less(.createdAt, than: Calendar.current.date(byAdding: .day, value: -1, to: Date())!)
                        ]),
                        .notcontainChennelID(channelIds: channelID)]),
                    .containMembers(userIds: [ChatClient.shared.currentUserId!])]
                )
            )
```

Let me know if this worked!

Thank you,
Nuno
