### ISSUE TITLE
Intercept Error Messages to allow Customer to use there own Messages

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#217]
## What are you trying to achieve?
Currently our customers see these cryptic error messages like:
Operation Couldn't be Completed
(StreamChatClient.AnyError error 1)

I would like to have the ability get a callback to allow us to show our own messages.
That way we can use our own Localization system and hide the fact that this is StreamChat as well.

## If possible, how can you achieve this currently?
Beats me

## What would be the better way?
Allow for a callback or delegate to let the client know there is an error

## GetStream Environment
**GetStream Chat version:**
2.0.0

**iOS version:**
all

**Swift version:**
5.1

**Xcode version:**
all
**Device:**
all

**Comment by b-onc** [comment]
Hello @khoogheem , thanks for the feature request. We'll definitely add this functionality in one of the upcoming releases.

**Comment by b-onc** [comment]
`show(error:)` can be overridden in both ChannelsViewController and ChatViewController
