### ISSUE TITLE
Extra space before first list item in ordered list

### ISSUE THREAD

**Issue by alexandersandberg** [GetStream/stream-chat-swift#2173]
## What did you do?

We recently upgraded from 4.15.0 to 4.18.0 and noticed that the first item in an ordered list now has some extra space.

I'm guessing this bug was introduced when markdown support was added in 4.17.0.

## What did you expect to happen?

No extra space in the first list item.

## What happened instead?

Extra space.

| 4.15.0 | 4.18.0 |
| --- | --- |
| <img width="296" alt="Before" src="https://user-images.githubusercontent.com/35671299/179250333-6ce2aa5b-d964-4a6b-b886-cee561a3804d.jpeg"> | <img width="296" alt="After" src="https://user-images.githubusercontent.com/35671299/179250753-c2a78a8f-2265-4153-8eaf-1d7833e80f12.jpeg"> |

## GetStream Environment
**GetStream Chat version:** 4.18.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.4
**Swift version:** 5.6
**Xcode version:** 13.3
**Device:** iPhone 12 mini

**Comment by nuno-vieira** [comment]
Hi @alexandersandberg!

Thank you for the bug report! I was able to reproduce it as well.

We will track it internally and fix it as soon as possible 👍 

Keep in mind, that if you are not interested in Markdown Support, you can always disable it like this:
`Appearance.default.formatters.isMarkdownEnabled = false`, this will unblock you for now until we fix this. If of course, you are fine with disabling Markdown.

Best,
Nuno

**Comment by alexandersandberg** [comment]
Thanks, @nuno-vieira! We've been waiting for markdown support, so we will live with this bug for now. But thanks for the tip! 🙂

**Comment by gsbernstein** [comment]
Seems like with markdown enabled the bug here is the opposite of how it's stated in the title: aligned indents and hanging indents are _desired_ in formatted lists, so the markdown is working correctly on the _first_ item but not on the subsequent items.

Is there any progress on a fix in that direction?

**Comment by laevandus** [comment]
Hello @alexandersandberg, we have released a new iOS SDK version [4.51.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.51.0) which addresses issues with markdown. Thank you for reporting this issue.
