### ISSUE TITLE
Navigation issues in channel list view

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swift#2181]
I'm trying to create a custom channel list view using SwiftUI and am having a problem where chatting in Stream kicks me out of the navigation view hierarchy back to the channel list view.

This is a follow-on issue to the previously created https://github.com/GetStream/stream-chat-swift/issues/2167#issuecomment-1184783058. The solution in this issue was to switch to subscribing to changes in `channels` using `@StateObject var channelList: ChatChannelListController.ObservableObject` as documented in the sample code for Stream. However, using the pattern of creating a channel list view [as documented](https://github.com/GetStream/stream-chat-swift/blob/develop/StreamChatSample/Samples/SwiftUISimpleChat/ChannelListView.swift#L54) leads to this issue where views get popped off the navigation stack, and you're kicked out of threads (back into a channel) and out of channels (back into the channel list).

I've reproduced this issue in the SwiftUI portion of the `StreamChatSample`. In this video, you can see me navigate into a channel, then when I begin to type, I'm kicked out of the channel back into the `ChannelListView` again. This is intermittent. This is the same issue we are having in our app — except this also happens anytime we navigate into threads as well.

https://user-images.githubusercontent.com/144283/180077363-ba26bc14-465a-4e49-ba4a-0aed439efd48.MOV

Notably, this issue does not exist in the [Stream SwiftUI project’s demo app](https://github.com/GetStream/stream-chat-swiftui/tree/main/DemoAppSwiftUI) — I can't reproduce any of our navigation issues in that app.

I’m going to study the SwiftUI project to see how it’s using `NavigationView` and `NavigationLink` such that these issues are avoided, but I wanted to create this issue to see if this is a thing you’ve struggled with before, and if you might have any guidance for avoiding that might not be obvious.

Maybe related to https://github.com/GetStream/stream-chat-swiftui/issues/122. Maybe a bug in `NavigationView`.

**Comment by moubry** [comment]
Update: It turns out, I was wrong earlier when I said this issue does not exist in [Stream SwiftUI project’s demo app](https://github.com/GetStream/stream-chat-swiftui/tree/main/DemoAppSwiftUI) — it looks like it does exist there too:

https://user-images.githubusercontent.com/144283/180087530-e66a6934-70c4-48ed-a663-8c8c349545e7.MP4

Interestingly, I can ONLY reproduce this issue when the message list view is scrolled up. If you're scrolled to the bottom, you won't get kicked out of the thread:

https://user-images.githubusercontent.com/144283/180088180-d87c849b-2b91-4be3-9f3b-11962613fc9f.MOV

**Comment by polqf** [comment]
Closing this issue as it has been moved here: https://github.com/GetStream/stream-chat-swiftui/issues/144
