### ISSUE TITLE
Context Menu doesn't open on collectionView sometimes on holding collectionView Item

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-swift#2182]
## What did you do?
--> ChannelListVCSubclass:

            @available(iOS 13.0, *)
            open func collectionView(_ collectionView: UICollectionView, contextMenuConfigurationForItemAt indexPath: IndexPath, point: CGPoint) -> UIContextMenuConfiguration? {
                            return UIContextMenuConfiguration(identifier: nil,
                            previewProvider: nil) { suggestedActions  in

                                        let leaveChat = UIAction(title: "Leave Chat",
                                            image: UIImage(systemName: "person.badge.minus")?.withTintColor(UIColor.white),
                                            identifier: nil, discoverabilityTitle: nil) { actionn  in
                                            }
                           return UIMenu(title:"", children: [leaveChat])
                        }

        }

## What did you expect to happen?
I expect to see a context menu everytime i hold the collectionView Item

## What happened instead?
The issue arises, that sometimes it opens and sometimes it doesn't. Here' s a video for the behaviour

https://user-images.githubusercontent.com/90596703/180162838-2d31946f-73c0-4ac2-bb17-867e72e64ce4.mov

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by polqf** [comment]
Hi @muaviyaijaz123,

If I get this right, this is your custom UI, correct? `ChannelListVCSubclass` is not part of our codebase, therefore there's not much we can do about it.

As per the issue itself, it seems the long press is conflicting with the scroll.

Closing this issue for now, let us know if there's anything else we can help with

**Comment by muaviyaijaz123** [comment]
Hi @polqf,

I am extending sdk class ChatChannelListVC for customising it . I have just found the issue with this . Issue is with swipeableview pangesturerecognizer . It gets conflicted with long press .

One would need to disable the panGesturdeRecognizer in ChatChannelListCollectionViewCell setUp class to disable the swipe and to implement the menu display
