### ISSUE TITLE
Share picture blinks

### ISSUE THREAD

**Issue by jrBordet** [GetStream/stream-chat-swift#2184]
## What did you do?

- Share picture or take photo
- Send it on chat
- The images sent <b>blinks</b> one time on the thread

## What did you expect to happen?

The image should not <b>blink</b>

## GetStream Environment
**GetStream Chat version: 4.18.0**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by polqf** [comment]
Hi @jrBordet,

Thank you for your report. We've internally logged it and we will work on it!

**Comment by jrBordet** [comment]
Hi guys, is there some news about this issue? Can I do something?

**Comment by nuno-vieira** [comment]
Hi @jrBordet,

This issue will be fixed by https://github.com/GetStream/stream-chat-swift/pull/2226. It will come on the next 4.21.0 release.

We will let you know when we officially release 4.21.0. The ETA is next week.

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi!

This issue is now solved in the **4.21.1** release.

Thank you for your patience! 

Best,
Nuno
