### ISSUE TITLE
CRASH - ChannelListController line 88

### ISSUE THREAD

**Issue by tr736-reclip** [GetStream/stream-chat-swift#2221]
I would love to give you more information but all ive got is the crashlogs and screens

<img width="653" alt="Screenshot 2022-08-07 at 20 55 01" src="https://user-images.githubusercontent.com/108519197/183308871-7f68deae-d77c-4f03-b870-17b9f10db1c5.png">

<img width="1007" alt="Screenshot 2022-08-07 at 20 51 27" src="https://user-images.githubusercontent.com/108519197/183308836-41f21388-a2dd-473e-88eb-b89f428ce673.png">

[crashlog.txt](https://github.com/GetStream/stream-chat-swiftui/files/9277396/crashlog.txt)

**Comment by hugobernalstream** [comment]
Hi @tr736-reclip,

Thanks for your report. Reviewing the info you provide, in the crashlog you can notice that this is a Watchdog termination, that usually means that there is a heavy task blocking the main thread and the system crashes the app. Also, in the stack trace I notice in 8 that the issue might be in a file called `ChatService.swift, line 379` Please check that you are not blocking the main thread with heavy tasks and you can set the combine signal to the main thread/loop when it is appropriated using `.receive(on:)`.

I leave a couple of links that you can check to understand the issue better:
- https://developer.apple.com/documentation/xcode/addressing-watchdog-terminations
- https://developer.apple.com/documentation/combine/publishers/map/receive(on:options:)

Hope this info helps you and let us know how it goes.

Regards,
Hugo

**Comment by nuno-vieira** [comment]
Hi @tr736-reclip,

I'm closing the issue for inactivity, and also it seems the issue is an integration problem. 

Let us know if you have any more questions, or if the info provided by Hugo did fix the problem.

Best,
Nuno
