### ISSUE TITLE
I was unable to get push notifications

### ISSUE THREAD

**Issue by inic07** [GetStream/stream-chat-swift#2235]
I have followed all steps listed here - https://getstream.io/chat/docs/sdk/ios/guides/push-notifications/ to implement push notifications with get stream and firebase. Have added private key generated from firebase to get stream dashboard and did configuration in my iOS code.

I was unable to get push notifications.
Any help would be greatly appreciated!

## GetStream Environment
**iOS version: 4.9.0**
**Xcode version:13.4 (13F17a)**
**Device:iPhone X**

**Comment by nuno-vieira** [comment]
Hi @inic07,

What is the SDK Version? It is 4.9.0? Firebase push notifications only work after 4.14.0. Can you update to the lastest version (4.20.0)?

In order for firebase to work, when adding the device, you need to set the firebase option: `addDevice(.firebase(...))`.

Thanks,
Nuno

**Comment by inic07** [comment]
` 
ChatClient.shared.currentUserController().addDevice(PushDevice.firebase(token: token)) { error in
      if let error = error {
                 Logger.log("adding a device failed with an error \(error)")
           }
 }`

**Comment by nuno-vieira** [comment]
Hi @inic07!

Thanks, we will further investigate this one and will get back to you once we have more details.

Best,
Nuno

**Comment by inic07** [comment]
@nuno-vieira  Thanks for your support there was a minor mistake in syntax, just needs to provide > "providerName" with it .
<img width="461" alt="Screenshot 2022-08-18 at 6 41 15 PM" src="https://user-images.githubusercontent.com/69636497/185403169-d4f79f3b-f227-4292-ac8a-4dbc0b06e0fb.png">

**Comment by nuno-vieira** [comment]
Awesome @inic07!
