### ISSUE TITLE
Flag User - Nothing in Dashboard

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#225]
## What are you trying to achieve?
Not sure this is a bug or Feature.. but if you Flag a user there is nothing that shows up in Dashboard.. so right now it seems to be a useless feature

## If possible, how can you achieve this currently?
I would assume if you Flag a user it should show up in moderation... However there really is no context as to why it was flagged.. I would assume that for the message change where the user was flagged that should potentially be sent up.. as the person that was flagging was probably saying hey this users Messages are out of line

## GetStream Environment
**GetStream Chat version:**
2.1.0
**iOS version:**
any
**Swift version:**
Any
**Xcode version:**
any
**Device:**
any

**Comment by b-onc** [comment]
Hello @khoogheem 
You're correct, currently flagged users are not visible on dashboard. We'll introduce this in the future.
I'm closing this since it's not iOS SDK related. Please reach us on our official support channel (support@getstream.io) for dashboard related queries.
