### ISSUE TITLE
No sound for push notifications

### ISSUE THREAD

**Issue by SSaleemSSI** [GetStream/stream-chat-swift#2256]
## What did you do?
Notification template is dropped in v2, so in v1 i was using my custom payload template to enable the notification sound how can i now enable the notifications sounds? Or from where i can set my custom payload for v2 notifications?
https://getstream.io/chat/docs/react/push_templates_in_v2/
I followed this document but i am unable to understand where i can fix this issue.

## What did you expect to happen?
Sound should come for push notifications

## What happened instead?
No sound

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by nuno-vieira** [comment]
Hi @SSaleemSSI,

You can add sound to notifications in the Notification Service Extension, here is the documentation on how to do it: https://getstream.io/chat/docs/sdk/ios/guides/push-notifications/#customising-remote-push-notifications

You can add a sound to the notification content. 

Closing the issue for now. Let us know if you have any further questions.

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @SSaleemSSI, that should be done in your app, it is not the responsibility of the SDK. You can observe events with the `EventsController`. Docs here: https://getstream.io/chat/docs/sdk/ios/uikit/controllers/events/#eventscontroller

**Comment by Zee-93** [comment]
> Hi @SSaleemSSI,
> 
> You can add sound to notifications in the Notification Service Extension, here is the documentation on how to do it: https://getstream.io/chat/docs/sdk/ios/guides/push-notifications/#customising-remote-push-notifications
> 
> You can add a sound to the notification content.
> 
> Closing the issue for now. Let us know if you have any further questions.
> 
> Best, Nuno

@nuno-vieira 
That link is not working. Could you please send the updated one?

**Comment by nuno-vieira** [comment]
Hi @Zee-93,

You can search on our docs, but here it is: https://getstream.io/chat/docs/sdk/ios/client/push-notifications/#notification-service-extension
