### ISSUE TITLE
Enable search capability through the Stream Dashboard

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2268]
## What are you trying to achieve?
- I need to search channel names, messages and usernames from all over the stream chat dashboard.
- I go through the [doc](https://getstream.io/chat/docs/ios-swift/search/?language=swift) and found that only swift SDK implementation is pending.
- Can you please share the expected time to release this feature? This is a high priority for us.

Thank you.

## GetStream Environment
**GetStream Chat version:** 4.20.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI

**Comment by polqf** [comment]
Hi @ajay-simform, 

You can go to your Dashboard > Your app > Channel Types > Click on the type you want. In there you have the capabilities section where you can enable/disable them.

**Comment by polqf** [comment]
As per the availability in the SDK, it is an issue in the docs that we are solving. You can search for messages using the following snippet:

```
let controller = client.messageSearchController()
        controller.search(
            query: MessageSearchQuery(channelFilter: .containMembers(userIds: ["john"]),
                                      messageFilter: autocomplete(.text, text: "supercalifragilisticexpialidocious"))
        ) { error in
            if let error = error {
                // Handle error
            } else {
                let messages = controller.messages
                // Use messages
            }
        }
```

**Comment by tbarbugli** [comment]
we also added this code example to the chat docs, thank you for letting us know they were missing :)
