### ISSUE TITLE
Xcode 14 build fails

### ISSUE THREAD

**Issue by Rohan-diy** [GetStream/stream-chat-swift#2283]
## What did you do?
Run a project with streams as a dependency.

## What did you expect to happen?
Project to run successfully 

## What happened instead?
Build failed

## GetStream Environment
**GetStream Chat version:*4.0.0*
**GetStream Chat frameworks:** StreamChatUI
**iOS version:*16*
**Swift version:*5.7*
**Xcode version:*14*
**Device:*iPhone 13 Simulator*

## Additional context
Error: Stored properties cannot be marked potentially unavailable with '@available'

**Comment by nuno-vieira** [comment]
Hi @Rohan-diy!

4.0.0 is an old version. As mentioned in the README [here](https://github.com/GetStream/stream-chat-swift#using-xcode-14-beta), if you need Xcode14, you should use 4.20.0+

Best,
Nuno

**Comment by Rohan-diy** [comment]
> Hi @Rohan-diy!
> 
> 4.0.0 is an old version. As mentioned in the README [here](https://github.com/GetStream/stream-chat-swift#using-xcode-14-beta), if you need Xcode14, you should use 4.20.0+
> 
> Best, Nuno

Thanks @nuno-vieira, My bad I missed it. A quick question. Have you identified any issues in your transition to Xcode 14/iOS 16 ?

**Comment by nuno-vieira** [comment]
@Rohan-diy,

All good for now 👍
