### ISSUE TITLE
Unread count gets reset after sending a message even though the message list screen was dismissed

### ISSUE THREAD

**Issue by matthewjsloane** [GetStream/stream-chat-swift#2284]
## What did you do?
I opened the message list for a channel and then dismissed it. From another user on a different device, I sent a message to that channel.

## What did you expect to happen?
I expected the unread count to go from 0 to 1.

## What happened instead?
The unread count went from 0 to 1, but then the channel was marked as read afterwards, causing it to reset to 0. Subsequent messages started incrementing the unread count again as expected.

## GetStream Environment
**GetStream Chat version:** 4.21.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15
**Swift version:** 5
**Xcode version:** 13.4.1
**Device:** iPhone 13 Pro Max

## Additional context
It's almost as if the message channel is "staying open" longer than it should, and causing messages to be marked as read even when the view is no longer on the screen. Possibly some sort of race condition? Let me know if you need any additional details.

**Comment by nuno-vieira** [comment]
Hi @matthewjsloane,

We were able to reproduce this in our demo app. We will investigate it and will let you know once we have more details.

Thank you for the report!

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi!

The issue has been fixed in the 4.22.0 release! 🚀 

Thank you for your patient!

Best,
Nuno

**Comment by matthewjsloane** [comment]
Thanks for the update and your quick support!
