### ISSUE TITLE
ThreadSafeWeakCollection create the internal queue wrong way

### ISSUE THREAD

**Issue by gongruike** [GetStream/stream-chat-swift#2299]
## What did you do?
Just checking the source code

## What did you expect to happen?
use a concurrent queue as a read&write lock

## What happened instead?
user a serial queue

## GetStream Environment
**GetStream Chat version:*main branch*
**GetStream Chat frameworks:*main branch* StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
ThreadSafeWeakCollection use a dispatch queue as a read&write lock, but if you don't pass the '.concurrent' attribute explicitly , the os will create a serial queue by default.

**Comment by polqf** [comment]
Hi @gongruike,

Thank you for the report! That was a miss from our side. 
Fixing it now.
