### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by Tayphoon** [GetStream/stream-chat-swift#23]
Does sdk has logout to support multiple users?

**Comment by buh** [comment]
@Tayphoon When your user will log in, set a Stream User for the Stream Chat Client with appropriate Token:
```swift
func set(user: User, token: Token)
func set(user: User, _ tokenProvider: TokenProvider)

```

**Comment by Tayphoon** [comment]
i think it would be right way to stop observe web socket events if user do logout.  You already have reset function but it private

**Comment by buh** [comment]
Do you keep `ChatViewController` in view hierarchy when your user was logged out?
The client will disconnect when all subscribers stop observing events. You have to stop any observations to avoid any extra work of the client.

**Comment by Tayphoon** [comment]
No, we do not keep ChatViewController instance, we have service which subscribed to channel events. Thanks i will review this way - unsubscribe all observers
