### ISSUE TITLE
Crash in version `2.1.0`

### ISSUE THREAD

**Issue by arthurchambsp** [GetStream/stream-chat-swift#230]
Hello, it's me again ! :)

## What did you do?
I just run my app after upgraded to `2.1.0` version and I run into a crash when I tried to query channels. 

## What did you expect to happen?
No crash 🤷‍♂️ 

## What happened instead?
A crash !

## GetStream Environment
**GetStream Chat version:**
`2.1.0`
**iOS version:**
`iOS 12.2 (16E226)`
**Swift version:**
`Swift 5`
**Xcode version:**
`Version 11.4.1 (11E503a)`
**Device:**
`iPhone X`

## Additional context

**It might be related to iOS version, I have no problem on my device in iOS 13.4 but on my simulator in iOS 12.2, it's a crash.**

**Also tested on an iOS 12.4 simulator, I encounter the crash**

**Also tested on an iOS 13.4.1 simulator, no crash**

I call `StreamService.getChannels` in my app :
![Screenshot 2020-04-30 at 15 39 25](https://user-images.githubusercontent.com/57522333/80718960-1ad7dc00-8afb-11ea-9892-786a148f6cac.png)

It calls `Client.queryChannels` :
![Screenshot 2020-04-30 at 15 39 35](https://user-images.githubusercontent.com/57522333/80719028-2f1bd900-8afb-11ea-8d30-00b4bcbb559a.png)

Then  `Client.request<A>` :
![Screenshot 2020-04-30 at 15 39 48](https://user-images.githubusercontent.com/57522333/80719034-304d0600-8afb-11ea-9455-90ea39238ff4.png)

Here's stack trace :
![Screenshot 2020-04-30 at 15 40 32](https://user-images.githubusercontent.com/57522333/80719038-30e59c80-8afb-11ea-9414-4292058a7c32.png)

**Comment by buh** [comment]
Hi @arthurchambsp!
I can't reproduce the issue. I tried iOS 12.2 and iOS 11.0.1.
But by your logs, I tried to fix it. Can you try `crash-iOS12` branch for `StreamChatClient`?
https://github.com/GetStream/stream-chat-swift/tree/crash-iOS12

**Comment by arthurchambsp** [comment]
Sorry for late notice ! I try it right away !

**Comment by arthurchambsp** [comment]
Still have the issue, same stack trace :/

**Comment by buh** [comment]
Hi @arthurchambsp
I'm sorry I can't reproduce the issue. Can you make an example app (or based on our example app)?

**Comment by b-onc** [comment]
PR #250 opened, which tests iOS 12.4 and iOS 11.4 integrations. Our integration tests seem to pass

**Comment by b-onc** [comment]
Hello @arthurchambsp ,
I cannot reproduce the issue on iOS 12.4 simulator. I can query channels successfully without crash, also all our tests pass for iOS 12.4 and 11.4.

Can you please prepare a sample project, or code block, anything to reproduce this? Might also be a compiler/runtime hiccup on your end, did you try cleaning derived data & such?

**Comment by arthurchambsp** [comment]
Hi ! Sorry for late notice

`2.2.2` version fixes the crashes ! 
Meantime I've clean my derived data and stuff, so maybe it was related.

**Comment by b-onc** [comment]
Great to hear!
