### ISSUE TITLE
Allow developers to filter message list

### ISSUE THREAD

**Issue by virbedi** [GetStream/stream-chat-swift#2305]
## What are you trying to achieve?
We are trying to hide/show threaded replies sent to the main channel based on a boolean flag. 

## If possible, how can you achieve this currently?
We are checking the content of each message and passing empty layoutOptions for ones we should hide. 
This affects scroll performance and does not always provide clean hide/show views of the channel.

## What would be the better way?
Making `ChatMessageListVC` > `dataSource` open so that we can override it or allow the ability for users to perform a query on the message list in order to decide which messages are rendered.

## GetStream Environment
**GetStream Chat version:**
4.15
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
16
**Swift version:**
5
**Xcode version:**
13.3
**Device:**
iPhone 13 Pro Max

## Additional context
This request was initially opened as a support ticket - 27570

**Comment by polqf** [comment]
Hi @virbedi ,

As we discussed in a support ticket, this is not a functionality we currently have in the SDK.
We will open a feature request and will prioritize it accordingly.

Will keep you updated

**Comment by nuno-vieira** [comment]
Hi @virbedi,

You can try overriding the following methods from `ChatChannelVC`: 

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/12814114/191239240-e6bba4ed-eb8f-4cdf-91d0-5cf95405be34.png">

Your suggestion is already possible. The `ChatMessageListVCDataSource` is already open, but you need to override it in the `ChatChannelVC`, not `ChatMessageListVC`. 

For your use case, we are not sure what could be the consequences of overriding this, so keep that in mind. 

Let us know if this worked for you.

Best,
Nuno

**Comment by virbedi** [comment]
Hello @nuno-vieira,
Overriding these functions seem to lead to frequent crashes related to mismatched indexes. 

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 124 from section 0 which only contains 48 rows before the update'
terminating with uncaught exception of type NSException
CoreSimulator 802.6 - Device: iPhone 13 (E33F5BC3-4E30-40F1-B369-6FDF712889AC) - Runtime: iOS 15.4 (19E240) - DeviceType: iPhone 13
```

**Comment by nuno-vieira** [comment]
Hi @virbedi!

Yes, that could be happening. Can you share how are you overriding all the methods above?

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @virbedi!

I can confirm this is not possible right now, it will require us to open more APIs, or even introduce a filter block that you could use to filter messages locally. We will discuss this internally and will let you know once we have more details and if this is something we want to support. 

Best,
Nuno

**Comment by virbedi** [comment]
Opening up the option to locally filter the list would really help with developing the threading UI we are working on.
I'll keep an eye out for updates in the mean time. 

Thank you!
