### ISSUE TITLE
Textview scroll while writing

### ISSUE THREAD

**Issue by BarragaoA** [GetStream/stream-chat-swift#2321]
Hello

## What did you do?
I'm writing a long message

## What did you expect to happen?
See what i'm writing 

## What happened instead?
The textview scroll up and down while

## GetStream Environment
**GetStream Chat version: 4.22.0**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version: 16.0**
**Swift version: 5**
**Xcode version: 14.0.1**
**Device: iPhone Xr**

## Additional context

https://user-images.githubusercontent.com/86778557/193777297-d4a513cd-7c79-4b2f-af73-7b9e0bc131d4.mov

**Comment by nuno-vieira** [comment]
Hi @BarragaoA!

I'm not able to reproduce this one in our DemoApp. Do you have any customizations of the Composer?

Thank you!

**Comment by BarragaoA** [comment]
Hello,

I remove my customizations and it works well, you're right. My bad, sorry for the inconvenience. 
I should have checked before if it came from my customizations, sorry again.

Thank you !

**Comment by nuno-vieira** [comment]
@BarragaoA No problem!

**Comment by BarragaoA** [comment]
FYI it comes from :
```
override func updateContent() {
        super.updateContent()
        composerView.attachmentButton.isHidden = false
    }
```

**Comment by nuno-vieira** [comment]
If you don't want attachments, you can disable them or the Dashboard. Or in the composer view you can also override `isAttachmentsEnabled`

**Comment by BarragaoA** [comment]
Actually I want it but it disappear when we start writing and that what i do not want.

**Comment by nuno-vieira** [comment]
You can try and override directly the `textViewDidChange` and hide it there 🤔
