### ISSUE TITLE
Dynamic Type changes not reflected in ChatMessageContentView.textView

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#2325]
## What did you do?
Adjusted the iOS system setting for Dynamic Type (Settings -> Accessibility -> Display & Text Size -> Larger Text)

## What did you expect to happen?
I expected all of the text elements in StreamChatUI to update to match the selected larger text size

## What happened instead?
Only some of the text elements updated. ChatMessageContentView.textView did not update. I had to restart the app to see the setting applied

## GetStream Environment
**GetStream Chat version:** 4.22.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.0

## Additional context
See attached sample project:
[StreamDynamicText.zip](https://github.com/GetStream/stream-chat-swift/files/9717678/StreamDynamicText.zip)

Steps to reproduce:
- Open app, tap Enter Channel List, enter channel, notice text element sizes
- Navigate to iOS Settings and increase Dynamic Type setting
- Return to app and notice that some elements (header, timestamps, composer placeholder) have their text sizes increased
- Notice the chat message UITextView's do NOT have their text sizes increased
- Restart app and navigate back to the chat channel
- Notice the chat message UITextView's now have their text sizes increased

See sequential screenshots below:
Set system setting to small size:
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 12 07 54](https://user-images.githubusercontent.com/4721220/194122706-25212dc1-ef96-41c8-ae5a-fff5869dd0c7.png)
Demo app shows small sizes:
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 12 08 11](https://user-images.githubusercontent.com/4721220/194122724-5402d8f2-fcab-4100-a047-56c021cb3fd7.png)
Set system setting to large size:
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 12 08 18](https://user-images.githubusercontent.com/4721220/194122736-ac0ba032-3bae-4bb0-a513-efc6746558b6.png)
Demo app shows some, but not all large sizes:
![Simulator Screen Shot - iPhone 14 Pro - 2022-10-05 at 12 08 27](https://user-images.githubusercontent.com/4721220/194122757-99b1fa85-8666-4903-84ef-54b9dd8a52a9.png)
After restarting app, all text elements show the large size
![afterAppRestart](https://user-images.githubusercontent.com/4721220/194122765-1b648af1-e8c6-4183-9c40-f80f9f3008bc.png)

**Comment by nuno-vieira** [comment]
Hi @srgray!

Thank you for the issue report! We will let you know once we have a fix available!

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @srgray!

We did an initial investigation, and we are correctly using `adjustsFontForContentSizeCategory` and we are using also `UIFont.preferredFont` as well, so everything should be everything fine, but it is not for some unknown reason. We will take a deeper look into it whenever possible 👍 

Best,
Nuno

**Comment by nuno-vieira** [comment]
UPDATE: I was able to understand the issue, and will open a PR soon 🙂

**Comment by nuno-vieira** [comment]
The fix will be available on the next release, we will close the issue once it is officially released.

Thank you!

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi!

The issue has been fixed in the 4.23.0 release! 🚀

Thank you for your patient!

Best,
Nuno
