### ISSUE TITLE
Resend action for messages with attachments 

### ISSUE THREAD

**Issue by saidReclip** [GetStream/stream-chat-swift#2326]
Hi there!
Is it possible to add support of resend message action for messages with attachments? 
![IMG_0913](https://user-images.githubusercontent.com/102264702/194117034-046e3a8d-96dc-43a3-a9b5-f0d1cdf78b24.PNG)
![IMG_0912](https://user-images.githubusercontent.com/102264702/194117065-9dc1b0c7-1d7f-4a3e-bf54-dca151b3be1c.PNG)

**Comment by nuno-vieira** [comment]
Hi @saidReclip,

This is already in our backlog, we will let you know once we pick this one up.

Best,
Nuno

**Comment by jfru** [comment]
Hi @nuno-vieira have you guys had a chance to work on this yet?
