### ISSUE TITLE
can't get channel members with specific role

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2327]
## What did you do?
- create a custom channel member role. let's say "channel_admin"
- assign this custom channel role to some users
- I only want to get a channel member which has "channel_admin" role
- Please help me how to create memberListController filter query for the same

## GetStream Environment
**GetStream Chat version:** 4.22.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.0
**Device:** iPhone-X

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

This is kinda explained in the docs, most filters work the same way. Here: https://getstream.io/chat/docs/sdk/ios/uikit/controllers/channels/#1-create-a-query

In the MemberList case, instead of `ChannelListFilterScope`, you need `MemberListFilterScope`. Example:

`let filter = Filter<MemberListFilterScope>.init(operator: .equal, value: "channel_admin")`

Thanks,
Nuno

**Comment by ajay-simform** [comment]
Hi @nuno-vieira ,
Thanks for replying.

This filter query doesn't help for me. This is the query I execute to get "channel_admin" list.
Could you please help me on that?
```
let filter = Filter<MemberListFilterScope>.init(operator: "$eq", key: "channel_role", value: "channel_admin")
let adminListController = chatClient.memberListController(
        query: ChannelMemberListQuery(
        cid: channel.cid,
        filter: filter))
adminListController.synchronize()
```

`synchronize` returned this error response:
```
{
  "code" : 4,
  "message" : "QueryMembers failed with error: \"unrecognized field \"channel_role\"\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "details" : [

  ],
  "StatusCode" : 400,
  "duration" : "0.00ms"
})
```

**Comment by nuno-vieira** [comment]
@ajay-simform,

Can you try this:

```swift
let adminListController = chatClient.memberListController(
             query: ChannelMemberListQuery(
             cid: channel.cid,
             filter: .equal(.role, to: .admin)))
```

**Comment by ajay-simform** [comment]
@nuno-vieira It doesn't work.
It throws me this response:

```
{
  "code" : 4,
  "message" : "QueryMembers failed with error: \"unrecognized field \"role\"\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "details" : [

  ],
  "StatusCode" : 400,
  "duration" : "0.00ms"
})
```

To understand the actual data structure, I shared a chat explorer screenshot.
<img width="732" alt="Screenshot 2022-10-10 at 4 34 47 PM" src="https://user-images.githubusercontent.com/47667077/194853103-d79b5347-0cd6-4f95-b369-bd027d8b6a5e.png">

**Comment by nuno-vieira** [comment]
Hi @ajay-simform!

I was to replicate the issue. The same filter is working for the User List, but not for Member List. So most likely it is a backend issue. We will let you know once we have this fixed. 

Thank you for your patience!

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

Right now the `channel_role` is not filterable in the Member List Query. The backend will change this soon, I'll let you know once this deployed on the backend 👍 

Best,
Nuno

**Comment by ajay-simform** [comment]
Hi @nuno-vieira 
Any update on this issue? It is major blocker for us 🤞

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

The ETA for this is to be released next week. We will keep you posted.

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @ajay-simform!

We have a patch ready for you. Do you mind sharing your APP_ID so that we can deploy it to your location? You reply here or send me to my email nuno@getstream.io in case you don't want to share your APP_ID here. 

Best,
Nuno

**Comment by ajay-simform** [comment]
Hi @nuno-vieira ,
Thanks for the patch ready.
I just sent an email to you with AppIds. Please find it.

Thank you.

**Comment by nuno-vieira** [comment]
> Hi @nuno-vieira ,
> 
> Thanks for the patch ready.
> 
> I just sent an email to you with AppIds. Please find it.
> 
> 
> 
> Thank you.

Hi! The fix in now deployed in your location 👍

Best,
Nuno
