### ISSUE TITLE
Query Filter on extraData

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swift#2329]
## What are you trying to achieve?

My root issue is I’m using SteamSwiftUI and want to filter the `ChannelListView` based on a custom value I’m currently storing in a channel’s extra data. In my app there is custom UI where users can tag channels with this special value, and I want to show all the channels where this is set.

The way that seems the most natural to achieve this in the Swift SDK is to create a `ChannelListViewModel` with a `ChannelListController` that has a `ChannelListQuery` that does this filtering, but there does not appear to be a way to create a channel list query on extra data.

## If possible, how can you achieve this currently?

As far as I know there's no way to filter a channel list on values in extra data.

## GetStream Environment
**GetStream Chat version:** `main`
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**Xcode version:** Version 14.0.1 (14A400)

**Comment by nuno-vieira** [comment]
Hi @moubry!

Yes, you can filter with extraData properties. We are planning on improving this in the documentation, but right now it is available here: https://getstream.io/chat/docs/sdk/ios/uikit/controllers/channels/#1-create-a-query 


So, you can use plain String keys, to define the custom extra data properties. Example: `.equal("state", to: "LA")`

Best,
Nuno
