### ISSUE TITLE
Mention feature not working with muting a chat

### ISSUE THREAD

**Issue by muaviyaijaz123** [GetStream/stream-chat-swift#2340]
## What did you do?
 I muted a chat. Then someone mentions me in that chat. I didn't receive a notification for that chat even though i have muted it but mention feature should have allowed me to receive that notification

## What did you expect to happen?
I should have received the notification because i was mentioned in a chat although i have muted it

## What happened instead?
I didn't receive any notification

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by polqf** [comment]
Hi @muaviyaijaz123 ,

Let me get back to you on this, I want to confirm this is not like this by design.

**Comment by polqf** [comment]
Hi @muaviyaijaz123 ,

I just confirmed that this is the expected behavior

**Comment by muaviyaijaz123** [comment]
Hi @polqf,

Can you please confirm that by expected behaviour by design, i should not receive notification of mention on mute chat or should i?

**Comment by polqf** [comment]
It is expected behaviour by design, yes. You will not be getting a notification for a muted channel when they mention you.
