### ISSUE TITLE
Message Actions Popup doesn't work in thread reply after restarting app

### ISSUE THREAD

**Issue by VictorSemenchuk** [GetStream/stream-chat-swift#2343]
## What did you do?
Precondition: I'm using the default UI from StreamChatUI.
1. Open any channel and add reply to any message. Long press on the left reply - context menu displays as expected.
2. Restart the app.
3. Go to the channel which was used at the 1st step and find your reply. Long press on the reply - nothing happens.

## What did you expect to happen?
Context menu displays each type I make long press on a thread reply.

## What happened instead?
Context menu is not displayed if the reply is taken from cache if I make long press on a thread reply. 
Looks like `channel` is `nil` in `MessageDTO` took via `FRC`.

## GetStream Environment
**GetStream Chat version:** 4.22.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.0.1
**Device:** iPhone 14 Pro

**Comment by nuno-vieira** [comment]
Hi @VictorSemenchuk!

I was able to reproduce the issue. Thank you for the report! We will let know once we have a fix for this one!

Best,
Nuno

**Comment by AlexanderFulcrum** [comment]
Stumbled on the same issue, can be pretty pesky for the user. Is there any ETA on the fix?

**Comment by nuno-vieira** [comment]
> Stumbled on the same issue, can be pretty pesky for the user. Is there any ETA on the fix? 

Hi @AlexanderFulcrum , we don't have a ETA yet, we will let you know once we pick this one up.

**Comment by nuno-vieira** [comment]
Hi @AlexanderFulcrum, @VictorSemenchuk!

Good news, this fix will be shipped in the next release :) 

We let you know once that happens, the ETA is this week, worst case scenario, next week. 

Best,
Nuno

**Comment by polqf** [comment]
Hi! This has been fixed in our latest release [4.25.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.25.0)
Closing this issue for now, feel free to reopen it if you encounter any issues.
