### ISSUE TITLE
Invalid URL [404] in Error Documentation

### ISSUE THREAD

**Issue by Sherlouk** [GetStream/stream-chat-swift#2344]
## What did you do?

Hey 👋  I'm currently going through the process of trying to setup the Stream SDK. I've run into a `ConnectionNotSuccessful` error (but this GitHub issue isn't about that! I'm still debugging 😄)

I just wanted to note though that the localised description links to [this page](https://getstream.io/chat/docs/sdk/ios/basics/getting-started/#your-first-app-with-stream-chat) which doesn't exist 😱  The code is [here](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/ChatClient.swift#L632).

## What did you expect to happen?

Well ideally, I wouldn't have seen an error 😛  but in this situation, I would've expected a URL to link to more helpful documentation (I'll let you know once I figure out what helpful documentation is!)

## What happened instead?

I got a dead URL

## GetStream Environment
**GetStream Chat version:** 4.22.0
**GetStream Chat frameworks:** StreamChat

**Comment by Sherlouk** [comment]
For those who stumble across this issue wondering why they're seeing a `ConnectionNotSuccessful` ("Connection to the API has failed.") - my root cause was because I forgot to hold a strong reference to the ChatClient instance which meant the connection request was being cancelled before it completed and as such throwing the error.

Perhaps there's a feature request here for the SDK to return a different error for cancelled requests as this feels like an easy mistake to make 😄 

Alas, this GitHub issue still stands as linking to a dead link is never helpful!

**Comment by nuno-vieira** [comment]
Hi @Sherlouk!

Thank you for your report! We have updated now the link with the correct one 🙂

Best,
Nuno
