### ISSUE TITLE
Ban/Unban query listing issue

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swift#2356]
### Parent issue link :- 
https://github.com/GetStream/stream-chat-swift/issues/1995#issuecomment-1290760750

## What did you do?
Unban user from the banned user list and after that fetched banned user list again.

## What did you expect to happen?
The user which was unban is still present in banned user list.

## What happened instead?

I am trying to unban user from channel when I try to do so it gives me success result but still when I pass query to get the list of ban user's I get the same results no updates.

Query for getting all the banned members from the channel :-

```
memberController = viewModel.chatClient.memberListController(
            query: .init(
                cid: channel.cid,
                filter: .equal(.isBanned, to: true),
                pageSize: 30))
        memberController?.synchronize { error in
            guard error == nil else {
                return
            }
            blockedUsers = memberController?.members.compactMap({$0}) ?? []
        }
```
After this as well i get the old same response. Any suggestions ?

GetStream Chat version: 4.22.0
GetStream Chat frameworks: StreamChat, StreamChatSwiftUI
iOS version: 16.0
Swift version: 5
Xcode version: Xcode-14

**Comment by nuno-vieira** [comment]
Hi @mdhanif-simformsolutions!

After further analysing your code, what you actually want, is something like this:

```swift
/// Setup the member controller, you need to remove the `filter: .equal(isBanned, to: true)`
memberController = viewModel.chatClient.memberListController(
            query: .init(
                cid: channel.cid
           )
)
memberController?.delegate = self
memberController?.synchronize()

/// Implement the memberControllerDelegate
func memberListController(
        _ controller: ChatChannelMemberListController,
        didChangeMembers changes: [ListChange<ChatChannelMember>]
    ) {
        blockedUsers = controller.members.filter(\.isBannedFromChannel)
    }
```

This should do the trick 🙂 

Let me know if you have further questions.

Best,
Nuno
