### ISSUE TITLE
Pagination issue in ChannelList

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2358]
Test case:
- set channelList page size = 10
- Load all the channels, for example, you have only 10 channels in your list: `Channel 1 -> Channel 10`
- Force close the app, let BE created 15 channels & marked you as the owner: `Channel 11 -> Channels 25`
- Open the app -> notice that it’s showing the last 4 channels correctly: `Channel 22 -> 25`
- call channel pagination to fetch more channels -> you can only see the `Channel 1 -> Channel 10` + `Channel 16 -> Channels 25` in your list, the middle part is missing

The reason is that,
* when you first go to the channelList & call synchronized, getstream will fetch the 1st page: `Channel 16 -> 25` in this case
* when you call getstream’s loadMoreChannel method, this is where the bug happens:
   * right now, we have 20 channels in total in our local cache: `Channel 1 -> 10` and `16 -> 25`
   * b/c of that, getstream set offset = 20 in the loadMoreChannel method
   * since the offset is 20, the API result is `channel 1 -> 5`
   * since the returned data size is less than the page size, getstream marks it that all data has been returned
* in the end, we are left w/ incomplete data: `Channels 1 -> 10` and `Channels 16 -> 25`

## GetStream Environment
**GetStream Chat version:** 4.23.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 16.0
**Swift version:** 5
**Xcode version:** 14.0

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

We are currently investigating this one, we will let you know once we have more details 👍 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

Are you able to test this WIP commit: 51e0332396c6c039e7e821bd94c26e1ee9091442

You should point the SDK dependency to that commit, and check if the issue is solved on your side.

Let us know how it goes.

Best,
Nuno

**Comment by 123andreas4** [comment]
Sent from Proton Mail for iOS
Please let all the emails send from GitHub stop

Op EE, MMM d, jjjjj om HH:mm, Ajay ***@***.***> schreef:

**Comment by nuno-vieira** [comment]
Hi @123andreas4,

What do you mean? If you don't want to get notified by email, you can stop watching the repository.

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

Did you have the time to test that commit?

Best,
Nuno

**Comment by ajay-simform** [comment]
Hi @nuno-vieira ,

The issue still happens with the commit you shared above.
If the page size is 10, showing the last 4 channels shouldn't correct behaviour. :crossed_fingers:

Thanks,
Ajay

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

Sorry, what do you mean?

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

> If the page size is 10, showing the last 4 channels shouldn't correct behaviour. 

Can you elaborate on what do you mean by this? Maybe show an example?

**Comment by nuno-vieira** [comment]
This fix is now available in the 4.26.0 release.

Thank you for your patience.

Best,
Nuno
