### ISSUE TITLE
Watching channel issue after background to foreground transition

### ISSUE THREAD

**Issue by jderes** [GetStream/stream-chat-swift#2359]
I have a strange issue around re-entering foreground and syncing the chat channel. Basically, when the chat channel screen is still visible after background->foreground transition, it behaves like I’m not observing the channel, because the NotificationMessageNewEvent events are triggered. To better explain here are the steps to reproduce:

1. Device A: Open a chat channel screen 
2. Background the app (home button or lock the screen)
3. Device B: Send a message to the channel from
4. Message is delivered as push notification 
5. Device A: Open the app again - NOT from the notification - just click on the app icon or unlock the screen
6. After a second the last message shows up - looks like the controller has reconnected and started watching the channel again
7. Send any new message in the channel, either from Device A or B. NotificationMessageNewEvent is triggered as if the channel was not observed.

We use NotificationMessageNewEvent for showing local notifications when you’re outside of chat screen, so it is an issue.
Is there a bug here or am I missing something and my use case is flawed?

## GetStream Environment
**GetStream Chat version: 4.22/4.23
**GetStream Chat frameworks: StreamChat, StreamChatUI

**Comment by polqf** [comment]
HI @jderes,

Every time we open the channel screen (or come from background), we make sure to observe the channel. I guess this is the reason why you might be receiving `NotificationMessageNewEvent`.
This is done to ensure that you receive events for that channel in edge cases where you might not be observing it anymore.

All in all, I think `NotificationMessageNewEvent` might not be your best ally for this use case. Or if you want to use it, you might need to check the id of the channel (`cid`) in the event to see if it matches or not.

**Comment by jderes** [comment]
Thank you, I understand. In this case i'm going to work around it.

**Comment by nuno-vieira** [comment]
Hi @jderes,

As Pol said, `NotificationMessageNewEvent` is probably not the best event for your use case. Or at least, you need to check if the channel screen is currently open. If it is, then don't show the notification. 

Closing this one for now.

Let us know if you have more questions.

Best,
Nuno
