### ISSUE TITLE
ChatViewController `Upload from a camera` is not work(2.1.0)

### ISSUE THREAD

**Issue by koishi** [GetStream/stream-chat-swift#236]
## What did you do?
After updated to 2.1.0, `Upload from a camera` doesn't work anymore.
The same is 2.1.1.
I set it back to 2.0.0 and it worked correctly.

## What did you expect to happen?
That a photo I took will be attached to the message

## What happened instead?
When I take a photo and return to the chat screen
I get the following error log and the photo is not attached.
> File URL cannot be determined for file named: photo_2020_05_03_205602.jpg

## GetStream Environment
**GetStream Chat version:** 2.1.0
**iOS version:** 13.3.1
**Swift version:** 5.1
**Xcode version:** 11.3.1
**Device:** iPhone 11 Pro

## Additional context
none

**Comment by koishi** [comment]
I created PR
https://github.com/GetStream/stream-chat-swift/pull/237

**Comment by buh** [comment]
PR #239
