### ISSUE TITLE
Completion fired twice on connectUser

### ISSUE THREAD

**Issue by remvst** [GetStream/stream-chat-swift#2362]
## What did you do?

- call `connectUser()`, receive completion 1
- call `logout()`
- call `connectUser()` again, receive completion 1 and 2

## What did you expect to happen?

I would expect only one completion per `connectUser()` call, instead of firing both.
If it is expected to fire multiple times, maybe it should be renamed to "listener"?

## What happened instead?

First completion handler was fired twice.

## GetStream Environment
**GetStream Chat version:** 4.23.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 15.6.0
**Swift version:** 4
**Xcode version:** 14
**Device:** iPhone X

**Comment by polqf** [comment]
Hi @remvst , this issue has been solved in 4.24.0
Feel free to reopen this issue if you encounter any problem
