### ISSUE TITLE
How are we meant to determine user's visibility preference?

### ISSUE THREAD

**Issue by sgoodwin** [GetStream/stream-chat-swift#2368]
## What are you trying to achieve?

I see in the docs where you can set a user to "invisible" mode so they don't show as online, but I want to make that a control the user can change. How are we meant to determine that the user has been set to invisible?

## If possible, how can you achieve this currently?

I thought to check the `lastActiveAt` value, but that remains populated wether the user is invisible or not. I also looked in the `extraData` field, but there's no hint there either.

## What would be the better way?

Ideally next to `isOnline` there's also be `isVisible`.

## GetStream Environment
**GetStream Chat version:** main branch
**GetStream Chat frameworks:** StreamChat
**iOS version:** 16
**Swift version:** 5
**Xcode version:** 14.1
**Device:** iPhone 13 Pro

**Comment by polqf** [comment]
Hi @sgoodwin ,

By invisible you mean a banned user? I'm sorry I am not fully understanding what you are doing and what is your expected outcome.

**Comment by sgoodwin** [comment]
@polqf I mean to hide a user's online status. Is that not a thing we can do?

**Comment by polqf** [comment]
This is a feature that is currently not available in iOS. We will be prioritizing it in our backlog! 🙏

**Comment by sgoodwin** [comment]
From poking around, it looks like `invisible` is a property present in the `CurrentUserPayload`, it just isn't persisted into the `CurrentUserDTO` so and subsequently pulled out into `CurrentUser`.

**Comment by polqf** [comment]
Correct @sgoodwin. This is something the API already returns, but we haven't implemented on the SDK side.

**Comment by polqf** [comment]
Hi! This has been fixed in our latest release [4.25.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.25.0)
Closing this issue for now, feel free to reopen it if you encounter any issues.
