### ISSUE TITLE
More clarity on Invites flow

### ISSUE THREAD

**Issue by mdhanif-simformsolutions** [GetStream/stream-chat-swift#2379]
## What did you do?
I wanted to add an invite feature in my app but not sure about the current implementation in the latest stream chat version as in the official docs it's mentioned that it's not fully implemented in the SDK yet. Here is the official doc link:- https://getstream.io/chat/docs/ios-swift/channel_invites/?language=swift

Can you share what are the implemented features and what is planned and needs to be implemented in near future(also if possible when can we expect those) so that we can avoid rework and can plan for implementation accordingly

## What did you expect to happen?
A clear idea of available features in the current SDK version.

**Comment by polqf** [comment]
Hi @mdhanif-simformsolutions , it seems to be a false positive on the documentation.

Invite, Accept/Reject Invite and Listing Invite Statuses is all available, as the documentation says on the documentation.
Please reopen this issue if you are missing anything.
