### ISSUE TITLE
moderator can't observe newly created channel

### ISSUE THREAD

**Issue by ajay-simform** [GetStream/stream-chat-swift#2424]
- update the member role for `User A` with `moderator`
- Update the channel list query with the following for `User A` to fetch channels with `xyz` type:
 ```
private func channelUserQuery(_ userId: String) -> ChannelListQuery {
        return .init(
            filter: .or([
                .and([
                    .equal(.type, to: .custom("xyz")),
                ]),
                .and([
                    .containMembers(userIds: [userId]),
                ])
            ])
        )
    }
```
- `User B` creates a channel with the `xyz` type. (`User A` is not a member of this channel).
- Problem: `User A` doesn't observe this new channel in his channel Listing. He has to restart the app to get these channels.

- Our goal is moderator can get all "xyz" types of channels. No matter whether he is a member or not. He can observe and chat on these channels. Currently, the user has to restart the app to get updated channels. Pls, suggest.

## GetStream Environment
**GetStream Chat version:** 4.25.0
**GetStream Chat frameworks:** StreamChatSwiftUI

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

The query is saying that the user should contain the member. So this is expected? You should remove the `.containMembers(userIds: [userId])` for the moderator then. 

Also, can you share what is the `filter` block of the `ChannelListController`? At runtime, whenever a new channel is created, it will first check the `filter` block to check if it belongs to the controller or not.

Best,
Nuno

**Comment by ajay-simform** [comment]
Hi @nuno-vieira ,
regarding query:
- If channel type is `XYZ` then no need to check for `containMembers`. The `containMembers` only checks for the other channel types. I don't add any filter block here.
- This is my actual query for channelListController:

```
channelListVC = ChatClient.shared.channelListController(
            query: .init(
                filter: .or([
                    .and([
                        .equal(.type, to: .custom("xyz")),
                    ]),
                    .and([
                        .containMembers(userIds: [currentUserID]),
                    ])
                ])
            )
        )
```

Also added boolean condition for `ChatChannelListControllerDelegate`:

 ```
func controller(
        _ controller: ChatChannelListController,
        shouldAddNewChannelToList channel: ChatChannel
    ) -> Bool {
        return shouldAddChannel(channel)
    }

    func controller(
        _ controller: ChatChannelListController,
        shouldListUpdatedChannel channel: ChatChannel
    ) -> Bool {
        return shouldAddChannel(channel)
    }

    private func shouldAddChannel(_ channel: ChatChannel) -> Bool {
        if channel.type == .custom("xyz") {
            if ChatClient.shared.currentUserController().currentUser?.userRole == "moderator" {
                return true
            } else {
                return channel.membership != nil
            }
        } else {
            return channel.membership != nil
        }
    }
```

These delegate methods are not called when a new "xyz" channel is created. User need to restart app to update the changes.
Please help.

**Comment by ajay-simform** [comment]
Hi @nuno-vieira ,
I update query with your suggestion. But no luck.
Channel is not visible directly. User have to restart the app to see in the listing.
Even `filter` closure doesn't observe "xyz" type channels. (when new "xyz" type channel created by other user.)

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

I will investigate with the backend team to understand what is happening, and what is the expected behaviour. Meanwhile, can you enable the WebSocket logging, and check if there is any event in the console log? You can enable it like this:

```swift
LogConfig.level = .info
LogConfig.subsystems = .webSocket
```

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @ajay-simform,

This is actually expected behaviour. Moderators do not get events for channels which they are not watching. So there is no way to observe if a new channel was created if you are not a member. This is by design to avoid an overload in the system. Since you could potentially create 1k+ channels in a couple of minutes and this would cause 1k+ notifications and events for the moderator. 

Best,
Nuno
