### ISSUE TITLE
Identify a code issue in ChatClient.Swift Classs - 4.25.0 Latest Version 

### ISSUE THREAD

**Issue by vineethnkforios** [GetStream/stream-chat-swift#2425]
## What did you do?
Updated to 4.25.0 Version

## What did you expect to happen?
loading messages

## What happened instead?
Not loading messages 

## GetStream Environment
**GetStream Chat version:** 4.25.0 Latest Version 
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS 15
**Swift version:** 5.0
**Xcode version:** 13.5
**Device:** iphone 13

## Additional context
File Name  : ChatClient.Swift
Line Number : 327 to 344

please find the code :

public func connectUser(
        userInfo: UserInfo,
        token: Token,
        completion: ((Error?) -> Void)? = nil
    ) {
        guard token.expiration == nil else {
            let error = ClientError.MissingTokenProvider()
            log.error(error.localizedDescription, subsystems: .authentication)
            completion?(error)
            return
        }

        connectUser(
            userInfo: userInfo,
            tokenProvider: { $0(.success(token)) },
            completion: completion
        )
    }

*************************
 Inside the code  , the guards statement must like below , right ?

guard token.expiration != nil else {
            let error = ClientError.MissingTokenProvider()
            log.error(error.localizedDescription, subsystems: .authentication)
            completion?(error)
            return
        }

Note:  "guard token.expiration == nil "    replaced by "guard token.expiration != nil "

Could you please confirm ?

**Comment by nuno-vieira** [comment]
Hi @vineethnkforios,

The logic is correct. You are using the tokenProvider call, which is a different function, on line [305](https://github.com/GetStream/stream-chat-swift/blob/develop/Sources/StreamChat/ChatClient.swift#L305).

If your token does not expire, then you should use the function which does not have the tokenProvider. Example:
```swift
    connectUser(
        userInfo: userInfo,
        token: .init(stringLiteral: token),
        completion: completion
    )
}
```

Feel free to re-open the issue if you still have problems.

Best,
Nuno

**Comment by vineethnkforios** [comment]
@nuno-vieira  
  Iam taliking about the same function on line 305. 

connectUser(
        userInfo: userInfo,
        token: .init(stringLiteral: token),
        completion: completion
    )

If i call the same then it happens recursion.

Solution: I just edit the code  to "guard token.expiration != nil " and seems fine .

**Comment by polqf** [comment]
@vineethnkforios 
You should not be using a token that has expiration if you don't provide a TokenProvider block to refresh it when it expires.

**Comment by nuno-vieira** [comment]
> @nuno-vieira The above line is for what purpose ? guard token.expiration != nil else { let error = ClientError.MissingTokenProvider() log.error(error.localizedDescription, subsystems: .authentication) completion?(error) return } I have value in token.expiration and every time when call this function it will logs an error...
> 
> In older versions it was not there and working perfect

@vineethnkforios, The purpose of this line is that if the token has an expiration, then you should be using a `tokenProvider`. This was working before, but it was actually a mistake. So right now things are working as expected, and the error log is actually a good thing since it is catching an integration mistake.

If your token has an expiration, then it means you should be using this function call `connectUser(userInfo:**tokenProvider**:completion:)` and not `connectUser(userInfo:token:completion:)`.

If your token does not have any expiration, then you should create the token with this constructor `Token(rawValue: String, userId: UserId, expiration: Date?)` and pass `nil` in the `expiration` argument.
