### ISSUE TITLE
Filtering in ChannelList does not work correctly

### ISSUE THREAD

**Issue by ezgiozkan** [GetStream/stream-chat-swift#2440]
Messages with the type "team" in ChatChannelListVC should not be listed. However, messages of this type continue to arrive, or messages with the type "messaging" do not appear, and the list returns empty. 

```
func getMessageListVC(userId: String) -> ChatChannelListVC {
        let channelList = ChannelListViewController()
        let query = ChannelListQuery(filter: .and([.containMembers(userIds: [userId]), .nonEmpty, .notEqual(.type, to: .livestream), .notEqual(.type, to: .team)]))
        channelList.controller = ChatClient.shared?.channelListController(query: query)

        return channelList
    }
```

## GetStream Environment
**GetStream Chat version: 4.20.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**Xcode version: 13.4.1

**Comment by nuno-vieira** [comment]
Closing the issue for now, let us know if you still have problems when introducing the filter blocks.

Best,
Nuno

**Comment by ezgiozkan** [comment]
I am using filtering as in the document. However, channels with .team type are displayed in the list as the message is received. The filtering process does not work correctly. I am rewriting the code I used for you to review.

`let query = ChannelListQuery(filter: .and([.containMembers(userIds: [userId]), .nonEmpty, .notEqual(.type, to: .team)]))`

**Comment by nuno-vieira** [comment]
@ezgiozkan

The filter you are missing is in the `channelController`.

```swift
let controller = ChatClient.shared.channelListController(query: query, filter: { channel in
    // the filtering logic goes here.
    return !channel.messages.isEmpty && channel.messages.lastActiveMembers.contains(userId) && channel.type != "team"
})
```

Something like that.

Best,
Nuno
