### ISSUE TITLE
https://github.com/GetStream/stream-chat-swift/issues/2431

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2442]
creating a new issue, since github doesn't allow me to re-open an issue closed by a org member https://github.com/GetStream/stream-chat-swift/issues/2431#issuecomment-1375852880

(please close this after you're able to re-open #2431)

**Comment by nuno-vieira** [comment]
I'll re-open the other one. No need to create a new one. When you do this, we will eventually read the comment in the older issue ,and re-open it 👍

**Comment by AndrewSB** [comment]
good to know! ok, i'll just comment on the closed one in the future 👍
