### ISSUE TITLE
Remove reaction notification handling

### ISSUE THREAD

**Issue by moubry** [GetStream/stream-chat-swift#2448]
The Stream platform does not send notifications for reactions (Stream Support confirmed this to me) but [the Swift SDK has code for receiving reaction notifications](https://github.com/GetStream/stream-chat-swift/blob/48f13c13684d9e31b4a2863a69f8defd15f009fc/docusaurus/docs/iOS/common-content/reference-docs/stream-chat/api-client/chat-push-notification-content.md), which is really confusing. This misled us into thinking that we were doing something wrong — we were not receiving reaction notifications, and spent a long time debugging the issue, but it never would have worked.

Alternatively, it might make sense to document that this enum case will never occur?

**Comment by Crysis21** [comment]
same thing here, we were mislead by the SDK that it receives notifications for reactions. It might have been the case in the past, but I don't remember really well. In the end, we connected our backend with getStream webhook and we send them ourselves.
