### ISSUE TITLE
Chat message cell update not triggered for some chat message updates

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#2451]
## What did you do?
I updated a chat message from my backend server

## What did you expect to happen?
I expected that to trigger an update to the chat message UI in my app

## What happened instead?
For some chat message changes, no UI update is triggered

## GetStream Environment
**GetStream Chat version:** 4.26.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
I've attached a sample project that demonstrates this:
[StreamUpdateMessage.zip](https://github.com/GetStream/stream-chat-swift/files/10429645/StreamUpdateMessage.zip)

Steps to reproduce:
- Run sample app, enter chat channel
- Notice the custom view for the chat message that displays a "number of comments" for an image attachment
- Edit/run the included 'editMessageAttachment.js' which mimics our backend server and how it modifies a chat message attachment
- Increase the `cnComments` value and run `editMessageAttachment`
- Notice the chat message display did NOT update to the new value
- Now again edit the 'editMessageAttachment' but this time increment `cnComments` and modify the message text to something different. Run that
- Notice that now (since the chat message text has changed) all of the chat message UI (included number of comments) is updated
- I want to be able to see the chat message UI updated when ONLY the cnComments value has changed

**Comment by nuno-vieira** [comment]
Hi @srgray!

Thank you for the bug report. This is indeed a bug on our side, it looks like we are not using the extra data of the attachments for the message diffing. 

We will let you know once this is fixed.

Best,
Nuno

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
