### ISSUE TITLE
Delay between sending the message and didUpdateChannel method call

### ISSUE THREAD

**Issue by NatashaLavrinenko** [GetStream/stream-chat-swift#2517]
## What did you do?
In order to show unread messages counter for a particular channel, `didUpdateChannel` method is used as per [documentation](https://getstream.io/chat/docs/ios-swift/unread_channel/?language=swift). It works correctly when app is running, but has issues for the app launch. The steps are the following:
1. Users A and B are in the same channel.
2. User A sent 1 message to channel.
3. User B opens the app(connection to getstream is configured) and counter for the channel is seen.

## What did you expect to happen?
It's expected to see the correct counter(in the following case it's 1) which is taken from `didUpdateChannel` delegate method.

## What happened instead?
The wrong value(in the following case it's 2) is returned from `didUpdateChannel` delegate method.
Also double checked the case when user opened the app and 2 new messages were sent, still could see 4 as a value returned from `didUpdateChannel` delegate method. Looks like the `EntityDatabaseObserver` object returns the value that's doubled.

## GetStream Environment
**GetStream Chat version: 4.25.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version: 16.2
**Swift version: 5.6
**Xcode version: 14.2
**Device: iPhone 11

**Comment by alteral** [comment]
Hi @NatashaLavrinenko,
Thanks for reporting this.

I see you are using StreamChat `4.25.0`. We've greatly improved the `unreadCount` feature in the following releases. Please update the SDK version to our latest release `4.28.0` and confirm if it solves your problem.

Hope this helps!

Best wishes,
Alexey

**Comment by NatashaLavrinenko** [comment]
Hi @alteral 
Thanks for answering, updating the SDK to `4.28.0` version solved the issue with duplicated `unreadCount`, but caused another one. The delay between sending the message and `didUpdateChannel` call is much higher than was previously, about 50-60 seconds. Is it a known issue?

**Comment by alteral** [comment]
Hi @NatashaLavrinenko,

No, I'm afraid it's not a known issue. Could you please provide some code examples with your implementation of StreamChat around sending messages and observing the unread messages counter?

Best,
Alexey

**Comment by NatashaLavrinenko** [comment]
Hey @alteral 
For sending messages the default logics from [documentation](https://getstream.io/chat/docs/ios-swift/creating_channels/) is used - the channel is built using channel id and once the send button is tapped, default StreamChat logics is used.
As for observing the unread messages counter, the class conforming the `ChatChannelControllerDelegate` protocol is created. It's set as delegate for chat controller and synchronize is called. Once the `didUpdateChannel` method of delegate is called, `unreadCount.messages` value is used for showing the counter value. It's implemented as stated in the documentation [here](https://getstream.io/chat/docs/ios-swift/unread_channel/?language=swift).
Please let me know in case more details needed.

**Comment by alteral** [comment]
Hey @NatashaLavrinenko,

We double-checked this behaviour in our DemoApp, and I can confirm that we get the updates instantly. There is a chance that something is wrong on your end, so it would be great if you could share your integration code. Otherwise, it's really hard to say what's going wrong there.

Best,
Alexey

**Comment by NatashaLavrinenko** [comment]
Hey @alteral 
I doubt that the issue is on our side since before updating the SDK to a new version, there were no delay, code wasn't updated after SDK increase.
I've taken several screenshots of the code used for showing the counter of unread messages - SDK connection, usage of `ChatChannelControllerDelegate` and its synchronization.
Should something be changed for channels configuration at dashboard after the SDK version bump?
Please let me know in case more details needed.
[GetstreamIssue.zip](https://github.com/GetStream/stream-chat-swift/files/10908599/GetstreamIssue.zip)

Best regards,
Nataliia.

**Comment by polqf** [comment]
Hi @NatashaLavrinenko , the reason why my colleague is asking for integration code is that this is not reproducible on our side. We internally rely on the updates that channels are emitting, and if this were to be an extended issue, we would have been flooded with tickets. We are trying to pinpoint what's the issue for you.

What I can tell you is that I basically added your code to our DemoApp, and I get the updates instantly, `sink`ing into (what I think is a PassthroughObject) `_didUpdateUnreadGroupChatCounter`.

Would be nice to understand when and how you call those methods, to try to see if there's anything that we are missing.
Ideally please share code as written text/snippets/files, copying from images makes our life a bit complicated.

How are you listening to `_didUpdateUnreadGroupChatCounter`? 
At which point in time are you calling `setUpObserver`?
Is the SDK fully connected when you invoke those methods?

**Comment by nuno-vieira** [comment]
Hello!

We are closing the issue for inactivity, but feel free to re-open it if you are still having issues. 

Best,
Nuno

**Comment by glennposadas** [comment]
Hi all. Sorry for bumping this closed stale ticket. But this could be somewhat related to my new ticket: https://github.com/GetStream/stream-chat-swift/issues/3089
