### ISSUE TITLE
Crash when removing device token

### ISSUE THREAD

**Issue by digimarktech** [GetStream/stream-chat-swift#252]
## What did you do?

According to [this](https://github.com/GetStream/stream-chat-swift/wiki/Push-Notifications) wiki, it is recommended to remove a user device using the following code: 
```swift
if let currentDevice = User.current?.currentDevice {
    Client.shared.removeDevice(deviceId: currentDevice.id).subscribe().disposed(by: disposeBag)
}
```

## What did you expect to happen?

That it removes the user device from the Stream account

## What happened instead?

The app crashes in the `Atomic.swift` file from the `StreamChatClient`.

![Screen Shot 2020-05-06 at 12 46 05 PM](https://user-images.githubusercontent.com/16762986/81204862-dbe0d500-8f97-11ea-8a68-7ff4eb170777.png)
![Screen Shot 2020-05-06 at 12 47 03 PM](https://user-images.githubusercontent.com/16762986/81204872-df745c00-8f97-11ea-9b0e-9dbd86d41e02.png)

## GetStream Environment
**GetStream Chat version:** 2.0.1
**iOS version:** 13.3.1
**Swift version:** Swift 5
**Xcode version:** 11.4
**Device:** iPhone X

## Additional context

I have also tried this same code on the latest version of Stream (2.1.1) with the same result

**Comment by VojtaStavik** [comment]
Hi @digimarktech, thank you for your report. I actually found this very bug yesterday and already have a WIP fix for it. It should be part of the next patch release probably later this week.

**Comment by digimarktech** [comment]
> Hi @digimarktech, thank you for your report. I actually found this very bug yesterday and already have a WIP fix for it. It should be part of the next patch release probably later this week.

thanks @VojtaStavik!
