### ISSUE TITLE
ChatMessageReactionsPickerVC is shown regardless of user capabilities

### ISSUE THREAD

**Issue by pzmudzinski** [GetStream/stream-chat-swift#2552]
## What did you do?
Disabled `CreateReaction` permission for role `user` in one channel type

## What did you expect to happen?
Reactions picker should not be displayed

## What happened instead?
Reactions picker is shown regardless of user capabilities (since check is done on channel-level only)

## GetStream Environment
GetStream Chat version:*4.29.0*
GetStream Chat frameworks:** StreamChat
iOS version:*16.2*
Swift version:*5.0*
Xcode version:*14.2*
Device:*iPhone 14 Pro max simulator*

## Additional context
It seems `ChatMessageListVC` does not check user capabilities and fully relies on channel config
```swift
        let reactionsController: ChatMessageReactionsPickerVC? = {
            guard message.localState == nil else { return nil }
            guard dataSource?.channel(for: self)?.config.reactionsEnabled == true else {
                return nil
            }

            let controller = components.reactionPickerVC.init()
            controller.messageController = messageController
            return controller
        }()
```

**Comment by nuno-vieira** [comment]
Hi @pzmudzinski,

The channel capabilities are not currently implemented in the iOS SDK. It is planned for Q2. We will let you know once we have this ready.

Best,
Nuno

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
