### ISSUE TITLE
Uploading Failed. JPEG not supported

### ISSUE THREAD

**Issue by glennposadas** [GetStream/stream-chat-swift#2580]
## What did you do?

All of a sudden, the uploading of photos broke.
Both on iOS and Android (native).

## What did you expect to happen?

Successful uploading of photos

## What happened instead?

Uploading Failed.

## GetStream Environment
**GetStream Chat version:** 4.27.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.2
**Swift version:** 5.7.2
**Xcode version:** 14.2
**Device:** Simulator, any device

## Additional context

Error from the logs:

```
2023-04-22 02:09:33.346 [ERROR] [com.apple.NSURLSession-delegate] [RequestDecoder.swift:67] [decodeRequestResponse(data:response:error:)] > API request failed with status code: 400, code: 4 response:
{
  "code" : 4,
  "message" : "UploadImage failed with error: \"File type image\/jpeg is not supported\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "details" : [

  ],
  "StatusCode" : 400,
  "duration" : "0.00ms"
})
```

Screenshot of the logs and of the UI:

![Screenshot 2023-04-22 at 2 14 55 AM](https://user-images.githubusercontent.com/12502679/233706747-cb943200-9bdf-4ecd-8299-b43307e6233c.png)

**Comment by Alen-T-Vinsent** [comment]
converting the jpeg to png will solve the issue 

guard let jpegData = UIImage(named: "myImage.jpeg")?.jpegData(compressionQuality: 1.0) else {
    print("Failed to get JPEG data")
    return
}

guard let image = UIImage(data: jpegData) else {
    print("Failed to create image from JPEG data")
    return
}

guard let pngData = image.pngData() else {
    print("Failed to get PNG data")
    return
}

// Now you can upload the PNG data using the API


im new to open source how can i fix this  
how can i contribute to this  give me a hand

**Comment by glennposadas** [comment]
Thanks. But that's definitely not the solution.

**Comment by Alen-T-Vinsent** [comment]
could you tell me why its not the solution

**Comment by ipavlidakis** [comment]
Hi @glennposadas

Thanks for reporting the issue you are facing. I just tried uploading the attached `jpeg` image and the operation completed successfully. Do you mind:
1. Try again the operation
2. Share the image you are trying to upload

Kind regards,
Ilias

![test](https://user-images.githubusercontent.com/472467/233944796-e874410a-aede-4e96-988b-e540ae231fab.jpg)

**Comment by glennposadas** [comment]
> could you tell me why its not the solution

Cause it's not. Imagine you have a car that runs on gasoline, but the gas station you usually go to suddenly stops selling gasoline and only sells diesel fuel. Someone suggests that you should convert your car to run on diesel fuel instead of gasoline. However, this is not a practical solution because it would require significant modifications to your car's engine and fuel system, which could be expensive and time-consuming. Plus, you might not even be able to find diesel fuel everywhere you go, which could leave you stranded.

**Comment by glennposadas** [comment]
> Hi @glennposadas
> 
> Thanks for reporting the issue you are facing. I just tried uploading the attached `jpeg` image and the operation completed successfully. Do you mind:
> 
> 1. Try again the operation
> 2. Share the image you are trying to upload
> 
> Kind regards, Ilias
> 
> ![test](https://user-images.githubusercontent.com/472467/233944796-e874410a-aede-4e96-988b-e540ae231fab.jpg)

I will try this week. But it seems that it's caused by a wrong configuration. For example, our QA said in our staging environment, everything works (including uploading images on the chat). However, in our test environment, this happens.
But still, the error is off.

**Comment by nuno-vieira** [comment]
Hello!

I'm closing this one for now. Please, feel free to re-open if you are still having issues.

Best,
Nuno
