### ISSUE TITLE
Subclassing ComposerVC Causes Keyboard issues

### ISSUE THREAD

**Issue by glennposadas** [GetStream/stream-chat-swift#2584]
## What did you do?

I have this subclass, see the complete codes in the additional context section, to remove the video option in the attachment action sheet.

## What did you expect to happen?

Easy subclassing, no need to implement other logics and handling of keyboards.

## What happened instead?

Kinda opens up a can of worms. I might be doing something wrong here.

## GetStream Environment
**GetStream Chat version:** 4.27.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.2
**Swift version:** 5.7.2
**Xcode version:** 14.2
**Device:** Simulator, any device

## Additional context

Issues that arise:

- keyboard blocking the input textView.
- input textView resigns as first responder but fails to back up when you select camera as attachment then cancel.
- emoji keyboard increases its height but not returning to normal when you switch back to the normal keyboard.
- (pre-iOS16), the speech-to-text keyboard increases its height but not returning to normal when you switch back to the normal keyboard.

```
import StreamChat
import StreamChatUI

class FNChatComposerVC: ComposerVC {
  
  // MARK: -
  // MARK: Properties
  
  lazy var cameraPicker: UIImagePickerController = {
    let picker = UIImagePickerController()
    picker.sourceType = .camera
    picker.delegate = self
    return picker
  }()
  
  
  lazy var photoPicker: UIImagePickerController = {
    let picker = UIImagePickerController()
    picker.sourceType = .photoLibrary
    picker.delegate = self
    return picker
  }()
  
  override var attachmentsPickerActions: [UIAlertAction] {
    let showCameraPickerAction = UIAlertAction(
      title: "Camera",
      style: .default,
      handler: { [weak self] _ in
        self?.showCameraPicker()
      }
    )
    
    let showPhotoPickerAction = UIAlertAction(
      title: "Photos",
      style: .default,
      handler: { [weak self] _ in
        self?.showPhotoPicker()
      }
    )

    let cancelAction = UIAlertAction(
      title: "Cancel",
      style: .cancel
    )
    
    return [showPhotoPickerAction, showCameraPickerAction, cancelAction]
  }
  
  override var isCommandsEnabled: Bool {
      false
  }
  
  private var keyboardWasPresent = false
  
  // MARK: -
  // MARK: Functions
  
  func showCameraPicker() {
    keyboardWasPresent = composerView.inputMessageView.textView.isFirstResponder
    present(cameraPicker, animated: true)
  }
  
  func showPhotoPicker() {
    keyboardWasPresent = composerView.inputMessageView.textView.isFirstResponder
    present(photoPicker, animated: true)
  }
  
  override func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any]) {
    super.imagePickerController(picker, didFinishPickingMediaWithInfo: info)
    
    if keyboardWasPresent {
      composerView.inputMessageView.textView.becomeFirstResponder()
    }
  }
  
  func imagePickerControllerDidCancel(_ picker: UIImagePickerController) {
    picker.dismiss()
    if keyboardWasPresent {
      composerView.inputMessageView.textView.becomeFirstResponder()
    }
  }
}
```

**Comment by polqf** [comment]
Hi @glennposadas , we'll have a look as soon as possible.

In the meantime, could you please share a video of the issues that you are listing? That way we make sure we are recreating the same behaviour.

**Comment by glennposadas** [comment]
@polqf sure.

https://user-images.githubusercontent.com/12502679/234696695-e354806d-74d8-4bb7-9cac-f224ac8cff61.mp4


https://user-images.githubusercontent.com/12502679/234697177-5f7a3e0f-9d46-4c57-a8ad-994bbf56912e.mov


https://user-images.githubusercontent.com/12502679/234697228-2ab88893-fa9d-4e5c-8bd0-c9efac4dfce9.mov

**Comment by polqf** [comment]
Hi @glennposadas,

We managed to reproduce the issue, and we will be working on it soon. 
We will keep you posted!

**Comment by glennposadas** [comment]
Hi everyone. Do we have an estimate for this? I mean no rush but just so I can update my team. Thanks!

**Comment by nuno-vieira** [comment]
Hi @glennposadas!

The ETA for this one is about 1/2 weeks 👍 

Best,
Nuno

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
