### ISSUE TITLE
Channel list failed

### ISSUE THREAD

**Issue by junjielu** [GetStream/stream-chat-swift#2585]
## What did you do?
After upgrading the sdk from version 4.27.0 to 4.31.0, all the channels in the channel list disappeared

## What did you expect to happen?
In version 4.27, I was able to get the correct channels by creating the channel list controller in this way, but now it doesn't work.
```swift
friendChannelController = client.channelListController(query: .friends(id: id)) {
  ($0.groupChatType == .public || $0.channelType == .friend || ($0.channelType == .request && $0.createdBy?.id == id.rawValue && $0.fromBubble != true))
    && $0.membership != nil
    && $0.isHidden == false
    && $0.isFrozen == false
}
requestChannelController = client.channelListController(query: .request(id: id)) {
  $0.channelType == .request
    && $0.createdBy?.id != id.rawValue
    && $0.isHidden == false
    && $0.isFrozen == false
}
expiredChannelController = client.channelListController(query: .expired(id: id)) {
  $0.channelType == .expired
    && $0.membership != nil
    && $0.isHidden == false
    && $0.isFrozen == false
}

extension ChannelListQuery {
  static func friends(id: UserModel.ID) -> Self {
    Self(
      filter: .and([
        .or([
          .and([
            .equal(.createdBy, to: id.rawValue),
            .equal(.channelType, to: SingleChatChannel.ChannelType.request.rawValue),
            .or([
              .equal(.fromBubble, to: false),
              .exists(.fromBubble, exists: false),
            ]),
          ]),
          .equal(.channelType, to: SingleChatChannel.ChannelType.friend.rawValue),
          .equal(.groupChatType, to: GroupChatChannel.GroupChatType.public.rawValue),
        ]),
        .containMembers(userIds: [id.rawValue]),
        .equal(.frozen, to: false),
        .equal(.hidden, to: false),
      ]),
      sort: [.init(key: .lastMessageAt)],
      pageSize: 20
    )
  }

  static func request(id: UserModel.ID) -> Self {
    Self(
      filter: .and([
        .equal(.type, to: .messaging),
        .equal(.channelType, to: SingleChatChannel.ChannelType.request.rawValue),
        .notEqual(.createdBy, to: id.rawValue),
        .containMembers(userIds: [id.rawValue]),
        .equal(.frozen, to: false),
        .equal(.hidden, to: false),
      ]),
      sort: [.init(key: .lastMessageAt)],
      pageSize: 20
    )
  }

  static func expired(id: UserModel.ID) -> Self {
    Self(
      filter: .and([
        .equal(.type, to: .messaging),
        .equal(.channelType, to: SingleChatChannel.ChannelType.expired.rawValue),
        .containMembers(userIds: [id.rawValue]),
        .equal(.frozen, to: false),
        .equal(.hidden, to: false),
      ]),
      sort: [.init(key: .lastMessageAt)],
      pageSize: 20
    )
  }
}
```

## What happened instead?
After the upgrade all the channels are not available anymore, the network interface returns the correct array of channels through network packet capture

## GetStream Environment
**GetStream Chat version:** 4.31.0
**GetStream Chat frameworks:** StreamChat
**iOS version:** 16.4
**Swift version:** 5.8
**Xcode version:** 14.3
**Device:** all

**Comment by polqf** [comment]
@junjielu you are completely right, we are looking into it.

If you have some time, could you try 4.30.0 and tell us if it works with automatic filtering enabled?
Thank you

**Comment by nuno-vieira** [comment]
Hi @junjielu,

Since you use some custom properties for the filters, you probably need to follow this guide: https://getstream.io/chat/docs/sdk/ios/client/controllers/channels/#filtering-with-extra-data, or as @polqf mentioned, this one: https://getstream.io/chat/docs/sdk/ios/client/controllers/channels/#manual-filtering.

Either way, ideally, this shouldn't have broken your original query. But switching to automatic filters was something that we needed to ship enabled by default so that it could simplify future integrations. Either way, if you are still blocked or have any other issues, let us know.

Until then, we will close the issue for now.

Best,
Nuno
