### ISSUE TITLE
Allow ChatViewController to use Custom MessageTableViewCell

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#259]
## What are you trying to achieve?
We would like to use our own subclass of MessageTableViewCell

## If possible, how can you achieve this currently?
Right now we would have to override a bunch of code that is internal to the SDK such as the 
extensions to Tableview for Resuse and Dequeue

Would also have to basically rewrite all of `extensionMessageCell` and its internal functions

## What would be the better way?
It would be nice to have ChatViewController have a way to indicate which cell should be used.  The default should be type = `MessageTableViewCell.self` however it could be overridden with `CustomerTableViewCell.self` to allow the custom cell to be ore easily injected into the current ChatViewcontroller

## GetStream Environment
**GetStream Chat version:**
2.0.1
**iOS version:**
all
**Swift version:**
5.1
**Xcode version:**
any
**Device:**
any

**Comment by b-onc** [comment]
Hello @khoogheem 
We did this for ChannelsViewController but not ChatViewController, it's on our roadmap.
I'm going to bump up the priority.

**Comment by VojtaStavik** [comment]
I'm closing this issue because we're approaching the `3.2` release which will contain a completely new set of fully customizable UI components.
