### ISSUE TITLE
Text input indicator goes out of view after 5 lines

### ISSUE THREAD

**Issue by virbedi** [GetStream/stream-chat-swift#2590]
## What did you do?
Paste a long message into the text input of the demo app.
Try adding text to the input after the message was pasted in.

## What did you expect to happen?
The blue input line should be in view so the user can see what they are typing

## What happened instead?
The blue input line is no longer visible and the user is not able to see any new text they add unless they manually scroll.

## GetStream Environment
**GetStream Chat version:** Demo app @ 4.31. Our app using StreamChatUI at 4.30
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.2
**Swift version:**Swift 5
**Xcode version:** 14.2
**Device:**iPhone 14 Pro Simulator

## Additional context
<img src="https://user-images.githubusercontent.com/43729852/235498957-e2f9bd2a-5122-4f62-94cb-3cb98d0f86b1.png" width="230"/>

**Comment by polqf** [comment]
Hi @virbedi ,

Thanks for your report. I just tested it and you are right, upon adding a long message you need to input some text for it to automatically scroll to where the input is.

We will be tackling this issue based on priority.

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
