### ISSUE TITLE
Filter channels

### ISSUE THREAD

**Issue by vWolfG** [GetStream/stream-chat-swift#262]
## What did you do?
Use .notIn("users", ["Jon"]) filter for ChannelsPresenter

## What did you expect to happen?
The result is channels where "Jon" is not in users parameters where "users" = [String]

## What happened instead?
The result is channels where  "Jon" is in users parameters

## GetStream Environment
**GetStream Chat version:** 2.2.0
**iOS version:** 13.3.1
**Swift version:** 5
**Xcode version:** 11.4.1
**Device:** iPhone 8

**Comment by b-onc** [comment]
Hello @vWolfG 
1. You should filter on `members` not `users`. So the correct filter would be `.notIn("members", ["Jon"])`
2. Is "Jon" the user name or id? You should supply user id.

**Comment by vWolfG** [comment]
Hello! It was just an example, I have my own array in extraData, it is array of user ids, and I want to get all channels where my user id not in this array. This is possible? 

  
>Вторник, 12 мая 2020, 12:44 +03:00 от Bahadır Öncel <notifications@github.com>:
> 
> 
>Hello  @vWolfG
>*  You should filter on members not users. So the correct filter would be .notIn("members", ["Jon"])
>*  Is "Jon" the user name or id? You should supply user id.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
_____________________
 
Best regards,
Veronika Goreva

**Comment by b-onc** [comment]
Hello @vWolfG 
You should be able to query by your extra data fields too, same logic applies.
Please enable logs and check:
When you query the channel, do you see your custom field in json response?
Can you parse your custom field in code?

**Comment by vWolfG** [comment]
Yes, I see my custom field in json response and also I can parse it.
And filter .in for my custom field works fine, it returns all channels where my custom field contains my user id and doesn't return other channels where my custom field doesn't contain my user id.

But .notIn doesn't work properly, it returns all channels where my custom field contains my user id.

**Comment by b-onc** [comment]
Hello @vWolfG 
Thanks for clarifying the question!
I've spoke with our backend team and learned that our equality operator is actually "is in subset" so for your case:
```swift
.notEqual("users", to: "Jon") // for single member
.notEqual("users", to: "Jon") | .notEqual("users", to: "Wolf") // for multiple members
```
should work.

I've also learned that `.in` filter does not work reliably on arrays so it's better to use `equal` and `notEqual`

This is mainly a backend question, so please reach us on support@getstream.io to get more info on this.
