### ISSUE TITLE
channelListController.synchronize multiple completion callbacks, reopen of #2568

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2627]
hey! just re-opening this because we're still seeing this. we're seeing about 5 of these a day, out of ~tens of thousands of connections opened, so it's a minuscule percent, but i'd like to get it fixed

the relevant code is
```swift
    private func fetchServerActiveChatChannels(currentUserId: UserId) async -> [ChatChannel] {
        let channelListController = chatClient.channelListController(query: .init(filter: .and([
            .containMembers(userIds: [currentUserId]),
            .equal(.type, to: .messaging),
            .equal(.memberCount, to: 2),
        ])))

        return await withCheckedContinuation { continuation in
            channelListController.synchronize { error in
                if let error = error {
                    CrashReporter.logNonFatal(error)
                } else {
                    self.channels = Array(channelListController.channels).filter { !$0.isGroupChat }
                }
                continuation.resume(returning: self.channels)
            }
        }
    }
```

maybe it has something to do with the `completion` being called multiple times in your APIClient.operation function, on L119

since it happens so rarely, maybe it's when the token expires during the request, or something with failing while in recovery mode

here's also a screenshot of the error, and stack trace, if it helps
<img width="828" alt="Screenshot 2023-05-18 at 12 40 59 PM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/ee6e0567-8a16-4527-8359-bef1ca2da189">

**Comment by nuno-vieira** [comment]
Hi @AndrewSB,

I'm closing this one and reopening the original issue here: https://github.com/GetStream/stream-chat-swift/issues/2568

Best,
Nuno
