### ISSUE TITLE
Exposing Extradata field for Custom Giphy

### ISSUE THREAD

**Issue by SSaleemSSI** [GetStream/stream-chat-swift#2629]
## What are you trying to achieve?
We have implemented the giphy on Android,web and iOS with custom implementation where all three devices are having compatibility issues as when we send giphy from iOS using custom implementation as shown in https://github.com/GetStream/stream-chat-swift/issues/2120 but it is showing as file type in android because iOS wont let us send extra data for giphy Object, which is missing. While web and android can send the extradata giphy object and custom giphy are showing perfectly on both iOS and Android.

One more case when we send giphy through command in iOS they are showing perfectly because it has the GIphy object.

## If possible, how can you achieve this currently?
If SDK expose the extra data field for custom giphy then we can create the objects for GIPHY in which height,width and all required fields are given then in that case giphy will show perfectly on Android.

## What would be the better way?
Exposing the extra data filed.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by nuno-vieira** [comment]
Hi @SSaleemSSI!

Thank you for the report!

We will expose the extra data field then 👍

We will let you know once we have this one released. 

Best,
Nuno

**Comment by SSaleemSSI** [comment]
Hi - @nuno-vieira whats the update on this? Is there any way around for this now? We are about to release the App for Android and yet there is this giphy issue as sending giphy from iOS won't load on android devices without extrdata field.

**Comment by nuno-vieira** [comment]
Hi @SSaleemSSI,

We are going to pick this one up very soon, it should come in the next release 👍 

Best,
Nuno

**Comment by nuno-vieira** [comment]
@SSaleemSSI This is now merged on develop branch and it will come in the 4.34.0 release 👍 

We will let you know once we release it 👍 

Best,
Nuno

**Comment by SSaleemSSI** [comment]
@nuno-vieira I want to add something to this code, i have explored your code to check if by sending the extra data giphy are dispayable on android messaging app but they were still displayed like the file. So i explored the stream dashboard and compare both the ios and android messaging fields in explorer. Issue i found is that we are not exposing the title_link for custom giphy due to which custom giphy are not supported on android. This is how i updated the streamSDK code to support the custom giphy compatible for both apps.

```
public typealias ChatMessageGiphyAttachment = ChatMessageAttachment<GiphyAttachmentPayload>

/// Represents a payload for attachments with `.giphy` type.
public struct GiphyAttachmentPayload: AttachmentPayload {
    /// An attachment type all `GiphyAttachmentPayload` instances conform to. Is set to `.giphy`.
    public static let type: AttachmentType = .giphy

    /// A  title, usually the search request used to find the gif.
    public var title: String?
    /// A link to gif file.
    public var previewURL: URL
    /// A title link to support the android messaging app custom gif
    public var titlelink: URL
    /// Actions when gif is not sent yet. (e.g. `Shuffle`)
    public var actions: [AttachmentAction]
    /// The extra data for the attachment payload.
    public var extraData: [String: RawJSON]?

    /// - Parameters:
    ///   - title: The title of the giphy.
    ///   - previewURL: The preview url of the giphy.
    ///   - actions: The actions when gif is not sent yet. (e.g. `Shuffle`)
    ///   - extraData: The extra data for the attachment payload.
    public init(
        title: String?,
        previewURL: URL,
        titlelink: URL,
        actions: [AttachmentAction] = [],
        extraData: [String: RawJSON]? = nil
    ) {
        self.title = title
        self.previewURL = previewURL
        self.titlelink = titlelink
        self.actions = actions
        self.extraData = extraData
    }
}

extension GiphyAttachmentPayload: Hashable {}

enum GiphyAttachmentSpecificCodingKeys: String, CodingKey {
    case actions
}

// MARK: - Encodable

extension GiphyAttachmentPayload: Encodable {
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: AttachmentCodingKeys.self)

        try container.encode(title, forKey: .title)
        try container.encode(previewURL, forKey: .thumbURL)
        try container.encode(titlelink, forKey: .titleLink)

        // Encode giphy attachment specific keys
        var giphyAttachmentContainer = encoder.container(keyedBy: GiphyAttachmentSpecificCodingKeys.self)
        try giphyAttachmentContainer.encode(actions, forKey: .actions)

        try extraData?.encode(to: encoder)
    }
}

// MARK: - Decodable

extension GiphyAttachmentPayload: Decodable {
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: AttachmentCodingKeys.self)
        // Used for decoding giphy attachment specific keys
        let giphyAttachmentContainer = try decoder.container(keyedBy: GiphyAttachmentSpecificCodingKeys.self)
        let actions = try giphyAttachmentContainer.decodeIfPresent([AttachmentAction].self, forKey: .actions) ?? []

        self.init(
            title: try container.decodeIfPresent(String.self, forKey: .title),
            previewURL: try container.decode(URL.self, forKey: .thumbURL),
            titlelink: try container.decode(URL.self, forKey: .titleLink),
            actions: actions,
            extraData: try Self.decodeExtraData(from: decoder)
        )
    }
}

```

**Comment by nuno-vieira** [comment]
Hi @SSaleemSSI,

That should not be needed. Since titleLink is just extra data. What is this titleLink? What is the value of this?

**Comment by SSaleemSSI** [comment]
@nuno-vieira I just used the media.url original url of the Giphy. But the problem is when i send custom giphy using this code

```
 let attachment = GiphyAttachmentPayload(title: title ?? "1.gif", previewURL: URL(string: gifURLoriginal)!, actions: [],extraData : extraData)
        let attachments = [AnyAttachmentPayload(payload: attachment)]
        print(attachments) 
        channelController?.createNewMessage(
            text: "",
            
            attachments: attachments)
        
```
it doesn't generate the title_url field

**Comment by SSaleemSSI** [comment]
here are two fields with and without field (title_url)
<img width="448" alt="Screenshot 2023-06-22 at 4 10 42 PM" src="https://github.com/GetStream/stream-chat-swift/assets/86655959/f982a7be-9cd0-462e-a5e3-1835d385e686">
in this iamge there isn't any title_url and android show file type as 
<img width="220" alt="Screenshot 2023-06-22 at 4 12 57 PM" src="https://github.com/GetStream/stream-chat-swift/assets/86655959/490c5d2a-b734-402b-90f8-b4e9926a3ddd">

and when i send title_url as in the image giphy displayed perfectly. 
<img width="445" alt="Screenshot 2023-06-22 at 4 11 12 PM" src="https://github.com/GetStream/stream-chat-swift/assets/86655959/7d260784-c8c4-4d5d-bb52-a23754f8bbdc">


can u please explain if i am wrong?

**Comment by SSaleemSSI** [comment]
@nuno-vieira i got it sending this as extra data also works 
extraData["title_link"] = RawJSON.string(media.url)
Thanks

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
