### ISSUE TITLE
SwiftyMarkdown code is copy-pasted into the library instead of included as a sub-dependency

### ISSUE THREAD

**Issue by gsbernstein** [GetStream/stream-chat-swift#2652]
## What did you do?
 - install Stream Chat dependency via cocoapods

## What did you expect to happen?
 - code from other sources should be included as a sub-dependency instead of duplicated

## What happened instead?
 - SwiftyMarkdown code is duplicated in the Stream Chat code

## GetStream Environment
**GetStream Chat version:** 4.28.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** any
**Swift version:** any
**Xcode version:** any
**Device:** any

## Additional context
 - if we also import the library ourselves, this causes name conflicts and wastes space
 - makes it harder for us to be compliant with the library's license
 - less likely to be updated

**Comment by polqf** [comment]
Hi @gsbernstein ,

Let me start by saying that Stream is not meant to be copied, but instead installed using one of the 3 dependency managers that we support.

One of the reasons why we went for embedding the dependencies (aside from wanting to control the versions and/or any possible fixes ourselves) is that we also wanted to avoid possible clashes with those dependencies if they were part of the host app.

The dependencies, given that they are part of StreamChat or StreamChatUI, will be namespaced, and thus should not create any conflicts. Independently of whether you use CocoaPods, Carthage or SPM, a framework (or an xcframework) is created internally, which creates this “sandbox” effect, where the inner content of our SDK does not affect the rest of the content on the host app.

Moreover, the size of our embedded dependencies is controlled frequently, and it is not significant.

**Comment by gsbernstein** [comment]
Yes, we’re including Stream using cocoapods. From what I’ve seen, the best practice is to let the dependency manager manage your sub-dependencies. Just don’t make the compatible version range narrower than it needs to be. You could even make your markdown features a subspec so clients can leave it out if they’re not using it.On May 26, 2023, at 5:51 AM, Pol Quintana ***@***.***> wrote:﻿
Hi @gsbernstein ,
Let me start by saying that Stream is not meant to be copied, but instead installed using one of the 3 dependency managers that we support.
One of the reasons why we went for embedding the dependencies (aside from wanting to control the versions and/or any possible fixes ourselves) is that we also wanted to avoid possible clashes with those dependencies if they were part of the host app.
The dependencies, given that they are part of StreamChat or StreamChatUI, will be namespaced, and thus should not create any conflicts. Independently of whether you use CocoaPods, Carthage or SPM, a framework (or an xcframework) is created internally, which creates this “sandbox” effect, where the inner content of our SDK does not affect the rest of the content on the host app.
Moreover, the size of our embedded dependencies is controlled frequently, and it is not significant.

**Comment by polqf** [comment]
Hi @gsbernstein,

If we let the dependency manager handle it, we can easily introduce incompatibilities between versions from the clients and our SDKs. So I am sorry to say this is way more problematic that our approach.

I also verified once again that having both StreamChat, StreamChatUI, and SwiftyMarkdown in the same app creates no issues.

We are then going to close this issue. Let us know if you need more help.
