### ISSUE TITLE
Device objects in User.devices have different fields on iOS and Android SDKs

### ISSUE THREAD

**Issue by vadubov** [GetStream/stream-chat-swift#266]
## What did you do?
On iOS app tried to load channels one of which in `members` field have a user created on Android app

## What did you expect to happen?
Channels presented correctly

## What happened instead?
Decoding error

## GetStream Environment
**GetStream Chat version: 2.2.0**
**iOS version: 13.4**
**Swift version: Swift 5**
**Xcode version: 11.4.1**
**Device: iPhone 11 Pro Simulator**

## Additional context
`Device` struct in StreamChatClient has required fields `id` and `created_at`, where `Device` class in 
stream-chat-android-client has `id` and `push_provider`, which leads to decoding error on iOS

**Comment by b-onc** [comment]
Hello @vadubov 
Can you enable logs and share the backend JSON response for the problematic request?

**Comment by vadubov** [comment]
It was 
`"created_by" : {
          "banned" : false,
          "online" : true,
          "name" : "m m",
          "id" : "9",
          "role" : "user",
          "created_at" : "2020-05-11T05:06:36.278544Z",
          "image" : "",
          "invisible" : false,
          "updated_at" : "2020-05-14T06:07:15.156177Z",
          "last_active" : "2020-05-14T06:05:23.63855Z",
          "devices" : [
              {
                "id" : "some token",
                "push_provider" : "firebase"
              }
            ]
        },`

**Comment by b-onc** [comment]
@vadubov Please share the full log, not only the part. We also need to see the request from logs.

**Comment by vadubov** [comment]
🐴 [14 May 18:52:01.396] ⬅️ Response 200 (3721 bytes): https://chat-proxy-us-east.stream-io-api.com/channels?api_key=twj335e5wcah&connection_id=3528dff2-534a-426c-9d13-409b333b6da1&payload=%7B%22presence%22:true,%22limit%22:20,%22state%22:true,%22message_limit%22:25,%22watch%22:true,%22filter_conditions%22:%7B%22$and%22:%5B%7B%22type%22:%22messaging%22%7D,%7B%22is_direct%22:true%7D,%7B%22members%22:%7B%22$in%22:%5B%2254%22%5D%7D%7D,%7B%22archived%22:%7B%22$ne%22:%5B%2254%22%5D%7D%7D%5D%7D%7D
🐴 [14 May 18:52:01.396] 📦 {
  "channels" : [
    {
      "messages" : [

      ],
      "watcher_count" : 1,
      "channel" : {
        "id" : "269",
        "is_direct" : true,
        "created_at" : "2020-05-14T13:51:14.017871Z",
        "created_by" : {
          "banned" : false,
          "online" : true,
          "name" : "Vit D3",
          "id" : "54",
          "role" : "user",
          "created_at" : "2020-05-14T13:48:42.839867Z",
          "image" : "\/images\/college\/1\/3b1e38d7-3353-4f54-9639-a44e49ecec11.jpeg",
          "updated_at" : "2020-05-14T13:51:48.328211Z",
          "last_active" : "2020-05-14T13:51:48.331736Z",
          "latest_hidden_channels" : [

          ]
        },
        "read_only" : false,
        "type" : "messaging",
        "cid" : "messaging:269",
        "frozen" : false,
        "member_count" : 2,
        "updated_at" : "2020-05-14T13:51:14.017871Z",
        "config" : {
          "automod_behavior" : "flag",
          "reactions" : true,
          "typing_events" : false,
          "mutes" : true,
          "max_message_length" : 5000,
          "created_at" : "2020-05-11T04:20:35.057523Z",
          "automod" : "disabled",
          "read_events" : true,
          "commands" : [
            {
              "set" : "fun_set",
              "args" : "[text]",
              "name" : "giphy",
              "description" : "Post a random gif to the channel"
            }
          ],
          "connect_events" : false,
          "replies" : true,
          "updated_at" : "2020-05-11T04:20:35.185619Z",
          "url_enrichment" : true,
          "search" : true,
          "message_retention" : "infinite",
          "uploads" : true,
          "name" : "messaging"
        },
        "admin" : [
          "52",
          "54"
        ],
        "group" : "257",
        "name" : "General"
      },
      "read" : [
        {
          "unread_messages" : 0,
          "user" : {
            "banned" : false,
            "online" : true,
            "name" : "Vit D3",
            "id" : "54",
            "role" : "user",
            "created_at" : "2020-05-14T13:48:42.839867Z",
            "image" : "\/images\/college\/1\/3b1e38d7-3353-4f54-9639-a44e49ecec11.jpeg",
            "updated_at" : "2020-05-14T13:51:48.328211Z",
            "last_active" : "2020-05-14T13:51:48.331736Z",
            "latest_hidden_channels" : [

            ]
          },
          "last_read" : "2020-05-14T13:51:14.242361344Z"
        },
        {
          "unread_messages" : 0,
          "user" : {
            "id" : "52",
            "banned" : false,
            "latest_hidden_channels" : [

            ],
            "last_active" : "2020-05-14T13:30:23.224806Z",
            "created_at" : "2020-05-14T13:28:30.222824Z",
            "devices" : [
              {
                "id" : "fuuxn8TBQKCgm6xoyAQCh2:APA91bEeYjlf0dD2ZGg9KD9JbksfOw53H2R-0Q-5aMAS163_eiFoI9VdsQo4XJ9qlt_YP4fYFHUraCuNgSBHshuEx-77XscWUWuNlgBV6zRZSgOwzqlz4AHwTGid_CZHmm3oGjr0hS-a",
                "push_provider" : "firebase"
              }
            ],
            "invisible" : false,
            "image" : "https:\/\/witley-dev-cdn.saritasa-hosting.com\/images\/college\/1\/af00704e-f49d-4e30-bd90-4fc16faec4ef.jpeg",
            "updated_at" : "2020-05-14T13:37:38.442052Z",
            "role" : "user",
            "online" : false,
            "name" : "Three Saritasa"
          },
          "last_read" : "2020-05-14T13:51:14.234717184Z"
        }
      ],
      "members" : [
        {
          "created_at" : "2020-05-14T13:51:14.223611Z",
          "updated_at" : "2020-05-14T13:51:14.223611Z",
          "role" : "member",
          "user" : {
            "id" : "52",
            "banned" : false,
            "latest_hidden_channels" : [

            ],
            "last_active" : "2020-05-14T13:30:23.224806Z",
            "created_at" : "2020-05-14T13:28:30.222824Z",
            "devices" : [
              {
                "id" : "fuuxn8TBQKCgm6xoyAQCh2:APA91bEeYjlf0dD2ZGg9KD9JbksfOw53H2R-0Q-5aMAS163_eiFoI9VdsQo4XJ9qlt_YP4fYFHUraCuNgSBHshuEx-77XscWUWuNlgBV6zRZSgOwzqlz4AHwTGid_CZHmm3oGjr0hS-a",
                "push_provider" : "firebase"
              }
            ],
            "invisible" : false,
            "image" : "https:\/\/witley-dev-cdn.saritasa-hosting.com\/images\/college\/1\/af00704e-f49d-4e30-bd90-4fc16faec4ef.jpeg",
            "updated_at" : "2020-05-14T13:37:38.442052Z",
            "role" : "user",
            "online" : false,
            "name" : "Three Saritasa"
          }
        },
        {
          "created_at" : "2020-05-14T13:51:14.223612Z",
          "updated_at" : "2020-05-14T13:51:14.223612Z",
          "role" : "owner",
          "user" : {
            "banned" : false,
            "online" : true,
            "name" : "Vit D3",
            "id" : "54",
            "role" : "user",
            "created_at" : "2020-05-14T13:48:42.839867Z",
            "image" : "\/images\/college\/1\/3b1e38d7-3353-4f54-9639-a44e49ecec11.jpeg",
            "updated_at" : "2020-05-14T13:51:48.328211Z",
            "last_active" : "2020-05-14T13:51:48.331736Z",
            "latest_hidden_channels" : [

            ]
          }
        }
      ],
      "membership" : {
        "created_at" : "2020-05-14T13:51:14.223612Z",
        "updated_at" : "2020-05-14T13:51:14.223612Z",
        "role" : "channel_member",
        "user" : {
          "banned" : false,
          "online" : true,
          "name" : "Vit D3",
          "id" : "54",
          "role" : "user",
          "created_at" : "2020-05-14T13:48:42.839867Z",
          "image" : "\/images\/college\/1\/3b1e38d7-3353-4f54-9639-a44e49ecec11.jpeg",
          "updated_at" : "2020-05-14T13:51:48.328211Z",
          "last_active" : "2020-05-14T13:51:48.331736Z",
          "latest_hidden_channels" : [

          ]
        }
      }
    }
  ],
  "duration" : "16.64ms"
}

**Comment by vadubov** [comment]
{
  "presence" : true,
  "filter_conditions" : {
    "$and" : [
      {
        "type" : "messaging"
      },
      {
        "is_direct" : true
      },
      {
        "members" : {
          "$in" : [
            "54"
          ]
        }
      },
      {
        "archived" : {
          "$ne" : [
            "54"
          ]
        }
      }
    ]
  },
  "state" : true,
  "message_limit" : 25,
  "watch" : true,
  "limit" : 20
}

**Comment by vadubov** [comment]
Decoding error from console

```
🐴 [15 May 11:25:45.919] ❌  keyNotFound(CodingKeys(stringValue: "created_at", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "channels", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "read", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "devices", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"created_at\", intValue: nil) (\"created_at\").", underlyingError: nil)) in parse(data:response:error:completion:)[305]
```

**Comment by b-onc** [comment]
Hello @vadubov 
I've checked with the backend team and this is probably a bug in our backend. We're investigating and we'll let you know.

**Comment by b-onc** [comment]
Hello @vadubov ,
This should be resolved. Are you still seeing this issue?

**Comment by vadubov** [comment]
For old users I still get JSON without `created_at` field:
`"devices" : [
                {
                  "id" : "some_id",
                  "push_provider" : "firebase"
                }
              ],`
and therefore a decoding error
`[ERROR] ❌  keyNotFound(CodingKeys(stringValue: "created_at", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "channels", intValue: nil), _JSONKey(stringValue: "Index 12", intValue: 12), CodingKeys(stringValue: "messages", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "mentioned_users", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "devices", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"created_at\", intValue: nil) (\"created_at\").", underlyingError: nil)) in parse(data:response:error:completion:)[309]`

Should it be checked for new Android users?

**Comment by vadubov** [comment]
After logging in with a user created on Android device I get this response:
```🐴 [08/06 14:36:46.952] ⬅️ Response 201: https://api.stream-io-api.com/api/v1.0/user/?api_key=8qh2853w39ny&get_or_create=1
🐴 [08/06 14:36:46.952] ⒿⓈⓄⓃ 166 bytes
 {
  "duration" : "0.81ms",
  "id" : "274",
  "data" : {
    "name" : "Boris B2",
    "profileImage" : null
  },
  "updated_at" : "2020-06-08T09:27:26.317255Z",
  "created_at" : "2020-06-08T09:27:26.317255Z"
}
🐴 [08/06 14:36:47.118] 👤 The current user was setupped with id: 274
[08 Jun 14:36:47.257] [DEBUG] ❤️ Connected. Waiting for the current user data and connectionId...
[08 Jun 14:36:47.269] [DEBUG] healthCheck 👤 274
[08 Jun 14:36:47.270] [INFO] 📦  {
  "created_at" : "2020-06-08T09:36:47.18661237Z",
  "me" : {
    "id" : "274",
    "banned" : false,
    "roles" : [

    ],
    "unread_channels" : 1,
    "mutes" : [

    ],
    "last_active" : "2020-06-08T09:36:47.18346104Z",
    "created_at" : "2020-06-08T09:04:31.761436Z",
    "devices" : [
      {
        "id" : "fWxtIt4uSmC6dfcs0wYeXD:APA91bGEna87U56VEof28SUcVOHqdb-rVMVhVIkvV3MnyGbNWrA9BHERkEVWK7sy8fbLxVIRfy_NMjoeJxGlN7SeaAMRlP7DXNSFnNJwSrbyogVnm1J8r-V_PI7nVn6fKPSnZfMUlSl6",
        "push_provider" : "firebase",
        "user_id" : "274",
        "created_at" : "2020-06-08T09:09:42.586684Z"
      }
    ],
    "invisible" : false,
    "unread_count" : 2,
    "channel_mutes" : [

    ],
    "image" : "\/images\/college\/2\/26a27e45-03c4-48b4-bd5b-85037f889667.jpg",
    "updated_at" : "2020-06-08T09:27:26.548595Z",
    "language" : "",
    "role" : "user",
    "total_unread_count" : 2,
    "online" : true,
    "name" : "Boris B2"
  },
  "type" : "health.check",
  "connection_id" : "4dcf6022-1a10-4e4b-97e9-d4d18df279a3",
  "cid" : "*"
}
```

But after querying channels I get `device` object for this user empty, so cannot check whether it parses correctly. But I noticed another user created by our QA team which still doesn't have `created_at` field in `devices` object and therefore parsing fails:
```
"user" : {
            "banned" : false,
            "online" : true,
            "id" : "271",
            "role" : "user",
            "created_at" : "2020-06-08T06:23:08.031484Z",
            "image" : "\/images\/college\/2\/0f33e46e-2d31-4e2f-8655-35ab87cb3ac8.jpeg",
            "invisible" : false,
            "updated_at" : "2020-06-08T09:30:00.836042Z",
            "devices" : [
              {
                "id" : "dZl7Hs0_QXK5B4MyyFLRkk:APA91bHHpBRfn3pkD7HU2hIoxOfoXO2YlPS7-2XrPkCvgCRy019WDICTk3wXlDmKBThhZR5tPxOOk0GoQNzx47USHt5eRp0A04lHx1mY3LqtGQdsfEPWSqkmKTCRRrvcWHMuHv7foEVT",
                "push_provider" : "firebase"
              }
            ],
            "last_active" : "2020-06-08T09:16:54.954163Z",
            "name" : "Alexander Sergeevich Romodanovskiy-Koltyga"
          },
```

**Comment by vadubov** [comment]
Could you please estimate when it will be fixed? We have this bug on our staging environment and the client sees it.

**Comment by b-onc** [comment]
Hello @vadubov ,
The backend team is working hard to fix this issue. It's hard to give an exact estimate, but it should be resolved within 2 weeks.
As a workaround, we'll make `created_at` an optional field in the next release, so it will not cause an error.

**Comment by vadubov** [comment]
Any update on this? `created_at ` is still required in `Device` model in the new 2.2.6 release

**Comment by arthurchambsp** [comment]
Same issue for us

**Comment by adeelnoor** [comment]
@b-onc the issue persist in the latest update [2.2.7](https://github.com/GetStream/stream-chat-swift/tree/2.2.7)

`[ERROR] ❌  keyNotFound(CodingKeys(stringValue: "created_at", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "channels", intValue: nil), _JSONKey(stringValue: "Index 3", intValue: 3), CodingKeys(stringValue: "channel", intValue: nil), DecodingKeys(stringValue: "created_by", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"created_at\", intValue: nil) (\"created_at\").", underlyingError: nil)) in parse(data:response:error:completion:)[309]`

**Comment by b-onc** [comment]
@adeelnoor Thanks for bringing this up. Seems like #346 did not totally resolve this issue - `created` was converted to an optional but it wasn't parsed as optional: `decode` vs `decodeIfPresent`. It's an overlook from our part, we'll fix it.

**Comment by adeelnoor** [comment]
Okay thanks @b-onc
