### ISSUE TITLE
Message sending delayed

### ISSUE THREAD

**Issue by jfru** [GetStream/stream-chat-swift#2674]
## What did you do?
We're seeing long delays in message sending for some messages.
User sends 4 messages
1 message is correctly sent and received
3 remaining messages are received > 24 hours later

## What did you expect to happen?
All messages should be immediately sent and received when users are connected to the service

## What happened instead?
Messages showed up hours or days later
See these two screenshots of the same thread from the different perspectives of each user in the channel. There are 3 messages missing from in the receiving user's channel
![IMG_1132](https://github.com/GetStream/stream-chat-swift/assets/17079221/21f018cc-8200-4d11-b388-a9c8597e7b85)
![IMG_2785](https://github.com/GetStream/stream-chat-swift/assets/17079221/71a67444-a601-4eb7-9baa-37b54470ce25)

then see this pic, where the 3 missing messages were eventually sent and moved to the bottom of the sender's view a day later
![IMG_4F7AF0D10F8C-1](https://github.com/GetStream/stream-chat-swift/assets/17079221/43a964c5-1e58-48e6-8f28-fca79f75c09e)

when i queried the database, I saw that the delayed messages were only 'created' at the same time they appeared in the receivers chat. For example, this is one the messages that was actually sent on 6/13, but it has a created at of 6/14. 
![Screenshot 2023-06-14 at 12 33 41 PM](https://github.com/GetStream/stream-chat-swift/assets/17079221/8640bb58-732c-4777-a675-95b43c1241de)

The message that was immediately received by the receiver has the correct created_at timestamp 
![Screenshot 2023-06-14 at 12 35 03 PM](https://github.com/GetStream/stream-chat-swift/assets/17079221/c9f20b24-5d5f-4f9a-989a-d954084d7916)

## GetStream Environment
**GetStream Chat version:**
4.33.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
StreamChatSwiftUI
**iOS version:**
16.4
**Swift version:**
**Xcode version:**
**Device:**
14

**Comment by jfru** [comment]
And finally a screenshot from the senders thread where the message order has changed since the messages showed up in the db...
![IMG_F9402C4915FC-1](https://github.com/GetStream/stream-chat-swift/assets/17079221/1f72db61-c3d6-4a56-88ee-1200a71c9282)

**Comment by polqf** [comment]
Hi @jfru ,

Is this an issue that started happening after any change? After an upgrade? This is the first time we hear about something like this.

Could you share any snippet of custom logic you might have around sending a message? Any custom handling?

**Comment by jfru** [comment]
Hey! I think we were a couple of versions behind may like 4.30 and then we update to 33 and the issue hasn't occurred again since then. No custom handling on our end. Will keep an eye on it to see if it happens again. Thanks!

**Comment by hyouuu** [comment]
Hi @polqf re-opening this as we saw it happen again. Regarding your question, we either call:
```
        let channelController = chatClient.channelController(for: channelID)
        self.channelController = channelController
        _ = try await channelController.safeSynchronize()
        try channelController.createNewMessage(
            text: text,
            quotedMessageId: quotedMessageId
        )
```

or this if there was no channel yet:

```
        try await chatService.startDirectMessageWith(userIds: [recipientId, currentUserId],
                                                             extraData: [Constants.Chat.isGroup: .bool(false)])

        _ = try await chatService.sendMessage(
                    to: [recipientId],
                    text: message,
                    attachments: [],
                    quotedMessageId: quotedMessageId
                )
```

They look pretty basic and were sent from iOS, and Josh verified in the database that the messages were not there until a later date, so my hypothesis is that with bad signal the messages didn't send right away and is stored in CoreData or disk files, but when signal becomes better they were not put in the right order before newer messages
