### ISSUE TITLE
Can't override ImageLoading

### ISSUE THREAD

**Issue by haipercb** [GetStream/stream-chat-swift#2692]
( Related to this issues: https://github.com/GetStream/stream-chat-swift/issues/2689 )

Since the declaration in the ImageLoading protocol and extension is different.
So I don't seem to be able to override this function.

So I had to override the updateContent function for most of the views. :(

in protocol ImageLoading:
```Swift
public protocol ImageLoading: AnyObject {
@discardableResult
    func loadImage(
        into imageView: UIImageView,
        from attachmentPayload: ImageAttachmentPayload?,
        maxResolutionInPixels: Double,
        completion: ((_ result: Result<UIImage, Error>) -> Void)?
    ) -> Cancellable?
}
```

in extension ImageLoading(completion defaults to nil):
Function from the extension is used in many locations in the SDK.
```Swift
public extension ImageLoading {
func loadImage(
        into imageView: UIImageView,
        from attachmentPayload: ImageAttachmentPayload?,
        maxResolutionInPixels: Double,
        completion: ((_ result: Result<UIImage, Error>) -> Void)? = nil
    ) -> Cancellable? {
   ...
}
}
```

_Originally posted by @haipercb in https://github.com/GetStream/stream-chat-swift/issues/2689#issuecomment-1620585849_

**Comment by nuno-vieira** [comment]
Hi @haipercb,

It is possible to override, but you must implement all protocol functions. Somehow, Swift is not able to use the default implementations for the custom protocol implementation unfortunately. So all functions need to be implemented from "scratch", although there's a way to avoid duplication. Here is an example:

```swift
class CustomImageLoader: ImageLoading {
    let nukeImageLoader = NukeImageLoader()

    @discardableResult
    func loadImage(
        into imageView: UIImageView,
        from url: URL?,
        with options: ImageLoaderOptions,
        completion: ((_ result: Result<UIImage, Error>) -> Void)?
    ) -> Cancellable? {
        nukeImageLoader.loadImage(
            into: imageView,
            from: url,
            with: options,
            completion: completion
        )
    }

    @discardableResult
    func loadImage(
        into imageView: UIImageView,
        from attachmentPayload: ImageAttachmentPayload?,
        maxResolutionInPixels: Double,
        completion: ((_ result: Result<UIImage, Error>) -> Void)?
    ) -> Cancellable? {
        // You custom implementation
    }

    @discardableResult
    func downloadImage(
        with request: ImageDownloadRequest,
        completion: @escaping ((_ result: Result<UIImage, Error>) -> Void)
    ) -> Cancellable? {
        nukeImageLoader.downloadImage(with: request, completion: completion)
    }

    func downloadMultipleImages(
        with requests: [ImageDownloadRequest],
        completion: @escaping (([Result<UIImage, Error>]) -> Void)
    ) {
        nukeImageLoader.downloadMultipleImages(with: requests, completion: completion)
    }
}
```

I just tested the example above, and it works. As you can see, I implemented all protocol definitions, and this is mandatory. Then I use our loader with composition to reuse our default implementations. 

Best,
Nuno

**Comment by haipercb** [comment]
However, in the ImageAttachmentGalleryCell class, because the loadImage method in updateContent omits the completion parameter, he will always execute the implementation in extension ImageLoading.

in ImageAttachmentGalleryCell:
```Swift
override open func updateContent() {
        super.updateContent()

        let imageAttachment = content?.attachment(payloadType: ImageAttachmentPayload.self)

        // ** No completion parameters
        // ** Will not call CustomImageLoader
        // ** The default extension ImageLoading will always be called here.
        components.imageLoader.loadImage(
            into: imageView,
            from: imageAttachment?.payload,
            maxResolutionInPixels: components.imageAttachmentMaxPixels
        )
    }
```
default extension ImageLoading:
```Swift
public extension ImageLoading {
    @discardableResult
    func loadImage(
        into imageView: UIImageView,
        from attachmentPayload: ImageAttachmentPayload?,
        maxResolutionInPixels: Double,
        completion: ((_ result: Result<UIImage, Error>) -> Void)? = nil
    ) -> Cancellable? {
    ...
}
```

**Comment by nuno-vieira** [comment]
Hi @haipercb,

I see, it seems you are correct. We will investigate this soon and see if we can fix it without any breaking changes. We will keep you updated.

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @haipercb!

We already have a fix for this ready 👍 

We will let you know once we have this available.

Best,
Nuno

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
