### ISSUE TITLE
Filtered list is not persisting after going back and forth twice in a chat

### ISSUE THREAD

**Issue by vaibhavrajsinghSys** [GetStream/stream-chat-swift#2699]
## What did you do?
1. I typed in the searchbar in the chat list
2. The result is filtered out according to the user input
3. user clicks the filtered chat result and open the chat
4. user goes back 
5. again the user click the same chat 
6. again user goes back 
7. the list only show one result but previously shows 5 items
8. when the user clicks the group chat the chat is automatically slides to the top

## What did you expect to happen?
The filtered list should persist even if the user goes back and forth.

## What happened instead?
the filtered list reduced from 5 to 1 after going back and forth twice on the same chat and the 
group chat is autoslided to the top.

## GetStream Environment
**GetStream Chat version:** 4.32.0 (34)
**GetStream Chat frameworks:** StreamChatSwiftUI
**iOS version:** 16.5.1
**Swift version:** N/A
**Xcode version:** N/A
**Device:** iphone X

## Additional context

https://github.com/GetStream/stream-chat-swiftui/assets/127815098/8067cc8f-a8d3-46ef-80e9-545fb5ed5696

**Comment by nuno-vieira** [comment]
Hi, @vaibhavrajsinghSys!

This is an issue on the Core SDK, so we moved it here.

We already have a fix available, and it will come out in the next release.

We will let you know once we have published it 👍 

Best,
Nuno

**Comment by testableapple** [comment]
Hi @vaibhavrajsinghSys,
This has been fixed in our latest release [4.35.1](https://github.com/GetStream/stream-chat-swift/releases/tag/4.35.1).
Closing this issue for now, feel free to reopen it if you encounter any issues.
