### ISSUE TITLE
Crash "resume cannot be sent to abstract instance of class NSURLSessionTask' 

### ISSUE THREAD

**Issue by vWolfG** [GetStream/stream-chat-swift#270]
## What did you do?
Call queryChannels func

## What did you expect to happen?
Not to crash

## What happened instead?
App crash

## GetStream Environment
**GetStream Chat version:** 2.2.0
**iOS version:** 12.4
**Swift version:** 5.0
**Xcode version:** 11.4.1
**Device:** iphone 6

## Additional context
prepareRequest can return empty URLSessionTask(), but this is not processed in a proper way where it is used, ex func request

**Comment by b-onc** [comment]
Hello @vWolfG 
Please provide all the environment info and steps to reproduce.

**Comment by vWolfG** [comment]
Sorry, I realized that it is the same as https://github.com/GetStream/stream-chat-swift/issues/261
