### ISSUE TITLE
Crash in ConnectionRepository.updateWebSocketEndpoint

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2702]
## What did you do?

initialized the SDK

## What did you expect to happen?

no crash

## What happened instead?

crash

<img width="993" alt="Screenshot 2023-07-12 at 10 27 17 AM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/d1e1f179-d43c-4138-ad22-839abffcb884">

i've seen this in 4.33.0 as well, i was hoping upgrading to 4.34.0 would solve

## GetStream Environment
**GetStream Chat version:** 4.34.0

**Comment by nuno-vieira** [comment]
Hi @AndrewSB!

Can you export the full crashlog? Can you also share where do you call `connectUser()` ?

Best,
Nuno

**Comment by AndrewSB** [comment]
[com.reclip_issue_ccdf123aa0863e5bad419491cbd5a321_crash_session_b62bdfcccf6e4476b87c5c5fd34fd2ce_DNE_0_v2_stacktrace.txt](https://github.com/GetStream/stream-chat-swift/files/12052296/com.reclip_issue_ccdf123aa0863e5bad419491cbd5a321_crash_session_b62bdfcccf6e4476b87c5c5fd34fd2ce_DNE_0_v2_stacktrace.txt)

[com.reclip_issue_baade0de3bddc89af739ca8476a79fb5_crash_session_4b9d6f81b7db4c408ac5794c4ccd8402_DNE_0_v2_stacktrace.txt](https://github.com/GetStream/stream-chat-swift/files/12052297/com.reclip_issue_baade0de3bddc89af739ca8476a79fb5_crash_session_4b9d6f81b7db4c408ac5794c4ccd8402_DNE_0_v2_stacktrace.txt)

**Comment by AndrewSB** [comment]
we call connectUser soon after init, from inside a `Task {}`

**Comment by nuno-vieira** [comment]
After Init? Which init? We will keep investigating this, but is there a chance you can call connectUser from the Main Thread to see if the crash goes away?

**Comment by AndrewSB** [comment]
`init` of the app

**Comment by AndrewSB** [comment]
yeah, we can try running the connectUser from inside a `MainActor.run {}`

**Comment by nuno-vieira** [comment]
Hi @AndrewSB!

We were able to reproduce this crash and we are already working on fix 👍 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi!

This issue has been resolved on the new [4.37.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.37.0) Release! 🚀 

Best,
Nuno
