### ISSUE TITLE
deadlock on main thread: ListChangeAggregator.controllerDidChangeContent

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2708]
## What did you do?

1 out of every 10 runs ends up on a deadlock once i navigate to the threadlist

<img width="1651" alt="Screenshot 2023-07-28 at 12 31 55 PM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/d1f8c320-96c0-4e37-b3e6-333c6de59744">
<img width="1638" alt="Screenshot 2023-07-28 at 12 32 02 PM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/bdce16b3-640a-46cf-8e29-a8b1d9975465">

i can see that this `@Atomic` property is accessed from multiple threads (for eg, i run `ChatChannelController.syncronize()` from within a Task, so it happens on a background thread

any ideas/tips on how to make it so this lock doesn't block the main thread? usually this ends with a watchdog termination

## GetStream Environment
**GetStream Chat version: 4.34.0

**Comment by chan-reclip** [comment]
To correct the wording, it isn't deadlock but it's blocking wait in the main thread.
Anyways, my colleague @AndrewSB found the above while debugging an issue where the app becomes almost unresponsive right after it's foregrounded.

Related to the issue, the following code caught my eyes while I'm having a look. https://github.com/GetStream/stream-chat-swift/blob/2554cc27202608b3f72996b612d26e672c1db3a8/Sources/StreamChat/Controllers/ListDatabaseObserver.swift#L240
Is there any chance `performAndWait` can cause a trouble here especially when we have big data to synchronise?

**Comment by testableapple** [comment]
Hi @AndrewSB and @chan-reclip,

This is a known problem in our Controllers. They need to be used from the main thread (see https://github.com/GetStream/stream-chat-swift/issues/2564 and https://github.com/GetStream/stream-chat-swift/issues/2687 for more details).
Please, consider using the controller from the main thread when calling synchronize() or accessing the .messages.

Hope this helps!

Best wishes,
Alexey

**Comment by jfru** [comment]
Hi Guys. Stephen mentioned to me that this is currently in your backlog. Is there somewhere that I can track it? As mentioned, it's causing some significant performance issue in our client, so I'd like to be able to keep an eye on it and receive a notification when it's resolved.
