### ISSUE TITLE
ServerErrorPayload 400 invalid json data

### ISSUE THREAD

**Issue by NatashaLavrinenko** [GetStream/stream-chat-swift#2711]
## What did you do?
[ConnectUser](https://getstream.io/chat/docs/react/init_and_users/?language=swift#connecting-the-user) function is called for a user which has name that consists ";" character. 

## What did you expect to happen?
Passing the name with any character shouldn't cause any issues.

## What happened instead?
The following error happens: 
`_API Error: Optional("Error WebSocket in  .../stream-chat-swift/Sources/StreamChat/WebSocketClient/WebSocketClient.swift:212 -> ServerErrorPayload(code: 4, message: \"invalid json data\", statusCode: 400)).")_`
The issue didn't happen to the username without special character:
"email;52" - ❌ 
"email52" -  ✅ 

Please see the logs attached - [debug.txt](https://github.com/GetStream/stream-chat-swift/files/12224155/debug.txt)

## GetStream Environment
**GetStream Chat version:** 4.33.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.1.1
**Swift version:** 5.7
**Xcode version:** 14.3.1
**Device:** iPhone 11

**Comment by testableapple** [comment]
Hi @NatashaLavrinenko,

Since this one is not related to iOS, you should report this to [support@getstream.io](mailto:support@getstream.io). Our support team will be able to identify if this is an issue on our side.

Best wishes,
Alexey
