### ISSUE TITLE
Infinite allocation loop in iOS 15

### ISSUE THREAD

**Issue by Crysis21** [GetStream/stream-chat-swift#2723]
I just updated the pod to 4.35. This are working fine in iOS 16, but on iOS 15.5 there is an infinite loop happening when creating events controller. This makes the app to shoot up to 2GB of memory usage in a few seconds and gets killed by the system. We've locked the pod to 4.34 for now and this are working.

**Comment by testableapple** [comment]
Hi @Crysis21,

This is probably a known issue. We've just released [4.35.1](https://github.com/GetStream/stream-chat-swift/releases/tag/4.35.1). Please, give it a try.

Best wishes,
Alexey
