### ISSUE TITLE
Crash on image long tap

### ISSUE THREAD

**Issue by kirillkunst** [GetStream/stream-chat-swift#2724]
## What did you do?

Hi, I found that application get crashed when I tried to long tap on any image in chat.

I attached more context:
1. crash stack log.
2. Screenshot where it happens.
3. Screenshot with crash log.
4. Screenshot with the place where it got crashed.

## What did you expect to happen?
I expected the SDK not crashing in this case.

## What happened instead?
Application crashed.

## GetStream Environment
**GetStream Chat version:** 4.35.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 16.4
**Swift version:** 5.8
**Xcode version:** 14.3.1
**Device:** iPhone 14 Pro Max

## Additional context
[crash_stack.log](https://github.com/GetStream/stream-chat-swift/files/12310234/crash_stack.log)

<img width="388" alt="Screenshot 2023-08-10 at 10 46 58" src="https://github.com/GetStream/stream-chat-swift/assets/44998413/5cb93821-0439-4623-b6ee-5f8665605b6a">

<img width="473" alt="Screenshot 2023-08-10 at 10 46 22" src="https://github.com/GetStream/stream-chat-swift/assets/44998413/5ec12d9c-ae60-41a1-b7d1-9de7a14dca54">
<img width="1929" alt="Screenshot 2023-08-10 at 10 46 38" src="https://github.com/GetStream/stream-chat-swift/assets/44998413/af111f37-75c2-430c-8afd-78a653fc12bc">

**Comment by testableapple** [comment]
Hi @kirillkunst,
Thanks for opening the issue.

Unfortunately, I could not reproduce the crash. Do you have any customizations? Also, could you try reproducing it in our [DemoApp](https://github.com/GetStream/stream-chat-swift/tree/develop/DemoApp), please? 

Best wishes,
Alexey

**Comment by kirillkunst** [comment]
Hi @testableapple , I wasn't able to reproduce it with your Demo App.
I started commenting out line by line all the code I did for the customization and found the root cause:

I had following:

```
class SLRPublicChatMessagePopupVC: ChatMessagePopupVC {
  override func viewDidLoad() {
    super.viewDidLoad()
    overrideUserInterfaceStyle = .dark
  }
}

Components.default.messagePopupVC = SLRPublicChatMessagePopupVC.self
```

And it got crashed. After removing these lines it started working fine.

**Comment by testableapple** [comment]
Hi @kirillkunst,
I see. This is weird. As a workaround, you can `overrideUserInterfaceStyle` for the required subviews, e.g.:

```swift
class SLRPublicChatMessagePopupVC: ChatMessagePopupVC {
  override func viewDidLoad() {
    super.viewDidLoad()

    reactionsController?.overrideUserInterfaceStyle = .dark
    actionsController?.overrideUserInterfaceStyle = .dark
  }
}

Components.default.messagePopupVC = SLRPublicChatMessagePopupVC.self
```

Please let me know if this helps.

Best wishes,
Alexey

**Comment by kirillkunst** [comment]
Hi @testableapple , it works, thanks a lot.

**Comment by testableapple** [comment]
You're welcome, @kirillkunst
