### ISSUE TITLE
Reactions on Pinned Messages

### ISSUE THREAD

**Issue by ondrejkorol** [GetStream/stream-chat-swift#2731]
Hi! I'm trying to build a feature around reacting to pinned messages, but it looks like there is a bug that results in losing reactions of the pinned messages. Sometimes the reactions aren't displayed, and sometimes they're displayed but they'll get out of sync when changing them (e.g. removing the reaction will keep the `reactionCounts` at 1, but `currentUserReactions` is 0).

This results in unreliable behavior, making it kinda a critical bug as it's not possible to rely on reactions. It's confusing for developers and furthermore for users.

The issue should be easily reproducible and visible on the recording created in the example app.
1) Pin a message and react to it
2) close the chat and return
3) The pinned message ~~has a weird removal/insert animation and~~ has 0 reactions.

The behavior is slightly different when you first react to the message and then pin the message. Also, there are unexpected changes when multiple people react to the pinned message.

Can you take a look at it, please? I haven't figured out what could be the underlying issue. Happy to help here.

## GetStream Environment
**GetStream Chat version:** 4.35.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI 4.35.1/main
**iOS version:** 15 – 16.5
**Swift version:** 5
**Xcode version:** 14.3.1
**Device:** doesn't matter

https://github.com/GetStream/stream-chat-swift/assets/68337693/ae9b38b8-396d-42fa-8da7-0065968f9327

**Comment by martinmitrevski** [comment]
Moving this back to the main repo, since it's a low-level client bug.

**Comment by nuno-vieira** [comment]
Hi @ondrejkorol!

We are going to investigate this soon, and will get back to you once we have more details 👍 

Best,
Nuno

**Comment by ondrejkorol** [comment]
Great, thank you @nuno-vieira! Please let me know if I can be of any help (e.g. observe a certain class/file)

**Comment by polqf** [comment]
Hi @ondrejkorol ,

We have identified the issue, our colleagues on the backend team will work on a fix as soon as possible.
Thank you

**Comment by polqf** [comment]
Hi @ondrejkorol ,

We have identified the issue and our colleagues on the backend team will work on a fix as soon as possible.
We will keep you posted!

**Comment by ondrejkorol** [comment]
Hi @polqf! That's great news!
Can I ask you please, do I understand correctly that this could be a server-side fix, meaning there won't be a need to update Stream Chat iOS SDK in order to fix this problem?

**Comment by ondrejkorol** [comment]
Any news, please? @nuno-vieira

**Comment by nuno-vieira** [comment]
Hi @ondrejkorol!

Currently, the backend team is very busy, so this one is in queue, but we do not have an ETA for this at the moment.

We recommend creating a ticket on our support page at https://getstream.io/contact/support/ so that is easier to keep track of this backend issue.

Since this is not an iOS Issue, we are going to close this one and we should move the tracking over to support 👍 

Hope you understand,

Best,
Nuno
