### ISSUE TITLE
SDK doesn't work on iOS 13.

### ISSUE THREAD

**Issue by kirillkunst** [GetStream/stream-chat-swift#2744]
## What did you do?

Hi, we integrated your SDK when have seen that it supports iOS11+.
But when we try to run our app with your SDK integrated, on, for example, iOS 14, we've got following issue:

```
dyld: Library not loaded: /System/Library/Frameworks/AVFAudio.framework/AVFAudio
  Referenced from: /Users/<>/Library/Developer/Xcode/DerivedData/Stoiximan-cppustdrfquuwqafgxopyyjdgyhd/Build/Products/Debug-iphonesimulator/StreamLayerSDK.framework/StreamLayerSDK
  Reason: image not found
Message from debugger: Terminated due to signal 6
```

Seems like you're using AVFAudio framework that supports only iOS 14.5+.

How to handle this sutiation?

## What did you expect to happen?

SDK works fine on iOS 13+

## What happened instead?

App is crashed when running on iOS 13 or iOS 14.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 14
**Swift version:**
**Xcode version:**
**Device:**

**Comment by polqf** [comment]
Hi @kirillkunst 

StreamLayerSDK is not any of our frameworks. Looks like you have wrapped Stream SDK(s) in a framework of your own named StreamLayerSDK, and there is where the issue is.

We are sorry we cannot help you further.
