### ISSUE TITLE
Opening Keyboard programatically hides messagebar

### ISSUE THREAD

**Issue by brianmwadime** [GetStream/stream-chat-swift#2745]
## What did you do?

Called `messageComposerVC.composerView.inputMessageView.textView.becomeFirstResponder()` to trigger keyboard to be displayed when a user opened our `ChatChannelVC` subclass.

## What did you expect to happen?
Expected the keyboard to open with the message composer view moved accordingly.

## What happened instead?
The keyboard opens and hides the message composer view.
![IMG_0963](https://github.com/GetStream/stream-chat-swift/assets/1143392/3b878c16-443d-4a50-8d28-0908f96c894c)

## GetStream Environment
**GetStream Chat version:** 4.32.0
**GetStream Chat frameworks:**  StreamChat, StreamChatUI
**iOS version:** 16
**Swift version:** 5
**Xcode version:** 14.3.1
**Device:** iPhone 8

**Comment by brianmwadime** [comment]
Thanks @polqf

**Comment by nuno-vieira** [comment]
Hi @brianmwadime,

The reason this happens is because `keyboardHandler.start()` is only called in `viewDidAppear()`. So it is better if you call it in `viewDidAppear()`.

In case you want to call it in `viewDidLoad()`, you need to call it this way:
```swift
keyboardHandler.start()
messageComposerVC.composerView.inputMessageView.textView.becomeFirstResponder()
```

Best,
Nuno
