### ISSUE TITLE
Tapping on Image Attachment Freezes the app

### ISSUE THREAD

**Issue by maxxlt** [GetStream/stream-chat-swift#2748]
## What did you do?
I opened the image attachment, then single-tapped on the image
## What did you expect to happen?
Nothing
## What happened instead?
Freezes the app

## GetStream Environment
**GetStream Chat version:** 4.35.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS 16.6
**Swift version:** 5
**Xcode version:** 14.3
**Device:** iPhone 14

**Comment by polqf** [comment]
Hi @maxxlt ,

What are the steps you are following to reproduce this issue? Can you reproduce it in the DemoApp?

**Comment by maxxlt** [comment]
@polqf I couldn't reproduce it in `DemoApp`. After debugging it for a while in our implementation, I narrowed the bug search down to `handleSingleTapOnCell(at indexPath: IndexPath)` function. The following lines were throttling the CPU to 100%:
```
topBarTopConstraint?.constant = areBarsHidden ? 0 : -topBarView.frame.height
bottomBarBottomConstraint?.constant = areBarsHidden ? 0 : bottomBarView.frame.height
```

**Comment by nuno-vieira** [comment]
Hello!

We are closing this one for inactivity. 

Feel free to re-open it if you find something.

Best,
Nuno
