### ISSUE TITLE
Blocking CoreData calls (performAndWait) in the main thread

### ISSUE THREAD

**Issue by chan-reclip** [GetStream/stream-chat-swift#2749]
## What did you do?

The following code caught my eyes: https://github.com/GetStream/stream-chat-swift/blob/2554cc27202608b3f72996b612d26e672c1db3a8/Sources/StreamChat/Controllers/ListDatabaseObserver.swift#L240

It turned out stream-chat-swift is calling [performAndWait](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506364-performandwait) in the main thread from many call sites.

While I can't really tell how exactly this is affecting our apps UX, it's common sense that one shouldn't use use blocking API calls such as file I/O (including DB) or network fetch calls, in the main UI thread.
We indeed experience laggy Chat UI issues and I suspect this (`performAndWait`) is contributing to the issues.

## What did you expect to happen?

In this particular case, there's an alternative function [perform](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506578-perform) which can be used in the main thread without hurting UI responsiveness.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by polqf** [comment]
Hi @chan-reclip, 

We understand your concern, and we are working on a plan to remove as much overhead as possible away from the main thread. Using `perform` straight away is not an option right now, and therefore it is not an easy change.

That said, this should not be the reason why you might be having issues.

We are going to close this issue for now. Thank you for your report.
