### ISSUE TITLE
SearchBar not showing in  ChatChannelListVC

### ISSUE THREAD

**Issue by appthesot** [GetStream/stream-chat-swift#2757]
## What did you do?
I have integrated the ChatChannelListVC in my iOS app using below code 
I do have below component enabled as well 
omponents.default.messageListDateSeparatorEnabled = true
        Components.default.messageListDateOverlayEnabled = true
        Components.default.isVoiceRecordingEnabled = true
        Components.default.messageSwipeToReplyEnabled = false
        Components.default.channelListSearchStrategy = .channels

```
let query = ChannelListQuery(filter: .containMembers(userIds: [GetStreamUserDataStore.shared.username ?? ""]))
                let controller = ChatClient.shared.channelListController(query: query)
                let channelListVC = ChatChannelListVC.make(with: controller)
                let channelListNVC = UINavigationController(rootViewController: channelListVC)

                let nav = tabbar.selectedViewController as! UINavigationController
                nav.pushViewController(channelListVC, animated: true)
```

## What did you expect to happen?
I expect search bar to be shown

## What happened instead?

I cannot see the search bar 

## GetStream Environment
**GetStream Chat version:** 4.35.2
**GetStream Chat frameworks:** StreamChat, StreamChatUI - 4.35.2
**iOS version:** 16.3
**Swift version:** Swift5 
**Xcode version:** 14.3.1
**Device:** simulator

## Additional context
Attaching screenshot
<img width="350" alt="Screenshot 2023-08-30 at 00 24 44" src="https://github.com/GetStream/stream-chat-swift/assets/137693874/f93eb145-3668-4a84-8c81-1740adb2c443">

**Comment by nuno-vieira** [comment]
Hello @appthesot,

The error is that you are not displaying the navigation controller, but the view controller only.

**Problem:**
nav.pushViewController(~**_channelListVC_**~, animated: true)
**Solution:**
nav.pushViewController(**_channelListNVC_**, animated: true)

You forgot the **N**

Best,
Nuno
