### ISSUE TITLE
Disappearing messages

### ISSUE THREAD

**Issue by Ga77ett** [GetStream/stream-chat-swift#2783]
## What did you do?
I opened a chat that contains messages.

## What did you expect to happen?
I expected the chat to be open, and the messages to be displayed.

## What happened instead?
The chat opened, the messages were displayed, then all of them disappeared except the last one, and after some time, they reappeared and didn't disappear again.

## GetStream Environment
GetStream Chat version: 4.36.0
GetStream Chat frameworks: StreamChat, StreamChatUI
iOS version: 16.4
Swift version: 5.0
Xcode version: 14.3.1
Device: iPhone 14 Pro Max

## Additional context
Hello, colleagues!
I am experiencing some strange issues with database updates that lead to unexpected results.
For example, I have a chat with a user who is offline, all messages are received on my device, and there have been no changes to them. I simply open the chat, see all the messages, then they disappear, and after some time, they reappear. This happens every time I move from the chat list to the chat itself, and only once.
As far as I understand, CoreData sends a .remove message, and then .insert, but I don't understand the reason for this behavior... Maybe you can help me with advice?

**Comment by ipavlidakis** [comment]
Hi @Ga77ett, thanks for reaching out. To help us understand more about the issue you are facing do you providing us with more info regarding the following questions/asks:
- Which user is the one that you see the issue with, the online one or the offline (that comes) online?
- Do you have a video maybe you can share with us that demonstrates the issue?

Best regards,
Ilias

**Comment by Ga77ett** [comment]
Hello @ipavlidakis! Thanks for your reply!
1. I see that issue with all users and they all offline
2. Yes, i have the video  https://github.com/GetStream/stream-chat-swift/assets/10651852/0b0b6bba-30b7-4b41-b8ca-c770121eab1a

Maybe it'll help, I have another bug with db updates on channel list vc. I attach one more video 
https://github.com/GetStream/stream-chat-swift/assets/10651852/80fa44f3-5ba8-4e29-bcd1-d7f7f366b2e0

**Comment by ipavlidakis** [comment]
Hi @Ga77ett 

Can you share with use the following snippets:
- How are you presenting the Channel controller?
- Do you have a subclass of the Channel controller? If yes, please provide us with the code of it.

Kind regards,
Ilias

**Comment by nuno-vieira** [comment]
We are closing this one due to inactivity.

Feel free to re-open if you are still having issues.

Best,
Nuno
