### ISSUE TITLE
Direct message chat made by Android users are showing up as groups in iOS

### ISSUE THREAD

**Issue by arnav-webknot** [GetStream/stream-chat-swift#2801]
## What did you do?
Nothing just opened the chat list

## What did you expect to happen?
Both should show up as direct message.

## What happened instead?
It showed group to me instead of direct message

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by ipavlidakis** [comment]
Hi @arnav-webknot 

Thanks for reaching out. In order to be able to help with the issue you are facing, you will need to provide more info for us:
- The SDK, iOS, Xcode version and device you are seeing the issue on
- A video showing the issue

Kind regards,
Ilias
