### ISSUE TITLE
Filters are not working sometimes. 

### ISSUE THREAD

**Issue by arnav-webknot** [GetStream/stream-chat-swift#2823]
## What did you do?
I have applied following filters:
### Function for fetching the channel
```
func channelListController(withNetworkId networkId: String, withProgramId programID: String) -> ChatChannelListController? {
  guard let id = client.currentUserId else {
      return nil
  }
  
  let filters: [Filter<ChannelListFilterScope>] = [
      .and([
          .equal(.type, to: .messaging),
          .containMembers(userIds: [id]),
          .in(.init(rawValue: "channel_type"), values: ["normal"]),
          .in(.init(rawValue: "programUuid"), values: [programID]),
          .in(.init(rawValue: "networkId"), values: [networkId]),
          .notIn(.init(rawValue: "channel_type"), values: ["program_admin_channel", "program_admin_one_to_one"])
      ])
          
  ]

  let controller = client.channelListController(
      query: .init(
          filter: .and(filters)
      )
  )
  
  return controller
}
```

### Calling this function on the view
```
.onAppear {
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
        guard let newcontroller = StreamChatViewModel.shared.channelListController(withNetworkId: network.id, withProgramId: programID) else {
            self.chatController = nil
            return
        }
        newcontroller.synchronize { error in
            if let error {
                chatErrorString = error.localizedDescription
                chatError = true
            } else {
                self.chatController = newcontroller
            }
        }
    }
}
```
### View for displaying the chat list
```
VStack {
    if let chatController {
        ChatChannelListView(
            viewFactory: DefaultChatsListViewFactory(chatClient: StreamChatViewModel.shared.client),
            channelListController: chatController,
            embedInNavigationView: false
        )
        .id(UUID().uuidString)
    } else {
        Spacer()
        ProgressView()
        Spacer()
    }
}
```

## What did you expect to happen?
Filters to work properly 

## What happened instead?
Filters works sometimes. And the channels with channel_type of program_admin_channel and program_admin_one_to_one are also coming the in controller. 

## GetStream Environment
**GetStream Chat version:*4.0.0*
**GetStream Chat frameworks: *StreamChatSwiftUI*
**iOS version: *iOS 16* (All iOS versions are effected)
**Swift version: *Swift 5.9*
**Xcode version: *Xcode 14*
**Device: *Simulator and on real device*

**Comment by polqf** [comment]
Hi @arnav-webknot 

It seems like `.in(.init(rawValue: "channel_type"), values: ["normal"]),` and `.notIn(.init(rawValue: "channel_type"), values: ["program_admin_channel", "program_admin_one_to_one"])` are clashing.

Could you have a look at it and let us know?

**Comment by Arnav-arw** [comment]
I tried it already. Initially I did .`in(.init(rawValue: "channel_type"), values: ["normal"])`, only but that didnt work so added notIn. But also that didnt work.

**Comment by polqf** [comment]
Have you tried `.equal(.init(rawValue: "channel_type"), to: "normal")`? 
Also, can you share a JSON snippet or a screenshot of the dashboard that shows that you have this property in the channel?

**Comment by arnav-webknot** [comment]
Yep sure here you go:
![image](https://github.com/GetStream/stream-chat-swift/assets/141209044/cbf9d3bc-26a9-436c-8316-5cb4db2fa4e0)
![image](https://github.com/GetStream/stream-chat-swift/assets/141209044/cd5e55c3-2540-4f38-89b3-d3e3003af1b2)

**Comment by arnav-webknot** [comment]
@polqf hey any update?

**Comment by testableapple** [comment]
Hi @Arnav-arw,

Could you let me know which version of StreamChat you use? I see you mentioned `4.0.0`, but back then we did not have auto-filtering.

Best,
Alexey

**Comment by arnav-webknot** [comment]
I am using 4.0.0 only?
<img width="857" alt="image" src="https://github.com/GetStream/stream-chat-swift/assets/141209044/77159666-941c-48c7-8a8e-381a7f7a632f">

**Comment by arnav-webknot** [comment]
Looks like updating to latest 4.39.0 fixed the issue. Earlier I tried updating to the latest branch but it was crashing the app so I went back to 4.0.0.
