### ISSUE TITLE
There is a bug in SwiftyScanner

### ISSUE THREAD

**Issue by behrad-kzm** [GetStream/stream-chat-swift#2825]
## What did you do?
I sent this url as a chat message:
`https://salam.com/khubi?chetori=salam_chetori_khubi`

## What did you expect to happen?
I expect that the url shows exactly the same as we sent via other platforms

## What happened instead?
in ios chat the url will show without underlines:
`https://salam.com/khubi?chetori=salamchetorikhubi`

## GetStream Environment
**GetStream Chat version:** 4.38.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** all
**Swift version:** all
**Xcode version:** all
**Device:** all

## Additional context
I tracked the inputString through out the streamChatUI and found out that in `SwiftyTokeniser` at `line 92` when you set `elementArray = scanner.scan()` it will detect those underlines as `type ElementType.tag` and this will cause the problem.

![Screenshot 2023-10-05 at 12 38 20 AM](https://github.com/GetStream/stream-chat-swift/assets/6783461/55ebd87f-d2d4-4bdc-8688-9caeaf2f94ac)

![Screenshot 2023-10-05 at 12 39 04 AM](https://github.com/GetStream/stream-chat-swift/assets/6783461/8fa2c7fd-dc35-4df5-b720-b0bcca291435)

**Comment by polqf** [comment]
Hi @behrad-kzm,

We are sorry to hear there is this issue in the library. We will have a look as soon as we can.

Thank you!

**Comment by laevandus** [comment]
Hello @behrad-kzm, we have released a new iOS SDK version [4.51.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.51.0) which addresses this issue.
