### ISSUE TITLE
deadlock, related to Authentication Token

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2840]
## What did you do?

hey! this looks like it may be related to https://github.com/GetStream/stream-chat-swift/pull/2827, not totally sure

when foregrounding our app, i see a deadlock between the following 2

<img width="1920" alt="Screenshot 2023-10-11 at 4 29 25 PM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/aca78cb8-a13b-457c-bb7a-ce8a0a10e67e">
<img width="1920" alt="Screenshot 2023-10-11 at 4 29 31 PM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/7377b009-b123-4c40-956e-0096b8feefc2">

one of them looks related to an async operation initiated from `ChatChannelListViewModel` to update the list of channels

the other is from accessing the currentUserId when rendering a list item

## What did you expect to happen?

no deadlock

## What happened instead?

deadlock

## GetStream Environment
**GetStream Chat version:** 4.39

# Additional context

let me know if i can provide any other information to help you debug this

**Comment by polqf** [comment]
Hi @AndrewSB,

Thanks for the report. I was able to reproduce it on my side, and created a PR to fix it.
Will let you know when it gets released.

**Comment by AndrewSB** [comment]
thanks @polqf, could we do a release soon? currently, every time we background the app while looking at a stream view we're getting a deadlock which requires restarting the app

**Comment by polqf** [comment]
Hi @AndrewSB , our next release is planned to be around mid next week. You are safe to use `develop` until then, as it only contains this fix, and a small improvement on the preview of the messages for the channel list
