### ISSUE TITLE
Unread badge does not clear when no connection

### ISSUE THREAD

**Issue by chan-reclip** [GetStream/stream-chat-swift#2873]
## What did you do?

Enter a chat screen and read a new message and then exit to the chat threads view while there's no connection.

## What did you expect to happen?

I want to see the unread badge cleared regardless of connection.

## What happened instead?

The unread badge does not clear.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat: 4.40.0, StreamChatUI: 4.40.0
**iOS version:**  17.0.3
**Swift version:**
**Xcode version:** 15.0.1
**Device:** iPhone 12 mini

## Additional context

See this video clip for repro where I simulated no connection by enabling the airplane mode.

https://github.com/GetStream/stream-chat-swift/assets/128518318/2692a637-64fc-4775-b443-f4e670484c83

**Comment by ipavlidakis** [comment]
Hi Chan,

Thank you for reporting this issue with us. Unfortunately, the `markRead` operation is an `online operation` in order to avoid inconsistencies between devices.

Kind regards,
Ilias

**Comment by chan-reclip** [comment]
@ipavlidakis Hi Ilias, I think I understood your point about avoiding inconsistencies between devices which makes a sense in a way.
However, I think the decision is a bit unfortunate because for some use cases (actually, I assume this is the majority) there aren't other devices to synchronize. In our case, we only support mobile devices and most of the users use only one mobile device for our app. On top of that, not clearing the unread badge when they surely read the new chat certainly feels like a bug.
Is there any chance you would make `markRead` while offline configurable?

**Comment by ipavlidakis** [comment]
Hey Chan, 

In order to support you on this one, I'm going to mark it as a feature request and raise it with the Product team here at Stream. Once there is an update you will receive and update.

Kind regards,
Ilias
