### ISSUE TITLE
Can't reconnect if internet connection of device change

### ISSUE THREAD

**Issue by koishi** [GetStream/stream-chat-swift#289]
## What did you do?
I am connected to the Stream while I am connected to Wi-Fi.
I got a list of channels and am now ready to chat.
Disable Wi-Fi here and change to a mobile connection.

## What did you expect to happen?
Chat will no longer work.
ChatViewController doesn't show the previous chats. Nothing is displayed.
The same goes for reappearing the chat from the channel list.

If switch internet connection back to Wi-Fi, will be reconnected.

The same issue can be seen when launching the app on a mobile connection and changing the internet connection to Wi-Fi.

## What happened instead?
The fact that I can chat no matter what internet connection I'm using.

## GetStream Environment
**GetStream Chat version:** 2.2.0, 2.2.1
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.4.1
**Swift version:** 5
**Xcode version:** 11.4.1
**Device:** iPhone 11 Pro, iOS Simulator

## Additional context
none

**Comment by b-onc** [comment]
Hello @koishi , 
Thanks for the bug report. I can reproduce the bug.
The PR #284 resolves the issue, however. We'll release it in 2.2.3 this week or early next week.

**Comment by b-onc** [comment]
Closed via #284
