### ISSUE TITLE
jumpToUnreadMessagesButton does not work

### ISSUE THREAD

**Issue by virbedi** [GetStream/stream-chat-swift#2896]
## What did you do?
Clicked on `jumpToUnreadMessagesButton` and `jumpToUnreadMessagesButton.closeButton` in a conversation with lots of unread messages.

## What did you expect to happen?
Expected to scroll to the topmost unread message when clicking on `jumpToUnreadMessagesButton` 
Expected to clear unread messages when clicking on `jumpToUnreadMessagesButton.closeButton`

## What happened instead?
Nothing

## GetStream Environment
**GetStream Chat version:** 4.42.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.0.1
**Swift version:** 5
**Xcode version:**15.0.1
**Device:** iPhone 15 and iPhone SE Simulator 

## Additional context

We have a heavily skinned version of StreamChatUI within our application and while trying to implement the Jump to Unread functionality, I noticed that it does not work as expected when clicking on the button (Nothing happens)

To confirm, I reproduced this issue on the demo app where neither the button nor the closeButton to clear the unread indicator worked. (Video attached below) 

Due to the scope of these components, we aren't able to override them in a subclass to fix this either. 

https://github.com/GetStream/stream-chat-swift/assets/43729852/1c5d1857-b0ed-4bb8-9b64-be6d843d1514

**Comment by virbedi** [comment]
I was able to fix this by editing the line in `ChatMessageListVC`
Old
`jumpToUnreadMessagesButton.addTarget(self, action: #selector(jumpToUnreadMessages))`
New
`jumpToUnreadMessagesButton.addTarget(self, action: #selector(jumpToUnreadMessages), for: .touchUpInside)`

**Comment by nuno-vieira** [comment]
Hi @virbedi,

We are aware of this; this will be added in the 4.43.0 release.

A PR is open already: https://github.com/GetStream/stream-chat-swift/pull/2894

Best,
Nuno

**Comment by virbedi** [comment]
Thanks @nuno-vieira!
