### ISSUE TITLE
Feature request: Filter for messages

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#29]
I'm using GetStream for chat with customer service. I need to support messages visible only to the customer service agent on web but invisible to the user on ios (like internal messages from other services). I tried writing code like this:
```
    override func messageCell(at indexPath: IndexPath, message: Message, readUsers: [StreamChatCore.User]) -> UITableViewCell {
        let attachment = message.attachments.first(where: { $0.extraData?.data is ExtraAttachmentData })
        if attachment?.type == AttachmentType.custom(type: "notification"), let notification = (attachment?.extraData?.data as? ExtraAttachmentData)?.data {
            if notification.isHidden {
                return tableView.dequeueReusableCell(withType: ChatHiddenCell.self, for: indexPath)
            } else {
                let cell = tableView.dequeueReusableCell(withType: ChatNotificationCell.self, for: indexPath)
                cell.setup(notification: notification)
                return cell
            }
        }
        return super.messageCell(at: indexPath, message: message, readUsers: readUsers)
    }
```
`ChatHiddenCell` is just UITableViewCell with height 0, `ChatNotificationCell` is my custom cell for notifications presented to the user.
However there will be a problem with date cells showing above invisible messages.
Would it be possible to add `filter` to `ChannelPresenter` or `ChatViewController` so GetStream can ignore some messages and never add them to `var items: [StreamChatCore.ChatItem]`?

**Comment by buh** [comment]
Hi @mpodeszwa 
Did you try to setup `ChannelPresenter` with `showStatuses: false`?
Here is init:
```
public init(channel: Channel, parentMessage: Message? = nil, queryOptions: QueryOptions = .all, showStatuses: Bool = true)
```

**Comment by mpodeszwa** [comment]
I could, but then user will never see date and it won't be clear when message was sent :/

**Comment by mpodeszwa** [comment]
As alternative, would it be possible to show date + time for every message (instead of relative date for last message)? It's also an option for us :)

**Comment by buh** [comment]
Do you mean to show a date in a message cell?

**Comment by buh** [comment]
It's already there with name and avatar. Can you share your design to understand clearly how it should look like?

**Comment by mpodeszwa** [comment]
![with status](https://user-images.githubusercontent.com/7826664/66133491-0da34f00-e5f7-11e9-8565-19e18de6535f.png)
so when statuses are enabled I can see date under `sdf` and `sdfh2` 😄 
![without status](https://user-images.githubusercontent.com/7826664/66133570-2f9cd180-e5f7-11e9-8adc-4ab37b4c6adc.png)
without status I lose information when `sdf` was sent.
Can I enable dates for all messages, not only last one in series of messages from one person?

**Comment by buh** [comment]
I see. I'll think about that.

**Comment by buh** [comment]
@mpodeszwa Hey do you still need this feature?

**Comment by mpodeszwa** [comment]
Hey @buh , not really. We solved this issue different way :)

**Comment by buh** [comment]
@mpodeszwa  Nice!
But anyway I added some feature to add additional date for messages. It will be in the next release.
So, basically you can specify a time threshold to trigger to add time for a message.
Additionally it has 2 styles: just keep user name and avatar with an additional date or add a time near a message.

Here are screenshots:

## Style1

![Style 1](https://raw.githubusercontent.com/GetStream/stream-chat-swift/master/docs/images/additionalDate1.jpg)

## Style2

![Style 2](https://raw.githubusercontent.com/GetStream/stream-chat-swift/master/docs/images/additionalDate2.jpg)
