### ISSUE TITLE
Allow custom font usage with default markdown library

### ISSUE THREAD

**Issue by dimarig** [GetStream/stream-chat-swift#2908]
Hey GetStream Team!
## What are you trying to achieve?
Our team trying to implement markdown in chat with our own font, but `DefaultMarkdownFormatter.Attributes.Code` and `SwiftyMarkdown` library are closed by internal access modifier

## If possible, how can you achieve this currently?
The only option is to add same or another markdown SDK to our project and override `format(_ string: String)` with same implementation, but different font

## What would be the better way?
In my honest opinion, best way is to make them public. Or create a new way to configure Markdown usage.  

## GetStream Environment
**GetStream Chat version:4.41.0**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:14+**
**Swift version:5.9**
**Xcode version:15.x**
**Device:Any**

Thanks!

**Comment by polqf** [comment]
Hi @dimarig,
We'll discuss it internally and come back to you. Sorry for the inconvenience!

**Comment by laevandus** [comment]
Hello @dimarig, we have released version [4.51.0 ](https://github.com/GetStream/stream-chat-swift/releases/tag/4.51.0)which addresses this request. Please refer to `Appearance.default.formatters.markdownFormatter`.
