### ISSUE TITLE
[CIS-172] Reaction Pagination

### ISSUE THREAD

**Issue by hashlin** [GetStream/stream-chat-swift#292]
## What are you trying to achieve?
I want to query reactions given to a message.

## If possible, how can you achieve this currently?
According to doc, swift client SDK doesn't support it. https://getstream.io/chat/docs/send_reaction/?language=swift#paginating-reactions

## What would be the better way?
It is an important API that should be in SDK.

## GetStream Environment
**GetStream Chat version:** 2.2.1
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore
**iOS version:** 13.4.1
**Swift version:** 5.0
**Xcode version:** 11.5
**Device:** Every devices

**Comment by b-onc** [comment]
Hello @hashlin ,
Thanks for the feature request. We've added this to our backlog and will add this in the upcoming releases.

**Comment by hashlin** [comment]
Is there any workaround while GetStream SDK is working in progress? @b-onc

**Comment by VojtaStavik** [comment]
I'm closing this issue because we're approaching the `3.2` release which will contain a completely new set of fully customizable UI components. Reactions pagination is a feature scheduled for this Q.
