### ISSUE TITLE
Notification not Receiving Sometimes 

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swift#2921]
## What did you do?
I have configured Push Notifications into an IOS app couple of months ago. At that time notifications works fine. Now sometimes I did not receive notifications. Many users also reported that issue. What could be the issue?

Also Stream dashboard did not show logs when notification not received. Yesterday I received messages but receive only notification of one message and did not see any logs on the Stream Dashboard.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by Zee-93** [comment]
<img width="285" alt="Screenshot 2023-12-07 at 7 02 37 AM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/c3057b4a-6014-4368-a342-06729c893798">

**Comment by testableapple** [comment]
Hi @Zee-93 ,

Is there a reason you leverage `StreamChatSwiftUI` from `main` and `StreamChat` from `4.28.0`? Ideally, both `StreamChatSwiftUI` and `StreamChat` should be on the same version. Please follow the [installation guide](https://getstream.io/tutorials/ios-chat/#installation), and, if possible, try to bump the version to our latest release [4.44.0](https://github.com/GetStream/stream-chat-swiftui/releases/tag/4.44.0).

Regarding push notifications, they should be configured on the app's side. The SDK should not affect that. Please check out our [docs](https://getstream.io/chat/docs/sdk/ios/client/push-notifications/) for more details. Hope this helps.

Best,
Alexey

**Comment by Zee-93** [comment]
Hi @testableapple thanks for you response. 

I am registering the device like this for Push Notification

**Connect User**
```Swift
func connectUser(onComplete: (()->())? = nil) {
        chatClient.connectUser(
            userInfo: .init(
                id: userAuthanticationManager.supportUserId!,
                name: userAuthanticationManager.username),
            token: try! Token(rawValue: userAuthanticationManager.supportToken!)
        ) { error in
            if let error = error {
                print("failed to connect the user with stream \(error)")
            } else {
                logger.info("user connected with the stream sdk", category: .chat)
                self.registerForPushNotifications()
            }
            onComplete?()
        }
    }
```

**Register For Push Notification**
```Swift
func registerForPushNotifications() {
        UNUserNotificationCenter.current()
            .requestAuthorization(options: [.alert, .sound, .badge]) { granted, error in
                guard granted else { return }
                DispatchQueue.main.async {
                    UIApplication.shared.registerForRemoteNotifications()
                }
            }
    }
```

**Add Device**
```Swift
func application(
        _ application: UIApplication,
        didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
    ) {
        guard chatClient.currentUserId != nil else {
            logger.debug("Cannot add the device without connecting as user first, did you call connectUser", category: .chat)
            return
        }
        
        chatClient.currentUserController().addDevice(.apn(token: deviceToken, providerName: "DJChatAPNPush")) { error in
            if let error = error {
                logger.debug("adding a device failed with an error \(error)", category: .chat)
            }else{
                logger.info("Successfully added device on stream chat.", category: .chat)
            }
        }
    }
```

**Remove Device on Logout**
We are removing the device when user logout from the app. We are saving `deviceId` into the UserDefaults and fetching the `deviceId` from UserDefaults for removing the device.
```Swift
    func removeDevice(){
        guard let deviceId else { return }
        
        chatClient.currentUserController().removeDevice(id: deviceId) { error in
            if let error = error {
                logger.error("removing the device failed with an error \(error)", category: .session)
            }
            logger.info("Successfully removed device", category: .session)
        }
    }
```

So where we are making the mistake? I think we are doing this correctly. 

Also we have configured the `UNUserNotificationCenterDelegate` correctly and it's working fine when we receive the notification. Sometimes we don't receiving the Push Notification. 

I guess sometimes Stream unable to send the Push Notifications may be.

We need your help because it is very critical issue in terms of our clients and users.

**Comment by testableapple** [comment]
Hmm, but StreamChat SDK does not send push notifications, it's done by your service provider (Apple, Firebase or something else that you might leverage).

Above I also mentioned the SDK version. This is quite unusual to use different versions of the UI and LLC SDKs and I guess this might cause some issues. Can you align the SDK versions please and let us know if this helps?

**Comment by Zee-93** [comment]
@testableapple I have updated the SDK to the latest release but issue still exist. What could be the problem?

**Comment by testableapple** [comment]
Hi @Zee-93, I see you pass `providerName` argument, so I assume you are leveraging [Multi-Bundle configuration](https://getstream.io/chat/docs/sdk/ios/client/push-notifications/#leveraging-multi-bundle-configuration), aren't you?:

```swift
chatClient.currentUserController().addDevice(.apn(token: deviceToken, providerName: "DJChatAPNPush"))
```

Do you use the different `apiKey`s for these bundles or the same one?

**Comment by testableapple** [comment]
Also, when push notifications do not pass through, do you see in the logs?:
-  "adding a device failed with an error \(error)"
- or "Successfully added device on stream chat."

**Comment by Zee-93** [comment]
Device adding successfully

**Comment by Zee-93** [comment]
@testableapple  have a look. Our following user is getting mostly that notification issue. 

When I try to send the test notification to that user then getting that error. This user is exists in our dashboard users.

<img width="721" alt="Screenshot 2023-12-15 at 11 58 00 AM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/70a61d15-a836-40c9-b201-956da663be0a">

**Comment by Zee-93** [comment]
@testableapple Do you read my last comment?
