### ISSUE TITLE
Xcode 15 Linker Warnings

### ISSUE THREAD

**Issue by steve-checkatrade** [GetStream/stream-chat-swift#2936]
## What did you do?
Integrated StreamChat and StreamChatUI (4.44.0) via prebuilt binaries using Carthage.

## What did you expect to happen?
Frameworks to link to project without warnings.

## What happened instead?
Warnings appeared in build log about duplicate linker paths:
<img width="397" alt="Screenshot 2023-12-14 at 08 36 21" src="https://github.com/GetStream/stream-chat-swift/assets/152978836/79ef71ff-3fd5-4214-9313-526b867a956f">

## GetStream Environment
**GetStream Chat version:** 4.44.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.0
**Swift version:** 5.9
**Xcode version:** 15.0.1
**Device:** iOS Simulator

## Additional context
There is more information available about this issue here: https://indiestack.com/2023/10/xcode-15-duplicate-library-linker-warnings/

The `otool -arch arm64 -l` output for StreamChat shows:
```
Load command 49
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 50
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
Load command 51
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 52
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
```

The same command for StreamChatUI also gives:
```
Load command 49
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 50
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
Load command 51
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/Frameworks (offset 12)
Load command 52
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/Frameworks (offset 12)
```

**Comment by nuno-vieira** [comment]
Hi @steve-checkatrade,

This feels like it is an Xcode bug, at least looking into this thread: https://developer.apple.com/forums/thread/733317

For now, adding the `ld_classic` to `Other Link Flags` fixes the warning. But I would recommend having the warning if your project compiles fine. Most likely the warning will go away in future Xcode releases.

If you are still seeing issues or have any other idea on how to fix, please feel free to re-open the issue.

Best,
Nuno

**Comment by nuno-vieira** [comment]
I've re-opened the issue because this should actually be an easy fix. Even tho, most likely newer Xcode versions will have optimisations for this 👍

**Comment by nuno-vieira** [comment]
@steve-checkatrade We have a fix available already here: https://github.com/GetStream/stream-chat-swift/pull/2937

Either way, which Xcode version are you using? We have some reports that Xcode 15.1 has fixed this issue automatically already. 

Best,
Nuno

**Comment by nuno-vieira** [comment]
I'm closing this one, this will be available on the next release 👍 

Best,
Nuno
