### ISSUE TITLE
Push Notification Issue

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swift#2944]
## What did you do?

Our following user is not getting push notifications most of the time. If I try to send the test notification from dashboard then getting following error.

<img width="715" alt="Screenshot 2023-12-20 at 6 02 01 AM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/28f582f9-1920-4a87-9389-56946e1a6eb2">

I have already created issue related to Push Notifications and that issue closed now but I re-comment on that issue but no one replied on that, thats why I am creating new issue.

https://github.com/GetStream/stream-chat-swift/issues/2921

## GetStream Environment
**GetStream Chat version:** 4.44.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI 
**iOS version:** 
**Swift version:**
**Xcode version:**
**Device:**

**Comment by martinmitrevski** [comment]
Hi @Zee-93,

The issue reporting on GitHub is for reporting bugs in the SDK. The push notification setup is something that is handled on your side. Our dashboard and push mechanism are reliably used by many of our customers, so it's most likely an issue on your side. 

Unfortunately, the engineering team here on GitHub can't provide debugging services to everyone. Any questions and support which are not directly reporting a clear bug in the SDK (with reproduction steps), will not be handled here.

Feel free to reach to our support instead: https://getstream.io/contact/support/, and based on your plan, your request will be prioritised accordingly.

Best, Martin
