### ISSUE TITLE
Editing a channel's members doesn't seem to work

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2973]
## What did you do?

hey! i'm using the `ChatChannelController.updateChannel(:)` API to try to edit the members of a group. here's an example:

```swift
let members = Set(newMembers).union(Set([currentUserId].compactMap { $0 }))
viewModel.channelController.updateChannel(name: newTitle, imageURL: nil, team: nil, members: members, completion: { error in ... })
```

## What did you expect to happen?

i expect both the name and members to be updated to the values passed in the API call

## What happened instead?

the name does update, but the members don't change. no error from the API

i see that the API request to `.updateChannel` comes back with a 201.

i've also gone into the roles and permission dashboard to make sure that it isn't a permissions issue. i made sure to add the UpdateChannel and UpdateChannelMembers permissions (but also, i assume that i'd get a 4xx response, not a 201 if the permissions were wrong

<img width="1367" alt="Screenshot 2024-01-17 at 1 38 08 PM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/eceda50d-9ef1-4a0b-8a09-3414233ae058">

## GetStream Environment
**GetStream Chat version:** 4.47.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by nuno-vieira** [comment]
Hi @AndrewSB,

Yes, it seems like it is a backend issue in this case. We recommend creating a ticket on support so that the backend team can handle it as soon as possible. 

Best,
Nuno
