### ISSUE TITLE
Still seeing #2840

### ISSUE THREAD

**Issue by AndrewSB** [GetStream/stream-chat-swift#2974]
hey! i was looking at our error rates and metrics, and i see that this AuthenticationRepository deadlock is still occurring. i don't have an easy repro like in #2840, but the trace goes back to that barrier operation for getting the auth token

are you seeing this too? can we get to the bottom of the error?

<img width="1144" alt="Screenshot 2024-01-16 at 9 49 00 AM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/e46cbcc7-7568-4e51-bd4c-5d88d88d7127">

**Comment by AndrewSB** [comment]
we were using `develop` of stream-chat-swift, i've just changed to using 4.47.0, so i can also report back in about a week to say whether it was just a versioning thing

**Comment by testableapple** [comment]
Hi @AndrewSB, unfortunately, we do not see this on our side, nor getting any other complaints about the AuthenticationRepository deadlock. Please do let us know if you'll find out that it was just a versioning thing.

Best,
Alexey

**Comment by nuno-vieira** [comment]
Hi @AndrewSB, how do you know it is a deadlock based on the error? 🤔 From the image above, it Timout Error just means that the request timed out. It could be just a bad network from the user etc..

**Comment by AndrewSB** [comment]
at the bottom of the screenshot above, i highlighted the error message. you can see mentions AuthenticationRepository:266 as the source of the error.

looking at that file, it looks like that WaiterTimeout comes from your auth repository failing to get an auth token:

<img width="1260" alt="Screenshot 2024-01-18 at 8 48 13 AM" src="https://github.com/GetStream/stream-chat-swift/assets/3814772/1b2ae189-7473-4dd9-8bf4-f7d574ec9b09">

does that all seem right? if so, i'll dig a little deeper and see if i can spot anything else for you

**Comment by nuno-vieira** [comment]
Hi @AndrewSB , yes that is fine, some requests can timeout. Before, while timing out, they were deadlocking. That was a problem, but it should not happen anymore. 

Feel free to re-open the issue if you can reproduce the timeout error and deadlock again 👍
