### ISSUE TITLE
Whole interface blocked when swipe photo in fullscreen mode

### ISSUE THREAD

**Issue by gellertk** [GetStream/stream-chat-swift#2975]
## What did you do?
Make smalls swipes to top

## What did you expect to happen?
Photo will correctly dismiss or left on screen

## What happened instead?
Whole interface blocked

## GetStream Environment
**GetStream Chat version:**
4.47.0 (all version)
**GetStream Chat frameworks:** StreamChat, StreamChatUI

**iOS version:**
16.4 (all version)
**Swift version:**
5 (all version)
**Xcode version:**
15.1 (all version)
**Device:**
iPhone 12 (all phones)

## Additional context

https://github.com/GetStream/stream-chat-swift/assets/54902273/129e5417-b6f4-4f9f-8dd8-cdfc36a6c977

**Comment by testableapple** [comment]
Hi @gellertk,

This fix has been shipped as part of [4.49.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.49.0) 👍

Best,
Alexey
