### ISSUE TITLE
Showing Translated Message After Delete The Message

### ISSUE THREAD

**Issue by ikaru19** [GetStream/stream-chat-swift#2983]
## What did you do?
I just translate the message to turkish, and then i delete the message.

go to chat -> Translate to (via action view) -> delete the message

## What did you expect to happen?
Showing the text "Message Deleted" like the untranslated message

## What happened instead?
Showing the translated text with grey text and don't have any action

## GetStream Environment
**GetStream Chat version:*4.47.0*
**GetStream Chat frameworks:** StreamChatUI
**iOS version:*17.2*
**Swift version:*5.9.2*
**Xcode version:*15.2*
**Device:*Simulator Iphone 15*
![Simulator Screenshot - iPhone 15 - 2024-01-25 at 00 53 33](https://github.com/GetStream/stream-chat-swift/assets/14922009/f9d306c1-3e10-4ba6-bff8-4b1625448a98)

**Comment by ipavlidakis** [comment]
Hi @ikaru19,

Thanks for reporting the issue with us. We are aware of the problem and currently have it in our backlog to fix. Once we have a plan or some progress, we will update you here. 

Thanks,
Ilias
