### ISSUE TITLE
Does ChatChannelController.loadPreviousMessages has a maximum pageSize?

### ISSUE THREAD

**Issue by mschuetz-viz** [GetStream/stream-chat-swift#2995]
## What did you do?
Initialise a channel controller with a initial page size of `25`, than called `loadPreviousMessages` with a page size of `1000`. The channel has `997` messages in it.

## What did you expect to happen?
I'd expect the channel controller to load all messages of the channel, or, `hasLoadedAllPreviousMessages` to return `false` if there's a maximum for the page size.

## What happened instead?
In the callback of `loadPreviousMessages` I verify with `controller.messages.count` is 325, not the expected `997`, and that `hasLoadedAllPreviousMessages` returns `true`.

PS: it seems that I can iteratively page through the whole conversation using a pageSize of 25.

## GetStream Environment
**GetStream Chat version:** 4.42.0 & 4.47.1
**GetStream Chat frameworks:** StreamChat
**iOS version:** 17.0
**Swift version:** 5.9
**Xcode version:** 15.2
**Device:** iPhone 14

**Comment by nuno-vieira** [comment]
Hi @mschuetz-viz, yes correct, the page size limit is 300. So you should use a value lower than that. It is mentioned in the docs for other endpoints, but not for messages actually. We will make sure to update this 👍 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Actually it is kinda hidden here: https://getstream.io/chat/docs/javascript/channel_pagination/

**Comment by nuno-vieira** [comment]
@mschuetz-viz, not because the way `hasLoadedAllPreviousMessages` is calculated is with `messages.count < pageSize`, that is why it returns true. The message count will be 300 and the pageSize will be 1000
