### ISSUE TITLE
Using ChatViewController second time doesn't work

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#3]
## What did you do?

I created ChatViewController using code:
```
channelPresenter = ChannelPresenter(channel: channel)
channelPresenter?.reload()
```
Chat is being presented to the user after logging in to the application. When user enters the app chat is working properly. However, when he logs out and logs back in (to the same account or a different one) chat is not loading.

## What did you expect to happen?

Chat is working every time.

## What happened instead?

Second ChatViewController never gets refreshed

## GetStream Environment
**GetStream Chat version:** 1.2.5
**iOS version:** 12.4
**Swift version:** 5.0.1
**Xcode version:** 10.3
**Device:** iPhone Xs

## Additional context

There are some logs.

First time ChatViewController is created:
```
📱  App state active
🕸  Available 🙋‍♂️
🐴 [27/08/2019 11:36:58.812] 🎫 Skip read.
🦄 [27/08/2019 11:36:59.075] ❤️ Connecting...
🦄 [27/08/2019 11:36:59.075] ➡️ GET wss://chat-us-east-1.stream-io-api.com/connect?......&stream-auth-type=jwt
🦄 [27/08/2019 11:36:59.076] Request headers:
◾️ Origin = wss://chat-us-east-1.stream-io-api.com

🦄 [27/08/2019 11:37:00.342] WebSocket connected. Waiting for the first health check message...
🦄 [27/08/2019 11:37:00.402] 📦 {
  "created_at" : "2019-08-27T09:37:00.28453431Z",
  ....
}
🦄 [27/08/2019 11:37:00.405] 🥰 Connected

.... more responses
```

Logging out:
```
🦄 [27/08/2019 11:37:06.995] 💔 Disconnected deliberately
```

Logging back in to the same account (same channel id, different instances of ChatViewController and ChatPresenter):
```
📱  App state active
🕸  Available 🙋‍♂️
🐴 [27/08/2019 11:37:19.012] 🎫 Skip read.
🦄 [27/08/2019 11:37:19.018] ❤️ Connecting...
🦄 [27/08/2019 11:37:19.019] ➡️ GET wss://chat-us-east-1.stream-io-api.com/connect?....&stream-auth-type=jwt
🦄 [27/08/2019 11:37:19.019] Request headers:
◾️ Origin = wss://chat-us-east-1.stream-io-api.com

🐴 [27/08/2019 11:37:19.059] 🎫 Skip read.
```

## Additional info:
There are no memory leaks, however I can see instances of following types still existing after logging out:
```
Client
ClientURLSessionTaskDelegate
InternetConnection
WebSocket
```

**Comment by buh** [comment]
@mpodeszwa thanks for the reporting. I'll check your logout/login issue. For now the Client is used as a shared instance and it will be in memory after logout. It holds web socket and other needed objects.

**Comment by buh** [comment]
@mpodeszwa I've tested logout and login in the example project and it works without any issues. How are you doing logout? Could you send me all logs?

**Comment by tbarbugli** [comment]
why was this closed?

**Comment by buh** [comment]
@mpodeszwa Please, check a new version 1.2.6

**Comment by mpodeszwa** [comment]
@buh Thanks, it's now working as expected 👍
