### ISSUE TITLE
Slack-style reactions

### ISSUE THREAD

**Issue by borut-t** [GetStream/stream-chat-swift#3001]
## What are you trying to achieve?
I want to implement reactions similar to how Slack is having them. Each reaction emoji can have multiple reactions (+2, +20, etc).

Currently I'm doing that:
1) adding a reaction for emoji that doesn't exist yet
- add reaction with type as hash of emoji unicode value
- add extraData with the author and emoji unicode value
2) adding a reaction for emoji that exists
- remove existing reaction
- add new as above

The issue with this approach is that one user cannot delete reactions from other users.

## If possible, how can you achieve this currently?
Cannot, since I'm blocked currently with the latestReactions limit. Which returns only the last 10 reactions.

## What would be the better way?
Not sure tbh. Can you please advise how to built emoji reactions Slack style?

## GetStream Environment
**GetStream Chat version:** latest
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.x
**Swift version:** 5.9
**Xcode version:** 15.x
**Device:** iOS

**Comment by nuno-vieira** [comment]
Hi @borut-t,

We have an example of Slack Reactions in our Slack Demo App. Here is an example: https://github.com/GetStream/stream-chat-swift/blob/develop/Examples/SlackClone/SlackReactionsView.swift,

In order to load all reactions you will need to use the `ChatMessageController.loadReactions` and `ChatMessageController.loadNextReactions` for that 

Thanks,
Nuno

**Comment by nuno-vieira** [comment]
I'm closing this one for now. Feel free to re-open the issue if you are still having troubles.

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @borut-t, each message has `reactionScores` and `reactionCounts` which might be enough for you. But if you want to have the full details of the reactions, like for example the author, you will need to use `loadReactions` and `loadNextReactions`. Usually `reactionScores` and `reactionCounts` is enough to display the data in the message list. But if you want the full details, usually you tap on the reactions and it opens a detail view containing all info of the reaction, like the author etc...

**Comment by borut-t** [comment]
Hi @nuno-vieira. Thanks for the feedback!

The thing is that you have a limitation of 30 characters for the `MessageReactionType` rawValue. And this blocks me from storing emoji names since the length can easily surpass this limitation. I cannot store the unicode value either since no special characters are allowed.

```swift
let emoji = 😅
let emojiUnicode = "\u{0001F605}"
let emojiName = "SMILING FACE WITH OPEN MOUTH AND COLD SWEAT"
```

I have tried with a hashing function but with this approach using `reactionsScores` I don't have access to the `extraData`.

What would you suggest in this case?

**Comment by nuno-vieira** [comment]
Hi @borut-t, I think for now your only option might be using the code inside `\u{XXXXXX}`, and then in your application, you wrap it with `\u{}`. If that is not enough for you for some reason, you might need to open a ticket on support to request this change in the backend. 

Best,
Nuno

**Comment by borut-t** [comment]
I've managed to make this work exactly like that. Now everything works. One issue is still not solvable with this approach and that is the sorting. We are now sorting based on the ChatReactionType. Not optimal, but not a big issue.
Thanks @nuno-vieira for all your help 🙌

**Comment by nuno-vieira** [comment]
No problem @borut-t 👍
