### ISSUE TITLE
Missing super.init in AsyncOperation

### ISSUE THREAD

**Issue by dongfanger2018** [GetStream/stream-chat-swift#3045]
## What did you do?
i don't know whether is's a bug or not
it seems you missing call super.init() in AsyncOperation

## What did you expect to happen?
add super.init

## What happened instead?
don't know

## GetStream Environment
**GetStream Chat version:*4.46.0*
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
AsyncOperation is a subclass of nsobject, you should call super.init

![image](https://github.com/GetStream/stream-chat-swift/assets/153170234/97f08b1b-d777-49b0-a8ea-966ea6ab06be)

**Comment by nuno-vieira** [comment]
Hello,

This is not bug. Calling super.init in this case has no impact. 

Best,
Nuno

**Comment by nuno-vieira** [comment]
Hi @dongfanger2018,

Update: We are going to change this either way. Even tho it should have no impact, the docs say that it is recommended to call super.init in NSOperations, here: https://developer.apple.com/documentation/foundation/nsoperation/1808546-init

So we will update it anyways 👍 

Best,
Nuno
