### ISSUE TITLE
Error "'shared' is unavailable in application extensions for iOS..." when using UNNotificationServiceExtension

### ISSUE THREAD

**Issue by kirsanov-dev** [GetStream/stream-chat-swift#3048]
Please, recommend how to solve this issue. I assume it should be solved on our side, but maybe you've helped your customers to solve it before.

## What did you do?
Created a NotificationService which inherits to UNNotificationServiceExtension in order to customize push notifications from Stream SDK. According to the example in the documentation added `import StreamChat` to get access to some Stream objects inside `didReceive` method.

## What did you expect to happen?
No errors when building a project with UNNotificationServiceExtension and imported StreamChat.

## What happened instead?
The error "'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead." for different code inside StreamChatSwiftUI source code where UIApplication object is used, for example (see 1st comment below).

## GetStream Environment
**GetStream Chat version: 4.48.0**
**GetStream Chat frameworks: StreamChat, StreamChatUI**
**iOS version: 13.6.3**
**Swift version: 5.8.1**
**Xcode version: 14.3.1**
**Device: MacBook Air M1 2020, project is built on simulator iPhone 14, iOS v. 17.2**

## Additional context
<img width="475" alt="Screenshot at Feb 27 22-53-16" src="https://github.com/GetStream/stream-chat-swift/assets/80982911/21679362-4241-48ee-8c9a-44074e1bb34e">

**Comment by kirsanov-dev** [comment]
<img width="475" alt="Screenshot at Feb 27 22-53-16" src="https://github.com/GetStream/stream-chat-swift/assets/80982911/21679362-4241-48ee-8c9a-44074e1bb34e">

**Comment by nuno-vieira** [comment]
Hi @kirsanov-dev,

That can't belong to the NSE Compilation Target, most likely. If you still want it, you need to extract the view from `UIApplication.shared` into a reference in `ShareActivityView`, like `var someView: UIView`, and you only set this property when initialising the `ShareActivityView`.

Closing this one since it is not a SDK issue.

Best,
Nuno
