### ISSUE TITLE
Message author miscomputed after user id change during the same session

### ISSUE THREAD

**Issue by combef-luna** [GetStream/stream-chat-swift#3084]
## What did you do?
On the same session I start by calling `chatClient.connectUser(...)` to connect stream chat to my user. Then I delete my account which triggers `chatClient.connectionController().disconnect()`. Then I create a new account with a new user id and call again chatClient.connectUser(...)`. I send a message in a conversation that is created on user creation by my server.

I checked on the dashboard the user id is correct.

## What did you expect to happen?
The message I send should be on the right side of the `MessageListView` with the current user colors.

## What happened instead?
It is displayed as an other user message on the left side with the profile image.

## GetStream Environment
**GetStream Chat version:** 4.49.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatSwiftUI
**iOS version:** 17.3
**Swift version:** 5.10
**Xcode version:** 15.3
**Device:** iPhone 12 mini, 15 Pro, ... seems to be on every iPhone

**Comment by combef-luna** [comment]
Hello @nuno-vieira,
Thanks for the quick answer. I am confused because I followed this doc: https://getstream.io/chat/docs/ios-swift/logout/?language=swift and it says to only use `disconnectUser`

**Comment by nuno-vieira** [comment]
I see @combef-luna,

That doc is outdated. Sorry! We will make sure we update this.

Thank you!
