### ISSUE TITLE
Upload Image to GetStream CDN

### ISSUE THREAD

**Issue by ikaru19** [GetStream/stream-chat-swift#3098]
## What are you trying to achieve?
I'm asking is possible to uploading image to GetStream CDN without sending a message?
I want to store avatar image on GetStream CDN since i don't have my own server. Thanks!

## GetStream Environment
**GetStream Chat version:4.47.0
GetStream Chat frameworks: StreamChatUI
**iOS version:17.2
**Swift version:5.9.2
**Xcode version:15.2
**Device:Simulator Iphone 15

**Comment by nuno-vieira** [comment]
Hi @ikaru19,

Yes that is possible, you can do it with `ChatChannelController.uploadAttachment()`

Best,
Nuno
