### ISSUE TITLE
Push Notifications not working with iOS 13

### ISSUE THREAD

**Issue by jbcaveman** [GetStream/stream-chat-swift#31]
## What did you do?
Sent messages to an iOS 13 device

## What did you expect to happen?
Receive a push notification and for channelsViewController to update the channel cells with the latest messages 

## What happened instead?
No push notification in or out of the app, and channelsViewController stays stale with old messages until you restart the app

## GetStream Environment
**GetStream Chat version:** stream-chat v1.1.4, StreamChatCore v1.3.20
**iOS version:** 13.1.2
**Swift version:** 5 
**Xcode version:** 11.0
**Device:** iPhone X

## Additional context
Observed push notifications behaving correctly on iOS 11/12 with same environment. Apple recently added a new attribute to the headers for APNS Headers, apns-push-type, which is required in iOS 13. https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc

**Comment by jbcaveman** [comment]
**UPDATE #2:** This appears to only be an issue in a production environment. iOS 13 receives and processes the push notifications as expected when testing locally with development apps/tokens.

**Comment by jbcaveman** [comment]
**CORRECTION:** tracing back a little further, I see that it is not an APNS issue. The failure is that the event isn't getting to the app. In this case ChannelPresenter calls Notifications.shared.showIfNeeded(newMessage: message, in: channel) upon a .messageNew event. This is what is not happening on iOS 13 in production.

**Comment by buh** [comment]
Hi @jbcaveman 
Could you check that you uploaded a production push notification certificate on our dashboard?

**Comment by jbcaveman** [comment]
Yes. I am using a new .p8 key. When I noticed the issues, I also tried to revert back to our active .p12 that we use with another service, but I didn't see a change. I also tried generating a new key, which had no effect.

**Comment by buh** [comment]
Did you check push logs in our dashboard?

**Comment by jbcaveman** [comment]
Just checked it. I guess the logs take a while to populate because I wasn't seeing any yesterday. Today I do see them and I see success for the iOS 13 user. So it would appear that the notifications are sent, but they are not populated through the app when it is active or in background.

**Comment by buh** [comment]
A push notification will be sent if the client was disconnected. When the app is going to the background the client will keep connection for a 1-5 min. Can you test when the app in the background for more than 5 min?

**Comment by buh** [comment]
Can you send to our support your issue and api key?

**Comment by jbcaveman** [comment]
I did notice the push will send if I wait for a minute or so. So I suppose the issue lies with the client handling of the event in iOS. I will pick this up with a support email. Thanks.

**Comment by buh** [comment]
@jbcaveman Now it looks like local notifications doesn't work for you. But now you can debug.
So, when your app in the background and the client still connected the client will send local notifications.
Try to enable logs for notifications `Notifications.logsEnabled = true` and test a new message when the app in the background.

**Comment by jbcaveman** [comment]
Here are some production logs where the app is not showing the updates in the ChannelsViewController. I can see the message data and the tab & app badge will increment, but the ChannelsViewController does not update.
[background_log.txt](https://github.com/GetStream/stream-chat-swift/files/3791330/background_log.txt)
[active_log.txt](https://github.com/GetStream/stream-chat-swift/files/3791331/active_log.txt)

**Comment by jbcaveman** [comment]
And here are development environment logs where the app is showing all updated messages normally. Notice the calls to "apns: Notifications: show(newMessage...)" in these logs that don't show up in the production logs.
[background_log_dev.txt](https://github.com/GetStream/stream-chat-swift/files/3791360/background_log_dev.txt)
[active_log_dev.txt](https://github.com/GetStream/stream-chat-swift/files/3791361/active_log_dev.txt)

**Comment by buh** [comment]
Are you debugging production build?

**Comment by buh** [comment]
Thanks for logs!

**Comment by jbcaveman** [comment]
Just updated the dev background log, going back a bit more to the app entering background mode.

**Comment by buh** [comment]
I know build types. I'm curious how you get Stream logs from production? Did you update ClientLogger log function?

**Comment by buh** [comment]
It's really weird. Did you try to compile and debug the production build? Does it have the same logs?

**Comment by jbcaveman** [comment]
I'm copying the logs from the Xcode console with 
```
        Client.config = .init(apiKey: STREAM_KEY, logOptions: .all)
        Notifications.shared.logsEnabled = true
```
The behavior is the same as the live app in the app store.

**Comment by buh** [comment]
Yes, that's what I'm asking.

**Comment by jbcaveman** [comment]
I have a remote logging feature that I can put into a true production release and install through TestFlight. It will take a few minutes.

**Comment by buh** [comment]
Is notifications authorization status ok at the beginning?
Can you send me full logs?

`ClientLogger` has a function
```swift
public static var logger: (_ icon: String, _ dateTime: String, _ message: String) -> Void
```
You can override the default behavior `print` to something else.

**Comment by buh** [comment]
When you tested the dev build, a chat view controller was opened?

**Comment by jbcaveman** [comment]
I have the app opening a ChatViewController at launch because that is the only way I found to kick start all notifications properly. 

My logger gets all stdout, so it is catching your logs. I'll publish a TestFlight app with this turned on to get as close to a real production experience as possible.

Meanwhile, here is a full production log when run using xcode. The notifications appear to be set right at launch.

[log_stdout.txt](https://github.com/GetStream/stream-chat-swift/files/3791449/log_stdout.txt)

**Comment by buh** [comment]
In the last logs I don't see background work.

**Comment by jbcaveman** [comment]
Ok. I was able to do the same test with the same results from a production TestFlight app. I sent messages while active, in background, and while channels view is up and while chat view is up. The messages tell the state of the receiving app. Here are the logs
[log_stdout.txt](https://github.com/GetStream/stream-chat-swift/files/3791591/log_stdout.txt)
[log_stderr.txt](https://github.com/GetStream/stream-chat-swift/files/3791592/log_stderr.txt)

.

**Comment by buh** [comment]
I’ve just found an article with push notifications changes for iOS 13.
https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/
Probably needs to update push notifications template. Needs to add: `apns-push-type: alert`
Could you try?

**Comment by jbcaveman** [comment]
I thought that was a header requirement rather than a part of the payload, but I will try that out.

**Comment by jbcaveman** [comment]
I actually noticed some negative effects when adding that to the payload like {"aps":{...},"apns-push-type":"alert"} According to this document, this is a header field. Is there a way to add headers through the CLI? I tried "--apns-push-type 'alert' \" but that of course threw an error.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

**Comment by buh** [comment]
No worries. Looks like we should fix it on our backend side. I told our backend team to check headers. Probably will be fixed tomorrow on CET time.

**Comment by jbcaveman** [comment]
Thanks so much for working through this!

**Comment by buh** [comment]
@jbcaveman Push notifications for iOS13 should work now.
