### ISSUE TITLE
Monitoring sending and receiving chat messages

### ISSUE THREAD

**Issue by Cordavi** [GetStream/stream-chat-swift#317]
## What are you trying to achieve?
I'm trying to find the right way to monitor when a message is sent by the user and when they receive a message. I need to be able to log analytic events for these cases.

## If possible, how can you achieve this currently?
I see that there is some ways to monitor messages being added to a channel with `Client.shared.rx.event` but it doesn't seems to give me the granularity I need to determine if I should log sent or received. 

## What would be the better way?

- Is there an expose way for me to know when a user taps the send button in a `ChatViewController`? Ideally that would let me log the send analytic. I likely could use `Client.shared.rx.event` for receiving a message in a channel. Ideally, it be nice to know that from within the `ChatViewController` if it is on screen. 

## GetStream Environment
**GetStream Chat version:** 2.4.4
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.5.1
**Swift version:** 5.1
**Xcode version:** 11.5
**Device:** iPhone 11 Pro

**Comment by Cordavi** [comment]
It appears like you are able to add a target on the send button like so `composerView.sendButton.addTarget(self, action: #selector(sendTapped), for: .touchUpInside)`.

In order to monitor messages received, it looks like you can do something like:

```swift
        Client.shared.rx.events(for: .messageNew)
            .observeOn(MainScheduler.instance)
            .bind(onNext:{ event in
                switch event {
                case let .messageNew(message, _, _, _):
                    if !message.isOwn {
                        
                    }
                default:
                    break
                }
            })
            .disposed(by: self.disposeBag)
```

Is this what you all recommend for monitoring send and received messages?

**Comment by b-onc** [comment]
Hello Cordavi,

You're right, you can use both events and target to observe.
There's also `ChannelPresenter.messagePreparationCallback` that'll be called before sending the message.
The code you've pasted above is also correct.
For multi-device users, you can use webhooks to get more granularity to our analytics.

**Comment by Cordavi** [comment]
Thanks.
