### ISSUE TITLE
UnBanned user event

### ISSUE THREAD

**Issue by vWolfG** [GetStream/stream-chat-swift#318]
## What did you do?
The user was unbanned from all channels using server-side

## What did you expect to happen?
Get event userUnbanned

## What happened instead?
Decoding Error

## GetStream Environment
**GetStream Chat version:** 2.2.4
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.4
**Swift version:** Swift 5
**Xcode version:** 11.4.1
**Device:** iPhone 11 Pro Simulator

## Additional context
StreamChatClient WebSocket.swift
Decode response dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "type", intValue: nil)], debugDescription: "Cannot initialize EventType from invalid String value user.unbanned", underlyingError: nil)) in parseEvent(with:)[366]
[16 Jun 13:43:29.640] [ERROR] 📦  {
  "channel_id" : "1285",
  "channel_type" : "messaging",
  "type" : "user.unbanned",
  "created_at" : "2020-06-16T06:43:29.554149291Z"
}

**Comment by b-onc** [comment]
Hello @vWolfG ,
Swift SDK does not include this event. We'll fix this and release with 2.2.5

**Comment by b-onc** [comment]
Hello @vWolfG ,
The event should always have the User object but the logs you've posted do not have it. We suspect it might be a backend bug, can you share your app id with us so we can investigate?

**Comment by vWolfG** [comment]
app id is 78928
