### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#32]
Framework crashed on our app with following error:
**Fatal Exception: NSInternalInconsistencyException**
```
Invalid parameter not satisfying: formatOptions == 0 || !(formatOptions & ~(NSISO8601DateFormatWithYear | NSISO8601DateFormatWithMonth | NSISO8601DateFormatWithWeekOfYear | NSISO8601DateFormatWithDay | NSISO8601DateFormatWithTime | NSISO8601DateFormatWithTimeZone | NSISO8601DateFormatWithSpaceBetweenDateAndTime | NSISO8601DateFormatWithDashSeparatorInDate | NSISO8601DateFormatWithColonSeparatorInTime | NSISO8601DateFormatWithColonSeparatorInTimeZone | NSISO8601DateFormatWithFullDate | NSISO8601DateFormatWithFullTime | NSISO8601DateFormatWithInternetDateTime))
globalinit_33_4C19912DD841259A848CA079747E3591_func7
```

Stacktrace:
[getstream crash.txt](https://github.com/GetStream/stream-chat-swift/files/3804427/getstream.crash.txt)

We shipped app with GetStream at commit f2ab4e8935126771414b3f1fb9e630b921b85cbc

**Comment by buh** [comment]
@mpodeszwa do you know the iOS version of the issue?

**Comment by buh** [comment]
I think it related for iOS 11.1-. Fixed here: https://github.com/GetStream/stream-chat-swift/commit/c572d7c43159d839d3ed1afcf658033cba4d406d
