### ISSUE TITLE
Mute intervals for channels doesn't seem to work

### ISSUE THREAD

**Issue by eugene-krinitsyn** [GetStream/stream-chat-swift#3238]
I Called `func muteChannel(expiration: Int? = nil, completion: ((Error?) -> Void)? = nil)` providing `expiration` parameter, which resulted API call `/moderation/mute/channel` with `"expiration":28800` in it's body. The call resulted with a success, all the controllers received an update and the UI state changed to the respective one. 
Although, after relaunching the app stream client synchronised with the API and received `notifications_muted` set to false from `/channels/<cid>` endpoint, which resulted the respective 'unmuted' UI state. 

## GetStream Environment
**GetStream Chat version:** 4.56.1
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** 17.4, 17.5.1 
**Swift version:** 5.10
**Xcode version:** 15.3 
**Device:** iOS Simulator, iPhone 13 Pro

**Comment by laevandus** [comment]
Hi @eugene-krinitsyn,

Could you please tell me if you were checking the `notifications_muted` value from channel `membership` or channel `members` payload (by looking up the current user)? 

Thank you!

**Comment by eugene-krinitsyn** [comment]
@laevandus 

I simply use `ChatChannelListController` and rely on channel's property `isMuted`. I've checked the server's response to understand if it's a client-side issue. 
I see that the SDK sends requests to `channels`, and also see that all the fields named `notifications_muted` are set to false. This happens only when I use intervals for muting. When I simply mute / unmute indefinitely all works well.

Hopefully this helps, please let me know if I can provide more information for you.

**Comment by testableapple** [comment]
Hi @eugene-krinitsyn,
I do apologise, it seems we forgot to reply to you.

Could you please let us know if the issue is still relevant?

Kind regards,
Alexey
