### ISSUE TITLE
Extra Data not able to search using contain key it alway give blank response (UserListFilterScope)

### ISSUE THREAD

**Issue by viralspoony** [GetStream/stream-chat-swift#3254]
## What did you do?
I am adding extra data when i am connect to user and after that i will try to search user using UserListFilterScope, with contain filter but it not give me result when i am typing few keyword and when i am use equal filter with exact word then it working fine 

for example in my extra data have sp_username = viralbhalala

with **.contain** key if i will type **viral** then it not give any result 
with **.contain** key if i will type **viralbhalala** then it not give any result 

with **.equal** key if i will type **viral** then it not give any result 
with **.equal** key if i will type **viralbhalala** then it give any result 

here i am attaching screen shot as well

![Screenshot 2024-06-18 at 11 08 29 AM](https://github.com/GetStream/stream-chat-swiftui/assets/172360475/5087f83c-d80e-41a0-a7dd-5683617d792e)
![Screenshot 2024-06-18 at 11 08 34 AM](https://github.com/GetStream/stream-chat-swiftui/assets/172360475/ccaa0e6a-e0a1-4522-8043-50a2571cd45c)

## What did you expect to happen?
with .contain if i am type viral then also it should give me result which right now not coming

## What happened instead?
it give no result 

## GetStream Environment
**GetStream Chat version:**  4.57.0
**GetStream Chat frameworks:** StreamChat, StreamChatSwiftUI
**iOS version:** - 17.5
**Swift version:** - latest SwiftUi
**Xcode version:** - 15.4
**Device:** - 14 Pro

**Comment by nuno-vieira** [comment]
Hi @viralspoony,

You most likely need to use the `autocomplete` filter and not `contains`. If this does not work then it could be a backend limitation.

Either way, you should reach out to our support team at https://getstream.io/contact/support/. They should be able to help you.

Thank you,
Nuno

**Comment by viralspoony** [comment]
when I am use autocomplete using extra Data field it give error 


{
  "code" : 4,
  "message" : "QueryUsers failed with error: \"$autocomplete is not supported in field \"sp_username\"\"",
  "more_info" : "https:\/\/getstream.io\/chat\/docs\/api_errors_response",
  "details" : [

  ],
  "StatusCode" : 400,
  "duration" : "0.00ms"
}
