### ISSUE TITLE
Message Search Not Working

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swift#3261]
## What did you do?
I am trying to search message but it did not search the message from current user's channels. Suppose we search "appointment" word and we have message which contains that word but we are not getting any search result. 

## What did you expect to happen?

As you can see message contains "appointment"  text but 

<img width="414" alt="Screenshot 2024-06-20 at 6 45 04 AM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/689e0a62-2397-456f-bc47-26625f058fd6">

That message is not showing

<img width="469" alt="Screenshot 2024-06-20 at 6 45 55 AM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/0585ccf8-6f69-4303-889d-215d34638e7a">

I have already log this bug before [3115](https://github.com/GetStream/stream-chat-swift/issues/3115) - You guys as me its a backend issue and contact to the support and I contacted with support and I got no solution there and as you can see support close our ticket without resolution of the issue. 

<img width="1201" alt="Screenshot 2024-06-20 at 6 48 54 AM" src="https://github.com/GetStream/stream-chat-swift/assets/127435927/28c4e3d6-42da-4a80-9034-604630c55b25">

**Comment by martinmitrevski** [comment]
Hi @Zee-93,

As I can see, that ticket was closed because you haven't provided the details that our support team asked you about.

Please proceed the communication there.

Best, Martin
