### ISSUE TITLE
Search Channel By User Name

### ISSUE THREAD

**Issue by Zee-93** [GetStream/stream-chat-swift#3262]
## What did you do?
Is it possible to search channel by user name? I have used username as a channel name and when I search user name then that channel not shows in search result.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by nuno-vieira** [comment]
Hi @Zee-93,

This is not support at the moment. You can request this feature request to the support team.

Thank you,
Nuno
