### ISSUE TITLE
Hard Delete a User and its Channels

### ISSUE THREAD

**Issue by tciuro** [GetStream/stream-chat-swift#3296]
## What are you trying to achieve?

Hard Delete a User and its Channels. My app is written in SwiftUI and the server is written in Vapor (Swift on Server).

## If possible, how can you achieve this currently?

I don't think I can do that currently, unless I'm missing something.

## What would be the better way?

Provide a server-side mechanism to accomplish this. Is there a REST API I can piggy-back on to Hard Delete a user and its channels?

## GetStream Environment
**GetStream Chat version:** 4.57.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.5.1
**Swift version:** 5.10
**Xcode version:** 15.4
**Device:** iPhone 14, 15

## Additional context

Due to GDPR, I need to add the capability so that the user can delete its user record. It seems strange that there is no obvious way to do so if the environment is SwiftUI (client) and Swift (server). Is there a way to invoke deleteUser()? Seems like a glaring omission, especially since there is an official Swift/SwiftIUI library.

**Comment by nuno-vieira** [comment]
Hi @tciuro,

The Swift SDK, is a client SDK and not meant to be used on the Server, although probably for some things you can use it.

For this scenario you need to use the REST API endpoint here: https://getstream.io/chat/docs/rest/#product:chat-deleteusers

You can also use the supported server-side SDKs:

<img width="1569" alt="image" src="https://github.com/GetStream/stream-chat-swift/assets/12814114/a84da441-f1d1-4ac0-9035-ad0afe7157da">

Docs: https://getstream.io/chat/docs/

Best,
Nuno
