### ISSUE TITLE
NSInternalInconsistencyException when updating ChatViewController

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#33]
Framework crashed with error:
```
Fatal Exception: NSInternalInconsistencyException
Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (28), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
```

Stacktrace:
[chat update table crash.txt](https://github.com/GetStream/stream-chat-swift/files/3815617/chat.update.table.crash.txt)

We shipped app with GetStream at commit f2ab4e8935126771414b3f1fb9e630b921b85cbc

**Comment by buh** [comment]
@mpodeszwa  I think it already fixed.
Can you reproduce the crash?
If so, can you try with the latest version?

**Comment by buh** [comment]
Please check the latest version 1.4.0

**Comment by mpodeszwa** [comment]
I can't reproduce it - it happened once. It looked weird, tbh I don't know what's the case where number of rows goes from 28 to 1. I made a release with newer version of GetStream, hopefully it won't happen again :)
