### ISSUE TITLE
Chat link previews not working for Twitter

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#3301]
## What did you do?
I created a chat message with a link to twitter.com or x.com

## What did you expect to happen?
I expected to see a rich link preview of that url's content in the chat message

## What happened instead?
I only see the link text with no rich link preview

## GetStream Environment
**GetStream Chat version:** 4.55.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI 4.55.0

## Additional context
Other urls do produce a rich link preview

![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-12 at 10 46 28](https://github.com/user-attachments/assets/0db8a726-297e-49f3-a467-6f0ffb5bcf3b)

**Comment by testableapple** [comment]
Hi @srgray,
Thanks for opening the ticket.

This is a known issue on the backend related to Twitter links. For more details, please contact our Support team at https://getstream.io/contact/support.

Kind regards,
Alexey
