### ISSUE TITLE
Crash Index out of range on LazyCachedMapCollection

### ISSUE THREAD

**Issue by fceldeiro** [GetStream/stream-chat-swift#3319]
## What did you do?
After updating to 4.59.0 randomly i get a crash (Fatal error: Index out of range) on LazyCachedMapCollection line 76. Could not find a pattern, just happens after i open/close an x number of channels.

Tried the same on the version 4.58.0 (opening and closing multiple times) and could not reproduce.

## GetStream Environment
**GetStream Chat version:** 4.59.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.5
**Swift version:** 5+
**Xcode version:** 15.4
**Device:** iPhone 15 Pro

## Additional context
<img width="1690" alt="Screenshot 2024-07-19 at 11 33 13" src="https://github.com/user-attachments/assets/c719657f-17eb-4d1d-9db8-8d99173b02a5">

**Comment by nuno-vieira** [comment]
Hi @fceldeiro,

This issue is now fixed on the 4.60.0 Release.

Best,
Nuno
