### ISSUE TITLE
ChatViewController.emojiReactionTypes display order is not consistent

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#332]
## What did you do?
The displayed order of `emojiReactionTypes` is not consistent. If you display `ChatViewController` multiple times, you will get a different display order for `emojiReactionTypes` each time.

## What did you expect to happen?
The display of `emojiReactionsTypes` should be consistent for each display

## GetStream Environment
**GetStream Chat version:** 2.2.5
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.5
**Swift version:**
**Xcode version:** 11.5
**Device:** Simulator

**Comment by b-onc** [comment]
Hello @srgray
Thanks for finding this bug! It's certainly true since `emojiReactionTypes` is a dictionary and dictionaries are not ordered. We'll fix this in upcoming releases.
