### ISSUE TITLE
Increasing username font size causes some text to be cut off

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#333]
## What did you do?
Adjust style of message username font in ChatViewController like:
`style.incomingMessage.nameFont = .systemFont(ofSize: 16)`

## What did you expect to happen?
Username font should be increased and display correctly

## What happened instead?
Username font was increased but the lower part of the label is now cut off (see screenshot)

## GetStream Environment
**GetStream Chat version:** 2.2.5
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.5
**Swift version:**
**Xcode version:** 11.5
**Device:** Simulator

## Additional context
<img width="545" alt="Screenshot 2020-06-29 07 00 24" src="https://user-images.githubusercontent.com/4721220/86003082-e5eee500-b9d6-11ea-9822-a988ffb4a11c.png">

**Comment by b-onc** [comment]
Hello @srgray 
Indeed that's a bug. The name label height is derived from avatar view's radius and vertical spacing, as can be seen in `MessageTableViewCell.swift:L59`:
```swift
private(set) lazy var nameAndDateStackView: UIStackView = {
    let stackView = UIStackView(arrangedSubviews: [nameLabel, dateLabel])
    stackView.axis = .horizontal
    stackView.spacing = style.spacing.vertical
    
    stackView.snp.makeConstraints {
        var height: CGFloat = 13
        
        if let avatarViewStyle = self.style.avatarViewStyle {
            height = max(height, avatarViewStyle.radius - self.style.spacing.vertical)
        }
        
        $0.height.equalTo(height).priority(999)
    }
    
    stackView.isHidden = true
    return stackView
}()
```
So a workaround is playing with these 2 properties in ChatViewStyle.incomingMessage to make sure label is shown.
We'll fix this bug in an upcoming release.
