### ISSUE TITLE
WebSocket Does Not Reconnect When App Resumes from Background (Guest User)

### ISSUE THREAD

**Issue by masarusanjp** [GetStream/stream-chat-swift#3338]
## What did you do?

I launched the app, waited for a few minutes, and then resumed it.

## What did you expect to happen?

I expected the WebSocket to reconnect when the app resumes from the background.

## What happened instead?

The WebSocket does not reconnect when the app resumes from the background.

## GetStream Environment
**GetStream Chat version:** 4.60.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** iOS17.4
**Swift version:** 5.9
**Xcode version:** 15.3
**Device:** Simulator iPhone 15 Pro

### Reproduce Step

- launch DemoApp 
- Tap `Guest User`
- Suspend app
- Waiting for few minutes
- Resume app
- Tap `Start a chat`

### Screencast

https://drive.google.com/file/d/1-parw6tuS02VBZW7cG3__1Pb4e3ciogL/view?usp=sharing
(Here is a link to GoogleDrive due to its large size)

### Additional Information

I discovered that the connectGuestUser function calls logOut first. As a result, ConnectionRecoveryHandler.stop is invoked, causing the monitoring of appDidBecomeActive and appDidEnterBackground to stop. This leads to the issue where "the WebSocket does not reconnect when the app resumes from the background.

https://github.com/GetStream/stream-chat-swift/pull/3303/files#diff-5aa17a3514ab85c33231ca8983e4c32096742c79d97924fe31e71ebb0ac7d540R385

This issue reliably reproduces with a guest user, but it is likely to occur under any condition where logOutFirst is true.

**Comment by nuno-vieira** [comment]
Hi @masarusanjp, thanks for spotting this issue!

The actual issue is that when reconnecting, logOut should not be happening, so the logic should be changed here. Stopping the recovery handler on logout is something that we want, but it caused this unwanted side effect due to the fact that logOutFirst in guest user is not properly implemented it seems.

**Comment by 98prabowo** [comment]
Hi @nuno-vieira, does this only affect guest user? or all user?

**Comment by nuno-vieira** [comment]
> Hi @nuno-vieira, does this only affect guest user? or all user?

Hello! Only guest and anonymous user yes.

**Comment by nuno-vieira** [comment]
This is now fixed on the latest release! 🚀 

Thank you for your patience!
