### ISSUE TITLE
Option for applying mention users

### ISSUE THREAD

**Issue by hashlin** [GetStream/stream-chat-swift#338]
## What are you trying to achieve?
I want to customize mention users by myself but SDK override it.

## If possible, how can you achieve this currently?
Currently, I need to modify SDK source code as a work around. There should be a better way.

## What would be the better way?
This is current method inside Client+Channel.swift. 
`func send(message: Message, to channel: Channel, _ completion: @escaping Client.Completion<MessageResponse>) -> Cancellable
`

It would be better to give developers an option for overriding mention users like the following.
`func send(message: Message, to channel: Channel, overrideMentionUsers: Boolean = true,  _ completion: @escaping Client.Completion<MessageResponse>) -> Cancellable
`

Add an extra parameter which will allow developers to choose. And only override mention users if it is true.

## GetStream Environment
**GetStream Chat version:** - 2.2.5
**GetStream Chat frameworks:** StreamChatClient
**iOS version:** 13
**Swift version:** 5.2
**Xcode version:** 11
**Device:**

**Comment by b-onc** [comment]
Hello @hashlin 
Can you describe what you're trying to achieve with more detail? What do you mean by "override mention users"? Do you want to disable that functionality?

**Comment by hashlin** [comment]
https://github.com/GetStream/stream-chat-swift/blob/528aeea6e4af1f0fd86ced1c18ce4c4e0bc3a636/Sources/Client/Client/Client%2BChannel.swift#L243-L275


At line 256 to 267, mention users are overridden inside this method.

So, even if I added mention users to message object, it is overridden.

**Comment by hashlin** [comment]
So, it would be nice if developer can choose whether mention users will be automatically created or not.

**Comment by b-onc** [comment]
@hashlin Thanks for clarifying it! We'll introduce this in an upcoming release. Seems like mentionedUsers shouldn't even be handled in Client, they should be handled in ChannelPresenter only.

**Comment by hashlin** [comment]
Exactly.

Thank you @b-onc

**Comment by mlanoy** [comment]
Hi,

I wanted to add the same issue.

In our case, we handle mention ourselves, adding users to `mentionedUsers` ourselves before sending a message. Moreover, we don't display the `@` character before names (we only relying on AttributedString with different font and color).

In my opinion, the main issue is line 257 where a new User array is instanciated instead of using the one coming from the Message object (and check if a user is already mentioned there)
