### ISSUE TITLE
Token not working in iOS 

### ISSUE THREAD

**Issue by Steveiosdev** [GetStream/stream-chat-swift#3394]
## What did you do?
I created chatClientConfig and managed code as same code as mentioned in docs.

## What did you expect to happen?
User should get connected to socket

## What happened instead?
Connect user function giving me error. Error : ServerErrorPayload(code: 5, message: "JWTAuth error: token contains an invalid number of segments", statusCode: 401)).

## GetStream Environment
**GetStream Chat version:** 4.0.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17.5
**Swift version:** 5.10
**Xcode version:** 15.4
**Device:** iPhone 15 Pro

**Comment by testableapple** [comment]
Hi @Steveiosdev, thanks for opening the issue.

Just to double-check, are you sure that you are using StreamChat v4.0.0? It's quite an old version, back to 2021.

Best,
Alexey

**Comment by Steveiosdev** [comment]
Hi,

Thanks for your response.

Yes, using 4.0.0 as your docs suggested. Let me know if I need to use the
latest one.

Link :- https://getstream.io/chat/docs/ios-swift/?language=swift

 [image: Screenshot 2024-08-22 at 9.26.38 PM.png]

**Comment by testableapple** [comment]
@Steveiosdev,

I think the package managers should download the latest version when you specify `'~> 4.0'` for Pods or `from: "4.0.0"` for SPM as in the docs.

But yes, please, do use the latest one, [4.62.0](https://github.com/GetStream/stream-chat-swift/releases/tag/4.62.0).

**Comment by Steveiosdev** [comment]
Hi

I have tried to install the latest pod and am still facing the same issue.
Can you please help out here?

Token i am using right now :
"﻿eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYXNoaXNoc3VyYW5hIn0._GhnWKV6hh29ErWgjl2VjA9EIVriyHNAo2OlyZ98jfc"

Sharing screenshot attached as proof and also again attached sample code i
am using.

**Comment by testableapple** [comment]
Hi @Steveiosdev, unfortunately, I don't see any screenshots. Perhaps you are trying to upload them via email? Could you please upload them on GitHub? Thanks

**Comment by testableapple** [comment]
Hi @Steveiosdev,
It sounds like an issue on the backend, or that something is wrong with your token.

Either way, you should reach out to our support team at https://getstream.io/contact/support/. They should be able to help you.

Thank you,
Alexey

**Comment by Steveiosdev** [comment]
Hi @testableapple 
Thanks for your quick response.

I have already reached out there with all details and waiting for their response as well.

Can you please arrange a meeting with technical person. Thanks
