### ISSUE TITLE
How to update ChannelListView with a new query [SwiftUI]?

### ISSUE THREAD

**Issue by hyqshr** [GetStream/stream-chat-swift#3395]
I try to build a chat type filter so when user click the picker, ChannelListView with be update with the type query.
![image](https://github.com/user-attachments/assets/cadea9cd-712c-4439-b177-fef3c1ea47b9)

I tried to create different controllers outside of the view like:

```
let allChannelListController: ChatChannelListController = {
    let controller = dependencies.chatClient.channelListController(
        query: .init(
            filter: .containMembers(userIds: [dependencies.chatClient.currentUserId ?? ""])
        )
    )
    print("$$ \(controller.channels.count) ALL")
    return controller
}()

let teamChannelListController: ChatChannelListController = {
    let controller = dependencies.chatClient.channelListController(
        query: .init(
            filter: .and([.equal(.type, to: .team), .containMembers(userIds: [dependencies.chatClient.currentUserId!])])
        )
    )
    print("$$ \(controller.channels.count) TEAM")
    return controller
}()
```

And then in chat view, I re-use the created controller based on type selection:

```
struct ConversationView: View {
    @EnvironmentObject var userViewModel: UserViewModel
    @State private var showSelectSheet = false
    @State private var selectedChatType: String = "All"
    
    var body: some View {
        VStack {
            ChatChannelListView(
                viewFactory: CustomChatUIFactory(userViewModel: userViewModel, selectedChatType: $selectedChatType),
                channelListController: channelListController(for: selectedChatType)
            )
        }
.....
    }

    private func channelListController(for chatType: String) -> ChatChannelListController {
        switch chatType {
        case "Team":
            return teamChannelListController
        default:
            return allChannelListController
        }
    }
}

```

It still doesn't work, the channels list will be unclickable and the filter query is not working.

Also when I try do `ChatClient.shared.channelListController` like the doc you suggested, it throw error:

```
Value of type 'ChatClient' has no member 'shared
```

https://getstream.io/chat/docs/sdk/ios/client/controllers/channels/#filtering-with-extra-data

**Comment by testableapple** [comment]
Hi @hyqshr, thanks for opening the issue.

Could you please share the SDK version that you are using?

Best,
Alexey

**Comment by hyqshr** [comment]
@testableapple The SDK version is 4.60.0

**Comment by testableapple** [comment]
Thank you.

Regarding:
> Value of type 'ChatClient' has no member 'shared'

`shared` in the docs is just an example of how to leverage the singleton instance of `ChatClient`. [Here is an example](https://github.com/GetStream/stream-chat-swift/blob/develop/Examples/SlackClone/ChatClient.swift#L9-L40) of it's usage in SlackClone demo app.

**Comment by hyqshr** [comment]
Thank you @testableapple, I injected the singleton `chatclient` as doc suggested.

How to update ChatChannelListView with different query in SwiftUI?

In `UIKit`, there is `ChatChannelListVC.replaceQuery() `, is there an identical in SwiftUI?

**Comment by martinmitrevski** [comment]
Hi @hyqshr,

The channel list view has a state object inside, which persists the controller. Therefore, you just need to do if-else on the channel list view, in order to create a new view with a different query. 
Something like this:

```swift
var body: some View {
        VStack {
            if selectedChatType == "Team" {
                  ChatChannelListView(
                       viewFactory: CustomChatUIFactory(userViewModel: userViewModel, selectedChatType: $selectedChatType),
                       channelListController: teamChannelListController
                  )
            } else {
                 ChatChannelListView(
                       viewFactory: CustomChatUIFactory(userViewModel: userViewModel, selectedChatType: $selectedChatType),
                       channelListController: allChannelListController
                  )
            }
        }
.....
    }
```

Hope that helps,
Martin

**Comment by hyqshr** [comment]
Hi @martinmitrevski Thank you! It solves the problem :)

Hopefully there could be a more dynamic way to update `ChatChannelListView` in the future.
