### ISSUE TITLE
How do I get pinned messages count?

### ISSUE THREAD

**Issue by f3dm76** [GetStream/stream-chat-swift#3408]
## What are you trying to achieve?
I'm trying to make a separate screen displaying all the pinned messages. The button leading to this screen should say "Pinned messages - 4", then you tap the button and only then I load them using pagination. While the button is not tapped I just need the counter of all the pinned messages.

## If possible, how can you achieve this currently?
I think I can keep loading new pages until `loadPinnedMessages` returns 0 messages, and then count them. 

```
let controller = chatClient.channelController(for: channel.cid)
        controller.loadPinnedMessages(pageSize: 15, sorting: [.init(key: .pinnedAt, isAscending: true)], pagination: pagination) {
            switch $0 {
            case let .success(messages):
                self.pinnedMessages.append(contentsOf: messages)
                if let last = messages.last {
                    self.pagination = PinnedMessagesPagination.after(last.id, inclusive: false)
                }
            case let .failure(error):
                print(error)
            }
        }
```

## What would be the better way?
Something like channel.pinnedCount or chatClient.channelController(for: channel.cid).pinnedCount, could be async and only fetched on demand.

## GetStream Environment
**GetStream Chat version:** 4.62.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 18.0
**Swift version:** Swift 5.10 (5.10.0.13)
**Xcode version:** 15.4 
**Device:** sim 15 pro max

**Comment by laevandus** [comment]
Hi @f3dm76, thank you for the feature request. Currently we do not have such convenient way for surfacing this information as an integer property. Since it affects all the SDKs, the best way to request it, is through our [engineering support](https://getstream.io/contact/support/). 
Thank you!
