### ISSUE TITLE
 Error WaiterTimeout in AuthenticationRepository.swift:277

### ISSUE THREAD

**Issue by Style44** [GetStream/stream-chat-swift#3411]
## What did you do?
I attempted to create a custom view for displaying a chat interface.

## What did you expect to happen?
I expected the chat to appear immediately upon navigating to the view within the application.

## What happened instead?
Instead, the error appears, and the chat interface does not load. The chat only appears after restarting the application.

## GetStream Environment
**GetStream Chat version:** 4.62.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI

## Additional context
```
[ERROR] [io.getstream.logger] [APIClient.swift:224] [executeRequest(endpoint:completion:)] > Error WaiterTimeout in /Users/username/Library/Developer/Xcode/DerivedData/app/SourcePackages/checkouts/stream-chat-swift/Sources/StreamChat/Repositories/AuthenticationRepository.swift:277
```

**Comment by laevandus** [comment]
Hi @Style44, could you please reach out to our [engineering support](https://getstream.io/contact/support/) for investigation.

**Comment by drtz** [comment]
@laevandus Was there a resolution for this? I'm intermittently running into the same issue.

**Comment by laevandus** [comment]
Hi @drtz, best is to reach out to us through the [technical support](https://getstream.io/contact/support/), then we can take a look at your integration and issues.
