### ISSUE TITLE
Increasing InputTextView's `minimumHeight` leads to placeholder and typing indicator being misaligned

### ISSUE THREAD

**Issue by dfed** [GetStream/stream-chat-swift#3420]
## What did you do?
I increased `InputTextView`'s `minimumHeight` to 50

## What did you expect to happen?
I expected the placeholder view and the typing indicator to be center aligned, or at least aligned

## What happened instead?
Placeholder view is aligned to center (expected!) and typing indicator is aligned to top (unexpected!): 
<img width="286" alt="image" src="https://github.com/user-attachments/assets/111968c2-7169-4228-9f32-6760a6d3ba23">

## GetStream Environment
**GetStream Chat version:** 4.62.0
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version:** 17
**Swift version:** 5.10
**Xcode version:** 15.4
**Device:** iPhone

**Comment by testableapple** [comment]
Hi @dfed, thanks for reporting the issue. I can confirm that it is an issue on our side when you increase the `minimumHeight` of the InputTextView. I will add it to our backlog, but, unfortunately, I can't share any ETA for now.

In the meantime, as a workaround, you could try to overwrite the `InputTextView.setUpAppearance()` function and align the typing indicator to your needs. Hope this helps.

Best,
Alexey

**Comment by laevandus** [comment]
Hi @dfed,

If you would like to make the input area to look larger, the recommended approach is to:

1. Subclass `InputChatMessageView`
2. Override `setUpLayout` and after calling super.setUpLayout(): 
`inputTextContainer.directionalLayoutMargins.top = 6`
`inputTextContainer.directionalLayoutMargins.bottom = 6`
3. Set the subclass: `Components.default.inputMessageView = MyInputChatMessageView.self`

Changing the margins this way gives:
<img width="514" alt="after" src="https://github.com/user-attachments/assets/a398406c-16db-4240-8899-327f2362d914">

Please reopen if additional assistance is needed.

Thank you!

**Comment by dfed** [comment]
That got the job done. Thanks for the tip!

Kinda curious how the minimum height variable is meant to be used but it's just an idle curiosity 🙂
