### ISSUE TITLE
Message Translation Clear

### ISSUE THREAD

**Issue by ikaru19** [GetStream/stream-chat-swift#3470]
## What are you trying to achieve?
Able to see translate and show original message of a Translated Message, on Android side the message translation can be clear the translate by calling the `MessageTranslator.clearTranslation(message.id)` can we achieve this on swift?

## Additional context
https://github.com/GetStream/stream-chat-android/issues/5349

**Comment by nuno-vieira** [comment]
Hi @ikaru19,

You can achieve this by overriding `ChatMessageContentView.updateContent()` and changing the textView text. Something like this:

```swift
class CustomChatMessageContentView: ChatMessageContentView {
    override func updateContent() {
        super.updateContent()

        if content?.shouldShowTranslated == false {
            let text = content?.textContent ?? ""
            let attributedText = NSAttributedString(
                string: text,
                attributes: [
                    .foregroundColor: messageTextColor,
                    .font: messageTextFont
                ]
            )
            textView?.attributedText = attributedText
        }
    }
}
```
