### ISSUE TITLE
ChatClient createDirectMessageChannelWith with new members ids incorrectly returns a group channel where one of the members was banned.

### ISSUE THREAD

**Issue by macshodan** [GetStream/stream-chat-swift#3486]
Trying to create a direct message channel between two users that didn't previously had channel together but interacts only in a group chat. The peculiar thing is that in the chat one of the user has been banned because blocked by another user in the same chat group. So the situation is: 

### Original Group Chat ###
Member A
Member B
Member C

member B blocks member C so in the group chat they both appear as banned. Only member A can write in the group.

### New direct message from A to B ###
the client returns the original group chat to A (the cid is the same), but only with members A and B reported. A can write but B can't reply.

## What did you expect to happen?
A new channel, with a new cid, only for A and B should be created and returned by the client. So A and B can communicate.

## What happened instead?
The old group channel between A, B and C is returned (same cid) with only A,B listed as members. 

## GetStream Environment
**GetStream Chat version: 4.64**
**GetStream Chat frameworks:** StreamChat, StreamChatUI
**iOS version: 18.1**
**Swift version:5.9**
**Xcode version:16.1**
**Device: iPhone, tested on simulators and devices**

## Additional context

We tried this on iOS Sdk and Android Sdk, the result is the same. We're using the chatClient channelController(createDirectMessageChannelWith: ) function, passing as arguments only the 2 members id involved.

**Comment by testableapple** [comment]
Hi @macshodan,
It sounds like an issue on the backend.

Could you please reach out to our support team at https://getstream.io/contact/support/. They should be able to help you.

Thank you,
Alexey

**Comment by testableapple** [comment]
Just to confirm:

1. There is a group channel with users `A`, `B` and `C`.
2. User `B` bans user `C`
3. User `A` sends a direct message to user `B`
4. The message is sent to that group channel where user `C` is banned? Or what's the actual result at this point?

**Comment by macshodan** [comment]
yes exactly, the cid returned from the chatclient call is the same of the group chat and not a new one for user A and B as I would expect.

**Comment by testableapple** [comment]
@macshodan, could you please share the code of how you create a group channel in the first step?

**Comment by macshodan** [comment]
@testableapple sure here's the function I use to create the channel, it's the same code no matter if we use a direct chat or a group chat.

```swift
private func sendChatMessageTo(_ users: [String], _ currentChatUser: UserId, _ attachment: AttachmentPayload?, _ displayChat: Bool, _ navigationController: UINavigationController, _ modal: Bool, _ completion: ChatCoordinator.completionClosure?) {
        
        var newChannelsMembersIds: Set<UserId> = Set(users)
        newChannelsMembersIds.insert(currentChatUser)
        
        do {
            let controller = try chatViewModel.chatClient.channelController(createDirectMessageChannelWith: newChannelsMembersIds,
                                                              isCurrentUserMember: true,
                                                              name: nil,
                                                              imageURL: nil,
                                                              extraData: [String: RawJSON]())
            
            controller.synchronize { error in
                if error == nil {
                    if let attachment = attachment as? LiberPostShareAttachment {
                        let attachments: [AnyAttachmentPayload] = [AnyAttachmentPayload(payload: attachment)]
                        controller.createNewMessage(text: "", attachments: attachments, extraData: [String : RawJSON]())
                    } else if let attachment = attachment as? LiberProfileShareAttachment {
                        let attachments: [AnyAttachmentPayload] = [AnyAttachmentPayload(payload: attachment)]
                        controller.createNewMessage(text: "", attachments: attachments, extraData: [String : RawJSON]())
                    } else if let attachment = attachment as? LiberStoryShareAttachment {
                        let attachments: [AnyAttachmentPayload] = [AnyAttachmentPayload(payload: attachment)]
                        controller.createNewMessage(text: "", attachments: attachments, extraData: [String : RawJSON]())
                    }
                    
                    if displayChat {
                        self.displayChatController(controller: controller, from: navigationController, modal: modal)
                    }
                    completion?(true, navigationController)
                } else {
                    self.displayError(message: error?.localizedDescription)
                    completion?(false, navigationController)
                }
            }
        } catch let error {
            debugPrint("Error creating channel: \(error.localizedDescription)")
        }
    }
```

Basically I call this method after having selected the user to chat with. No matter if it's 1 or more users, then I add the current user in the list of members.

Let me know if you need something else.

Thanks.

**Comment by testableapple** [comment]
@macshodan, the problem is that in the first step you created a `direct channel` between 3 members (using argument `createDirectMessageChannelWith: members`) instead of a `group channel` between 3 members (using argument `for: channelId`).

Please refer to this doc for more details: [Creating a Channel Using a Channel Id](https://getstream.io/chat/docs/ios-swift/creating_channels/#1-creating-a-channel-using-a-channel-id).

Hope this helps!

**Comment by macshodan** [comment]
@testableapple thanks for your reply, I don't think using a custom channel Id it's a viable method for our scenario.
I've read the docs you linked and that's why I choose the second method described on point 2 (Creating a channel for a list of members - distinct channels). 
From its description it fits exactly our needs, a distinct channel between a group of users, without the ability to add more users, as quoted:

> [2. Creating a Channel for a List of Members - distinct channels](https://getstream.io/chat/docs/ios-swift/creating_channels/#2-creating-a-channel-for-a-list-of-members---distinct-channels)

> Channels can be used to create conversations between users. In most cases, you want conversations to be unique and make sure that a group of users have only one channel. These are also referred to as ‘distinct channels’.

> You can achieve this by leaving the channel ID empty and providing channel type and members. When you do so, the API will ensure that only one channel for the members you specified exists (the order of the members does not matter).

In fact this method works great as long as there's no banned users inside the channel, and it constantly returns the correct channel. The only problem seems to be when there's banned users inside and for whatever reason the server query used to determine if returning an existing channel or create a new one don't fetch the correct members of the channel.

If you think that the only workaround for this is to use the different approach on how we create the channels then fine, but I think it's still a bug in the library.

Thanks again for your time

**Comment by nuno-vieira** [comment]
Hi @macshodan,

The issue only happens when one of the users is banned? Are you sure are providing the correct member ids? At the moment we are not able to reproduce this.

Best,
Nuno

**Comment by macshodan** [comment]
Hi @nuno-vieira,

yes we've been able to replicate the issue when one of the user in the channel blocks another user in the same channel. The result is that in channel explorer I see that both users are banned from that particular channel and then the bug when trying to create a new channel.

To summarize:

- User A, B and C are in a group chat (cid: ABC)
- User B blocks user C
- In the channel ABC I can see that both user B and C are banned from the channel
- User A tries to create a direct channel with user B
- The chat client returns the channel with cid ABC instead of a new one
- User A can write on the channel
- User B can see the messages but can't reply
- Also user C can see the messages.

Let me know if you need more info.

Thanks,
Simone

**Comment by testableapple** [comment]
@macshodan, we discussed this internally and for us it still sounds like a backend issue, especially because you mentioned that you have the same issue on Android.

Could you please reach out to our support team at https://getstream.io/contact/support/, as I previously suggested? They should be able to help you. They will debug it further, and depending on where the issue is, on the backend or on the client side, we will work on it.

Also, please make sure to specify whether you `block` or `ban` users because, technically, these are two different features.

Thanks

**Comment by nuno-vieira** [comment]
Hi @macshodan,

Can you clarify the action? We have `ban`, `mute` and `block`. You have bean saying `ban` and sometimes `block`, but they exist both, and they are different things. Can you share the code where you perform this action?

Thanks,
Nuno

**Comment by macshodan** [comment]
> Hi @macshodan,
> 
> Can you clarify the action? We have `ban`, `mute` and `block`. You have been saying `ban` and sometimes `block`, but both exist, and they are different things. Can you share the code where you perform this action?
> 
> Thanks, Nuno

@nuno-vieira 

Sure you're right, I get confused also because operations are different for different context. Let me give you more background info:
In our App a user can decide to `block` another user, that results in the two users not seeing each other anymore. What our server does in this situation is also to `block` the user on your platfom that's all. After the `block` operation we noticed that in the specific channels where the two users where chatting both of them results as `banned`.

So:

**On our App**
User A blocks User B
Our server `block` user B for user A on StreamChat
**On Stream Chat**
User B and User A are marked as `banned` from the channel where there are both members.

I apologize if it's the wrong place to report this bug, to me it's clearly something server side and not specifically tied to the swift sdk (or the Android sdk for instance) but I couldn't find anywhere else to report it. Probably I've misunderstood what @testableapple meant when addressing this as a backend issue, because I thought he was referring to something related to the admin web interface and not to the server.

**Comment by macshodan** [comment]
> @macshodan, we discussed this internally and for us it still sounds like a backend issue, especially because you mentioned that you have the same issue on Android.
> 
> Could you please reach out to our support team at https://getstream.io/contact/support/, as I previously suggested? They should be able to help you. They will debug it further, and depending on where the issue is, on the backend or on the client side, we will work on it.
> 
> Also, please make sure to specify whether you `block` or `ban` users because, technically, these are two different features.
> 
> Thanks

Hi @testableapple,
I apologize if I misunderstood what you meant initially as a backend related problem. I'm going to report it to the support team as well.

Thanks for your support

**Comment by testableapple** [comment]
No problem at all @macshodan, you are welcome. Hope the issue will be resolved soon for you.
