### ISSUE TITLE
ChannelsPresenter dosen't use channelType for filtering by default

### ISSUE THREAD

**Issue by janweinkauff** [GetStream/stream-chat-swift#35]
The `ChannelsPresenter` dosen't use `channelType` for filtering by default, I had to set a filter for the channel type by hand.

Is this behavior by intention?

**Comment by buh** [comment]
Hi @janweinkauff 
Yes, by default `ChannelsPresenter` have a filter equal to `.none`. 
What a filter do you use?

**Comment by janweinkauff** [comment]
Hi @buh - I was a little bit confused because I thought that the `channelType` will be used for filtering in the `ChannelPresenter`, cost me some time to find it out why I don't getting only messaging channels. 🙈

Right now I`m using `ChannelsPresenter(channelType: .messaging, filter: .key("type", .equal(to: "messaging")))`

**Comment by buh** [comment]
I'm sorry. Now I understand you. The parameter `channelType` is useless and can confuse. It will be removed.

**Comment by janweinkauff** [comment]
Not a problem. Thank you for the quick reply 👌🏻

**Comment by buh** [comment]
After several refactoring I missed to fix it.
