### ISSUE TITLE
URLs in the chat text and the range of URL taps are different

### ISSUE THREAD

**Issue by koishi** [GetStream/stream-chat-swift#350]
## What did you do?
I used ChatViewController to post the URL.
I tapped on the URL part.

## What did you expect to happen?
I was expecting to see a WebView.

## What happened instead?
I noticed that the URLs in the chat text and the range of URL taps are different.
I tapped on the text of the URL, but it shows an emoji reaction.

## GetStream Environment
**GetStream Chat version:**
2.2.5
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
iOS 13.5
**Swift version:**
5.0
**Xcode version:**
11.5
**Device:**
iPhone 11 Pro, Simulator

## Additional context
The URL is the green part, but the actual URL tap range is the red part.
![IMG_0476](https://user-images.githubusercontent.com/1259461/87244249-e4adc580-c476-11ea-9d06-228a9d0122b4.jpg)

**Comment by buh** [comment]
Hi @koishi!
Thanks! This is probably due to #243 
We’ll check.
