### ISSUE TITLE
Adjust the height of the Message Composer View

### ISSUE THREAD

**Issue by ruYJWkgd** [GetStream/stream-chat-swift#3505]
## What are you trying to achieve?
We have several users who are using larger font sizes on their device, and when trying to send a message they can only see one or two lines of text at a time. We would like the message composer to grow up to the top of the screen (similar to the way that iMessage works), but I haven't found a way to adjust the height of that component (or allow it to grow).

## If possible, how can you achieve this currently?
Doesn't appear possible without overwriting the existing composer and creating a new one from scratch.

## What would be the better way?
I would like the message composer component to grow as large as it can (like the one in iMessage) so that users on smaller devices and/or with larger font sizes can see more that a couple lines of the message that they are trying to send.

## GetStream Environment
**GetStream Chat version:*4.66.0*
**GetStream Chat frameworks:** StreamChat, StreamChatUI (4.66.0)
**iOS version:*16+*
**Swift version:*5+*
**Xcode version:*16.1*
**Device:*multiple iOS devices*

**Comment by nuno-vieira** [comment]
Hi @ruYJWkgd,

You can do this by overriding `Components.default.inputTextView` and change the `maximumHeight` to `0`. With this it will have the same behaviour as Apple. We will make sure to add this to the docs.

Thank you for your question!

Best,
Nuno
