### ISSUE TITLE
messageUpdated event doesn't  update the last message in the channelPresenter

### ISSUE THREAD

**Issue by vWolfG** [GetStream/stream-chat-swift#351]
## What did you do?
The last message was updated in the channel, . 

## What did you expect to happen?
The lastMessage parameter in the channelPresenter class will be as the channel's last message.

## What happened instead?
The lastMessage parameter in the channelPresenter doesn't be changed after the channel's last message had been updated. 

## GetStream Environment
**GetStream Chat version:** 2.2.6
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.4
**Swift version:** Swift 5
**Xcode version:** 11.4.1
**Device:** iPhone 11 Pro Simulator

## Additional context
It seems when messageUpdated event comes, it isn't handled by the ChannelsPresenter class in the func parse(event: StreamChatClient.Event), in that case, in the ChannelPresenter class func parse(event: StreamChatClient.Event) isn't called and messageUpdated event also isn't handled and func appendOrUpdateMessageItem(_ message: Message, at index: Int = -1) isn't called there.

**Comment by vWolfG** [comment]
Hello @b-onc! If there is some info about the described issue?

**Comment by buh** [comment]
Hi @vWolfG
Can you give me an example of the flow that you are testing?
We're updating the last message in `ChannelPresenter`, you can find the code [here](https://github.com/GetStream/stream-chat-swift/blob/master/Sources/Core/Presenter/Channel/ChannelPresenter%2BEvents.swift#L162-L170).

**Comment by buh** [comment]
Thanks! We will fix that.

**Comment by vWolfG** [comment]
Hello! Our app has already in the AppStore and we want to know when there will be a new release with the fixed bug, could you please tell us the approximate date? Thank you!
