### ISSUE TITLE
Deprecation warning: Filter.notEqual

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#3529]
I am using the `Filter.notEqual` to search for users that are not my currentUserId, example:
```
        let notCurrentUserFilter: Filter<UserListFilterScope> = .notEqual(.id, to: currentUserId)
```
I get a deprecation warning for using the `.notEqual` filter. Can you recommend a replacement for that?

StreamChat version: 4.68.0

**Comment by laevandus** [comment]
Hi @srgray, there is no replacement for the notEqual operator.
One alternative is to manually filter results before displaying them. Results are value types so removing the current user from this list is fast.

If you have additional questions, please contact us through the [engineering support](https://getstream.io/contact/support/) (please also include if You use UIKit or SwiftUI or custom UI). We have dedicated support engineers who are happy to take this 1:1 and find a solution for your use-case.
