### ISSUE TITLE
Composer view changes position if ChatViewController is not on very top of the screen

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#36]
## What did you do?

In our app ChatViewController is not always on very top of the screen. Because of that composer view gets too high.

## What did you expect to happen?

I expect `ComposerView` to be always on the bottom of ChatViewController, no matter what's the position of view controller (when keyboard is closed)

## What happened instead?

ComposerView moves around :D

## Additional context

I created commit with animation to show the problem:
https://github.com/mpodeszwa/stream-chat-swift/commit/ff7f4bef7957bcdb571032423122887d32e2c371

And there is a gif 😂 

![composer offset](https://user-images.githubusercontent.com/7826664/69341377-c5ed8b00-0c69-11ea-88ef-6a9dfd6e023f.gif)

**Comment by mpodeszwa** [comment]
If I may suggest something, did you think about using [UIView.convert(_:to:)](https://developer.apple.com/documentation/uikit/uiview/1622504-convert) or [UIView.convert(_:from:)](https://developer.apple.com/documentation/uikit/uiview/1622498-convert) to get true position of ComposerView on the screen?

**Comment by buh** [comment]
Hi @mpodeszwa 
I'll check! Thanks for the gif 😂

**Comment by buh** [comment]
@mpodeszwa please check v.1.5.1
