### ISSUE TITLE
Customize name-generated AvatarView 

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#370]
## What are you trying to achieve?
Customize the appearance of SDK-generated avatar images. For example, use only the first initial of user's name instead of two letters.

## If possible, how can you achieve this currently?
I don't know of a way to do this currently

## What would be the better way?
Perhaps creating an AvatarNamingStrategy enum that possible options `firstLetter`, `firstLetterOfEachWord`, etc. Maybe that could be a new property on `AvatarViewStyle`

## GetStream Environment
**GetStream Chat version:**
2.2.6
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context
I believe the Android SDK has a different default behavior for this functionality than iOS does, so bringing the 2 SDKs into alignment would be nice, as well.

gz#4665

**Comment by shodgetts** [comment]
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/4665'>Zendesk ticket #4665</a>:<br><br>Assigned to Bahadir
