### ISSUE TITLE
ChannelsViewController does not update with recreated channel after deletion

### ISSUE THREAD

**Issue by j-j-m** [GetStream/stream-chat-swift#392]
## What did you do?
While using `ChannelsViewController` 

1. delete a channel by swiping or manually using `Channel.delete`
2. recreate the channel `Channel.create` (create a direct message channel with the same user)

## What did you expect to happen?

I expect the channel to appear in the list in my `ChannelsViewController` (like it does when I create the channel without deleting the chat with the same user before hand)

## What happened instead?

The channel does not appear until I recreate the controller. 

note that I can interact with the channel if I instantiate a `ChatViewController` in the `Channel.create` completion. It just doesnt appear int the `ChannelsViewController` table.

## GetStream Environment
**GetStream Chat version:**  2.2.8 and prior.
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 11 and up
**Swift version:** 5.1
**Xcode version:** 11.6
**Device:** All

gz#5225

**Comment by cardoso** [comment]
Hi @j-j-m ! Thanks a lot for opening this issue. We're working to ship a fix for it soon.

While it's not live, it would be very helpful if you could check it works for you by using the branch 'fix/channel_delete_create.392'.

**Comment by j-j-m** [comment]
@cardoso 
after installing via
```
pod 'StreamChat', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix/channel_delete_create.392'
```
I can't seem to build.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/5327798/89852821-b8f92a80-db5d-11ea-86e4-272b4a66ef08.png">

**Comment by cardoso** [comment]
@j-j-m please try specifying the 3 dependencies like so:

```ruby
pod 'StreamChat', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix/channel_delete_create.392'
pod 'StreamChatCore', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix/channel_delete_create.392'
pod 'StreamChatClient', :git => 'https://github.com/GetStream/stream-chat-swift.git', :branch => 'fix/channel_delete_create.392'
```

Thanks

**Comment by j-j-m** [comment]
of course. the above change got it building and the fix works as expected.

**Comment by cardoso** [comment]
Thanks a lot for confirming the fix @j-j-m . It should be available in the next release.
