### ISSUE TITLE
Feature request: Custom attachments

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#4]
Hi, I need to support custom attachments in my app. I found `Attachment` class [here](https://github.com/GetStream/stream-chat-swift/blob/master/Sources/Core/Model/Attachment.swift) but it's not really sufficient for my case. I need more custom fields inside. 

Is there a way to register my custom `Attachment` struct for a given attachment's `type`? Or is there any override point where I can add my custom type?

**Comment by buh** [comment]
@mpodeszwa Our server side is ready for attachments with extra data, but iOS client for now support only extra data for channels and messages. I can fix it and if you can give me a case example how you will use attachments with some extra data it will help.

**Comment by mpodeszwa** [comment]
@buh At this moment we have structure like this:
```
    "attachments": [{
      "type": "custom_type",
      "data": {
        "action_required": false,
        "created_at": "2019-08-26T16:29:37.436199Z",
        "id": 475,
        "object_id": 304,
        "status": "SCHEDULED",
        "users": [84]
      }
    }],
```
Usually it comes with even more fields in `data`. We can modify it if you have an idea how I can read it on ios.

**Comment by buh** [comment]
@mpodeszwa check a new release v.1.2.7
 Here is the steps to add your extra data to channels, messages or attachments:
1. You need to create a coddle type for your extra data.
2. Register your types for decoding. For example:
```swift
// Some extra data.
struct Meta: Codable, Equatable {
    let meta: String
}

// Register types for decoding.
ExtraData.decodableTypes = [.channel(Meta.self), .message(Meta.self), .attachment(Meta.self)]
```
3. Attach extra data:
```swift
let meta = Meta(meta: "test")
let channel = Channel(id: "channel_with_extra_data", extraData: meta)
    
let attachment = Attachment(type: .link,
                            title: "Stream Chat iOS SDK",
                            url: URL(string: "https://getstream.io/tutorials/ios-chat/"),
                            extraData: meta)

let message = Message(text: "Check my link!", attachments: [attachment], extraData: meta)
```
4. Get an extra data back:
```swift
// Create a channel.
channel.query(pagination: .limit(1))
    .subscribe(onNext: { response in 
        print(response.channel.extraData?.data as? Meta)
    })
    .disposed(by: disposeBag)

// ... later when a channel was created:

// Send a new message.
channel.send(message: message)
    .subscribe(onNext: { response in 
        print(response.message.extraData?.data as? Meta)
        print(response.message.attachments.first?.extraData?.data as? Meta)
    })
    .disposed(by: disposeBag)
```

**Comment by mpodeszwa** [comment]
Works great, thanks :)
