### ISSUE TITLE
Clear message history with hide doesn't appear to work

### ISSUE THREAD

**Issue by swpilot3** [GetStream/stream-chat-swift#41]
## What did you do?
I called:
self.channelsPresenter.hide(channelPresenter, clearHistory: true).drive().disposed(by: self.disposeBag)

like in the example code.

## What did you expect to happen?
I expected it to hide the channel and clear the message history

## What happened instead?
It hid the channel, but when a new message was sent on the channel, the entire message history came back for this user... it wasn't cleared.

## GetStream Environment
**GetStream Chat version:**
1.5.4

**iOS version:**
13.3

**Swift version:**
5

**Xcode version:**
11.3

**Device:**
iPhone 8 plus

**Comment by buh** [comment]
Hi @swpilot3!
It will work soon. It's a backend issue.

**Comment by Bogdan-D** [comment]
Hi @swpilot3, 

the feature wasn't enabled for your app, it should work now.

Please, feel free to reopen the issue if there are any problems.
