### ISSUE TITLE
Channel Extra Data Codable - map with key path issue

### ISSUE THREAD

**Issue by khoogheem** [GetStream/stream-chat-swift#414]
## What did you do?
try to use 2.2.9 and won't compile as there is an issue with a map `extension:`. error of `Type of expression is ambiguous without more context`

`                // Save generated name to nameAndImageForCurrentUser since there isn't any
                nameAndImageForCurrentUser.name = namingStrategy.name(for: User.current,
                                                                      members: members.map(\.user))
`

## GetStream Environment
**GetStream Chat version:**
2.2.9

**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
13.2.2

**Swift version:**
5.1.2

**Xcode version:**
11.2.1

gz#5427

**Comment by khoogheem** [comment]
I believe the issue here is that the Pod says 5.1 support but using a 5.2 feature of swift

**Comment by b-onc** [comment]
Hello @khoogheem 
Thanks for reporting this issue. Indeed, this is a Swift 5.2 feature but podspec reports Swift 5.1 as SDK version.
We can resolve this in 2 ways:
1. Update podspec to report 5.2
2. Introduce map with keypath extension to support all swift versions.

Would "1) Update podspec to swift 5.2" be any problem to you?

**Comment by khoogheem** [comment]
Moving it to 5.2 right now would not be a problem for me.. for the map solution you really would only need something like so any compiler under 5.2 would use it...
```  
 #if swift(<5.2)
    /// Map using Keypath
    ///
    /// - Parameter keyPath: Keypath
    /// - Returns: An array containing the transformed elements of this sequence
    func map<T>(_ keyPath: KeyPath<Element, T>) -> [T] {
        return map { $0[keyPath: keyPath] }
    }
#endif
```
