### ISSUE TITLE
App crashes when running Client.configureShared twice

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-swift#415]
I'm running the latest StreamChatClient pod. We have different environment (prod,dev,staging) associated with different projects/api keys. In our app we can switch environments, but it looks like if I try to reconfigure the client with a different API key it crashes `Client.configureShared(.init(apiKey: apiKey, logOptions: .info))` is there any way to do this?

gz#5432

**Comment by b-onc** [comment]
Hello @amardeepranu 
That is expected. If you want to switch api keys, please assign it via `Client.apiKey` directly, do not call `configureShared` more than once.
