### ISSUE TITLE
Token provider not called/ expired token not refreshed

### ISSUE THREAD

**Issue by amardeepranu** [GetStream/stream-chat-swift#421]
### GetStream Environment
**GetStream Chat version: 2.2.9
**GetStream Chat frameworks:** StreamChatClient
**iOS version:** 13.x

Currently, we're using stream-chat-react-native for the front-end of our chat feature, this works great. We only use the StreamChatClient for swift to update unread counts on our native side so we only use it for subscription events. When the app is backgrounded and brought to the foreground after token expiry, the subscriptions break and the token provider is not called again. This is from the logs

```
[23 Aug 17:10:12.301] [DEBUG] ⬅️ Response 200 (0 bytes): https://chat-proxy-us-east.stream-io-api.com/connect?api_key=XXXXXXXXXX
[23 Aug 17:10:12.301] [INFO] 📦 ""
[23 Aug 17:10:12.301] [DEBUG] ♨️ TCP connection heated up.
[23 Aug 17:10:12.301] [ERROR] 📦  {
  "error" : {
    "code" : 40,
    "message" : "Connect failed with error: \"JWTAuth error: token is expired (exp)\"",
    "StatusCode" : 401,
    "duration" : "0.00ms"
  }
}
[23 Aug 17:10:12.302] [DEBUG] Parsing WebSocket disconnect... (error: The operation couldn’t be completed. (Starscream.WSError error 1.))
[23 Aug 17:10:12.302] [DEBUG] Clearing state after disconnect...
[23 Aug 17:10:12.302] [DEBUG] Cancelling background work...
[23 Aug 17:10:12.302] [DEBUG] Disconnected. 🀄️ Token is expired
```

After this the logs go silent and all subscriptions are silent. I assume that I need to make a request via the Client to trigger a token refresh, but we only use it for subscriptions. What would be the appropriate pattern to force a token refresh? Thanks!

gz#5502

**Comment by b-onc** [comment]
Hello @amardeepranu 
Can you share the code snippet where you're setting up the client and setting the user?

**Comment by amardeepranu** [comment]
```
getStreamInfo { [weak self] streamInfo in
            guard let streamInfo = streamInfo else {
                return
            }

            if self?.isConfigured == false {
                Client.configureShared(.init(apiKey: streamInfo.apiKey, logOptions: .info))
            } else {
                Client.shared.apiKey = streamInfo.apiKey
            }

            Client.shared.set(user: User(id: streamInfo.streamId), tokenProvider: tokenProvider) { result in
                if !result.isSuccess {
                    log("Setting user failed with error \(String(describing: result.error))")
                    return
                }

                completion()
            }
        }


private lazy var tokenProvider: StreamChatClient.TokenProvider = { [weak self] tokenCallBack in
        self?.getStreamInfo({ (streamInfo) in
            guard let streamInfo = streamInfo else {
                return
            }

            tokenCallBack(streamInfo.token)
        })
    }
```

Token provider is called for the first token fetch by the Stream client so I can confirm that it's configured correctly. However, it doesn't get recalled after disconnecting. I'm only using the client for the following subscription:

```
unreadCountSubscription = Client.shared.subscribeToUnreadCount { count in
            DispatchQueue.main.async {
                completion(count.messages)
            }
        }
```

Also, the workaround for this issue is to call setUser again when the client is disconnected (using Client.shared.isConnected)

**Comment by amardeepranu** [comment]
@b-onc thanks for the quick turnaround! Possible to get a new release soon? This would allow me to clean up a lot of client code on my end

**Comment by b-onc** [comment]
@amardeepranu We are aiming for a release early next week
