### ISSUE TITLE
Attachment '+' button doesn't appear when chat channel is first created

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#437]
## What did you do?
Create a new chat channel and navigate to it from ChannelsViewController

## What did you expect to happen?
I expect the '+' button in ComposerView to be immediately visible

## What happened instead?
The '+' button in ComposerView isn't visible until I exit the chat and re-enter

## GetStream Environment
**GetStream Chat version:**
2.2.6
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context

gz#5575

**Comment by b-onc** [comment]
Hello @srgray 
Can you share an example project, or at least the code snippets?
The issue is not reproducible on latest version (2.2.9), can you try that?

**Comment by srgray** [comment]
In trying to reproduce this in an example project, I realized the bug is in my code where I conditionally set `ChatViewController.defaultComposerAddFileTypes`.
Sorry for the false alarm and thanks for looking into this.
