### ISSUE TITLE
Support multiple avatars in AvatarView for group message channels

### ISSUE THREAD

**Issue by srgray** [GetStream/stream-chat-swift#458]
## What are you trying to achieve?
For channels with more than 2 members, it would be nice if the iOS SDK would display multiple avatar images, like the Android SDK does.
See example:
![Screenshot_1599064220](https://user-images.githubusercontent.com/4721220/92011535-ccd51e00-ed10-11ea-9f5f-350a6ab9bb6d.png)

## If possible, how can you achieve this currently?
I don't know of a way to do this currently

## GetStream Environment
**GetStream Chat version:** 2.2.9
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## Additional context

gz#5710

**Comment by b-onc** [comment]
Hello @srgray 
UI SDK 2.x doesn't support this, but UI SDK 3.0 will support this, it's in our roadmap.
