### ISSUE TITLE
How can I prevent users from deleting/editing their messages?

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#48]
Hi, 
we want to remove option for users to delete or edit their own messages. I found `Permissions` in chat settings and I configured it as on the screenshot below but users can still delete their messages. Are permissions implemented? :) Or is there another way to disable these functionalities?
![Screenshot 2020-01-02 at 12 40 10](https://user-images.githubusercontent.com/7826664/71665392-12de7a00-2d5d-11ea-9016-f03e952aa911.png)

**Comment by tbarbugli** [comment]
At the moment permissions are enforced by the API but are not reflected by the UI; this means that you need to disable / hide the delete action for a message . @buh can you share some advice on how to do this (probably good to add this to FAQ as well)

**Comment by buh** [comment]
Hi @mpodeszwa at the current version of SDK you can override the method:
```swift
func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath)
```
I'll add some improvements message menu customization.

**Comment by buh** [comment]
Please check the `master` branch. Here are upcoming changes: https://github.com/GetStream/stream-chat-swift/blob/master/CHANGELOG.md

`ChatViewController` has `defaultMessageActions` you can override in your subclass or just change value of `messageActions` property. There are options:
```swift
.reactions, 
.reply, 
.edit, 
.muteUser, 
.flagMessage, 
.flagUser, 
.banUser, 
.copy, 
.delete
```
For example to enable only `.reactions` and `.copy`:
```swift
var messageActions: MessageAction = [.reactions, .copy]
```

**Comment by mpodeszwa** [comment]
Awesome, Thanks @buh !

**Comment by WayneFilmalter** [comment]
i want to do the same but in typescript
