### ISSUE TITLE
StreamChat Roadmap

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/stream-chat-swift#54]
General discussion about the roadmap for the iOS library, let us know your thoughts. 

1. The low level client should be usable if you're not using RXSwift

**Comment by buh** [comment]
We are working on the low level client and extension for a classic way for API. I thought it will be 1.6.0
2.0.0 -> Offline

**Comment by tschellenbach** [comment]
renamed it

**Comment by saurabhPV** [comment]
> General discussion about the roadmap for the iOS library, let us know your thoughts.
> 
> 1. The low level client should be usable if you're not using RXSwift

This is important for us too because we need to build an app extension and can not include stream core pod in it because RxAppstate uses  UIApplication.shared so it throws error

> 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

**Comment by buh** [comment]
Hi @saurabhPV!
We are working hard to release 2.0. You can check [2.0-alpha here](https://github.com/GetStream/stream-chat-swift/tree/release/2.0) and we removed `RxAppstate` dependency.

| Framework | Dependencies | Description |
| --- | --- | --- |
| **StreamChatClient** | `Starscream` `GzipSwift` | low-level Client |
| **StreamChatCore** | `RxSwift` `RxCocoa` `ReachabilitySwift` | Core framework with presenters, Internet connection, app state and etc |
| **StreamChat** | `Nuke` `SnapKit` `SwiftyGif` `RxGesture` | UI framework |

**Comment by saurabhPV** [comment]
Thank you @buh I will try and let you know!

**Comment by khoogheem** [comment]
How about updating the podspecs for 2.0 to allow for the 5.1.X of RX which will help in removing the extensions for UIWebView and stop the annoying review messages. the ~> x.x.x seem too restrictive...

**Comment by khoogheem** [comment]
as well Reachability is up to 5.X as well

**Comment by b-onc** [comment]
Hello @khoogheem , thanks for the suggestion. It definitely makes sense to update our dependencies with the new version.

**Comment by khoogheem** [comment]
@b-onc BTW unless 2.0 will be updated sometime soon.. we will need a 1.X version that allows the RX to be at 5.1.X... as that is the version that remove the UIWebView, which Apple has said it will stop allowing Submissions sometime in April 2020

**Comment by b-onc** [comment]
@khoogheem I'm currently uploading 2.0 :) Stay tuned!

**Comment by stunjiturner** [comment]
I have seen one issue related to swiftui, has anybody worked with the SDK and swiftui?

**Comment by koishi** [comment]
Hi
I'm currently using 2.0 for my app and developing it.
There is a bug in getting the number of unreads.
When will a version that fixes these issues be released?

**Comment by VojtaStavik** [comment]
Hi @koishi, we're in the process of releasing a new version, and it should be public within a day or two. We fixed a couple of bugs related to the unread message count in it. Once it's out, please let me know if your issue is fixed. Feel free to open a new issue for that, if not.

**Comment by b-onc** [comment]
Closing since we've changed our roadmap towards a new architecture (3.0)
Please open a feature request or issue for any queries.
