### ISSUE TITLE
`Remove(members:from:_)` not removing member properly.

### ISSUE THREAD

**Issue by mlanoy** [GetStream/stream-chat-swift#568]
## What did you do?
Using `Remove(members:from:_)` from a channel to remove a particular member.

## What did you expect to happen?
The corresponding member should be removed.

## What happened instead?
The member is actually removed as it happens but when fetching channels from this user using `Filter.currentUserInMembers`, the channels where the user was removed are still there, even though he is NOT in the `members` property of the channel.
Quick and dirty fix for me is to make `membership` property on `Channel` public (Pod forking so...) and filter because I cannot rely on `members` to check if current user is there because it is paginated.
Moreover, if we want to check if the current user is member of a channel using `queryMembers`, the response object (`MembersQueryResponse`) got only a `members` attribute which is not public. This endpoint is not usable as it is.
## GetStream Environment
**GetStream Chat version: 3.4.1
**GetStream Chat frameworks:** StreamChatCore
**iOS version:14.x
**Swift version: 5.1
**Xcode version: 12.0
**Device: iPhone 6S Max, iPhone 8, iPhone X

gz#6871

**Comment by mlanoy** [comment]
Moreover, even if this user is added again in the channel afterwise, it seems that he cannot receive any `notificationMessageNew` event, just as if he is not a member of the channel.

**Comment by b-onc** [comment]
Hello @mlanoy 

Thanks for the bug report. It's a backend issue, I'm in touch with our backend engineers about this. Will update this ticket when it's resolved.

**Comment by mlanoy** [comment]
thanks @b-onc 

I've just added something about `queryMembers` (`members` attribute is not public)

**Comment by b-onc** [comment]
Thanks @mlanoy , for the 2 properties I've opened #574

**Comment by mlanoy** [comment]
thanks a lot ^^

**Comment by b-onc** [comment]
Hello @mlanoy 
Are you still seeing this behavior?

**Comment by mlanoy** [comment]
Ok, it seems fixed. Thanks.
