### ISSUE TITLE
Only start to get notifications after switching to chat tab

### ISSUE THREAD

**Issue by nin-echo** [GetStream/stream-chat-swift#599]
## What did you do?
1. I implement chat view controller under a tab controller (3rd tab)
2. Followed the getstream.io doc steps about notifications
3. successfully get notification permissions from users on home view controller (1st tab)

## What did you expect to happen?
Able to get chat notifications after getting users' permission

## What happened instead?
1. If I didn't switch to the chat tab, just stay in other tabs, then put app to background, I will never get chat notifications when new messages come in
2. If I switch to the chat tab, and put app to background, I will be able to get the chat notifications

## GetStream Environment
**GetStream Chat version:** 2.4.1
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14.1
**Swift version:** 5
**Xcode version:** 12.3 beta
**Device:** iPhone 12 Pro Max

## Additional context

gz#7488

**Comment by b-onc** [comment]
Hello @nin-echo ,

When are you calling `Client.shared.addDevice`?

This sounds like a problem regarding how you're setting up the "chat" tab.
It'd be ideal if you can provide a quick sample app to reproduce this.

**Comment by nin-echo** [comment]
Hello @b-onc ,

I called addDevice in AppDelegate's `didRegisterForRemoteNotificationsWithDeviceToken` method. 
I've looked into it and found it wasn't called before somehow. It has been solved right now.

Thank you!
