### ISSUE TITLE
Composer is not visible if ChatViewController is offset from the top

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#6]
## What did you do?

On my application ChatViewController doesn't start from the top, it has offset.

## What did you expect to happen?

When keyboard appears composer should move up so user can see his message while typing

## What happened instead?

Composer is under keyboard, user can't see textfield when keyboard is open

## Additional context

I created branch to show the problem:
https://github.com/mpodeszwa/stream-chat-swift/commits/demo/vc-offset

![Simulator Screen Shot - iPhone Xs - 2019-09-02 at 15 10 27](https://user-images.githubusercontent.com/7826664/64117033-5667ae00-cd94-11e9-9bc6-78efe33a0a97.png)

![Simulator Screen Shot - iPhone Xs - 2019-09-02 at 15 15 21](https://user-images.githubusercontent.com/7826664/64117096-83b45c00-cd94-11e9-9423-c630d5c63860.png)

**Comment by buh** [comment]
Hi @mpodeszwa!
It's weird, I'll make a fix in the next release. Please fix your fork like that:
here:
https://github.com/GetStream/stream-chat-swift/blob/master/Sources/UI/User%20Story/Chat/Composer/ComposerView.swift#L261-L262

to:
```swift
                let bottom: CGFloat = style.edgeInsets.bottom
                    + max(0, height - (height > 0 ? .safeAreaBottom + self.toolBar.frame.height : 0))

```

**Comment by buh** [comment]
Fixed in v.1.2.9
