### ISSUE TITLE
Unable to send message with attachment.

### ISSUE THREAD

**Issue by DanyloPolishchuk** [GetStream/stream-chat-swift#611]
## What did you do?
(In ChatViewController) Tap "+" button -> Select "Upload a photo or video" -> select a photo -> selected photo appears in collectionView in composerView and starts uploading. once image is uploaded sendButton becomes enabled -> I tap on "sendButton" -> composerView resets

## What did you expect to happen?
I expected a new message with an image attachment to show up in chat

## What happened instead?
if i enter some text in composerView textView in addition to attached image then a new message is shown but only with text, no image attached.
if i only attach image and then tap on sendButton nothing shows in chat.

## GetStream Environment
**GetStream Chat version:** 2.4.1
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 13.4.1
**Swift version:** 5
**Xcode version:** 11.4.1
**Device:** ANY

## Additional context

Same happens when instead of image, file is attached to a message and sent. 
Other message variations (message with link/YouTube link/image link) work as supposed to. 

As far as I've researched the problem is rather in
- **`composerView.reset()`** (which calls `uploadManager?.reset()` and resets `public private(set) var images: [UploadingItem] = []` and `public private(set) var files: [UploadingItem] = []` arrays ) 
**being called before `createMessage(with: text`** that leads to message being created without any attachments.

**OR**

- in **`item.attachment`** still somehow being **nil after successful `startUploading(item:` completion** in spite of response logs with uploaded attachment url 
`{
  "duration" : "257.41ms",
  "file" : "https:\/\/stream-chat-us-east-c7.imgix.net\/99234\/images\/ddf16731-9d34-4641-b7c6-1b14dfa4fa1b.IMG_0004.JPG?ro=0&s=9d1267b05b7d9003e13012bb9398b43a"
}`

gz#7618

**Comment by b-onc** [comment]
Hello,

This is a known issue in 2.4.1 and was fixed in 2.4.2
