### ISSUE TITLE
Can activity feeds be used with Objective-C?

### ISSUE THREAD

**Issue by haarj** [GetStream/stream-chat-swift#645]
Can activity feeds be used with Objective-C?

gz#8017

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/8017'>Zendesk ticket #8017</a>:<br><br>Hi there,

Yes, but you'll need to take advantage of our REST API. I'll link you to that documentation here: https://getstream.io/chat/docs_rest/

**Comment by b-onc** [comment]
Hello @haarj 
Firstly, this is Chat SDK, you're asking about https://github.com/GetStream/swift-activity-feed

There's no official Obj-C support as of yet.
