### ISSUE TITLE
Search. 500 error when query text contains two spaces in a row

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#651]
```
let filter = Filter.currentUserInMembers
let query = SearchQuery(filter: filter,
                                query:"test  test",
                                pagination: [.channelsPageSize])
Client.shared.search(query: query) { (result) in ..... 
```

The answer is 500 status.

## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone 12 Pro Max

gz#8050

**Comment by Kravet** [comment]
Same happens when on Android SDK.

**Comment by b-onc** [comment]
Hello all,

This is backend issue so I'm relaying this to them, will keep this ticket updated.

**Comment by b-onc** [comment]
Backend team informs me this bug is fixed, so closing this ticket.

**Comment by lexin** [comment]
Yes, it works properly now. Thanks!
