### ISSUE TITLE
Search.  SearchQuery looks for whole word, not the containing. 

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#652]
I am using the next code for searching messages
```
        let text = "test" 
        let filter = Filter.currentUserInMembers
        let query = SearchQuery(filter: filter,
                                query: text,
                                pagination: [.channelsPageSize])
        Client.shared.search(query: query) { (result) in
```

If I have some messages with the word "test" they are included in the response if the query is "test". But if I put "tes" or "est" they aren't. We checked Android SDK as well, it seems that in that SDK all cases return messages with "test". 
We can guess that the search engine is different (match vs contain). 
Do we have a possibility to change the search rule on iOS? Some additional parameters or something like that? 
Or it's an issue and could be fixed? 

## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone 12 Pro Max

gz#8051

**Comment by Kravet** [comment]
Yes, same happens on Android SDK.

**Comment by cardoso** [comment]
Hi @lexin @Kravet , in order to get the behavior you described on iOS, you should use `messageFilter` with `autocomplete`: 

```swift
let text = "tes"
let filter = Filter.currentUserInMembers
let query = SearchQuery.init(filter: filter,
                             messageFilter: .autocomplete("text", with: text),
                             pagination: [.channelsPageSize])
Client.shared.search(query: query) { (result) in

}
 ```

Let us know if that helps :)

**Comment by lexin** [comment]
Thanks!
