### ISSUE TITLE
ChatViewController. Layout overlaps if user uploads Photo file & Video in one message

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#654]
Layout overlaps if user uploads Photo file & Video in one message
![IMG_2589](https://user-images.githubusercontent.com/367295/102199072-d7847f00-3ecb-11eb-875c-20dec58d78e5.PNG)

## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone XS

gz#8055

**Comment by lexin** [comment]
There are other issues. 
1. If user selects photos and videos and try to touch the plus button in left bottom corner - the menu with options for attachments is under the message preview. It’s not possible to select anything

**Comment by lexin** [comment]
2. If user selects photo and several videos it brakes the layout. Also user is not able to press send button

**Comment by lexin** [comment]
3. If user sends photos and videos is one message - only photos are added to the mesasge ahen it's sent.

**Comment by lexin** [comment]
Tested with v. 2.6.3

**Comment by lexin** [comment]
May we reopen the issue or create new one?

**Comment by lexin** [comment]
Can you help me, please? Is it released in any updates? we use 2.6.3 version now. Can't fin in your release notes this fix.

**Comment by kcollignon** [comment]
@lexin your question on video might similar to one i asked, #1173 - it looks like this isn't supported yet unfortunately

**Comment by b-onc** [comment]
@kcollignon Video attachments are supported in 2.x, but not yet in 4.0, @lexin reported a bug with 2.x. Due to spending majority of our time towards development of 4.x, we couldn't allocate time to fix the 2.x bug, but we'll get to it, so we're keeping the issue open. Thanks for understanding 🙌

**Comment by b-onc** [comment]
Hello @lexin ,

Happy to report that all issues are resolved via 2.6.8 release
