### ISSUE TITLE
ChatViewController. Uploaded file's preview is NOT visible on Edit Message

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#655]
Currently, file's preview is present only if user adds the message. - It's absent on message editing

![IMG_82B82724BC66-1](https://user-images.githubusercontent.com/367295/102199681-917beb00-3ecc-11eb-9ca5-db02838e23de.jpeg)
## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone XS

gz#8056

**Comment by b-onc** [comment]
Hello @lexin 
This feature will only be included in v3 StreamChatUI SDK, which is currently in beta.

**Comment by lexin** [comment]
thanks
