### ISSUE TITLE
ChatViewController. Localization for texts.

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#658]
Is it possible to use some strings as keys for localization on ChatViewController? We would like to show texts in other languages. For example "Write a message" placeholder in a textfield, or menu items. 
We will provide translates by ourselves, the only questions - keys for localizations. 

## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone 12 Pro Max

gz#8061

**Comment by b-onc** [comment]
Hello @lexin 
Localization is a v3 only feature and will not be implemented for v2. Please check StreamChatUI (currently in Beta) out!

**Comment by lexin** [comment]
Thanks, got it!
