### ISSUE TITLE
Crash when presenting UIDocumentMenuViewController inside web view

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#66]
## What did you do?

- I've received message containing link to [https://ahoy.io/getpassbook/](https://ahoy.io/getpassbook/)
- I clicked on the link and chat presented webview
- I clicked on button "Select file" (it's a file picker)
- App crashed with exception:
```
Your application has presented a UIDocumentMenuViewController (<UIDocumentMenuViewController: 0x154bc92b0>). In its current trait environment, the modalPresentationStyle of a UIDocumentMenuViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.
```

## What did you expect to happen?

No crash :)

## What happened instead?

It crashes on iPhone 11 Pro Max (iOS 13.3), doesn't crash on iPhone 5s (iOS 12.4). I didn't check more devices.

## GetStream Environment
**GetStream Chat commit:** ad9e3c82d4dc5de93dfc6888606c8a4dac0276e6
**iOS version:** 13.3
**Swift version:** 5.1
**Xcode version:** 11.3.1
**Device:** iPhone 11 Pro Max

**Comment by b-onc** [comment]
Hello @mpodeszwa ,

Thanks for the excellent issue description, it's easily reproducible. We'll investigate and fix this, hopefully in 1.5.5 :)
