### ISSUE TITLE
ChatViewController. Sending message animations are not aligned.

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#661]
1. If user swipes down the page (to hide the keyboard), - message field goes to the bottom sharply. It would be nice if keyboard is hidden and Message area is shifted smoothly. 
2. If user writes first(second) message in a channel, - this message is hidden under header after sending
3. If possible, it would be great, to have reduced space between message field and keyboard

Please take a look at videos in zip

[videos.zip](https://github.com/GetStream/stream-chat-swift/files/5695301/videos.zip)

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone XS

gz#8063

**Comment by b-onc** [comment]
Hello @lexin 
These issues are related to how ChatViewController is displayed. It'd be great if you can provide a sample project, having the same view hieararchy as the videos.

**Comment by VojtaStavik** [comment]
Closing this issue for now because of inactivity. Please re-open in case you have more information. Thank you 🙏
