### ISSUE TITLE
ChatViewController. Incorrect background on dark mode if message is focused with 3d-touch 

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#663]
Really minor thing, but still.  If the user calls a menu from the message, the background becomes black and with corners. 
Please, take a look at video in a zip 

[RPReplay_Final1606135794.MP4.zip](https://github.com/GetStream/stream-chat-swift/files/5695354/RPReplay_Final1606135794.MP4.zip)

## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone XS

gz#8065

**Comment by b-onc** [comment]
Hello @lexin 
Thanks for finding & reporting this. We're tracking this issue internally and will fix it in the future.
