### ISSUE TITLE
StreamChatClient.ChannelExtraDataCodable doesn't contain custom field on iOS

### ISSUE THREAD

**Issue by lexin** [GetStream/stream-chat-swift#669]
When we create the channel via API we add a custom property "description", which user enters on UI. 
After that we make a query to get the channels. 
The answer in Xcode console contains whole data and presents it in a log, but when I use the response object StreamChatClient.Channel and try to get _extraData_ property, it contains _name_ and _imageUrl_ only

<img width="1185" alt="Screenshot 2020-12-17 at 14 38 57" src="https://user-images.githubusercontent.com/367295/102489209-d3946080-4075-11eb-8c75-40f492d124d2.png">

**At the same time, Android SDK contains  _description_ when making the same query.** 

![image (2)](https://user-images.githubusercontent.com/367295/102489175-c9726200-4075-11eb-827c-d20c129cd4d0.png)

Is it an issue that extraData doesn't contain this value?

## GetStream Environment
**GetStream Chat version:** 2.4.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
**iOS version:** 14
**Swift version:** 5
**Xcode version:** 12.2
**Device:** iPhone 12 Pro Max

gz#8113

**Comment by VojtaStavik** [comment]
Hi @lexin , thank you for reaching out. `ExtraData` is a default implementation of the `ChannelExtraDataCodable` protocol. To add your own fields, your custom type should conform to this protocol:
```swift
struct CustomChannelData: ChannelExtraDataCodable {
    // Required
    var name: String?
    var imageURL: URL?
    
    // Custom
    let myField: String
}

// This has to be done just once but *before* you do anything with the client
Channel.extraDataType = CustomChannelData.self
```

More info can be found here https://getstream.io/chat/docs/ios_custom_data/?language=js. Let me know if this helps.

**Comment by lexin** [comment]
Yeah. It works! Thanks a lot!
