### ISSUE TITLE
A Web Socket connection id is empty. Authorization missed

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#70]
Occasionally our users get an error "A Web Socket connection id is empty. Authorization missed". Usually it happens right after application is becoming active (after being in background), sometimes up to 20 seconds after becoming active. Do you know what may be happening?

## GetStream Environment
**GetStream Chat commit:** ad9e3c82d4dc5de93dfc6888606c8a4dac0276e6
**iOS version:** 13.3
**Swift version:** 5.1
**Xcode version:** 11.3.1
**Device:** iPhone XS

(device and ios version from sample report)

**Comment by buh** [comment]
Hi @mpodeszwa 
Can you tell me do you use expired tokens?

**Comment by mpodeszwa** [comment]
Hi @buh , we use tokens without expiration date

**Comment by saurabhPV** [comment]
I am having the same problem however I have observed it happens when the network connection is unstable or absent for brief period.

**Comment by buh** [comment]
@mpodeszwa  thank you for the report. Can you reproduce the issue? Did you try with the latest version to reproduce the issue? We will investigate it.

**Comment by mpodeszwa** [comment]
Unfortunately I couldn't reproduce it. I just saw few events in our logs. For us, it happens only after coming back from the background. Maybe it's caused by unstable internet connection as @saurabhPV suggests.

**Comment by buh** [comment]
Hi @mpodeszwa, we're able to replicate this issue and working on a fix.

**Comment by buh** [comment]
@mpodeszwa we have a fix for that. The PR in review and it will be in the next release with nested frameworks issue.

**Comment by mpodeszwa** [comment]
awesome, thanks :)
