### ISSUE TITLE
`channel.create` consistently fails when called as response to user opening a push notification

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#710]
## What did you do?
As a response to user tapping the push notification, I attempt to create (query) the channel:
```swift
let channel = Client.shared.channel(type: .messaging, id: reference.channelId)
channel.create { [weak self] result in
         // show the `ChannelsViewController` or handle failure
}
```

This works fine when it happens after the app is opened for a while.

## What did you expect to happen?
`result` to be a success

## What happened instead?
`result` is a failure with `ClientError.emptyConnectionId` error

It seems that maybe the websocket isn't yet established at the point when we call `channel.create`. 

Isn't SDK supposed to be handling this internally and waiting for the websocket to be established? Also, why is `create` a call that requires the websocket at all?

## GetStream Environment
**GetStream Chat version:**
2.6.1

**GetStream Chat frameworks:** 
StreamChatClient, StreamChatCore, StreamChat

**iOS version:**
14.3

**Xcode version:**
12.3

**Device:**
iPhone 11

## Additional context

gz#8341

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8341'>Zendesk ticket #8341</a>:<br><br>Hi,

Thanks for reaching out! We will look into this and get back to you as soon as possible.

Best,
Ryan

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8341'>Zendesk ticket #8341</a>:<br><br>Hi,

Could you please provide your AppID and organization name in Stream?

Best,
Ryan

**Comment by cardoso** [comment]
Hi @MatejBalantic !

The backend needs a websockets connection id to forward the resulting events. Before making the call, you can check if the client is connected with `Client.shared.isConnected`. If it's `false`, you should call `Client.shared.set(user:)` and make the `channel.create` call inside the completion block.

**Comment by b-onc** [comment]
Hello @MatejBalantic 
To add on my collegue's answer, `create` is just `queryChannel`, you can query the channel yourself without any options to create the channel without connection id required.
```swift
channel.query(options: []) { _ in
    // ...
}
```
