### ISSUE TITLE
Not receiving local push notifications

### ISSUE THREAD

**Issue by MatejBalantic** [GetStream/stream-chat-swift#711]
## What did you do?
Testing push notifications

## What did you expect to happen?
Push notifications work reliably:
1. when app has been killed/backgrounded for significant time
2. when app is in the foreground
3. when app has been backgrounded just now

## What happened instead?
Push notifications only work reliably in the first case. 

Reading the docs I assume the second case isn't supported, so a filled a separate [feature request](https://github.com/GetStream/stream-chat-swift/issues).

However in the third case (when app has been backgrounded just now), push notifications never seem to be sent. As far as I understand the setup, those should be sent locally by the backgrounded app, but they are not.

## GetStream Environment
**GetStream Chat version:**
2.6.2

**GetStream Chat frameworks:** 
StreamChatClient, StreamChatCore, StreamChat

**iOS version:**
14.3

**Xcode version:**
12.3

**Device:**
All devices

## Additional context

As a workaround, we have set the `stayConnectedInBackground` to `false`. This basically forces the client to disconnect, so that remote push notifications start being sent immediately after background. It's a good enough workaround, but the reconnections when app is foregrounded seem to be pretty costly, so I would rather get the local push notifications working.

Even better would be if you solve entire thing with remote push notifications (see the feature request referenced above). There is no reason why push notifications should not be send from remote server at all times, and then client can decide which ones to show.

However, I understand that requires infrastructural changes, so for now it would be great if you can help me troubleshoot why local push are not being sent.

I am currently handling all push notifications manually, so I am not using any of the `Notifications.shared` methods. Ideally I'd like that to continue because we have a need to mix/match push notifications from GetStream and our own.

gz#8342

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8342'>Zendesk ticket #8342</a>:<br><br>Hi,

Thank you for providing this information! It is very helpful. I will take a look at this and get back to you shortly.

Best,
Ryan

**Comment by cardoso** [comment]
Hi @MatejBalantic !

When your app is connected it won't receive remote notifications. You need to display the local notification manually and we provide helper methods for that in the `Notifications` class.

You can show a local notification using `Notifications.shared.showIfNeeded(newMessage: message, in: channel)` or `Notifications.shared.show(newMessage: message, in: channel)` if you want to bypass the default checks.

**Comment by cardoso** [comment]
Hi @MatejBalantic ! Closing this one due to inactivity. Let us know if you still have the issue and I'll re-open it.

**Comment by ajay-simform** [comment]
@cardoso Found same issue with push notification.
Push notification received only when app is killed. It should receive notification even in foreground or background mode.
@cardoso  I did not find `Notifications` helper class in streamchat repo.
could you please help me out to elevate this issue?

**Comment by b-onc** [comment]
Hello @ajay-simform ,

Push notifications are not delivered when WS connection is alive, that is, app is active. You need to subclass `EventsController`, observe `MessageNewEvent` and display a local notification yourself.

**Comment by ajay-simform** [comment]
Thank you @b-onc
