### ISSUE TITLE
Malformed call to /users endpoint without team filter on SDK launch

### ISSUE THREAD

**Issue by Aurazion** [GetStream/stream-chat-swift#729]
## What did you do?
Everytime the SDK tries to connect, it does a call to the `/users` API endpoint, which result to the following `403` error :

```
HTTP/1.1 403 Forbidden
Server: fasthttp
Date: Mon, 11 Jan 2021 17:57:58 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 190
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Access-Control-Allow-Headers: x-requested-with, content-type, accept, origin, authorization, x-csrftoken, x-stream-client, stream-auth-type, x-csrf-token, content-encoding
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Cache-Control: no-cache
X-Ratelimit-Limit: 1000
X-Ratelimit-Remaining: 998
X-Ratelimit-Reset: 1610387880
Content-Encoding: gzip
Keep-Alive: timeout=58, max=1000
Connection: keep-alive

{"code":17,"message":"QueryUsers failed with error: \"you must include a team filter to use this endpoint client-side\"","StatusCode":403,"duration":"0.00ms","more_info":"https://getstream.io/chat/docs/api_errors_response"}
```

## What did you expect to happen?
No API call to this endpoint on SDK init.

## GetStream Environment
**GetStream Chat version:**
2.6.2

**GetStream Chat frameworks:**
StreamChatClient

 **iOS version:**
14.3

 **Xcode version:**
12.3

**Device:**
All devices

## Additional context

Here is the line which make the API call without team filter :
https://github.com/GetStream/stream-chat-swift/blob/8d9ef364e9685a02d601bad9ef50a249f17c08b5/Sources/Client/Client/Client.swift#L260

gz#8547

**Comment by shodgetts** [comment]
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8547'>Zendesk ticket #8547</a>:<br><br>Hi,

Thanks for reaching out! I will look into this as soon as possible and get back to you shortly. Please let me know if you have any other questions in the meantime.

Best,
Ryan
