### ISSUE TITLE
Allows customising the Message before displaying the MessageTableViewCell

### ISSUE THREAD

**Issue by Truzicka** [GetStream/stream-chat-swift#773]
## What are you trying to achieve?
We want to have rich text displayed in the MessageTableViewCell in conjunction with end-to-end encryption using Virgil.

Currently, the message text enrichment is done in the internal function `func willDisplay(cell: UITableViewCell, at indexPath: IndexPath, message: Message)` from _ChatViewController+Cells.swift_
The message object text is encrypted and need to be decrypted before being passed to the function `enrichText`, otherwise the sdk fails to enrich it.
As the message object comes from the _ChatViewController_ `items` property, which cannot be edited outside the sdk, it is currently not possible to have rich text with end-to-end encryption.

## If possible, how can you achieve this currently?
Not possible currently without overwriting the sdk _ChatViewController+Cells.swift_ file

## What would be the better way?

A simple solution would be to declare public the function `func willDisplay(cell: UITableViewCell, at indexPath: IndexPath, message: Message)` so we we can manually call it, and pass a message object with the text decrypted.

## GetStream Environment
**GetStream Chat version:** 2.6.3
**GetStream Chat frameworks:** StreamChat
**iOS version:** Any
**Swift version:** 5
**Xcode version:** 12.3
**Device:** Any

gz#8962

**Comment by b-onc** [comment]
Hello @Truzicka ,
We have a tutorial for just this case: https://getstream.io/blog/ios-cryptokit-framework-chat/
Can you check it and let me know the solution described in that works for you case, and if not why?

**Comment by Truzicka** [comment]
Hello @b-onc,

we have the e2e encryption working, but we also want to display rich text (like clickable link or bold text).

This is because the message enrichment is done from the sdk method `willDisplay(cell: UITableViewCell, at indexPath: IndexPath, message: Message)` and is called from
```
   open func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        guard indexPath.row < items.count else {
            return
        }
        
        let item = items[indexPath.row]
        
        if case .loading(let inProgress) = item {
            if !inProgress {
                items[indexPath.row] = .loading(true)
                presenter?.loadNext()
            }
        } else if let message = item.message {
            willDisplay(cell: cell, at: indexPath, message: message)
        }
    }
```
The message object passed to willDisplay is coming directly from the items which contains the messages with the text encrypted. So the enrichment at `ChatViewController+Cells.swift:175` does nothing, as it's applied on the encrypted text.

A simple solution would be to declare public the function `func willDisplay(cell: UITableViewCell, at indexPath: IndexPath, message: Message)` so we we can manually call it, and pass a message object with the text decrypted.

**Comment by b-onc** [comment]
@Truzicka Wouldn't mutating `message.text` in `tableView(:willDisplay:forRowAt:)` before calling `willDisplay` work for you?

**Comment by Truzicka** [comment]
yes it would, but how can we access the message from tableView(:willDisplay:forRowAt:) ? (maybe I wasn't clear, but the code I showed above is coming from the sdk file `ChatViewController.swift`)
and this is the declaration of the `items` (also coming from the sdk file `ChatViewController.swift`) so we cannot mutate the items messages
`public private(set) var items = [PresenterItem]()`
