### ISSUE TITLE
DemoApp - Standard Library Issues

### ISSUE THREAD

**Issue by WayneEld** [GetStream/stream-chat-swift#783]
## What did you do?
Attempted to install and run the DemoApp

## What did you expect to happen?
Demo application would run after SPM install.

## What happened instead?
Build failed with error "<unknown>:1:1: unable to load standard library for target 'x86_64-apple-macosx10.15'" and "SwiftLint:1:1: manifest parse error(s):". 

## GetStream Environment
**GetStream Chat version:**
3.0
**iOS version:**
14.3
**Swift version:**
5.3.2
**Xcode version:**
12.4
**Device:**
Simulator (iPhone 12)

## Additional context
If my memory recalls correctly this was a problem when using the Xcode 12 beta's when they were released... It had to do something with excluding certain architectures in the build settings (excluding arm64 for example). However, my memory fails me and I do need some help.

Thanks.

gz#9020

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out.
The Swift demo app requires the following versions: https://github.com/GetStream/stream-chat-swift-demo#requirements
We haven't updated the demo app with the stream-chat-swift v3 as the UI client is still in beta version.
Our team will update the docs and tutorial as soon as the final version is released.

Best regards,
