### ISSUE TITLE
Messages if not a member

### ISSUE THREAD

**Issue by WayneEld** [GetStream/stream-chat-swift#788]
## What did you do?
Getting channel via channel id: `ChatClient.shared.channelController(for: ChannelId(type: .messaging, id: "general"))`

## What did you expect to happen?
Expected to get the messages from the 'general' channel.

## What happened instead?
Error appeared "[com.apple.NSURLSession-delegate] [RequestDecoder.swift:71] [decodeRequestResponse(data:response:error:)] > keyNotFound(ChannelCodingKeys(stringValue: "member_count", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "channel", intValue: nil)], debugDescription: "No value associated with key ChannelCodingKeys(stringValue: \"member_count\", intValue: nil) (\"member_count\").", underlyingError: nil))"

User is not a member of that channel but still can't get the channel instance. Do I need to be a member of the channel to get the messages from it? I would assume not.

## GetStream Environment
**GetStream Chat version:**
3.0.0
**iOS version:**
14.3
**Swift version:**
5.3.2
**Xcode version:**
12.4
**Device:**
iPhone 11

## Additional context
If I need to be a member of the channel to get the messages then this may be void.

**Comment by b-onc** [comment]
Hello @WayneEld ,
You're right, user doesn't have to be a member. We're looking into this

**Comment by b-onc** [comment]
I've learned that this is already fixed in main branch, can you try and let me know if it works?

**Comment by WayneEld** [comment]
@b-onc thanks. I did try when the PR was opened, about 15 minutes ago.  Anything else I should try to debug it?

**Comment by VojtaStavik** [comment]
Hi @WayneEld , This problem happens when there are no users in the channel. The issue should be fixed in https://github.com/GetStream/stream-chat-swift/pull/782. It mas merged after we cut the latest release. The next beta release should happen again on Friday this week. Can you try the version directly from `main` in the meantime?

**Comment by WayneEld** [comment]
@VojtaStavik I can confirm that this is now working. Thanks for the quick response time.
