### ISSUE TITLE
Channel.Config never gets updated

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#8]
## What did you do?

I'm creating ChannelPresenter using code:
```
let channel = Channel(type: type, id: id, name: name)
let channelPresenter = ChannelPresenter(channel: channel)
```

When first query succeeds framework is receiving response:
```
{
	"channel": {
                 ......
		"config": {
			"created_at": "2019-08-22T08:24:56.766147237Z",
			"updated_at": "2019-08-22T08:24:56.766147316Z",
			"name": "commerce",
			"typing_events": true,
			"read_events": true,
			"connect_events": true,
			"search": true,
			"reactions": true,
			"replies": true,
			"mutes": true,
			"message_retention": "infinite",
			"max_message_length": 5000,
			"automod": "disabled",
			"automod_behavior": "flag",
			"commands": [{
				"name": "flag",
				"description": "Flag a user",
				"args": "[@username]",
				"set": "moderation_set"
			}, {
				"name": "ban",
				"description": "Ban a user",
				"args": "[@username] [text]",
				"set": "moderation_set"
			}, {
				"name": "unban",
				"description": "Unban a user",
				"args": "[@username]",
				"set": "moderation_set"
			}, {
				"name": "mute",
				"description": "Mute a user",
				"args": "[@username]",
				"set": "moderation_set"
			}, {
				"name": "unmute",
				"description": "Unmute a user",
				"args": "[@username]",
				"set": "moderation_set"
			}]
		}
	},
        .......
```

## What did you expect to happen?

I expect channel's config to change according to data received from backend. 

Alternatively I need option to change config from the code (currently `Config` doesn't have public initializer and `Channel`'s initializer doesn't accept config as a parameter).

## What happened instead?

Config always stays with default values. I especially need `readEventsEnabled` to show number of unread messages on the badge (and mark messages as read)

## GetStream Environment
**GetStream Chat version:** 1.2.8
**iOS version:** 12.4
**Swift version:** 5.0
**Xcode version:** 10.3
**Device:** Any device

**Comment by tschellenbach** [comment]
Thanks for reporting this issue (and the other ones). What sort of chat app are you working on?

**Comment by mpodeszwa** [comment]
We are migrating chat in our app https://ahoy.io/ to GetStream :)

**Comment by buh** [comment]
Thanks @mpodeszwa I'll fix it soon.

**Comment by buh** [comment]
Fixed in v.1.2.9

**Comment by mpodeszwa** [comment]
@buh I think there might be a bug with this fix. Channel is now changing but event observer is set up once when creating ChannelPresenter:
```
    private lazy var webSocketChanges: Driver<ViewChanges> = channel.onEvent()
        .map { [weak self] in self?.parseChanges(event: $0) ?? .none }
        .filter { $0 != .none }
        .map { [weak self] in self?.mapWithEphemeralMessage($0) ?? .none }
        .asDriver { Driver.just(ViewChanges.error(AnyError(error: $0))) }
```
Old channel is deallocated when new channel comes from backend and first filter in `Channel.onEvent` fails, because `self` is nil

**Comment by buh** [comment]
@mpodeszwa Thanks! `onEvent` method use `channeld` to filter web socket events. I'll fix the presenter for deallocating issue.

**Comment by buh** [comment]
@mpodeszwa Fixed in v.1.2.10
