### ISSUE TITLE
Thread Reply - Demo App

### ISSUE THREAD

**Issue by WayneEld** [GetStream/stream-chat-swift#800]
Please note that the context below is for the demo app in the repo.

## What did you do?
Long pressed on a message, then tapped thread reply.

## What did you expect to happen?
A thread reply screen would appear.

## What happened instead?
Context menu with actions options disappear.

## GetStream Environment
**GetStream Chat version:**
3.0.0

**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
3 beta 4

**iOS version:**
14.4

**Swift version:**
5.3.1

**Xcode version:**
12.4

**Device:**
iPhone

## Additional context
I am not sure if thread reply needs to be enabled and is off by default. Normal reply works perfectly.

**Comment by cjmconie** [comment]
After some investigation I found:

`ChatMessageListVC`'s `didTapOnThreadReplyFor` method is simply calling dismiss.

```swift
 open func chatMessageActionsVC(
        _ vc: _ChatMessageActionsVC<ExtraData>,
        didTapOnThreadReplyFor message: _ChatMessage<ExtraData>
    ) {
        dismiss(animated: true)
        }
    }
```

I would expect it to call into a delegate method, e.g. `self.delegate?.didTapOnThreadReply?(self, message)`. 

`ChatMessageListVC.Delegate` would need to be extended to include:

```
public var didTapOnThreadReply: ((_ChatMessageListVC, _ChatMessage<ExtraData>) -> Void)?
```
