### ISSUE TITLE
Crash - Attempted to read an unowned reference

### ISSUE THREAD

**Issue by WayneEld** [GetStream/stream-chat-swift#801]
## What did you do?
Navigating through several chat view controller views. Not easily replicable.

## What did you expect to happen?
Normal channel and messages load.

## What happened instead?
App crashed. 

> Fatal error: Attempted to read an unowned reference but object 0x283d363a0 was already deallocated2021-02-05 16:45:35.114284+0200 Pulse Staging[3223:877853] Fatal error: Attempted to read an unowned reference but object 0x283d363a0 was already deallocated
Fatal error: Attempted to read an unowned reference but object 0x283d363a0 was already deallocated

Line 92 EntityDatabaseObserver
`    /// Acts like the `NSFetchedResultsController`'s delegate and aggregates the reported changes into easily consumable form.
    private(set) lazy var changeAggregator = ListChangeAggregator<DTO, Item>(itemCreator: itemCreator)
        .onChange { [unowned self] listChanges in
            log.assert(listChanges.count <= 1, "EntityDatabaseObserver predicate shouldn't produce more than one change")
            if let entityChange = listChanges.first.map(EntityChange.init) {
                self._item.reset() <- Crash Here
                self.listeners.forEach { $0(entityChange) }
            }
        }`

## GetStream Environment
**GetStream Chat version:**
3.0.0
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat
StreamChatUI 3 - beta 4
**iOS version:**
14.4
**Swift version:**
5.3.1
**Xcode version:**
12.4
**Device:**
iPhone 11

## Additional context
I haven't experienced it before but I was pushing the "demo like" chat view controllers on and off the nav stack for animation testing.

**Comment by VojtaStavik** [comment]
Hi @WayneEld , thank you for your report. I believe this was fixed 2 days ago in this PR https://github.com/GetStream/stream-chat-swift/pull/796 . Managing the lifecycle of an object across multiple threads is fun 🙃

**Comment by WayneEld** [comment]
Thanks @VojtaStavik. (All in the mind of the beholder.... but yes)
