### ISSUE TITLE
Crash on video upload > 20MB

### ISSUE THREAD

**Issue by saurabhPV** [GetStream/stream-chat-swift#81]
## What did you do?

I uploaded a video and app crashed. I see in logs, body size exceeded the limit (20M)
## What did you expect to happen?

It should not crash instead should throw error , if possible before even upload begins.

## What happened instead?
Crashed with

Thread 1: Fatal error: Binding error: responseError(StreamChatCore.ClientErrorResponse(code: 22, message: "body size exceeded the limit (20M)", statusCode: 400))
```

🐴 ⏫ [7] 32768/78055962, 0.0%
🐴 ⏫ [7] 65536/78055962, 0.0%
🐴 ⏫ [7] 98304/78055962, 0.0%
🐴 ⏫ [7] 131072/78055962, 0.0%
🐴 ⏫ [7] 163840/78055962, 0.0%
🐴 ⏫ [7] 229376/78055962, 0.0%
🐴 ⏱ Response received: 1.853 +1.853
🐴 ⬅️ Response 413 (95 bytes): https://chat-proxy-us-east.stream-io-api.com/channels/messaging/!members-HSeqPt/file?api_key=&user_id=&client_id=
🐴 📦 {
  "code" : 22,
  "message" : "body size exceeded the limit (20M)",
  "StatusCode" : 400,
  "duration" : "0.00ms"
}

```
## GetStream Environment
**GetStream Chat version:**  Stream Chat v.1.5.4
**iOS version:** 13
**Swift version:**  5
**Xcode version:**  11.3.1
**Device:** iPhone 7

**Comment by tbarbugli** [comment]
the API don't allow uploading a file/video/image larger than 20MB 

@buh @b-onc we should return a clear error but not crash

**Comment by buh** [comment]
@saurabhPV thank you for the report. Of course, it shouldn't. We will investigate the issue.
