### ISSUE TITLE
Localized strings do not work with Cocoapods for StreamChatUI v3

### ISSUE THREAD

**Issue by ericgroom** [GetStream/stream-chat-swift#839]
## What did you do?
* Integrated StreamChatUI (`3.2-beta` though looking at git history I imagine it applies to all versions)

## What did you expect to happen?
* Strings with their localization to display

## What happened instead?
* String keys are displayed

## GetStream Environment
**GetStream Chat version: 3.2-beta**
**GetStream Chat frameworks:** StreamChatUI
**iOS version: <=12.0**
**Swift version: 5.x**
**Xcode version: 12.2**
**Device: Simulator**

## Additional context

I looked through your code and it seems like you are creating a separate resource bundle than the one referenced in `L10n.swift`. I would submit a PR but it seems like `L10n.swift` is generated and you need to keep using this separate bundle for static frameworks, so I'm not quite sure what the solution here is...

**Comment by VojtaStavik** [comment]
Hi @ericgroom , thank you for your bugreport. Can you please try the fix from the `fix-strings-cocoapods` branch and let me know if it solves the issue?

**Comment by ericgroom** [comment]
@VojtaStavik The issue appears to be fixed on `fix-strings-cocoapods`!
