### ISSUE TITLE
Not able to send video and image both at same time 

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-swift#842]
when any user upload video and image file both same time in version 2.6.4 then image sent successfully but Video not sent.

**Comment by JeremPlln** [comment]
I have a similar issue but with an image only. If I upload an image and send it, it doesn't appear in the chat. I have to dismiss the view and show the view again to see my image. It also happens when I join a text message with the image.

sum up :
image + text message = nothing appears on screen
image only = nothing appears on screen

**Comment by iosiappmemes** [comment]
Hi @JeremPlln 

even after 4 days  of posting issue, i m waiting for response from stream Team.

It seems they they no time for reply and resolve the issue.

**Comment by VojtaStavik** [comment]
Hi 👋 @iosiappmemes @JeremPlln, sorry for the seeming inactivity in this issue. We're investigating it and will post the update here shortly. Thank you for your patience.

**Comment by iosiappmemes** [comment]
Hi @VojtaStavik 

Thank you. will wait for update.

**Comment by JeremPlln** [comment]
Thank you @VojtaStavik ! Here is a video of the problem :) 

Uploading Image d’iOS (2).MP4…

**Comment by b-onc** [comment]
Hello @iosiappmemes 
The issue of not being able to send images and files at the same time were resolved in commit 17fc2c6e53bec43be35c2a8364f8a5c5abb597b9 and will be released in 2.6.7.

@JeremPlln , thanks for the video! I cannot reproduce the issue. Can you enable and share the logs for this session?

**Comment by b-onc** [comment]
Hello @iosiappmemes 
The issue was fixed in 2.6.7

@JeremPlln , if you're still seeing the issue, please open a new ticket with logs, thank you!
