### ISSUE TITLE
Remove User from Channel

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-swift#843]
If Admin of the channel delete any user and that user already on same chat (online) , then that channel is not get deleted at deleted user
That channel should get deleted from deleted User end.
Deleted user is able to send the message in Channel from where he/she is deleted.

**Comment by iosiappmemes** [comment]
Hi @Stream Team

even after 8 days of posting issue, i m waiting for response from stream Team.

It seems Stream Team is on long vacation or  have no time for reply and resolve the issue.

**Comment by VojtaStavik** [comment]
Hi @iosiappmemes, this bug should be fixed in `v3.1.8` and `v3.2.0-beta.8`. Please re-open the issue in case you still experience the problem. Thank you.
