### ISSUE TITLE
ChatViewController marks messages as read even if it's not visible

### ISSUE THREAD

**Issue by mpodeszwa** [GetStream/stream-chat-swift#9]
## What did you do?

I present `ChatViewController` in `UITabBarController`. If user is not on the chat tab I'm observing new messages using code:
```
        Client.shared.onEvent(.messageNew)
            .subscribe(onNext: { [weak self] event in
                if case let .messageNew(_, unread, _, _, _, _) = event {
                    self?.presenter.setBadge(unread)
                }
            })
```

## What did you expect to happen?

I expect unread messages counter to increase with every new message and messages should be marked as read only after user enters the view. I can see code doing that:
```
    open override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        startGifsAnimations()
        markReadIfPossible()
    }
```
However there is this code in `viewDidLoad` which marks messages as read even if view controller is currently not visible:
```
        presenter.changes
            .filter { [weak self] _ in self?.changesEnabled ?? false }
            .do(onNext: { [weak self] _ in self?.markReadIfPossible() })
            .drive(onNext: { [weak self] in self?.updateTableView(with: $0) })
            .disposed(by: disposeBag)
```

## What happened instead?

Every message received is immediately marked as read even though user is on another tab.

## GetStream Environment
**GetStream Chat version:** 1.2.10

**Comment by buh** [comment]
Hi @mpodeszwa! Thanks! You are right. I'll do update soon.

**Comment by buh** [comment]
@mpodeszwa Please check v.1.3.0.
If you want custom behaviour for visibility of chat view controller, you can override `isVisible` variable.
