### ISSUE TITLE
Access control of StreamChatUI types

### ISSUE THREAD

**Issue by cjmconie** [GetStream/stream-chat-swift#907]
## What did you do?

Port the Demo App's `presentChat(userCredentials:)` extension on `UIViewController` and use it in our app.

This function leverages `StreamChatUI` to a) show a chat channel list using `ChatChannelListVC` and b) set a custom list router through `UIConfig.default.navigation.channelListRouter`. The purpose of the custom list router is to override the `openCreateNewChannel()` function:

```
class DemoChatChannelListRouter: _ChatChannelListRouter<NoExtraData> {
    override func openCreateNewChannel() {
        // ...
    }
}
```

The issue I am facing is most types within `StreamChatUI` are marked as `internal` and therefore not accessible. E.g. `UIConfig.default.navigation.channelListRouter` and `_ChatChannelListRouter`.

The access control of types between the cloned SDK and when installing through a dependency manager like Cocoapods is different. The Demo app is able to reference these types but 3rd parties are not.

## What did you expect to happen?

`StreamChatUI` types to be accessible.

## What happened instead?

Certain `StreamChatUI` types are marked as `internal`.

## GetStream Environment

**GetStream Chat version:** 3.1.3
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 13.0
**Swift version:** 5.3.2
**Xcode version:** 12.4
**Device:** Any

## Additional context
Cocoapods for dependency management.

**Comment by b-onc** [comment]
Hello @cjmconie 
This is on purpose and it's stated in our README:
> Roadmap
> - Open UI components for subclassing and customization (3/2021, available in 🅱️ 3.2.0-beta)

We still haven't finalized the API for StreamChatUI and released the components as `internal`. As we finalize the API, we'll `open` them up with each release.

**Comment by cf-lam** [comment]
@b-onc How would I go about using the beta version in my app? I'm using CocoaPods to install version 3.1.3 of StreamChatUI

**Comment by cf-lam** [comment]
Nevermind, I figured it out by putting this in my Podfile:

pod 'StreamChatUI', '~> 3.2.0-beta.4'
