### ISSUE TITLE
StreamChatUI Pods issue

### ISSUE THREAD

**Issue by iosiappmemes** [GetStream/stream-chat-swift#951]
## What did you do?
I just install the StreamChatUI SDK using CocoaPods. 

## What did you expect to happen?
This should work properly.

## What happened instead?
it is showing some errors in internal files of the SDK.

## GetStream Environment
**GetStream Chat version:** StreamChatUI 3.1
**GetStream Chat frameworks:** StreamChat, StreamChatUI, StreamChatClient, StreamChatCore
**iOS version:** 14.4
**Swift version:** 5.3
**Xcode version:** 12.2
**Device:** No device
<img width="1387" alt="Screenshot 2021-04-02 at 5 18 24 PM" src="https://user-images.githubusercontent.com/54673061/113413086-77144180-93d7-11eb-8742-53a8520b3036.png">

**Comment by VojtaStavik** [comment]
Hi @iosiappmemes , can you share your podfile and podfile.lock please? So far we can’t reproduce the issue. Maybe just an issue with a cashed build? Did you try to clean and build?

**Comment by iosiappmemes** [comment]
This is only I can share with you @VojtaStavik .
target 'Meme' do
  use_frameworks!
   pod 'StreamChat'
   pod 'StreamChatUI'
end

**Comment by iosiappmemes** [comment]
Hi @VojtaStavik , I just updated the used pods to latest version , it's working fine now. 
But I have one question .
What is different BW StreamChat or StreamChatClient?
should I need to use StreamChatClient in latest SDK 3.1.4?

**Comment by iosiappmemes** [comment]
Hi @VojtaStavik , My problem has been resolved by using latest SDK version 3.1.4, Thanks for your time.
