### ISSUE TITLE
Date separator support in Chat Messages Screen

### ISSUE THREAD

**Issue by cf-lam** [GetStream/stream-chat-swift#958]
## What are you trying to achieve?
Date separators that are common in other chat apps like iMessage and WhatsApp.

## If possible, how can you achieve this currently?
Potentially injecting my custom UICollectionView cell into the framework.

## What would be the better way?
If there was built in support for a UICollectionView Header cell that marked the date that a group of chat messages belonged to.

## GetStream Environment
**GetStream Chat version:**
**GetStream Chat frameworks:** StreamChatClient, StreamChatCore, StreamChat Beta
**iOS version:**
**Swift version:**
**Xcode version:**
**Device:**

**Comment by VojtaStavik** [comment]
Solved in Zendesk
