### ISSUE TITLE
CIS-42 Support markdown for links

### ISSUE THREAD

**Issue by b-onc** [GetStream/stream-chat-swift#98]
## What are you trying to achieve?
Get `[link](www.url.com)` to render in markdown (as [link](www.url.com))

## If possible, how can you achieve this currently?
None

## What would be the better way?
None

## GetStream Environment
**GetStream Chat version:1.5.6**
**iOS version:All**
**Swift version:All**
**Xcode version:All**
**Device:All**

**Comment by khoogheem** [comment]
@b-onc on the flip side of this... is there a way to turn off support for links?  either in the dashboard or via the app.  If we can override the way links get opened that would be great as well.. For those that already have a way to show web pages internally it would be nice to use that vs what is part of the UI provided by the SDK.

**Comment by b-onc** [comment]
Closing due to internal tracking
